### ISSUE TITLE
display empty levels in hchart.factor 

### ISSUE THREAD

**Issue by cstubben** [jbkunst/highcharter#101]
If I have a factor with 3 levels and one is missing, shouldn't hchart.factor display all three levels, including the missing "B" here?

```
 x <- factor(c("A", "A", "A", "C"), c("A", "B", "C"))
hchart(x)
```

**Comment by jbkunst** [comment]
Hi @cstubben 

I think you're right:

```
table(x)

x
A B C 
3 0 1 
```

I'll fix this ;)! Thanks!

**Comment by jbkunst** [comment]
@cstubben it's done.

Thanks again!
