### ISSUE TITLE
hc_annotations doesn't seem to be working

### ISSUE THREAD

**Issue by nuno-agostinho** [jbkunst/highcharter#103]
Hey @jbkunst, I tried to add some text to a plot using the function `hc_annotations` with no success. I recreated the example given in http://www.highcharts.com/plugin-registry/single/17/Annotations

```r
library(highcharter)
highchart() %>%
    hc_chart(renderTo="container") %>%
    hc_series(list(data=c(29.9, 71.5, 106.4, 129.2, 144.0, 176.0))) %>%
    hc_annotations(list(xValue=4, yValue=125, title=list(text="Annot")))
```

The plot works fine but it doesn't show the text annotation. See the result of running this code in here: http://rpubs.com/nuno-agostinho/182157

**Comment by jbkunst** [comment]
@nuno-agostinho 

Ups! Fixed! Thanks!
