### ISSUE TITLE
could not find function "hc_yAxis_multiples"

### ISSUE THREAD

**Issue by albertocalderari** [jbkunst/highcharter#105]
Hi,

I am trying to run the multi-axis example (Tokyo Climate) using the code from http://jkunst.com/highcharter/highcharts.html.

When I run the code I get the following error:

Error in function_list[[i]](value) : 
  could not find function "hc_yAxis_multiples"

Is there something wrong with my package or R version or is this a bug?
I'm Running  RStudio Version 0.99.893 wir R 3.2.4 (on Windows 7)  revised and highcharter version 0.3.0

Thanks

Alberto

**Comment by albertocalderari** [comment]
Just found the problem, is a bug in the code in the http://jkunst.com/highcharter/highcharts.html page.
You need to replace "hc_yAxis_multiples" with "hc_yAxis".

**Comment by jbkunst** [comment]
Hi @albertocalderari 

It's  not really a bug. It's a mistake (my mistake!) because in the page I show/use the development version of highcharter. So consider use the `hc_yAxis_multiples` when the next version (0.4) reach CRAN.

Thanks for point this out and sotty for the issue.

**Comment by tbenschop** [comment]
Hi @jbkunst 

Is it correct that this function might not work on MAC? It works on my windows machine but on MAC it throws up the could not find function "hc_yAxis_multiples" whereas I'm running version 0.3.1.9999

**Comment by jbkunst** [comment]
Hi @tbenschop 

I think this is not correct. Can you confirm you have the last version in your two machines?

The version number only apply on CRAN releases. I update the version number only when I make a release.
