### ISSUE TITLE
.hc_get_fonts doesn't handle fonts names with multiple spaces

### ISSUE THREAD

**Issue by sz-cgt** [jbkunst/highcharter#107]
Specifying a font like `Franklin Gothic Book` in a chart causes the chart to not generate.

The issue is in `.hc_get_fonts` at line 133 of theme.R.  Instead of 

    str_replace("\\s+", "+") %>% 

it should be

    str_replace_all("\\s+", "+") %>%

otherwise only the first space in the font name is converted to a `+`

**Comment by jbkunst** [comment]
Thanks so much for found these bugs!
