### ISSUE TITLE
reduce typing of dataframe

### ISSUE THREAD

**Issue by ziyadsaeed** [jbkunst/highcharter#11]
there is lot of retyping dataframe$var1, dataframe$var2 etc. It would be nice to use the dataframe once and then just refer to the vars for eg. in rbokeh

```r
library(rbokeh)

p <- figure() %>%
   ly_points(Sepal.Length, Sepal.Width, data = iris,
    color = Species, glyph = Species,
    hover = list(Sepal.Length, Sepal.Width))
p
```

**Comment by jbkunst** [comment]
Yes. I know. That's is one big limitation (just I said in the blog post) in *this* package. My first idea was write a highchart just like to write the javascript object to get a chart in a webpage `{chart: {type: 'line'}, ...}`. I'm not so familiar with non standar evaluation so I'm not sure in a short time I change this.

Anyway you can always do the things in a not fancy way:

```
hc <- highchart()
for (cyl in unique(mtcars$cyl)) {
  hc <- hc %>%
    hc_add_serie_scatter(mtcars$wt[mtcars$cyl == cyl], mtcars$mpg[mtcars$cyl == cyl],
                         name = sprintf("Cyl %s", cyl), showInLegend = TRUE)
}

hc
```

Or something like that.

I will close the issue. But I hope some day I will do something like rbokeh :smile: . 

Thanks.

**Comment by jbkunst** [comment]
Hi @ziyadsaeed ,

How much time since this issue? Well, now highcharter haver a similar implementation. Like qqplot, check
http://rpubs.com/jbkunst/highcharter-hchart-data-frames

;) regards
