### ISSUE TITLE
Add redraw capability

### ISSUE THREAD

**Issue by bogdanrau** [jbkunst/highcharter#112]
It would be extremely useful to get a way to update the data in a highchart without having to redraw everything. For example, in a shiny app, say I have a drop down that controls what gets charted, but the series categories in a bar chart remain the same, it would be useful to have the chart just regenerate the bars (or update them), without having to redraw the entire thing.

It seems like the functionality I'm looking for is here: http://stackoverflow.com/questions/14100011/highcharts-redraw-vs-new-highcharts-chart

Is this already available or could this make it into a future milestone?

Thank you for this awesome package! It's been making my life a hell of a lot easier!

**Comment by nuno-agostinho** [comment]
I'd also like to have this! Highcharts supports dynamic charts using the functions [`addSeries`](http://api.highcharts.com/highcharts#Chart.addSeries), [`addPoint`](http://api.highcharts.com/highcharts#Series.addPoint), [`removePoint`](http://api.highcharts.com/highcharts#Series.removePoint), [`redraw`](http://api.highcharts.com/highcharts#Chart.redraw) and others.

I find that the best examples of dynamic charts are [adding live data points](http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/dynamic-update/) and [adding user supplied points](http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/dynamic-click-to-add/)

**Comment by jbkunst** [comment]
@bogdanrau 

Thanks for the comment!

Yep, this could be a **really** nice feature. I need time to think if this is relative easy. I'm aware about all highcharts funcionalities but I'm not sure right now how to implement. I'll start thinking about it.

Regards!

**Comment by jbkunst** [comment]
From the site http://www.highcharts.com/news/215-highcharts-5-preview

> Another, related improvement in Highcharts 5 is the general Chart.update method. In Highcharts 4 we have methods like Series.update, Axis.update and Point.update, but there was no simple way to update things like the legend, tooltip or general chart settings without destroying the chart, modifying the options and create a new chart.

Demo http://jsfiddle.net/gh/get/jquery/1.7.2/highcharts/highcharts/tree/master/samples/highcharts/members/chart-update/

So, let's try to implemente when this version come out.

**Comment by jbkunst** [comment]
Start WIP http://jsfiddle.net/jbkunst/qrjccvu7/

**Comment by MathieuMarauri** [comment]
Hello,

Thank you a lot for this great package. I am having lots of fun using it. 

I want to be able to hide/show a serie in a chart from an input button without having the plot being rerendered. It seems to be linked with this issue. Are there any news?

Thank you again for this package. 

Mathieu

**Comment by jkr216** [comment]
Hi, I'm trying to use this updater in Shiny and wondering if the work has made its way to highcharter. Thanks!

**Comment by aarora79** [comment]
Exactly same use case as jkr216's comment, would really love to have this feature in highcharter.

**Comment by nklepeis** [comment]
I'm looking into dynamic charts from R with ability to quickly change series and points on the fly.

**Comment by jbkunst** [comment]
Hi,

After 4 years we can close this issue 🙈 .

Thanks to @JohnCoene and @PaulC91 I've implement some function to avoid redraw the entire chart. You can see some examples in https://jbkunst.shinyapps.io/highcharter-proxy/ and the code here https://github.com/jbkunst/highcharter/blob/master/dev/sandbox/proxy-shiny.R

The functions implemented by now are:

- `hcpxy_add_series`
- `hcpxy_remove_series`
- `hcpxy_update`
- `hcpxy_update_series`
- `hcpxy_add_point`
- `hcpxy_remove_point`
- `hcpxy_loading`

Would be great if you can test and bring all the new bugs! 😄 

Cheers.

**Comment by JohnCoene** [comment]
The demo looks fantastic @jbkunst, well done!
