### ISSUE TITLE
Does not work correctly for 3 level Treemaps

### ISSUE THREAD

**Issue by kickbox** [jbkunst/highcharter#117]
Thank you for the package and supporting treemaps of Highcharts. :+1: 

I am having trouble creating a three level treemap. The structure of the treemap is something like CostCenter->Vendor->Tool. 

Using highcharter - when I select VendorA in level 2, I am shown all the Tools under VendorA and not just the ones under the parent ConstCenter. 

However the tm(treemap) plot shows this correctly.

**Comment by kickbox** [comment]
Could anyone please point me to a workaround if possible? 

Sorry for the question but, I came to highcharter after weeks of struggling with rCharts. Currently I dont have much time to complete my dashboard :(

**Comment by jbkunst** [comment]
Hi @kickbox 

Mmm not sure, Have you a minimal reproducible example to work with?

The `hc_add_series_treemap` function needs some rework because not support all the cases. As alternative you can make by hand the 3level treemap, I know this is not optimal but is an alternative.

```
highchart() %>% 
  hc_add_series(
    type = "treemap",
    layoutAlgorithm = "squarified",
    allowDrillToNode = TRUE,
    levels = list(
      list(
        level = 1,
        dataLabels = list(
          enabled = TRUE
          ),
        borderWidth = 3
        ),
      list(
        level = 2,
        dataLabels = list(
          enabled = TRUE
        ),
        borderWidth = 2
      )
      ),
    data = list(
      # LEVEL I
      list(
        id = "A",
        name = "apples",
        color = "#EC2500"
        ),
      list(
        id = "B",
        name = "Bananas",
        color = "#ECE100"
        ),
      # LEVEL II
      list(
        name = "Anna",
        parent = "A",
        value = 4
        ),
      list(
        name = "Anna2",
        parent = "A",
        value = 2
        ),
      list(
        id = "R",
        name = "Rick",
        parent = "B"
        ),
      list(
        id = "P",
        name = "Paul",
        parent = "B"
      ),
      # LEVEL 3
      list(
        name = "SubRick",
        parent = "R",
        value = 3
        ),
      list(
        name = "SubRick2",
        parent = "R",
        value = 3
        ),
      list(
        id = "SP",
        name = "SubPaul",
        value = 5,
        parent = "P"
        )
      )
    )
```

**Comment by kickbox** [comment]
Hi @jbkunst thank you for pointing me towards working with the api, Instead of creating the list manually, I have automated the generation process. I spent some effort and without (hc_add_series_treemap/treemap) I was able to create a key/pair value list to feed into the data field. 

I am just summarising the steps I followed for others' benefits.

1. Created a tree structure, with the order of using the package data.tree 
-> you can specify the order of grouping like in index in the treemap package
-> has flexibility of aggregating of values for the parent nodes
2. Converted to data.frame
3. Converted each row of data.frame to key/pair using [toJSONArray2()](https://github.com/ramnathv/rCharts/blob/389e214c9e006fea0e93d73621b83daa8d3d0ba2/R/toJSON.R) function of rCharts

This helped me to solve my immediate issue. As with your request for a reproducible example, I will update that here asap.

**Comment by jbkunst** [comment]
@kickbox  nice,

Can you share the code? I need to remake `hc_add_series_treemap` (#110), and I'd like to see other alternatives.

Regards,!

**Comment by kickbox** [comment]
@jbkunst Sure! 

```
structure(list(Costcenter = c("N1", "N1", "N1", "N1", "N1", "N1", 
"N1", "N1", "N2", "N2", "N2", "N2", "N2", "N2", "N3", "N3", "N4", 
"N5", "N5", "N6"), Vendor = c("L2", "L2", "L2", "L2", "L2", "L2", 
"L2", "L2", "L1", "L2", "L2", "L2", "L3", "L3", "L2", "L2", "L2", 
"L2", "L2", "L2"), absDiff = c(103.0776, 37.9086, 269.7629, 6.0888, 
515.388, 27.2604, 27.2604, 6.3608, 4.5434, 88.5966, 982.2193, 
139.4249, 0.5452, 722.9811, 130.3381, 147.8434, 271.8786, 88.5966, 
327.4065, 366.564), value = c(103.0776, 37.9086, 269.7629, 6.0888, 
515.388, 27.2604, 27.2604, 6.3608, 4.5434, 88.5966, 982.2193, 
139.4249, 0.5452, 722.9811, 130.3381, 147.8434, 271.8786, 88.5966, 
327.4065, 366.564), Tool = c("M1", "M2", "M4", "M5", "M6", "M9", 
"M10", "M11", "M8", "M5", "M9", "M10", "M3", "M7", "M4", "M5", 
"M5", "M5", "M10", "M5")), .Names = c("Costcenter", "Vendor", 
"absDiff", "value", "Tool"), row.names = c(NA, -20L), class = "data.frame")
```
```
#specify the tree hierarchy
df$pathString <- paste("Root" ,df$Costcenter, df$Vendor, df$Tool,   sep = "/")

library("data.tree")
s <- as.Node(df ,mode="table")

#create values for parent nodes, by aggregation of children values
s$Do(function(node) node$value <- Aggregate(node , attribute = "value", aggFun = sum), traversal = "post-order")

# assign ids to all nodes
s$Set(id = 1:s$totalCount)
# calculate parent ids for all children, using parent1 as parent is system reserved by data.tree
s$Set(parent1 = c(function(self) GetAttribute(self$parent, "id", format = identity)))

#copy the data tree structure to a data.frame
test <- print(s,"Costcenter","Vendor","Tool","value", "level", "id", "parent1")
test <- data.table(test)

#manip to get the correct level name
test[,name:= gsub("[^[:alnum:]]", " ", levelName)]
test[,name:= trimws(name)]

test[,parent:= as.character(parent1)] # parent and ids should be of character for highcharts
test[,id:=as.character(id)] # parent and ids should be of character for highcharts
#deleting unnecessary columns
test[,value:= as.numeric(trimws(value))]
test[,levelName:=NULL]
test[,Costcenter:=NULL]
test[,Vendor:=NULL]
test[,Tool:=NULL]
test[,parent1:=NULL]
test[,level:=NULL]

str(list)
library(rCharts)
list <- toJSONArray2(test,FALSE)

#list[[1]]$parent <- NULL
#list[[1]]$value <- NULL

highchart() %>% 
  hc_add_series(
    type = "treemap",
    layoutAlgorithm = "squarified",
    allowDrillToNode = TRUE,
    levels = list(
      list(
        level = 1,
        dataLabels = list(
          enabled = TRUE
        ),
        borderWidth = 3
      ),
      list(
        level = 2,
        dataLabels = list(
          enabled = TRUE
        ),
        borderWidth = 2
      )
    ),
    data= list
  ) 

```

Hope this helps. Am not sure of the system performance of this code.

**Comment by kickbox** [comment]
Hi @jbkunst do you plan to make progress on this topic in the coming days?

**Comment by alexpghayes** [comment]
I'm also having trouble with 3 level treemaps at https://textonomer.shinyapps.io/treemap/ with the following settings

Top level heirarchy: Location
Second level heirarchy: Author
Third level hierarchy: Publisher
Max treemap cells: 50
Include Missing: True

If you drilldown on London > Unknown Author, instead of having a single cell for "Unknown Publisher" there are multiple cells, which is incorrect. The treemap package plots the data correctly and as expected, however. Checking whether or not I can share the code for this.

**Comment by jbkunst** [comment]
Hi @alexpghayes 

This is a well known issue. I'm working in the _rework_ of this function using @kickbox code.

I hope I will fix this in 2 weeks. If you want you can try https://github.com/jbkunst/highcharter/blob/master/dev/treemap5.R

**Comment by parkjared** [comment]
Thanks for this great package! Any updates on the rework that will accommodate 3 level treemaps? I'm building a dashboard and want to know if I can just hold out for your much anticipated updates, thanks!

**Comment by jbkunst** [comment]
Hi everyone, 

@alexpghayes create in the dev version the `hctreemap2` function, so if you still have the issue please try it.

I tested the @kickbox  example using:

```r
hctreemap2(df, c("Costcenter", "Vendor", "Tool"), size_var = "absDiff", color_var = "value")
```
With 0 problems
