### ISSUE TITLE
Series.hide()

### ISSUE THREAD

**Issue by hsy9045** [jbkunst/highcharter#121]
Hi, is it possible to use highcharter to hide plotted series, similar to this example? This seems to be a great feature when one needs to hide multiple series with one mouse click, instead of clicking on the legend one by one.

http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/members/series-hide/

Thank you.

**Comment by jbkunst** [comment]
Have you tried the `linkedTo` argument? Please check http://rpubs.com/jbkunst/highcharter-issues-121 and tell me if this work for you.

Cheers

**Comment by hsy9045** [comment]
Thank you for the prompt reply! This works great. 
For my own case, I also added `showInLegend = T` when defining `series`, so that I can still control individual series as usual.

**Comment by jbkunst** [comment]
Nice! :wink:

**Comment by AndreasHaldIncom** [comment]
Hi, the issue 121 link doesn't work. Is there any example on the linkedTo argument with a button with show/hide without having to re-render the whole plot? I've been looking at the develop version of this awesome package with the proxy functions but without luck for this particular show/hide.
