### ISSUE TITLE
could not find function "hc_add_series_list"

### ISSUE THREAD

**Issue by Rhoboot** [jbkunst/highcharter#122]
```
library(highcharter)
ds <- lapply(seq(10), function(x){
  list(data = cumsum(rnorm(100, 1, 5)), name = x)
})

highchart() %>%
  hc_plotOptions(
    series = list(
      showInLegend = FALSE,
      marker = list(enabled = FALSE)
    )
  ) %>%
  hc_add_series_list(ds) 
```

Error in function_list[[k]](value) : 
  could not find function "hc_add_series_list"

**Comment by jbkunst** [comment]
You probably are using the CRAN version and not the development one. Please try `devtools::install_github("jbkunst/highcharter")` first, then your code,

Regards

**Comment by Rhoboot** [comment]
Muchas Gracias, eso era..

**Comment by jbkunst** [comment]
De nada! ;) gracias por testear highcharter.
