### ISSUE TITLE
Add secondary x-axis

### ISSUE THREAD

**Issue by tbenschop** [jbkunst/highcharter#124]
Dear @jbkunst 
I'm trying to create a secondary x-axis from this example: [link](http://jsfiddle.net/W43Zb/) but it won't work. I have tried it with this example:
```
ds <- lapply(seq(5), function(x){
  list(data = cumsum(rnorm(5, .05, .01)), name = paste0("test",x))
})
hc<-highchart() %>%
  hc_chart(type="area")%>%
  hc_xAxis(list(categories=1:7,title=list(text="first axis")),
           list(categories=11:17,title=list(text="second axis"),opposite=T)) %>%
  hc_plotOptions(stacking="percent",series = list(marker = list(enabled = FALSE))) %>%
  hc_add_series_list(ds)
hc

```
I understand I'm missing this part from the js code: `, function(chart) {
        var extremes = chart.xAxis[0].getExtremes();
        chart.xAxis[1].setExtremes(extremes.min-0.5,extremes.max+0.5);` but I have no idea how to implement it. Is this something that can be accommodated in the current version of highcharter? Thanks, Tim

**Comment by jbkunst** [comment]
Hi @tbenschop 

Some considerations:

- First of all, the multiples axis are not supported for the X, 
- For create yAxis, you need to use hc_yAxis_multiples, see this example http://rpubs.com/jbkunst/create_yaxis
- You can preset the `extremes` via `min` and `max` arguments for each axis and avoid to use the get extremes. However, is possible if you want to, do it via `function(chart) ...`  but I dont recommend it beacuse this is more a js-like solution.

Hope it helps,

**Comment by tbenschop** [comment]
Hi @jbkunst 
Just coming back to this with a different example from highcharts. Would this be possible to achieve:
http://www.highcharts.com/plugin-registry/single/11/Grouped-Categories
I tried this...
Many thanks, Tim

```
x_categories<-c("apples","bananas","Grapes","Oranges","Grapes") #example that works without group

x_categories<-list( #Example that doesnt work where I tried to group
  list(name="fruit",data=c("apple","Bananas")),  #c("apples","bananas","Grapes","Oranges","Grapes")
       list(name="fruit5",data=c("apple","Bananas")),
            list(name="fruit4",data=c("apple","Bananas")),
                 list(name="fruit3",data=c("apple","Bananas")),
                      list(name="fruit2",data=c("apple","Bananas")))

data_series<-list(list(name="John",data=c(1:5),stack="Male"),list(name="George",data=c(11:15),stack="Male"),
                  list(name="Jane",data=c(11:15),stack="Female"),list(name="Janet",data=c(21:25),stack="Female"))

highchart() %>% 
  hc_chart(type = "column") %>% 
  hc_title(text = "MyGraph") %>% 
  hc_xAxis(categories=x_categories) %>%
  #hc_xAxis(title = list(text = "Vintage Year"),categories = df[[1]]) %>% 
  hc_yAxis(title = list(text = "Weights")) %>% 
  hc_plotOptions(column = list(
    dataLabels = list(enabled = FALSE),
    stacking = "normal",
    enableMouseTracking = TRUE)
  ) %>% 

```  hc_add_series_list(data_series)

**Comment by jbkunst** [comment]
Mmm... Can you check if this work for you? I'm just playing with dependencies.

```
data_series<-list(list(name="John",data=c(1:5),stack="Male"),list(name="George",data=c(11:15),stack="Male"),
                  list(name="Jane",data=c(11:15),stack="Female"),list(name="Janet",data=c(21:25),stack="Female"))

hc <- highchart() %>% 
  hc_chart(type = "column") %>% 
  hc_title(text = "MyGraph") %>% 
  hc_xAxis(categories=x_categories) %>%
  #hc_xAxis(title = list(text = "Vintage Year"),categories = df[[1]]) %>% 
  hc_yAxis(title = list(text = "Weights")) %>% 
  hc_plotOptions(column = list(
    dataLabels = list(enabled = FALSE),
    stacking = "normal",
    enableMouseTracking = TRUE)
  ) %>%
  hc_add_series_list(data_series)

library(htmltools)
dep <-  htmlDependency(
  name = "grouped-categories",
  version = "1.1.0",
  src = c(
    href = "http://blacklabel.github.io/grouped_categories"
  ),
  script = "grouped-categories.js"
)

hc$dependencies <- c(hc$dependencies, list(dep))

hc
```

**Comment by jbkunst** [comment]
I tried the pluging example:

```
library(highcharter)
library(htmltools)


hc <- highchart() %>% 
  hc_chart(type = "column") %>% 
  hc_title(text = "MyGraph") %>% 
  hc_add_series(data = c(4, 14, 18, 5, 6, 5, 14, 15, 18)) %>% 
  hc_xAxis(categories = list(
    list(
      name =  "Fruit",
      categories = list("Apple", "Banana", "Orange")
    ),
    list(
      name =  "Vegetable",
      categories = list("Carrot", "Potato", "Tomato")
    ),
    list(
      name = "Fish",
      categories = list("Cod", "Salmon", "Tuna")
    )
  ))
  
hc

dep <-  htmlDependency(
  name = "grouped-categories",
  version = "1.1.0",
  src = c(
    href = "http://blacklabel.github.io/grouped_categories"
  ),
  stylesheet = "css/styles.css",
  script = "grouped-categories.js"
)

hc$dependencies <- c(hc$dependencies, list(dep))

hc
```

**Comment by jbkunst** [comment]
**Please**, this is not related with the title of this issue so you can open a new one if this follow the rules in https://github.com/jbkunst/highcharter/blob/master/CONTRIBUTING.md

**Comment by tbenschop** [comment]
Thanks again @jbkunst 
This is exactly what I was looking for.

**Comment by tbenschop** [comment]
@jbkunst Would you prefer to have this question in SO rather than github?

**Comment by jbkunst** [comment]
If is a kind of questions/ how to do I prefer put in SO, if is a bug or ask a pluging or feature like this open a new issue ;).

**Comment by LilianaPacheco** [comment]
Thanks for your help and wonderful package. I have a question, what if I want the label of Vegetables (and "Carrot", "Potato", "Tomato") in a different color? I am trying to add this of code (not sure where) but I am not getting any result:

```
formatter= JS("function () {
        if ('Vegetable' === this.value) {
            return '<span style='fill: red;'>' + this.value + '</span>';
        } else {
            return this.value;
        }
    }"
)
```

Thanks

**Comment by LilianaPacheco** [comment]
Thank you for your answers and this great package. I have a question, what if I want the label of "Vegetables" (and "Carrot", "Potato", "Tomato") to be in a different color? I am trying to use this piece of code (not sure where to place it) but I'm not getting any result:

`formatter= JS("function () {
        if ('Vegetable' === this.value) {
            return '<span style='fill: red;'>' + this.value + '</span>';
        } else {
            return this.value;
        }
    }"
)`

Is somewhat similar to this example: [Example](http://jsfiddle.net/tDSrd/)

**Comment by jbkunst** [comment]
Hi @LilianaPacheco ,

Compare what you put:
```
return '<span style='fill: red;'>' + this.value + '</span>';
``` 

with the example:
```
return '<span style="fill: red;">' + this.value + '</span>';
```

In R you as you are using `"` at the beginning of the `JS` you need scape the `"` used inside of the text, this is:

```
JS("..

return '<span style=\"fill: red;\">' + this.value + '</span>';

...")
```

Tell me if this work for you ;)

**Comment by LilianaPacheco** [comment]
Thank you @jbkunst!

Well, with your suggestion the label "Vegetable" is red, but "Carrot", "Potato" and "Tomato" are still not red colored. I'm still trying to find the way :(

**Comment by jbkunst** [comment]
I think you can just use a _or_  (`this.value == 'carrot' | this.value == 'othercarrot' | ...`) in the `if` statement, not that elegant, but possible.

**Comment by LilianaPacheco** [comment]
Hmmm, and what if the second level states the same number of labels, such as 

- Apple= 2015, 2016, 2017,
- Vegetable= 2015, 2016, 2017
 and 
- Fish= 2015, 2016, 2017
?

I tried previously your suggestion, but it is coloring all '2015' not just the one for Vegetables but for Apple and Fish too.

Is there some way to specify the level of the series label? Something like: color in the first level when it says Vegetable and in the Second level 2015, 2016 and 2017....


Thank you very much!
