### ISSUE TITLE
No column plots visible anymore

### ISSUE THREAD

**Issue by jwinter6** [jbkunst/highcharter#127]
Hi all,

since some time I am not able to have column plots anymore, it just does not show any data (but everything else).
I followed your github changes quite intense, but somehow it does not work anymore and I don't know what I am doing wrong here.

In my shiny app there are many errors, but also in the minimum example below no columns are shown.
The errors in the shiny app:

> --- Running modules/map.src.js from GitHub, branch/commit/tag "v4.2.4" ---
> highstock.js:53 GET http://127.0.0.1:6635/undefined 404 (Not Found)
> getBBox @ highstock.js:53
> L @ highstock.js:80
> k.textSetter @ highstock.js:82
> attr @ highstock.js:45
> k.onAdd @ highstock.js:81
> add @ highstock.js:54
> init @ highstock.js:166
> z.Tooltip @ highstock.js:166
> init @ highstock.js:176
> (anonymous function) @ highstock.js:423
> a.(anonymous function) @ highstock.js:22
> (anonymous function) @ map.js:960
> a.(anonymous function) @ highstock.js:22
> z.Pointer @ highstock.js:175
> firstRender @ highstock.js:236
> init @ highstock.js:214
> (anonymous function) @ highstock.js:403
> a.(anonymous function) @ highstock.js:22
> (anonymous function) @ highstock.js:419
> a.(anonymous function) @ highstock.js:22
> (anonymous function) @ highcharts-3d.js:26
> a.(anonymous function) @ highstock.js:22
> (anonymous function) @ data.js:24
> a.(anonymous function) @ highstock.js:22
> getArgs @ highstock.js:213
> z.Chart @ highstock.js:212
> J.jQuery.fn.highcharts @ highstock.js:29
> renderValue @ highchart.js:62
> shinyBinding.renderValue @ htmlwidgets.js:508
> onValueChange @ output_binding.js:16
> delegator.(anonymous function) @ htmlwidgets.js:112
> onValueChange @ output_binding_adapter.js:21
> receiveOutput @ shinyapp.js:257
> (anonymous function) @ shinyapp.js:424
> _sendMessagesToHandlers @ shinyapp.js:409
> dispatchMessage @ shinyapp.js:393
> c.onmessage @ shinyapp.js:91
> 46highstock.js:178 Uncaught TypeError: Cannot read property 'clientX' of undefinedrunPointActions @ highstock.js:178
> onContainerMouseMove @ highstock.js:186
> b.onmousemove @ highstock.js:18`

The minimum example which also doesnt work anymore:
```
> head(data.plot)
                              x    y
CASP8_0_31008     CASP8_0_31008   58
CASP8_0_38760     CASP8_0_38760 2369
CASP8_1_23256     CASP8_1_23256   22
CASP8_1_31008_L CASP8_1_31008_L    0
CASP8_1_38760     CASP8_1_38760  414
CASP8_1_46512     CASP8_1_46512  179`

```
```
hc <- highcharter::highchart()
hc <- highcharter::hc_chart(hc, type="column", polar=FALSE)
hc <- highcharter::hc_title(hc, text = paste("sgRNA Read Count of", gene, sep= " "))
hc <- highcharter::hc_subtitle(hc, text = paste("For data sets" , paste(cp$dataset.names, collapse = ","), sep = " "))
hc <- highcharter::hc_xAxis(hc,title = list(text = "sgRNAs"))
hc <- highcharter::hc_yAxis(hc, title= list(text = "ReadCount"), gridLineInterpolation = "polygon",
            lineWidth = 0,
            min = 0)
hc <- highcharter::hc_add_series_df(hc, type = "column", data = data.plot, fillOpacity = 0.5, lineWidth=0)

hc

```
![documents phd github scripts crispr carpools-development - rstudio 2016-06-09 12-47-18](https://cloud.githubusercontent.com/assets/7203572/15927196/56b9a184-2e40-11e6-89ae-d6c2b9a5ff8a.png)

Any ideas? 

cheers
Jan

**Comment by jbkunst** [comment]
@jwinter6 Hi Jan,

First of all I cant reproduce your example :(.

Second, you are not given the right names and type in the data. From the highcharts documentation (http://api.highcharts.com/highcharts#series<column>.data) to give a data to a column series you need something like:

```
data: [{
    x: 1,
    y: 5,
    name: "Point2",
    color: "#00FF00"
}, {
    x: 1,
    y: 9,
    name: "Point1",
    color: "#FF00FF"
}]
```

So you need to change the `x` name to `name`: 

```
library("highcharter")
library("dplyr")
data("iris")

data.plot <- count(iris, Species) %>% 
  setNames(c("name", "y")) 

data.plot
> Source: local data frame [3 x 2]
> 
>         name     y
>       (fctr) (int)
> 1     setosa    50
> 2 versicolor    50
> 3  virginica    50
> 

highchart() %>%
  hc_chart(type="column") %>% 
  hc_xAxis(categories = data.plot$name) %>% 
  hc_add_series_df(type = "column", data = data.plot)
```

:B
