### ISSUE TITLE
Cant manage to use Highcharter combined with rmarkdown

### ISSUE THREAD

**Issue by juansecal** [jbkunst/highcharter#129]
Is there an easy way to print my highcharts in my rmarkdown, so far they does not get displayed.

I saw a previous post of yours http://stackoverflow.com/questions/17168464/2-knitr-r-markdown-rstudio-issues-highcharts-and-morris-js but it didnt help, I'm not an expert on java.

I would appreciate your help

**Comment by jbkunst** [comment]
Hi @juansecal 

Not sure how I can help you. Can you give me a minimal example of your Rmd file?

**Comment by juansecal** [comment]
Those ar the graphics I want to display:

`for(t`` in factor_variables){
h=highchart()%>%
  hc_title(text = t) %>% 
  hc_xAxis(categories = unique(as.character(Base_Finale_Modelisation_00_05[,t]))) %>%
  hc_yAxis(
    list(
      title = list(text = "Exposition"),
      align = "left",
      showFirstLabel = FALSE,
      showLastLabel = FALSE,
      labels = list(format = "{value}", useHTML = TRUE)
    ),
    list(
      title = list(text = "Charges totales"),
      align = "right",
      showFirstLabel = FALSE,
      showLastLabel = FALSE,
      labels = list(format = "{value}", useHTML = TRUE),
      opposite = TRUE
    )
  )%>%
hc_add_series(name = "Exposition", type = "column",
                data = aggregate(formula(paste0("anp~", t)),data=Base_Finale_Modelisation_00_05,FUN = sum)[,2],yAxis = 1)%>%
hc_add_series(name = "Charges totales moyennes", type = "line",
              data = aggregate(formula(paste0("charge10ans~", t)),data=Base_Finale_Modelisation_00_05,FUN = mean)[,2]) 
print(h)
}
`
If executed normally it will do it on the console , but inside a
```{r echo=FALSE, warning=FALSE}
```
It would do nothing`

`

**Comment by juansecal** [comment]
`for(t in factor_variables){
h=highchart()%>%
  hc_title(text = t) %>% 
  hc_xAxis(categories = unique(as.character(Base_Finale_Modelisation_00_05[,t]))) %>%
  hc_yAxis(
    list(
      title = list(text = "Exposition"),
      align = "left",
      showFirstLabel = FALSE,
      showLastLabel = FALSE,
      labels = list(format = "{value}", useHTML = TRUE)
    ),
    list(
      title = list(text = "Charges totales"),
      align = "right",
      showFirstLabel = FALSE,
      showLastLabel = FALSE,
      labels = list(format = "{value}", useHTML = TRUE),
      opposite = TRUE
    )
  )%>%
hc_add_series(name = "Exposition", type = "column",
                data = aggregate(formula(paste0("anp~", t)),data=Base_Finale_Modelisation_00_05,FUN = sum)[,2],yAxis = 1)%>%
hc_add_series(name = "Charges totales moyennes", type = "line",
              data = aggregate(formula(paste0("charge10ans~", t)),data=Base_Finale_Modelisation_00_05,FUN = mean)[,2]) 
print(h)
}
`

**Comment by jbkunst** [comment]
You can do:

1) Put all the htmlwidgets in a list
2) Then use `tagList` function from the hmtools package.

Example: http://rpubs.com/jbkunst/highcharter-129

Reference: http://stackoverflow.com/questions/30509866/for-loop-over-dygraph-does-not-work-in-r

Tell me if work for you!

**Comment by juansecal** [comment]
It worked thank you so much

**Comment by juansecal** [comment]
Just added u on linked-in btw

**Comment by jbkunst** [comment]
Nice! Ok :wink:
