### ISSUE TITLE
hc_add_series_df: line chart

### ISSUE THREAD

**Issue by terencezzh** [jbkunst/highcharter#130]
I tried to follow the instruction on Shortcuts page:http://jkunst.com/highcharter/shortcuts.html and made a line chart instead. However, it seems not working that the graph is empty.

`require("dplyr")`
`library("viridisLite")`
`df = data_frame(x = c("2015-01-02","2015-01-03","2015-01-04","2015-01-05","2015-01-02","2015-01-03","2015-01-05"),y = c(100,105,110,120,80,90,98),name = c("A","A","A","A","B","B","B"))`

`highchart() %>% hc_add_series_df(data = df, type = "line")%>%` 
`hc_xAxis(categories = as.numeric(as.POSIXct(as.Date(test1$Date)))*1000,type = 'datetime',labels = list(format = '{value:%b %d}'))`

The regular hc_add_series doesn't work very well here because I have some missing value in df. For example, "B" is missing data on "2015-01-04".

Did I do anything wrong with `hc_add_series_df`?

Thank you in advance!

**Comment by jbkunst** [comment]
Hi @terencezzh 

Dont work for you:

```
df <- df %>% 
  mutate(x = datetime_to_timestamp(lubridate::ymd(x)))

highchart() %>%
  hc_add_series_df(data = df, type = "line") %>%
  hc_xAxis(type = 'datetime',labels = list(format = '{value:%b %d}'))
```

When you use the `hc_add_series_df` you must ensure have the right type of data, in this case the line chart need: http://api.highcharts.com/highcharts#series<line>.data `x` as a numeric value:

```
require("dplyr")
library("viridisLite")
df = data_frame(x = c(1:7),y = c(100,105,110,120,80,90,98),name = c("A","A","A","A","B","B","B"))

highchart() %>%
  hc_add_series_df(data = df, type = "line") %>% 
  hc_xAxis(categories = 1:7, type = 'datetime',
           labels = list(format = '{value:%b %d}'))

``` 

Finally, the `hc_add_series_df` is for add **just one** series. Thats why the first example chart one line.

Tell me if this help you ;).

**Comment by terencezzh** [comment]
Hi @jbkunst ,

Thanks a lot for your clear explanation and thanks again for creating this fascinating package. I appreciate it. The date transform function is also very helpful.

If `hc_add_series_df` is for adding just one series, is there a way to add multiple series by input a data.frame? I know I can use 'apply' to programmatically add multiple `hc_add_series_df`, but I am wondering if there is a more efficient way to do that. 

Note: assuming not all series have the same length (many missing values), so I think `hc_add_series_list` won't able to do that. 

Thank you very much in advance!

**Comment by jbkunst** [comment]
Hi @terencezzh 

You're welcome.

About add multiples series. You can do a group, to make a data (list) and then create a list of series:

```
series <- diamonds %>% 
  sample_n(1000) %>% 
  group_by(name = cut) %>% # the series dont have the same length :B
  do(data = list.parse2(data.frame(x = .$price, y = .$carat))) %>% 
  list.parse3()

highchart() %>% 
  hc_chart(type = "scatter") %>% 
  hc_add_series_list(series)
``` 

Also, you can use the hc_add_series_df_tidy data frame wich can do something like you need.


```
dat <- data.frame(id = c(1,2,3,4,5,6),
                  grp = c("A","A","B","B","C","C"),
                  value = c(10,13,9,15,11,16))

dat

highchart() %>% 
  hc_chart(type = "line") %>% 
  hc_add_series_df_tidy(data = dat, group = grp, values = value)
```

You can see the example live here: http://rpubs.com/jbkunst/highcharter-130

**Comment by terencezzh** [comment]
Hi @jbkunst ,

Thank you so much!! These solutions are both great for me. I appreciate your help. I have learned a lot from your notes as well.

Thanks again.

**Comment by terencezzh** [comment]
Hi @jbkunst ,

I have a follow-up question. Please see below codes:
```
dat <- data.frame(id = c("2015-01-01","2015-01-02","2015-01-01","2015-01-03","2015-01-02","2015-01-03"),
                  grp = c("A","A","B","B","C","C"),
                  value = c(10,13,9,15,11,16))
dat$id = datetime_to_timestamp(as.Date(dat$id))

highchart() %>% 
  hc_chart(type = "line") %>% 
  hc_xAxis(categories = dat$id,type = 'datetime',labels = list(format = '{value:%b %d}')) %>%
  hc_add_series_df_tidy(data = dat, group = grp, values = value)
```

If I do something as above, the values don't match the date (id). Do you have any suggestions? Also, the tooltip wasn't able to display `YEAR `correctly.

**Comment by jbkunst** [comment]
In this case I dont recommend use `hc_add_series_df_tidy` because the groups dont share the same x-values. 

In my opinion a good approach is use `hc_add_series_list`:

```
library(highcharter)
library(lubridate) # ymd
library(dplyr) # group_by

dat <- data.frame(id = c("2015-01-01","2015-01-02","2015-01-01","2015-01-03","2015-01-02","2015-01-03"),
                  grp = c("A","A","B","B","C","C"),
                  value = c(10,13,9,15,11,16))

dat$time <- datetime_to_timestamp(ymd(dat$id)) # its easy to convert to a date

head(dat)

series <- dat %>% 
  arrange(time) %>% 
  group_by(name = grp) %>% # we create a series for every category
  do(data = list.parse2(data_frame(.$time, .$value))) %>% # a line chart need IN ORDER the x and y
  list.parse3() # then convert every row in a list preserving names

series


# Now you dont need specify categories
# bc every data has his own xs.

# Yo appear the YEAR you need to specidfi in the 
# format. see http://www.cyberciti.biz/faq/linux-unix-formatting-dates-for-display/

highchart() %>% 
  hc_chart(type = "line") %>% 
  hc_xAxis(type = 'datetime',labels = list(format = '{value:%Y %m %d}')) %>% 
  hc_add_series_list(series)
```

I know the `hc_add_series_list` is not so easy to learn but is SUPER powerful when is used in the correct way ;).

**Comment by terencezzh** [comment]
Hi @jbkunst ,

Sorry for replying late. Thank you very much for your quick response. I do appreciate your detail explanation in the example. Even though I am still learning how to use `hc_add_series_list`, your example could apply for most of my graphs. 

Thanks again.

**Comment by jbkunst** [comment]
Hi @terencezzh 

I've working in a easy way (a tidy way) to chart data frames. No more `hc_add_series_list ` :wink:  . Please check **http://rpubs.com/jbkunst/highcharter-hchart-data-frames**

If you ggplot2 is familiar to you this function can help you a lot.
