### ISSUE TITLE
Feature Request: legendItemClick events

### ISSUE THREAD

**Issue by terencezzh** [jbkunst/highcharter#133]
First thank you very much for creating this package, making us easily create high charts. I love Highcharts but if it is possible, it will be great to have the functionality of legend click events like nvd3 has. Please see this [page ](http://walkerke.github.io/2014/03/tfr-in-europe/)for your reference.

In other words, I am trying to allow select single series by double clicking the legend. I found some JS codes from this SO [page](http://stackoverflow.com/questions/6608410/highcharts-series-want-to-show-hide-all-except-selected-series-reversal-of-de). I picked the second answer since it's much faster than the 1st one. 

```
dat <- data.frame(id = c(1,2,1,2,1,2),
                  grp = c("A","A","B","B","C","C"),
                  value = c(10,13,9,15,11,16))

highchart() %>% 
  hc_chart(type = "line") %>%
  hc_xAxis(categories = dat$id) %>%
  hc_add_series_df_tidy(data = dat, group = grp, values = value)%>%
  hc_plotOptions(
  series = list( 
    events = list(
      legendItemClick = "#! function(e) {
      var hideAllOthers = e.browserEvent.metaKey|| e.browserEvent.ctrlKey;
      if (hideAllOthers) {
      var seriesIndex = this.index;
      var series = this.chart.series;
      for (var i = 0; i < series.length; i++) {
      if (series[i].index === seriesIndex) {
      if (!series[i].visible) series[i].setVisible(true, false);
      } else {
      if (series[i].visible) series[i].setVisible(false, false);
      }
      }
      this.chart.redraw();
      return false;
      }} !#")
    )
  )
```

It should allow me to ctrl+click a legend to select a single series but I will need a reset button as well, which I don't know how to do. Also, above codes are not working (but they work in rCharts), so I am wondering if I did something wrong when I tried to include JS codes using `hc_plotOptions`?

Thank you very much in advance!

**Comment by jbkunst** [comment]
Hi @terencezzh 

Thanks for your kind words.

rCharts works a little different when you want to send js code. In this case (highcharter, htmlwidgets in general) you need write:

```
 legendItemClick = JS("function(e) { .... } ")
```

instead of;


```
 legendItemClick = "#! function(e) { .... } !#")
```

Tell me if this work for you ;).

**Comment by terencezzh** [comment]
Hi @jbkunst ,

Thanks so much for your help. Now the JS codes are working. May I ask you a follow-up question? Do you know how to make a reset button? I have little knowledge of JS, but I tried to work around it by using an action button to re-render the graph. However, it would take a while to re-render if the graph is complex. 

Thanks again.

**Comment by jbkunst** [comment]
Hi @terencezzh !

Do you solve tour last question?

**Comment by chenx2018** [comment]
@jbkunst 
Do you know how to make a reset button from @jbkunst's last question?
