### ISSUE TITLE
weird behavior of xAxis category 

### ISSUE THREAD

**Issue by zhenyiy** [jbkunst/highcharter#135]
Here's the code:
```
library(highcharter)

hc <- highchart() %>%
  hc_chart(type="scatter", zoomType="xy") %>%
  hc_xAxis(type="category", categories=list("a","b","c","d")) %>%
  hc_plotOptions(
    scatter=list(marker=list(radius=3))
  ) %>% 
  hc_add_series_scatter(x=1:4, y =1:4) 

hc
```
The xAxis of the graph creates starts from b instead of a. Is it a bug or is there something wrong with my code? Thanks.
![image](https://cloud.githubusercontent.com/assets/4512771/16493041/1445a8c0-3eb2-11e6-8922-f2b403bd75e7.png)

**Comment by jbkunst** [comment]
Hi @zhenyiy 

Is not a bug, there's nothing wrong with your code, the problem is javascript XD, nah. Javascript count start at **0**, so you need to change:

```
hc_add_series_scatter(x=1:4, y =1:4) 
```

by

```
hc_add_series_scatter(x=1:4-1, y =1:4) 
```
