### ISSUE TITLE
Enable `row` and `column` mappings in highchart grid

### ISSUE THREAD

**Issue by Yang-Tang** [jbkunst/highcharter#139]
It's really cool to enable ggplot2-like aesthetic mappings in `hc_add_series_df`. I'm wondering if it possible to further enable mapping `grid_row` and `grid_column` (maybe through `hw_grid`) in this function? Just like what the `facet_grid` do in ggplot2.

**Comment by jbkunst** [comment]
Yep, `facet_grid`is one the most greatest freatures in ggplot2. I think its possible but I need some time to figure what is a good approach. If you have some ideas just share here ;).
