### ISSUE TITLE
Can't replicate hchart examples from the site

### ISSUE THREAD

**Issue by tbenschop** [jbkunst/highcharter#144]
Hi @jbkunst 

I'm on highcharter version 0.3.1.9999 and I can replicate the `hchart` examples from here: http://jkunst.com/highcharter/hchart.html for example this one:
`mpgman2 <- count(mpg, manufacturer, year)
hchart(mpgman2, "column", x = manufacturer, y = n, group = year)`
gives me the error:
`Error: Objects of class/type grouped_df/tbl_df/tbl/data.frame are not supported by hchart (yet).`

Am I doing something wrong? Thanks, Tim

**Comment by jbkunst** [comment]
Hi @tbenschop,

That's why at the bottom of the site says 

> Generated 2016/07 using highcharter **0.4.0**

:wink:

**Comment by tbenschop** [comment]
@jbkunst Oh... My apologies. I immediately update!

**Comment by tbenschop** [comment]
@jbkunst 
Sorry for my amateurism regarding the highcharts.... But how should I use the highcharts api with `hchart()` I want for example a stacked barchart like http://www.highcharts.com/demo/column-stacked Is there documentation on how to do that? Or any standard procedure?

**Comment by jbkunst** [comment]
I guess you check the **options** in the link you show me. right, check the `plotOptions` part then you realize that if you have already the colum in the first example, now you need change the options to show a stacked bar instead of the *default* one, something like:

```
hchart(.... code to have bars side by side) %>%
  hc_plotOptions(colum = list(stacking: 'normal'))
```

I dont tested yet but I have this produce what you want.

**Comment by tbenschop** [comment]
Thanks, changing colum to column and stacking :'normal' to stacking = normal seems to work. Last question/comment: I get the ugly 0.00000000000000000000001 in this plot:

`x<-data.table(Measure=seq(from=0,to=.2,by=.01),
              value=seq(from=0,to=.2,by=.01),variable=c(as.character(seq(from=0,to=.2,by=.01))))
hchart(x, type = "column", x = Measure, y = value, group = variable,stackedLabels=T)%>%
hc_title(text='ja')  %>%
hc_plotOptions(column = list(stacking = 'normal'))`

Is that a bug? I also noticed that in the `rCharts` package.

**Comment by jbkunst** [comment]
Please, try tu format the code you put in the issue!

**Comment by jbkunst** [comment]
It's a highcharts issue, but I think this is due a you try to put numeric values in a `column` chart.

**Comment by d8aninja** [comment]
Should I be getting this same error if I am using v0.5?

```
> t <- out %>%
+     dplyr::group_by(Date, direction) %>%
+     dplyr::mutate(count = sum(as.numeric(n_flows))) %>%
+     dplyr::ungroup() %>%
+     dplyr::select(Date, direction, count) %>%
+     dplyr::arrange(Date, direction) %>% 
+     unique()
> t <- as.xts(t[, c("direction", "count")], t$Date)
> t
           direction   count
2017-03-23         0 4021754
2017-03-23         1 7928404
2017-03-23         2   20086
2017-03-23         3 4824600
2017-03-24         0 1339778
2017-03-24         1 3101010
2017-03-24         2    7392
2017-03-24         3 1881550
```

But then,

```
> hchart(
+         data = t, 
+         # type = input$nf_plot_type,
+         type = 'scatter',
+         hcaes(
+           x = Date, 
+           y = count))
Error: Objects of class/type hcaes/uneval are not supported by hchart (yet).
```

**Comment by jbkunst** [comment]
Hi Jeff @d8aninja 

`hcaes` is **only** used if the `data` argument is a `data.frame`, so avoid the `t <- as.xts(...`  and try again ;)

**Comment by d8aninja** [comment]
I will eventually be doing forecasting with that object though - don't I need `xts`?

**Comment by jbkunst** [comment]
You can add the forecast (objects) later using `hc_add_series(forecast, addOriginal = FALSE)`

If we can work with a _minimal reproducible_ it would be great.

**Comment by d8aninja** [comment]
Working on one now - confirm for me that I can pass factors for the groups / names to hc_add_series if the data object is a `forecast` one?
