### ISSUE TITLE
 Error: object ‘has_name’ is not exported by 'namespace:tibble' 

### ISSUE THREAD

**Issue by jwinter6** [jbkunst/highcharter#149]
Hi,
just a quick notice that a recent install from GitHub will lead to the following error:

` Error: object ‘has_name’ is not exported by 'namespace:tibble' `

cheers
Jan

**Comment by jbkunst** [comment]
Hi Jan @jwinter6 ,

Try to update the tibble package.

Let me know if this helps.

**Comment by jwinter6** [comment]
Hi,
just installed it before, was the latest version :)
Nevertheless I tried the following again:
I  removed it and installed it again, this time from github instead of CRAN.
Same problem :(
I then installed highcharter again from CRAN -> this works.
Then I did the same for the github version (force=TRUE) and now it works, THANKS :)

problem solved :)

**Comment by jbkunst** [comment]
Nice! Thanks for test!
