### ISSUE TITLE
Error in UseMethod("Select_") with hchart on other laptop.

### ISSUE THREAD

**Issue by tbenschop** [jbkunst/highcharter#150]
Hello @jbkunst 

The `hchart` functions works well on my private laptop. But when I want to use it on a company laptop, highly protected, I get the following error: `Error in UseMethod("select_") : 
  no applicable method for 'select_' applied to an object of class "NULL"`
Does this ring a bell? highcharter v.0.3.1.9999 (or something like that) worked just fine on that laptop.
I tried this example:
`x<-data.table(Measure=seq(from=0,to=.2,by=.01),  value=seq(from=0,to=.2,by=.01),variable=c(as.character(seq(from=0,to=.2,by=.01))))`

`hchart(x, type = "column", x = Measure, y = value, group = variable)`

**Comment by jbkunst** [comment]
Do you update the package?

**Comment by tbenschop** [comment]
@jbkunst Yes:
`> packageVersion('highcharter')
[1] ‘0.4.0’
>  x<-data.table(Measure=seq(from=0,to=.2,by=.01), value=seq(from=0,to=.2,by=.01),variable=c(as.character(seq(from=0,to=.2,by=.01)))) 
>  hchart(x, type = "column", x = Measure, y = value, group = variable)
Error in UseMethod("select_") : 
  no applicable method for 'select_' applied to an object of class "NULL"`

**Comment by jbkunst** [comment]
Can you print your `sessionInfo()`? I'm not sure what can be. Can you update all the packages in that laptop? Starting with dplyr and, tibble?

**Comment by tbenschop** [comment]
Updating dplyr and tibble solved it, thanks. Next time I'll update all packages highcharter depends on. Apologies again.

**Comment by jbkunst** [comment]
No problem! ;)

**Comment by tbenschop** [comment]
Hi @jbkunst 
We are moving some code to a production server that only has ``dplyr`` version ``0.4.3.`` and they don't want to update.... Is there a workaround to get the hchart function working:
``hchart(data.table(Message='This graph is not applicable for this selection'), "treemap", x = Message, value = 1)`` with dplyr v0.4.3

**Comment by jbkunst** [comment]
Session info please! ;)

**Comment by tbenschop** [comment]
```
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.7 (Santiago)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] data.table_1.9.6  highcharter_0.4.0

loaded via a namespace (and not attached):
 [1] igraph_1.0.1      Rcpp_0.12.5       magrittr_1.5      mnormt_1.5-4
 [5] viridisLite_0.1.3 lattice_0.20-33   R6_2.1.2          TTR_0.23-1
 [9] stringr_1.0.0     plyr_1.8.4        dplyr_0.4.3       xts_0.9-7
[13] tools_3.3.1       quantmod_0.4-5    parallel_3.3.1    grid_3.3.1
[17] broom_0.4.1       nlme_3.1-128      psych_1.6.9       DBI_0.4-1
[21] htmltools_0.3.5   lazyeval_0.2.0    assertthat_0.1    digest_0.6.9
[25] tibble_1.2        purrr_0.2.2       reshape2_1.4.1    tidyr_0.5.1
[29] htmlwidgets_0.6   rlist_0.4.6.1     stringi_1.1.1     jsonlite_0.9.22
[33] lubridate_1.5.6   chron_2.3-47      foreign_0.8-66    zoo_1.7-13

```

**Comment by jbkunst** [comment]
What is the error? Not sure if this is a dplyr problem

**Comment by tbenschop** [comment]
```
> hchart(data.table(Message='This graph is not applicable for this selection'), "treemap", x = Message, value = 1)
Error in UseMethod("select_") :
  no applicable method for 'select_' applied to an object of class "NULL"

```

**Comment by jbkunst** [comment]
Sorry, I forgot the title! 

Mmm... did you try:

```r
 hchart(data.table(Message='This graph is not applicable for this selection', value = 1), "treemap", x = Message, value = value)?
```

**Comment by tbenschop** [comment]
@jbkunst Thanks, no luck unfort.:
```
hchart(data.table(Message='This graph is not applicable for this selection', value = 1), "treemap", x = Message, value = value)
Error in UseMethod("select_") :
  no applicable method for 'select_' applied to an object of class "NULL"
```

**Comment by jbkunst** [comment]
Sorry, for ask some tries. But did you test the development version?  I test this and it work.

```r
hchart(data.frame(Message='This graph is not applicable for this selection'), "treemap", hcaes(x = Message, value = 1))
```

**Comment by tbenschop** [comment]
No, we are limited in using ``highcharter`` 0.4.0...

**Comment by Yang-Tang** [comment]
@tbenschop Is it a shiny app? I think you can solve the issue by adding a folder containing newer version of packages in the shiny app dir, and add some code to detach old packages and load new packages before starting shiny.

**Comment by tbenschop** [comment]
Thanks, unfortunately I can't place files on the server, I only can change the r code. So I need to find a workaround to get the hchart working without new package versions... @jbkunst is there a way to rewrite the hchart or any other bypass? I would like to prevent the option to rewrite the charts without using the hchart shortcut...

**Comment by jbkunst** [comment]
`hchart` is kind of _experimental_ (in 0.4.0) shortcut, and as a shorcut is not __that__ robust or clear as write/code the explicit chart what you want using the API. Being that said I recommend you write the chart using the `hc_add_series` and friend to get the chart. I guess this is possible between the requirements.

**Comment by tbenschop** [comment]
@jbkunst Thanks! I'm just pushing them to get us the latest dplyr version.

**Comment by jbkunst** [comment]
I'm not sure if this about dplyr version; surely/maybe is a highcharter bug. Hope this work! Good luck.
