### ISSUE TITLE
Q: How to implement column chart with groupings?

### ISSUE THREAD

**Issue by bogdanrau** [jbkunst/highcharter#156]
Hi @jbkunst,

I'm about 99.9% certain that this question is beyond basic, but I've exhausted all remaining ideas. I'm trying to get column groupings to work and can't seem to make it stick. What I'm trying to do is the following:

```
# Sample data
data <- data.frame(year = c(2011,2011,2012,2012,2013,2013),
                   percent = c(10,12,13,12,13,14),
                   label = c("ONE", "TWO", "ONE", "TWO", "ONE", "TWO"))

# This works as intended
hchart(data, "column", x = label, y = percent, group = year)

# I need to use highchart() instead of hchart() for further customizations, but I can't figure out how to get the grouping to work as well.
highchart() %>%
  hc_xAxis(categories = data$label) %>%
  hc_add_series(data = data$percent, type = "column") 
```

Any insight on how to get groupings to work? I need to show error bars on each (coming from another column), which would likely be another hc_add_series...but I need to group them by year and by label first.

Thank you!

Bogdan

**Comment by Yang-Tang** [comment]
You can first process your data into a list that group by year, and then send it to `hc_add_series_list()`:
```r
library(dplyr)

data <- data.frame(year = c(2011,2011,2012,2012,2013,2013),
                   percent = c(10,12,13,12,13,14),
                   label = c("ONE", "TWO", "ONE", "TWO", "ONE", "TWO"))

data_lst <- data %>% 
  group_by(year) %>% 
  do(data = list.parse2(.[, c('label', 'percent')])) %>% 
  rename(name = year) %>% 
  mutate(type = 'column') %>% 
  list.parse3()

highchart() %>%
  hc_xAxis(categories = data$label) %>%
  hc_add_series_list(data_lst)
```

**Comment by bogdanrau** [comment]
Thank you for the suggestion @Yang-Tang! It seems like this solution is order-dependent. For example, running your suggestion results in an expected graph. However, switching the label categories around will shuffle the columns around:

```
data <- data.frame(year = c(2011,2011,2012,2012,2013,2013),
                   percent = c(10,12,13,12,13,14),
                   label = c("ONE", "ONE", "TWO", "TWO", "THREE", "THREE"))
###### Notice the label column above is ordered differently

data_lst <- data %>% 
    group_by(year) %>% 
    do(data = list.parse2(.[, c('label', 'percent')])) %>% 
    rename(name = year) %>% 
    mutate(type = 'column') %>% 
    list.parse3()

highchart() %>%
    hc_xAxis(categories = data$label) %>%
    hc_add_series_list(data_lst)
```
 Any insight? Happy to take this to stackoverflow if you want to keep your issues list clear of non-issues. 

Thanks again for your help guys!

Bogdan

**Comment by Yang-Tang** [comment]
You are right @bogdanrau . I guess when using `hc_xAxis(categories = data$label)`, highchart only take the first two items of `data$label` and set them as x axis labels, because there are only two data points in each group.

**Comment by d8amonk** [comment]
Trying to better understand last answer; I have hc_xAxis set to an hourly category, and hc_yAxis set to a count of flows (which I set with `data` in hc_add_series).  Problem is there are multiple obs per (direction) category for each hour, so as it is right now I have an hc_xAxis that has "1 1 1 1 1 2 2 2 2 3 3 3 3 3 ...." for the time across X axis. Futhermore,  the hover tip is showing its "X" as its ID, not it's "hour" value....Very confused.

**Comment by d8amonk** [comment]
What I'm looking for, given by ggplot: 

```
output$flows_plot <- renderPlot({
    ggplot(data = data.frame(frm())) +
      facet_grid(factor(isEncrypted) ~ factor(direction), scales = 'free') +
      ggthemes::theme_fivethirtyeight(base_size = 14) +
      stat_summary(aes(x = updatedTimeHour, y = n_flows, color = factor(direction)), 
                   # color = 'black', 
                   alpha = 0.6,
                   fun.y = function(x) sum(x), 
                   geom = "line") +
      scale_y_continuous(labels=function(x) x/1000000) +
      labs(
        x = 'Hour of Day', 
        y = 'Flows (Millions)',
        title = paste(sprintf('Number of Flows, by Hour [Encrypted X Direction]'))
      )
  })

```
