### ISSUE TITLE
y axis range 

### ISSUE THREAD

**Issue by haohua** [jbkunst/highcharter#157]
Hi, 

Thank you for the great package. 

I am wondering how can I set a ylim/xlim for the highcharts. 
highchart() %>% 
  hc_add_series_boxplot(x = iris$Sepal.Length, by = iris$Species, name = "length") 
can you help me to add some ylim/xlim here?

thanks
andy

**Comment by Yang-Tang** [comment]
I think you can use `hc_xAxis(max = x_max, min = x_min)` and `hc_yAxis(max = y_max, min = y_min)` to set xlim/ylim here, and there are much more highcharts axis options. You can find them [here](http://api.highcharts.com/highcharts#yAxis).

**Comment by haohua** [comment]
Thank you so much. It works perfect.
