### ISSUE TITLE
is there an issue with the latest highcharter cran(cran.rstudio) repository?

### ISSUE THREAD

**Issue by kickbox** [jbkunst/highcharter#159]
After installation, when I try to load the package, I get the following error 

```
library(highcharter)
Error : object ‘has_name’ is not exported by 'namespace:tibble'
Error: package or namespace load failed for ‘highcharter’
```

**Comment by jbkunst** [comment]
Hi @kickbox ,

Try to update/install the last versión of tibble package.

**Comment by andreasiversen** [comment]
@jbkunst updating tibble package worked! thanks :)

**Comment by jbkunst** [comment]
:D nice! thanks for the reply!
