### ISSUE TITLE
Improve performance through boost.js

### ISSUE THREAD

**Issue by nuno-agostinho** [jbkunst/highcharter#160]
Hey @jbkunst, I noticed you tried to implement [boost.js module](http://www.highcharts.com/news/175-highcharts-performance-boost) in the past (https://github.com/jbkunst/highcharter/issues/43), but it seems the function `highcharts2` is not currently working.

As I need to plot thousands of points, I would love to have this working. Do you happen to know what's needed for this to work? If you need, I can help. 😄

**Comment by jbkunst** [comment]
Hi @nuno-agostinho.

It seems I forgot update the yaml for highchart2 when I updated the highcharts version. Can you try and tell me if now works for you? :grin:

**Comment by hsy9045** [comment]
Hi @jbkunst  I must be missing something too. As an minimal example, what should I change in the following with highchart2 to make it work? Getting "Error: The theme used is not from hc_theme class"
```R
data(citytemp)

hc <- highchart2() %>% 
  hc_xAxis(categories = citytemp$month) %>% 
  hc_add_series(name = "Tokyo", data = citytemp$tokyo) %>% 
  hc_add_series(name = "London", data = citytemp$london) %>% 
  hc_add_series(name = "Other city",
                data = (citytemp$tokyo + citytemp$london)/2)

hc
```

**Comment by jbkunst** [comment]
Hi @hsy9045 !

Can you download the github version again and check please? Thanks!

**Comment by hsy9045** [comment]
Thanks @jbkunst for the prompt update! The new version works fine with highchart2(). However it seems to break the original highchart(). Running the same example with highchart() gave me this error:

Error in eval(expr, envir, enclos) : 
  could not find function ".is_highchart"

**Comment by hsy9045** [comment]
Never mind. My bad. It's all good now. Thank you!

**Comment by hsy9045** [comment]
Does this work with shiny? I am getting a blank plot using highchart2: 
```R
shiny::shinyApp(
  ui = fluidPage(
    h6('Chart'),
    highchartOutput('mychart'),
    h6('Chart2'),
    highchartOutput('mychart2')
  ),
  server = shinyServer(function(input,output){
    
           output$mychart = renderHighchart({
           data(citytemp)
           
           hc <- highchart() %>% 
             hc_xAxis(categories = citytemp$month) %>% 
             hc_add_series(name = "Tokyo", data = citytemp$tokyo) %>% 
             hc_add_series(name = "London", data = citytemp$london) %>% 
             hc_add_series(name = "Other city",
                           data = (citytemp$tokyo + citytemp$london)/2)
           
           hc
           })
           output$mychart2 = renderHighchart({
             data(citytemp)
             
             hc <- highchart2() %>% 
               hc_xAxis(categories = citytemp$month) %>% 
               hc_add_series(name = "Tokyo", data = citytemp$tokyo) %>% 
               hc_add_series(name = "London", data = citytemp$london) %>% 
               hc_add_series(name = "Other city",
                             data = (citytemp$tokyo + citytemp$london)/2)
             
             hc
           })
}))

```

**Comment by jbkunst** [comment]
Hi @hsy9045 

Sorry for the issue..

1. First of all, I've never coded the render and output function for the highchart2 (boost pluging) widget. But, I update a version (3834dead375e0b730aed8f3e862900c44c06390d) with `renderHighchart2` and `highchartOutput2` which works with `highchart2`.

2. You can use highcharts and highchart2 in the same app (in the same tab, but you can show them both using `iframe`s) because highchart uses highstock.js, and the boost module works only with highcharts.js thats why I implemented two widgets.

I hope this clear the doubts. If you have more question just let me know ;).

Bests,

**Comment by hsy9045** [comment]
Thank you for the clarification! Really appreciate the help here.

**Comment by jbkunst** [comment]
You're welcome. Note I edited the previous comment. it is: *you __can't:__ use*
