### ISSUE TITLE
Consider using HTMLWidgets.dataframeToD3()

### ISSUE THREAD

**Issue by joh024** [jbkunst/highcharter#161]
See: http://www.htmlwidgets.org/develop_advanced.html#htmlwidgets.dataframetod3

`htmlwidgets` converts data frames to "long" form:
```JSON
{
  "Sepal.Length": [5.1, 4.9, 4.7],
  "Sepal.Width": [3.5, 3, 3.2],
  "Petal.Length": [1.4, 1.4, 1.3],
  "Petal.Width": [0.2, 0.2, 0.2],
  "Species": ["setosa", "setosa", "setosa"]
} 
```

While highcharts wants data in "wide" form:
```JSON
[
  {
    "Sepal.Length": 5.1,
    "Sepal.Width": 3.5,
    "Petal.Length": 1.4,
    "Petal.Width": 0.2,
    "Species": "setosa"
  },
  {
    "Sepal.Length": 4.9,
    "Sepal.Width": 3,
    "Petal.Length": 1.4,
    "Petal.Width": 0.2,
    "Species": "setosa"
  },
  {
    "Sepal.Length": 4.7,
    "Sepal.Width": 3.2,
    "Petal.Length": 1.3,
    "Petal.Width": 0.2,
    "Species": "setosa"
  }
] 
```

As I don't believe there's ever a case where highcharts wants series data in "long" form, using `HTMLWidgets.dataframeToD3()` would make it possible to simply pass regular R dataframes as data, and forego all the list parsing that's currently required.

**Comment by jbkunst** [comment]
Hi @joh024 

I'm aware about the `HTMLWidgets.dataframeToD3()` function ;).

Actually, You can pass data frame to hchart function.  http://rpubs.com/jbkunst/highcharter-hchart-data-frames . Is this what you want? 

Disclaimer: First of all, at the beggining I wanted to have all the functionalities of the highcharts API, thats why all is a list oriented, I know this may be not R user firendly but usually the wrappers lose some functionalities imo. Then, thinking in the useRs I created `hchart`  and other shortcuts to chart data frames and others usual R objects.

**Comment by joh024** [comment]
If you know about it and are choosing not to use it, that's fine and your decision to make. I just thought it might be a better solution than the list parsing that's currently done.

**Comment by jbkunst** [comment]
I see your point but for me it's easier done the parsing and the data manupilation in R. Thanks for the recommendation :wink:
