### ISSUE TITLE
Legend Order

### ISSUE THREAD

**Issue by terencezzh** [jbkunst/highcharter#162]
Hi @jbkunst ,

Thanks for creating this fantastic package. I am converting from rCharts to highcharter. Do you know how to re-order the legend order? 

In rCharts, I will need something like:
`legendOrderTable = data.frame(variable = c("L1","L2","L3"),
                                                    rank = c(2,1,3))`

`h1$params$series <- lapply(h1$params$series, function(d){`
      `d$legendIndex = legendOrderTable [variable == d$name]$rank`
     ` return(d)
})`

I am wondering if I can do something similar in highcharter. 

Thanks.

**Comment by jbkunst** [comment]
Hi @terencezzh ,

Yep, you can do a similar thing. In your code your access to the data vía `h1$params$series`, in highcharter you do `h1$x$series`.

Hope this helps! :wink:

**Comment by terencezzh** [comment]
Thank you so much. It works perfectly.
