### ISSUE TITLE
hc_get_colors()

### ISSUE THREAD

**Issue by marcoblume** [jbkunst/highcharter#163]
Hi,

I was trying to replicate the diagram from the example section: http://jkunst.com/highcharter/highcharts.html.
```
library(highcharter)
rainfall <- c(49.9, 71.5, 106.4, 129.2, 144, 176,
              135.6, 148.5, 216.4, 194.1, 95.6, 54.4)

temperature <- c(7, 6.9, 9.5, 14.5, 18.2, 21.5,
                 25.2, 26.5, 23.3, 18.3, 13.9, 9.6)

col1 <- hc_get_colors()[3]
col2 <- hc_get_colors()[2]
```

but it seems that hc_get_colors() is not included in the package anymore. 

```
> packageVersion("highcharter")
[1] ‘0.4.0’
```

Thanks,

Marco

**Comment by jbkunst** [comment]
Hi @marcoblume 

Sorry, but in highcharter v0.4.0 there's no `hc_get_colors` function due I want all `hc_*` functions to be api related, and `hc_get_colors` return default highcharts colors.

You can use:

```
col1 <- "#90ED7D"
col2 <- "#5C5C61"
```
Sorry for the issue. Tell me if this work for you. Thanks!
