### ISSUE TITLE
stack column chart: mismatch

### ISSUE THREAD

**Issue by terencezzh** [jbkunst/highcharter#165]
Hi @jbkunst ,

I am trying to create a stack column chart but the data is mismatched. Please see below sample:

`data1 <- data.frame(`
`people = c("A","A","B","B","C","C"),`
                  ` value = c(6,8,11,5,9,7),`
                   `label = c("ONE", "TWO","ONE", "THREE","TWO", "THREE"))`

`hchart(data1, "column",x = people, y = value, group = label)%>%hc_plotOptions(column = list(stacking = "normal"))`

The graph is supposed to have three columns and each column has two data points stacking together. I am wondering if I use hchart inproperly? 

In rCharts, I will do something like:
`Plot1 <- hPlot(value~people, data = data1, `
              ` group = "label", `
              ` type = "column")`
`Plot1$plotOptions(column = list(stacking = "normal"))`
`Plot1`

Thank you very much in advance!

**Comment by jbkunst** [comment]
Hi @terencezzh,

In the `rCharts` version, where is C category? In the highcharter version I have the 3 categories with 2 values as you said.

Highcharter try to get similar result to ggplot2. Check: 
```
library(ggplot2)

ggplot(data1) +
  geom_bar(aes(x = people, y = value, fill = label), stat = "identity")

# which have the same result in highcharter (3 colums with 2 values each)
hchart(data1, "column",x = people, y = value, group = label) %>%
  hc_plotOptions(column = list(stacking = "normal"))
```

I don't see the problem yet. Can you show some examples in rpubs?

**Comment by terencezzh** [comment]
Hi @jbkunst,

Thanks for your quick response. Yes, the plot generated by ggplot2 is what I am looking for. I don't know why I am getting a different graph in highcharter. Please see blow:
http://rpubs.com/terencezzh/highchart1

I am using highcharter of version 0.4.0 (from CRAN).

Do you have any ideas?

**Comment by terencezzh** [comment]
I just tried to download highcharter from GitHub and it works. I guess there may be something wrong in CRAN's version?

**Comment by jbkunst** [comment]
Not sure. :/ yet.
