### ISSUE TITLE
Make "hc_annotations" accept multiple arguments

### ISSUE THREAD

**Issue by Yang-Tang** [jbkunst/highcharter#171]
Currently `hc_annotations` only accept a list of options as arguments:

``` r
highchart() %>% 
  hc_title(text = 'Title', align = 'right') %>% 
  hc_add_series(data = list(29.9, 71.5, 106.4, 129.2, 144.0, 176.0)) %>% 
  hc_annotations(list(xValue = 4, yValue = 125, title = list(text = 'Annotated chart!')))
```

To make it consistent with other `hc_*` functions like `hc_title` and `hc_add_series`, I think it's better to add  `hc_add_annotations` function that accept multiple arguments like this:

``` r
highchart() %>% 
  hc_title(text = 'Title', align = 'right') %>% 
  hc_add_series(data = list(29.9, 71.5, 106.4, 129.2, 144.0, 176.0)) %>% 
  hc_add_annotations(xValue = 4, yValue = 125, title = list(text = 'Annotated chart!'))
```

**Comment by jbkunst** [comment]
Hi @Yang-Tang ,

Oops. Let me check.

**Comment by jbkunst** [comment]
Hi @Yang-Tang 

3 month later and I can check this issue :(.

Sorry for late but I think you are right, You can't add multiples annotations either. I'll come with updates soons. Thanks!

**Comment by jbkunst** [comment]
Closed in 37d77596cc19eaa6a322a58bd1629397db15856d

**Comment by jbkunst** [comment]
The added functions are:

`hc_add_anotation(hc, xValue = "asda", title = list(text = "asda))`

`hc_add_annotations(hc, x)`

**Comment by Yang-Tang** [comment]
@jbkunst That's great! Thank you for the fix. Looking forward to the new v0.5.0 version :)
