### ISSUE TITLE
Add parameters to the documentation/theme used is not from hc_theme class

### ISSUE THREAD

**Issue by pgensler** [jbkunst/highcharter#172]
Hello,

As I was looking at the documentation for the hc_chart method, I noticed that there really was nothing defined, which makes it very hard to understand if I can even pass in a dataframe into the method, along with other paramters like x, y, group, etc(which are listed on your examples) page. 

I am trying to create a bar chart similar to this example on your website:

```
mpgman2 <- count(mpg, class, year)
hchart(mpgman2, "column", x = class, y = n, group = year)

```

However, when I try to create a bar chart using my data, it gives me the error:
I'm not really trying to use the specific API stuff like hc_add_series or hc_xAxis to create my graph if possibble. Below is my code:

  ```
Category <- c("Furniture","Furniture","Furniture","Furniture",
                "Office Supplies","Office Supplies", "Office Supplies", "Office Supplies",
                "Office Supplies", "Office Supplies", "Office Supplies", "Office Supplies",
                "Office Supplies", "Technology","Technology","Technology","Technology"),
  SubCategory <- c("Bookcases","Chairs","Furnishings","Tables","Appliances","Art","Binders","Envelopes", 
                   "Fasteners","Labels","Paper","Storage",  "Supplies", "Accessories","Copiers","Machines",
                   "Phones"),
  sales <- c(889222.51,920892.65,239840.16,445823.93,614737.91,225594.68,281494.68,104903.88,50156.06,44269.30,
             150113.36,692903.08,152196.19,463383.33,965899.78,458655.43,1005525.38)
mydf <- data.frame(Category,SubCategory,sales)
hc <- hc_chart(mydf, "bar", x = Category, y = sales, group = SubCategory)
Error: The theme used is not from hc_theme class

```

**Comment by jbkunst** [comment]
Hi @pgensler ,

In your example you used the `hc_chart` instead of `hchart` function. Can you retry and tell me if this work for you?

**Comment by pgensler** [comment]
This works, but it's not really producing the plot I would like. I'd like to color based on Category, but group based on SubCategory. This is an example of the chart I'd like in Tableau, but I haven't quite got it with high charts.
![grouped-barchart](https://cloud.githubusercontent.com/assets/7308115/18036549/04148a3e-6d33-11e6-8794-96ac817724fd.png)

**Comment by pgensler** [comment]
This is what I have so far, but the coloring is not really working....thoughts?
test <- hchart(mydf, "bar", x = SubCategory, y = sales, group = Category, color = SubCategory)

![image](https://cloud.githubusercontent.com/assets/7308115/18036861/782bb05c-6d3b-11e6-9e31-d3f9effd8e71.png)

**Comment by jbkunst** [comment]
Hi @pgensler ,

Sorry for the late response. This chart it's possible but you need to do manually becuase is not a standar chart for highcharts, futhermore need a pluging http://www.highcharts.com/plugin-registry/single/11/Grouped-Categories for group categories, like you need.

```
library(highcharter) # chart
library(purrr)           # map function to make grouped categories argument
library(dplyr)           # for select function 
library(htmltools)   # to add the dependencies, like the plugin what we'll use.

mydf <- data.frame(Category,SubCategory,sales, color = colorize(Category))

categories_grouped <- map(unique(Category), function(x){
  list(
    name = x,
    categories = SubCategory[Category == x]
  )
})


hc <- highchart() %>% 
  hc_chart(type = "bar") %>% 
  hc_xAxis(categories = categories_grouped) %>% 
  hc_add_series(data = list_parse(select(mydf, y = sales, color = color)),
                showInLegend = FALSE)

hc

# adding the pluging. Probably in the future this will not be
# necessary becuase I'll add this as default in highcharter
dep <-  htmlDependency(
  name = "grouped-categories",
  version = "1.1.0",
  src = c(
    href = "http://blacklabel.github.io/grouped_categories"
  ),
  stylesheet = "css/styles.css",
  script = "grouped-categories.js"
)

hc$dependencies <- c(hc$dependencies, list(dep))

hc

```
http://rpubs.com/jbkunst/highcharter-issue-172

![image](https://cloud.githubusercontent.com/assets/56481/18796371/4f6c9cee-819f-11e6-9650-d4d6305dbf4e.png)

**Comment by pgensler** [comment]
Thanks for your answer, I appreciate it. I'm pretty new to interactive plots, but why do we need to piece apart the chart with hc_chart, hc_xaxis, and so forth? Why do I need to define my own grouping function with purr, and pass it into hc? Shouldn't that be what the group function or color is supposed to do?? I'd like to see some clarity on what the difference between using the API to construct the graph from the ground up vs using the regular syntax with hc_chart, as reading the documentation is very bare bones. I'd love to try and help with revamping the documentation, but just seems like some complex code for a simple plot.

**Comment by jbkunst** [comment]
You're welcome.

Highcharter is mainly the higcharts API plus some shortcuts to chart R objects.

As I said this is not a standar plot for highcharts (try to find something similar in www.highcharts.com/demo), that's why exists this pluging for create grouped categories. Why you need purrr? Because to use this pluging the groups needs to be as a nested list (you can do the same with lapply)

About the simple plot, that's relative, try to do this plot in standar base R graphics functions or ggplot in one line. Obvisouly you can make look simple this chart if we wrap in a function ;).

Finally, not sure if you are meaning hchart (generic funcition) when you said hc_chart (highcharts API related) 

https://cran.r-project.org/web/packages/highcharter/vignettes/replicating-highcharts-demos.html

**Comment by zac-garland** [comment]
Hi @jbkunst,

Is there any way to make this method work for a heatmap with the same subcategory's but different groups? When I attempt to do this it combines the subcategory values rather than recognizing it as groups. 

Simple reprex:

```
library(gapminder)
library(janitor)
library(highcharter)
library(tidyverse)

data <- gapminder::gapminder %>%
  mutate(country = as.character(country)) %>%
  filter(country %in% c("China", "United States", "India", "France")) %>%
  janitor::clean_names() %>%
  mutate_at(vars(life_exp:gdp_percap), funs(percent_rank)) %>%
  select(-continent) %>%
  gather(name, value, -(1:2))

grouped_cat <- data %>%
  distinct(country, name) %>%
  split(.$country) %>%
  map(~ {
    list(name = unique(.x$country), categories = unique(.x$name))
  }) %>%
  setNames(rep(NULL, length(.)))

data %>%
  hchart("heatmap", hcaes(
    x = year, y = name, value = year,
    group = country
  )) %>%
  hc_yAxis(categories = grouped_cat)
```
