### ISSUE TITLE
Single bar in a barchart leads to `hc_xAxis(category="Bar Name")` truncation unless a list is given

### ISSUE THREAD

**Issue by martinjhnhadley** [jbkunst/highcharter#173]
When used in a shiny app a highcharter bar chart may reasonably only have one series, and one category - which could be visualised as follows

```r
highchart() %>%
  hc_chart(type = "bar") %>%
  hc_xAxis(categories = "Bar Label") %>%
  hc_add_series(name = "Number of Things", data = 5)
```

But the label on the x axis has been truncated!

![image](https://cloud.githubusercontent.com/assets/9363263/18127133/5ca340ba-6f76-11e6-826e-a12c18289b76.png)

To fix this, the categories must be provided as a list:

```r
highchart() %>%
  hc_chart(type = "bar") %>%
  hc_xAxis(categories = list("Bar Label")) %>%
  hc_add_series(name = "Number of Things", data = 5)
```

![image](https://cloud.githubusercontent.com/assets/9363263/18127149/75b38bfa-6f76-11e6-82cc-b6d4f86ee59a.png)

As categories (and all?) options can be provided as lists, is it a sensible change to coerce everything to a list before handing over to highchart.js?

**Comment by jbkunst** [comment]
Hi @martinjhnhadley ,

This is a know behavior due `jsonlite` package and default options in `htmlwidgets` package related with the `auto_unbox` parameter and how the R lists are coverted o json data structure when the data is of length 1. 

There's  information in #155, #65 and #71.

I'll close the issue but we can keep the conversation if you have more doubts ;).

Have a nice day.

**Comment by martinjhnhadley** [comment]
Totally failed to spot these issues when I glanced through the repo - thanks for very comprehensive reply considering you've already answered this before :)
