### ISSUE TITLE
useUTC argument is not available

### ISSUE THREAD

**Issue by zhangyan715** [jbkunst/highcharter#174]
there is no change whether useUTC is true or false

here is the code:

highchart(debug=T,hc_opts = list(global=list(useUTC=F)))%>%hc_chart(type="spline",animation=JS("Highcharts.svg"),marginRight=10,events=list(load=JS("function () {
                        var series = this.series[0];
                        setInterval(function () {
                            var x = (new Date()).getTime(), // current time
                                y = Math.random();
                            series.addPoint([x, y], true, true);
                        }, 1000);
                    }")))%>%hc_xAxis(type='datetime',tickPixelInterval=150)%>%
  hc_yAxis(title=list(text='Value'))%>%hc_tooltip(firmatter=JS("function () {
                    return '<b>' + this.series.name + '</b><br/>' +
                                                               Highcharts.dateFormat('%Y-%m-%d %H:%M:%S', this.x) + '<br/>' +
                                                               Highcharts.numberFormat(this.y, 2);
                                                               }"))%>%hc_exporting(enabled=T)%>%hc_legend(enabled=T)%>%
  hc_add_series(name="PV",data=JS("(function () {var data = [],
                                time = (new Date()).getTime(),
                                i;
                                for (i = -19; i <= 0; i += 1) {
                                data.push({
                                x: time + i * 1000,
                                y: Math.random()
                                });
                                }
                                return data;
                                }())"))%>%hc_title(text='Live random data')%>%hc_plotOptions(plotLines=list(value=0,width=1,color="#808080"))%>%hc_add_theme(hc_theme_economist())

**Comment by jbkunst** [comment]
Hi @zhangyan715 ,

Did you look http://stackoverflow.com/questions/12052671/timezone-on-highcharts?

Next time try to format your code :wink: please. It's easier to other read what are you coding.

**Comment by zhangyan715** [comment]
@jbkunst 
Got it!
I'm so sorry for that
Thanks for your kindness
I'll tidy up my code from now on and form good habits!
Thanks again!
