### ISSUE TITLE
drill-down to different graph type

### ISSUE THREAD

**Issue by terencezzh** [jbkunst/highcharter#177]
Hi @jbkunst ,

Thanks for creating this fascinating package. We are using it for all our Shiny pages. I am trying to implement the drill-down functionality by following your sample code:

https://github.com/jbkunst/highcharter/blob/master/devscripts/drill-down-ex.R

However, is it possible to change graph types for drill-downs? For example, in this example, could we drill down to a pie chart instead of a column chart?

Thank you in advance!

**Comment by jbkunst** [comment]
Hi @terencezzh 
 
You need first an example in (pure js) highcharts So http://lmgtfy.com/?q=drill%20down%20highcharts%20pie%20example

Then you read https://cran.r-project.org/web/packages/highcharter/vignettes/replicating-highcharts-demos.html 

I think the links can help you! Good luck!

Finally, some of your shiny are public?

**Comment by terencezzh** [comment]
thanks. No, all pages are internally used within the team.
