### ISSUE TITLE
Transition

### ISSUE THREAD

**Issue by GiovanninoPaneEvino** [jbkunst/highcharter#185]
Hello,
I am currently using highcharter with shiny. I wanted to ask if, when I change a filter which the chart is dependent on (for example reducing a column height from 5 to 3), the transition could be smooth instead of the chart being deleted and rebuilt ? Is there an option I do not get or it's a feature missing :-)? 

Thanks!!!

**Comment by jbkunst** [comment]
Hello @GiovanninoPaneEvino ,

Currently highcharter rebuilt the chart :disappointed:, but is in the future work try to add the funcionality :wink: you can track in #112

I'll close the issue by now if you don't have more doubts. 

Regards

**Comment by GiovanninoPaneEvino** [comment]
Thanks a lot for the answer!
