### ISSUE TITLE
Export highchart widget as figure in R

### ISSUE THREAD

**Issue by Yang-Tang** [jbkunst/highcharter#186]
I'm wondering if there is any way to save a highchart htmlwidge as  a figure (png or jpg) in R (Not through hc_exporting and js in brower).

**Comment by jbkunst** [comment]
Hi @Yang-Tang ,

In this case you can use the webshot package https://github.com/wch/webshot, here's is an example to use with and arbitrary htmlwidget https://github.com/wch/webshot/issues/10

**Comment by Yang-Tang** [comment]
It's very helpful! Thank you @jbkunst for the suggestion!

**Comment by tbenschop** [comment]
Hi @jbkunst, It seems that for example the labels are not loaded:

```
HFI <- data.table(one=c(1:5),two=c(11:15),var=c('a','b','c','d','e'))
data_series<-list(list(name='#one',data=100*HFI$one,stack='Current',yaxis=0,
                       dataLabels=list(enabled=T,align= 'center',format= '{point.y:.1f}')),
                  list(name='#two',data=100*HFI$two,stack='Current',yaxis=0,
                       dataLabels=list(enabled=T,align= 'center',format= '{point.y:.1f}'))
)
abc<-  highchart() %>%
  hc_chart(type='column') %>%
  hc_xAxis(categories=unique(HFI$var)) %>%
  hc_add_series_list(data_series) #%>%
# hc_plotOptions()

## sample widget
library(mapview)
m <- mapview(breweries91)

## save to html
htmlwidgets::saveWidget(widget = abc, file = "~/map.html")
setwd("~")
## save html to png 
webshot::webshot(url = "map.html", 
                 file = "map.png")
```
Is there a way to fix that? I found some discussions about that over [here](https://github.com/brenden/node-webshot/issues/114) but can't get it working in R...

**Comment by jbkunst** [comment]
Mmm, I've not used weshot before, but try using the `delay` (https://cran.r-project.org/web/packages/webshot/vignettes/intro.html) parameter to wait to show the labels, not sure  it will work but is it a try ;).

**Comment by tbenschop** [comment]
@jbkunst Thanks! WOrks
