### ISSUE TITLE
how to add legend to `xts` 

### ISSUE THREAD

**Issue by changshun** [jbkunst/highcharter#187]
Hi @jbkunst  ，

I try to use  `hc_legend` to add legend to `hc_add_series_xts` plot， but it did not work

**Comment by jbkunst** [comment]
Hi @changshun ,

Can you put some code please? Have you tried `hc_legend(enabled = TRUE)`.

`hc_add_series_xts` change the type to stock which uses highstock which disable legends by default.

```
library("quantmod")

usdjpy <- getSymbols("USD/JPY", src="oanda", auto.assign = FALSE)
eurkpw <- getSymbols("EUR/KPW", src="oanda", auto.assign = FALSE)

highchart(type = "stock") %>% 
  hc_add_series_xts(usdjpy, id = "usdjpy", name = "USD/JPY") %>% 
  hc_add_series_xts(eurkpw, id = "eurkpw") %>% 
  hc_legend(enabled = TRUE)
```

Finally, I use github issues mainly to report bug or ask features ;) https://github.com/jbkunst/highcharter/blob/master/CONTRIBUTING.md. You can ask in stackoverflow, I take a look sometimes the [r] [highcharts] tags :wink:
