### ISSUE TITLE
Two values in map tooltip

### ISSUE THREAD

**Issue by knsamati** [jbkunst/highcharter#188]
Hi,
It's possible to have two value for tooltip in `hc_add_series_map`? For example the name of the area and other variable.
Thank

**Comment by jbkunst** [comment]
Hi @knsamati ,

Yes, you can. In fact you can make the tooltip so customized as you want. In this case `hc_add_series_map` is simply a shortcut and remove data from the `data`  argument. So I recommend use hc_add_series, but in this case you need to parse in to a list the data frame, thats the only detail:

```
library(highcharter)

data(worldgeojson, package = "highcharter")
data("GNI2014", package = "treemap")

head(GNI2014)

GNI2014$value <- GNI2014$population # to make a choropleth

highchart(type = "map") %>% 
  hc_add_series(mapData = worldgeojson, data = list_parse(GNI2014),
                joinBy = "iso3") %>% 
  hc_colorAxis() %>% 
  hc_tooltip(useHTML = TRUE, headerFormat = "",
             pointFormat = "this is {point.name} and have {point.population} people with gni of {point.GNI}")
```

![image](https://cloud.githubusercontent.com/assets/56481/18724357/93665e82-8012-11e6-890b-38b2d34356a7.png)


Other examples are:

- http://jsfiddle.net/jbkunst/p0xnx1xw/embedded/result/ from http://jkunst.com/r/viz-gross-income-movies/ ![image](https://cloud.githubusercontent.com/assets/56481/18723706/1b7ca61c-8010-11e6-8cec-42474b5ff668.png)

- http://jkunst.com/htmlwidgets/pokemon-visualize-em-all/highchart_pnjkfev.html from http://jkunst.com/r/pokemon-visualize-em-all/ 
![image](https://cloud.githubusercontent.com/assets/56481/18723733/33b7fb32-8010-11e6-8ede-567f39a65529.png)

**Comment by jbkunst** [comment]
Finally, next time I recommend write in stackoverflow first https://github.com/jbkunst/highcharter/blob/master/CONTRIBUTING.md :smile:

**Comment by knsamati** [comment]
Thank very much!!!
