### ISSUE TITLE
"hc_size" doesn't work

### ISSUE THREAD

**Issue by igutierrezm** [jbkunst/highcharter#195]
I can't reproduce the example in the documentation. When I execute:
    hc_size(hcts(rnorm(100)), 400, 200)
The output is 
    Error: could not find function "hc_size"

**Comment by jbkunst** [comment]
Ji @igutierrezm 

`hc_size`it's a relative new function. Maybe you need you update `highcharter`. Can you run

```
> library(highcharter)
Highcharts (www.highcharts.com) is a Highsoft software product which is
not free for commercial and Governmental use
> 
> hc_size(hcts(rnorm(100)), 100, 100)
> 
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Spanish_Chile.1252  LC_CTYPE=Spanish_Chile.1252    LC_MONETARY=Spanish_Chile.1252
[4] LC_NUMERIC=C                   LC_TIME=Spanish_Chile.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

```
And check highcharts you have version 0.4.0?

**Comment by igutierrezm** [comment]
Strange ... When I try, this is the result.
![image](https://cloud.githubusercontent.com/assets/19560665/19091625/c2ee891c-8a59-11e6-8d56-a38fce1a8237.png)

**Comment by jbkunst** [comment]
Sorry, my bad! 

`hc_size`  comes in the next release of highcharter (https://github.com/jbkunst/highcharter/issues/146), you need install the development versión using **devtools**:

```
library(devtools)
install_github("jbkunst/highcharter")
``` 


Finally, are you from Chile too? XD

**Comment by igutierrezm** [comment]
It works! ty 👍
