### ISSUE TITLE
Area range charts

### ISSUE THREAD

**Issue by hmaeda** [jbkunst/highcharter#196]
Hello,

I was wondering if it is possible to show area range charts as suggested here (http://www.highcharts.com/demo/arearange) using the highcharter package in R...if so, I would much any hints or an example script that demonstrates this.

Kindest regards,

Hiddi

**Comment by jbkunst** [comment]
Hi @hmaeda ,

Generally, every chart in the demo page in highchart can be replicated in highcharter, please check https://cran.rstudio.com/web/packages/highcharter/vignettes/replicating-highcharts-demos.html.

If you check the code in the given link  the data is:

```
...
[1388538000000, 1.1, 4.7],
[1388624400000, 1.8, 6.4],
[1388710800000, 1.7, 6.9],
[1388797200000, 2.6, 7.4],
...
```

So to replicate this format, in R:

```
> library(highcharter)
> library(tidyverse)
> 
> n <- 10
> 
> mydata <- data_frame(
+   date = datetime_to_timestamp(seq.Date(Sys.Date(), by = 1, length.out = n)),
+   low = -runif(n),
+   high = runif(n)
+ )
> 
> mydata_to_highcharts<- list_parse2(mydata)
> 
> head(mydata_to_highcharts, 2)
[[1]]
[[1]][[1]]
[1] 1.475712e+12

[[1]][[2]]
[1] -0.2334355

[[1]][[3]]
[1] 0.6164944


[[2]]
[[2]][[1]]
[1] 1.475798e+12

[[2]][[2]]
[1] -0.3935494

[[2]][[3]]
[1] 0.8781325


> 
> highchart() %>% 
+   hc_add_series(data = mydata_to_highcharts, type = "arearange") %>% 
+   hc_xAxis(type = "datetime")
```

![image](https://cloud.githubusercontent.com/assets/56481/19159834/2a8b934c-8bc4-11e6-9819-edced980ccc7.png)


Finally, please, next time consider https://github.com/jbkunst/highcharter/blob/master/CONTRIBUTING.md :wink:
