### ISSUE TITLE
Marginal plots in Highcharter

### ISSUE THREAD

**Issue by nuno-agostinho** [jbkunst/highcharter#198]
Hello @jbkunst!

Do you know how to create marginal plots using your package ([for instance, like this](http://sas-and-r.blogspot.pt/2011/06/example-841-scatterplot-with-marginal.html))?
Unfortunately, I am not sure if this is even possible using Highcharts.

Thanks in advance!

**Comment by jbkunst** [comment]
Hi @nuno-agostinho !

As we know, highcharts don't have facet and grid plots :cry: , but you/we can code every chart a put then in a grid of div like http://rpubs.com/jbkunst/higcharter-grid-test.

Basically it will be something like:

```
div <- htmltools::tags$div

grid <- div(
  div(width = "60%", hc_hist1),
  div(width = "40%", blankbox),
  div(width = "60%", hc_scatter),
  div(width = "40%", hc_hist2),
)

htmltools::browseable(grid)
```

I guess it will need a little of theming work to get the right scales.
