### ISSUE TITLE
Intraday CandleSticks

### ISSUE THREAD

**Issue by TonyDIRL** [jbkunst/highcharter#20]
Hi,

I believe hc_add_series_ohlc is not correctly handling intraday xts. 
Example:
```
ProdData <- xts(runif(100,0,1), seq(as.POSIXct("2016-01-04 08:00:00"), as.POSIXct("2016-01-15 08:01:00"), length = 100),tz="GMT");
names(ProdData)<-"Price"
highchart(highstock = TRUE) %>% 
     hc_add_series_ohlc(to.period(ProdData,period = 'secs',k = 10))
hc
```

I believe the issue is in hc_add_series_ohlc where your convert to date_to_timestamp and cutoff the time segment. I understand this could be worked around by coverting to JSON but just thought I'd point it out.

Cheers

**Comment by jbkunst** [comment]
Oh!

The date_to_timestamp is now called datetime_to_timestamp ;). I will push this change. Can you check?

**Comment by TonyDIRL** [comment]
Confirmed. Thank you

**Comment by jbkunst** [comment]
Thank you so much :smile:
