### ISSUE TITLE
Update to highcharts 5.0

### ISSUE THREAD

**Issue by sz-cgt** [jbkunst/highcharter#202]
@jbkunst 

I forked your repository to add this but wanted to check something before sending you a pull request. 

What's the intent behind  the `highchart2` HTMLwidget?  Is that supposed to be a minimalist version  of the `highchart` widget without either HighStock or HighMap capability?  Or were you going somewhere else with it?

I ask because the 5.0 release added support for css styled charts (no more styling each element) in addition to the existing capability.

If the `highchart2` widget is supposed to be a simpler, more lightweight version of `highchart` widget, then it makes sense to enable styled mode through it.

If not, then I will just create a `highchart-styled` widget in addition to the current widgets you have.

**Comment by jbkunst** [comment]
@sz-cgt 

`highcharts2` add the `boost.js` extension to plot thouthand of points. This is a separate widgets because don't work highstock and other plugins.

About the hc5, the styling by options will keep maintained (as said @gvaartjes said http://disq.us/p/19tb00l). I dont want to go so fast with this important release.

I'm not sure how can your  `highchart-styled` is implemented :wink: , and not sure if this will change the way we wrote higcharts widgets now. Do you have some examples? How different is change the styles?

**Comment by sz-cgt** [comment]
Ahh... I didn't notice that boost .js was in the dependencies.  That makes things simpler.

Swapping to styled charts is mostly a case of using different js libraries.  The 5.0 installer includes both versions and the default is still fully optioned version.  The styled version is really just a reduced code base that's missing all the `style="..."` generating logic.

Given they need different libraries loaded, this will have to be a different htmlwidget class, `highchart-styled` perhaps (actually that name is horrible)?  That way nothing breaks for the current user base.

As background, I want to use the styled versions so I can manipulated the styling of my shiny apps without having to edit the server function each time - and lower the amount of data shiny is pushing to the client each time something changes.  No examples yet, but I'll see if I can come up with something simple.

**Comment by jbkunst** [comment]
@sz-cgt  Ok, I'll wait ;).

Make sense what you said about send the style over and over. Not sure if this is a really issue if you set previously the theme via `options` (so you change once), anyway, it will be nice if highcharter can implement this feature.

Regards, ;)

**Comment by jbkunst** [comment]
@sz-cgt  I've added hc v5, see https://github.com/jbkunst/highcharter/issues/208 ;).

If you want to add something like `highchartscss()` (or `highcharts_css()`) you can do something similar to https://github.com/jbkunst/highcharter/blob/dc7be246e80a0dbaf996f8a96d86ec5519903e31/devscripts/download-highcharts-code.R, and script to automatically download the highcharts script from and specific versión. 

If you are a little busy maybe I can do it XD.

**Comment by sz-cgt** [comment]
Yes, have been a little busy.  I’ll play with this over the Thanksgiving break.

**Comment by jbkunst** [comment]
I will close this due inactivity ;)! We can reopen the issue if is needed.
