### ISSUE TITLE
bug with .is_hc_theme assertion

### ISSUE THREAD

**Issue by sz-cgt** [jbkunst/highcharter#203]
Line 18 in R/assertthat.R is currently

     assertthat::on_failure(.is_highchart) <- function(call, env) {

It should be

    assertthat::on_failure(.is_hc_theme) <- function(call, env) {

I found this tracking down why I couldn't chain `highchart2()` to `hc_plotOptions()`.  Was thoroughly confused why my theme was wrong when I wasn't using one :-)

**Comment by jbkunst** [comment]
Hi @sz-cgt 

`highchart2`si kind of experiment, let's talk in #202 :wink:
