### ISSUE TITLE
highchart2() not usable with hc_* functions that call .is_highchart()

### ISSUE THREAD

**Issue by sz-cgt** [jbkunst/highcharter#204]
The object returned from `highchart2()` has a different class than the object returned from `highchart()`.  That's appropriate as they are different htmlwidgets.  

However, `.is_highchart()` in R/assertthat.R isn't `highchart2()` aware, causing most `hc_*` functions to fail when passed a `highchart2()` generated object.

This patch fixes the problem
 ```
--- a/R/assertthat.R
+++ b/R/assertthat.R
@@ -1,8 +1,7 @@
 #' @importFrom assertthat are_equal on_failure
 .is_highchart <- function(hc){
   are_equal(TRUE, TRUE)
-  are_equal(class(hc), c("highchart", "htmlwidget"))
-  are_equal(class(hc), c("highchart", "htmlwidget"))
+  are_equal(class(hc), c("highchart", "htmlwidget")) || are_equal(class(hc), c("highchart2", "htmlwidget"))^M
 }

 assertthat::on_failure(.is_highchart) <- function(call, env) {
```

**Comment by jbkunst** [comment]
Hi @sz-cgt ,

First of all, what version are you using? Can you use the development/gthub version?

**Comment by sz-cgt** [comment]
thought I was but I see in master that the whole function is now gone, so nevermind.

close #204
