### ISSUE TITLE
Embed highchart into Excel

### ISSUE THREAD

**Issue by terencezzh** [jbkunst/highcharter#207]
Hi @jbkunst ,

I am looking for ways to present highcharts to general users. And I am just curious if it is possible to insert the highcharts into Excel spreadsheet?

Or do you have any other recommendations of outputting highcharts?

Thanks.

**Comment by jbkunst** [comment]
Hi @terencezzh 
#178 :wink: 

Meantime, you can add the plugin manually, example https://github.com/jbkunst/highcharter/issues/172#issuecomment-249262645 using other pluging, the `htmlDepency` part.

**Comment by jbkunst** [comment]
Aps, sorry, you mean as a plot, right? I'm not sure, you can autoamtically generate a `png` then put as image

**Comment by terencezzh** [comment]
Thanks a lot for the quick response. Because Excel's default charts are all static and we usually build reports with Excel, it will be great if I can embed highcharts into Excel. If I save it as .png file, it will be a static image and lose all animations. I am just curious if you are aware of any ways that can embed highchart into excel with full animations remaining?

**Comment by knsamati** [comment]
Interactive it is for HTML page

**Comment by jbkunst** [comment]
I will close this due inactivity ;)! We can reopen the issue if is needed.
