### ISSUE TITLE
mapbubble creation with highcharter?

### ISSUE THREAD

**Issue by christopheLouat** [jbkunst/highcharter#209]
Is it possible to create map with mapbubble series with highcharter? I have tried with a lot of dataset and I don't succed to create a chart. I can generate date for mappoints series but they don't work for mapbubble series. Can you tell me how to represent data?

**Comment by jbkunst** [comment]
Hi @christopheLouat ,

Can you post 2 things? 1) What have you done/code? 2) Similar demo example from http://www.highcharts.com/maps/demo

Thanks

**Comment by christopheLouat** [comment]
Hi @jbkunst 

1)I have a dataset like this (dataTable)

code | latitude | longitude | z
------------ | ------------ | ------------ | ------------
AAA | 30.322500 | -9.411388 | 1200
BBB | 50.901390 | 4.484444 | 9120
CCC | 25.252777 | 55.364445 | 41200

I have test the following code:
world <- "https://raw.githubusercontent.com/johan/world.geo.json/master/countries.geo.json" %>% 
  GET() %>% 
  content() %>% 
  jsonlite::fromJSON(simplifyVector = FALSE)

parksgjs <- geojson_json(dataTable, lat = "latitude", lon = "longitude")

highchart(type = "map") %>% 
  hc_title(text = "Most frequented place") %>% 
  hc_add_series(mapData = world, 
                nullColor = "#425668 ",
                showInLegend = FALSE) %>% 
  hc_add_series(data = parksgjs , type = "mapbubble",
                dataLabels = list(enabled = FALSE),
                
                minSize= 4,
                maxSize= 20
                ) %>%
  hc_mapNavigation(enabled = TRUE,
                   buttonOptions = list(
                     align = "right",
                     verticalAlign = "bottom"))

i have test with the geojson transformation of the data and without but i don't have the expected result. 
If I use the type mappoint (and geojson transformation of data) I can obtain a result but I prefer Bubble.

2) http://www.highcharts.com/maps/demo/latlon-advanced

Thanks

**Comment by jbkunst** [comment]
I'm working on this. I think I'll need to add some `if` in the case of this type of data.

**Comment by jbkunst** [comment]
Hi @christopheLouat !!!!

Uff, so much time but I worked on `hcmap` function and fix some details in the highcharts binding.

Try the following in the development version:


```r
cities <- data_frame(
  name = c("London", "Birmingham", "Glasgow", "Liverpool"),
  lat = c(51.507222, 52.483056,  55.858, 53.4),
  lon = c(-0.1275, -1.893611, -4.259, -3),
  z = c(1, 2, 3, 2)
)

hcmap("countries/gb/gb-all", showInLegend = FALSE) %>% 
  hc_add_series(data = cities, type = "mapbubble", name = "Cities", maxSize = '10%') %>% 
  hc_mapNavigation(enabled = TRUE) # Zoom


hcmap("custom/world", showInLegend = FALSE) %>% 
  hc_add_series(data = cities, type = "mappoint", name = "Cities", maxSize = '1%') %>% 
  hc_mapNavigation(enabled = TRUE) # Zoom

```

**Comment by christopheLouat** [comment]
Hi Joshua!

thanks a lot for the corrections on the hcmap function. The bubble map is great!!!
