### ISSUE TITLE
hc_motion in highchart of 'map' type

### ISSUE THREAD

**Issue by cpgonzal** [jbkunst/highcharter#211]
I'm trying to use the hc_motion plugin with a map as we can see here:

http://jsfiddle.net/gh/get/jquery/1.9.1/larsac07/Motion-Highcharts-Plugin/tree/master/demos/map-australia-colors-demo/

However, I don´t get the correct way to introduce data series in the object highchart by using the hc_add_series method. ¿Any idea or suggestion? Thanks

**Comment by jbkunst** [comment]
Hola @cpgonzal 

You can check this example http://jkunst.com/r/adding-motion-to-choropleths/ ;) Tell me if this help you please.

Saludos,

**Comment by cpgonzal** [comment]
Gracias, @jbkunst for your help. This example have helped me so much. Now I can combine the motion with my maps... Greetings for this useful library.

**Comment by MERE55** [comment]
> Hola @cpgonzal
> 
> You can check this example http://jkunst.com/r/adding-motion-to-choropleths/ ;) Tell me if this help you please.
> 
> Saludos,

Hi,
I just also struggle with that topic but unfortunately the link as you mentioned above and which could hopefully help me doesn´t work any more :-(
The case where I would use this is a daily chorpleth map of the German counties. I first load the shapefile of the map data and change it to JSON and then load my data, but then how can I accomplish the animated choropleth ?
Thanks for support and help and best wishes

**Comment by MERE55** [comment]
> Hola @cpgonzal
> 
> You can check this example http://jkunst.com/r/adding-motion-to-choropleths/ ;) Tell me if this help you please.
> 
> Saludos,

Hi @jbkunst,
I just also struggle with that topic but unfortunately the link as you mentioned above and which could hopefully help me doesn´t work any more :-(
The case where I would use this is a daily chorpleth map of the German counties. I first load the shapefile of the map data and change it to JSON and then load my data, but then how can I accomplish the animated choropleth ?
Thanks for support and help and best wishes

**Comment by JrmFRL** [comment]
Hi @MERE55 ,
you can still find this page on Web Archive: https://web.archive.org/web/20190131123620/https://jkunst.com/r/adding-motion-to-choropleths/

**Comment by MERE55** [comment]
> Hi @MERE55 ,
> you can still find this page on Web Archive: https://web.archive.org/web/20190131123620/https://jkunst.com/r/adding-motion-to-choropleths/

Hi @JrmFRL ,
thx a lot - will have a look at it :-)
Found also another example and could create a version with my data here : 
https://myblog.photonade.com/aktuelles/landkreisebw/animationcovid-19incidencelkbw/
Only awesomeicon for starting the sequence is not working yet (button is empty).
Perhaps the version you sent me the link has a hint for that.

**Comment by jbkunst** [comment]
Hi everyone,

This is the actual url https://jkunst.com/blog/posts/2016-04-12-adding-motion-to-choropleths/
