### ISSUE TITLE
Does Highcharter have "groupedOptions" for styling separately when using "grouped categories"?

### ISSUE THREAD

**Issue by Rhoboot** [jbkunst/highcharter#212]
`xAxis: {    
    labels: {
        groupedOptions: [{
            style: {
                color: 'red' // set red font for labels in 1st-Level  
            }
        }, {
            rotation: -45, // rotate labels for a 2nd-level
            align: 'right'
        }],
        rotation: 0 // 0-level options aren't changed, use them as always
    }`

**Comment by jbkunst** [comment]
Hi @Rhoboot ,

Have you tried that? :) The pluging is implemented so I guess that will work. 

Please, tell me if this work.

**Comment by Rhoboot** [comment]
It does not work for me, I do not know if I'm entering the lists wrong or something.

For example in this case, I try to leave the first red axis and the second with a rotation of -90.

############
library(highcharter)
library(purrr)           # map function to make grouped categories argument
library(dplyr)           # for select function 
Category <- c("Furniture","Furniture","Furniture","Furniture",
              "Office Supplies","Office Supplies", "Office Supplies", "Office Supplies",
              "Office Supplies", "Office Supplies", "Office Supplies", "Office Supplies",
              "Office Supplies", "Technology","Technology","Technology","Technology")

SubCategory <- c("Bookcases","Chairs","Furnishings","Tables","Appliances","Art","Binders","Envelopes", 
                 "Fasteners","Labels","Paper","Storage",  "Supplies", "Accessories","Copiers","Machines",
                 "Phones")
sales <- c(889222.51,920892.65,239840.16,445823.93,614737.91,225594.68,281494.68,104903.88,50156.06,44269.30,
           150113.36,692903.08,152196.19,463383.33,965899.78,458655.43,1005525.38)
mydf <- data_frame(Category,SubCategory,sales, color = colorize(Category))
categories_grouped <- map(unique(Category), function(x){
  list(name = x,categories = SubCategory[Category == x])
})

highchart() %>% 
  hc_chart(type = "column") %>% 
  hc_xAxis(categories = categories_grouped,labels=list(groupedOptions=c(list(style=list(color='#FF0000'),rotation=-90)))) %>% 
  hc_add_series(data = list_parse(dplyr::select(mydf, y = sales, color = color)),showInLegend = FALSE)
############

In this other example, where the axes are entered separately, I apply formatting to each one already. But it is not the most elegant way to solve it.
##########
highchart() %>% 
  hc_chart(type = "column") %>% 
  hc_title(text = "Total fruit consumtion, grouped by year") %>% 
  hc_yAxis(allowDecimals=FALSE,min=0,title=list(text='Number of fruits'))%>%
  hc_xAxis(list(categories = c('Apples', 'Oranges', 'Pears', 'Grapes', 'Bananas'),opposite='true',labels=list(style=list(color='#FF0000'))),
           list(categories = c('2014', '2015', '2014', '2015', '2014', '2015','2014', '2015', '2014', '2015'),labels=list(rotation=-90))) %>%
  hc_plotOptions(column = list(stacking = "normal")) %>%
  hc_series(list(name='John',data=c(5, 3, 4, 7, 2),stack='2014',color= '#ff4400'),
            list(name='Joe',data=c(3, 4, 4, 2, 5),stack='2014',color= '#44ff00'),
            list(name='John',data=c(2, 5, 6, 2, 1),showInLegend = FALSE,stack='2015',color= '#ff4400'),
            list(name='Joe',data=c(3, 0, 4, 4, 3),showInLegend = FALSE,stack='2015',color= '#44ff00'),
            list(name='',data=c(0,0,0,0,0,0,0,0,0,0),stack='2015',showInLegend = FALSE,xAxis=1))
#############

![screenshot of rstudio 09-11-16 11-32-39](https://cloud.githubusercontent.com/assets/7344313/20141735/7433453c-a670-11e6-9faa-806cb3d13219.png)

**Comment by Rhoboot** [comment]
It does not work for me, I do not know if I'm entering the lists wrong or something.

For example in this case, I try to leave the first red axis and the second with a rotation of -90.

############
library(highcharter)
library(purrr) # map function to make grouped categories argument
library(dplyr) # for select function 
Category <- c("Furniture","Furniture","Furniture","Furniture",
"Office Supplies","Office Supplies", "Office Supplies", "Office Supplies",
"Office Supplies", "Office Supplies", "Office Supplies", "Office Supplies",
"Office Supplies", "Technology","Technology","Technology","Technology")

SubCategory <- c("Bookcases","Chairs","Furnishings","Tables","Appliances","Art","Binders","Envelopes", 
"Fasteners","Labels","Paper","Storage", "Supplies", "Accessories","Copiers","Machines",
"Phones")
sales <- c(889222.51,920892.65,239840.16,445823.93,614737.91,225594.68,281494.68,104903.88,50156.06,44269.30,
150113.36,692903.08,152196.19,463383.33,965899.78,458655.43,1005525.38)
mydf <- data_frame(Category,SubCategory,sales, color = colorize(Category))
categories_grouped <- map(unique(Category), function(x){
list(name = x,categories = SubCategory[Category == x])
})

highchart() %>% 
hc_chart(type = "column") %>% 
hc_xAxis(categories = categories_grouped,labels=list(groupedOptions=c(list(style=list(color='#FF0000'),rotation=-90)))) %>%
hc_add_series(data = list_parse(dplyr::select(mydf, y = sales, color = color)),showInLegend = FALSE)
############

In this other example, where the axes are entered separately, I apply formatting to each one already. But it is not the most elegant way to solve it.
##########
highchart() %>% 
hc_chart(type = "column") %>% 
hc_title(text = "Total fruit consumtion, grouped by year") %>% 
hc_yAxis(allowDecimals=FALSE,min=0,title=list(text='Number of fruits'))%>%
hc_xAxis(list(categories = c('Apples', 'Oranges', 'Pears', 'Grapes', 'Bananas'),opposite='true',labels=list(style=list(color='#FF0000'))),
list(categories = c('2014', '2015', '2014', '2015', '2014', '2015','2014', '2015', '2014', '2015'),labels=list(rotation=-90))) %>%
hc_plotOptions(column = list(stacking = "normal")) %>%
hc_series(list(name='John',data=c(5, 3, 4, 7, 2),stack='2014',color= '#ff4400'),
list(name='Joe',data=c(3, 4, 4, 2, 5),stack='2014',color= '#44ff00'),
list(name='John',data=c(2, 5, 6, 2, 1),showInLegend = FALSE,stack='2015',color= '#ff4400'),
list(name='Joe',data=c(3, 0, 4, 4, 3),showInLegend = FALSE,stack='2015',color= '#44ff00'),
list(name='',data=c(0,0,0,0,0,0,0,0,0,0),stack='2015',showInLegend = FALSE,xAxis=1))
#############

![screenshot of rstudio 09-11-16 11-32-39](https://cloud.githubusercontent.com/assets/7344313/20141771/9cfeb88e-a670-11e6-8f99-e632b001f6da.png)

**Comment by Rhoboot** [comment]
It does not work for me, I do not know if I'm entering the lists wrong or something.

For example in this case, I try to leave the first red axis and the second with a rotation of -90.

############
library(highcharter)
library(purrr) # map function to make grouped categories argument
library(dplyr) # for select function 
Category <- c("Furniture","Furniture","Furniture","Furniture",
"Office Supplies","Office Supplies", "Office Supplies", "Office Supplies",
"Office Supplies", "Office Supplies", "Office Supplies", "Office Supplies",
"Office Supplies", "Technology","Technology","Technology","Technology")

SubCategory <- c("Bookcases","Chairs","Furnishings","Tables","Appliances","Art","Binders","Envelopes", 
"Fasteners","Labels","Paper","Storage", "Supplies", "Accessories","Copiers","Machines",
"Phones")
sales <- c(889222.51,920892.65,239840.16,445823.93,614737.91,225594.68,281494.68,104903.88,50156.06,44269.30,
150113.36,692903.08,152196.19,463383.33,965899.78,458655.43,1005525.38)
mydf <- data_frame(Category,SubCategory,sales, color = colorize(Category))
categories_grouped <- map(unique(Category), function(x){
list(name = x,categories = SubCategory[Category == x])
})

highchart() %>% 
hc_chart(type = "column") %>% 
hc_xAxis(categories = categories_grouped,labels=list(groupedOptions=c(list(style=list(color='#FF0000'),rotation=-90)))) %>%
hc_add_series(data = list_parse(dplyr::select(mydf, y = sales, color = color)),showInLegend = FALSE)
############

In this other example, where the axes are entered separately, I apply formatting to each one already. But it is not the most elegant way to solve it.
##########
highchart() %>% 
hc_chart(type = "column") %>% 
hc_title(text = "Total fruit consumtion, grouped by year") %>% 
hc_yAxis(allowDecimals=FALSE,min=0,title=list(text='Number of fruits'))%>%
hc_xAxis(list(categories = c('Apples', 'Oranges', 'Pears', 'Grapes', 'Bananas'),opposite='true',labels=list(style=list(color='#FF0000'))),
list(categories = c('2014', '2015', '2014', '2015', '2014', '2015','2014', '2015', '2014', '2015'),labels=list(rotation=-90))) %>%
hc_plotOptions(column = list(stacking = "normal")) %>%
hc_series(list(name='John',data=c(5, 3, 4, 7, 2),stack='2014',color= '#ff4400'),
list(name='Joe',data=c(3, 4, 4, 2, 5),stack='2014',color= '#44ff00'),
list(name='John',data=c(2, 5, 6, 2, 1),showInLegend = FALSE,stack='2015',color= '#ff4400'),
list(name='Joe',data=c(3, 0, 4, 4, 3),showInLegend = FALSE,stack='2015',color= '#44ff00'),
list(name='',data=c(0,0,0,0,0,0,0,0,0,0),stack='2015',showInLegend = FALSE,xAxis=1))
#############

![screenshot of rstudio 09-11-16 11-32-39](https://cloud.githubusercontent.com/assets/7344313/20141787/acbe773c-a670-11e6-946e-026f0ce7c374.png)

**Comment by jbkunst** [comment]
Ok, I will look this.

Finally, please use ``` instead of ############ ;)

**Comment by jbkunst** [comment]
If we look the highchars code:

```
...
    groupedOptions: [{
            style: {
                color: 'red' // set red font for labels in 1st-Level  
            }
        }
...
```

Note the `[{`  in the first line, this means is a list of stye in a list element.

 So you need:

```
...
  labels=list(groupedOptions=list(list(style=list(color='#FF0000'),rotation=-90)))) %>%
```

Note `list(list(style=`

Can you test this? 

Finally if you see https://cran.r-project.org/web/packages/highcharter/vignettes/replicating-highcharts-demos.html at the end you can compare want you want with you are doing in via highcharter.

```
hc <- hc_add_series(highchart(), data = c(1,2,3))
library("jsonlite")
toJSON(hc$x$hc_opts, pretty = TRUE, auto_unbox = TRUE)
```

**Comment by Rhoboot** [comment]
Yes, work...
`hc_xAxis(labels=list(groupedOptions=list(list(style=list(color='#FF0000'),rotation=0)),rotation=-90),categories = categories_grouped) %>%`

<img width="583" alt="screenshot of rstudio 11-9-16 22-37-44" src="https://cloud.githubusercontent.com/assets/7344313/20161450/4fb37fbc-a6cd-11e6-83e1-aaf160deb1d4.png">

But the parameter **opposite='true'**, I do not know where to put it.

Thank you!

**Comment by dkoltg** [comment]
Hi, is there also a groupedOptions-code to modify the ticks for the main-category only? I would like to hide the ticks between the sub-categories, but leave them between the main categories.

Thanks for any help!

**Comment by LuShuYangMing** [comment]
And a new question, how could I add the group labels on the top of the **boxplot** and add the box name at the bottom ? similar to this picture, but no need to stack
 
![image](https://user-images.githubusercontent.com/26463478/137467961-9a257383-f03d-439f-bb59-6042f344a45b.png)

@jbkunst @Rhoboot
