### ISSUE TITLE
Irregular time intervals

### ISSUE THREAD

**Issue by Rustastra** [jbkunst/highcharter#219]
Hello,

was wondering if you could help me. I have a data frame, where some observations are daily and others are monthly (so all dates except end-of-month have NA values). 

What I am trying to do it reproduce this example http://www.highcharts.com/demo/spline-irregular-time 
Is this option supported in R package?

thanks a lot!

**Comment by jbkunst** [comment]
Hi @Rustastra ,

First of all, search help in stackoverflow or similar ;), Every day I check the [r] tags. This is section is mainly (I hope!) for features and bugs (https://github.com/jbkunst/highcharter/blob/master/CONTRIBUTING.md)

A good resource is https://cran.r-project.org/web/packages/highcharter/vignettes/replicating-highcharts-demos.html 

Finally, you need to use de timestamp, in highcharter there is a helper function:

```
> library(highcharter)
> 
> n <- 5
> 
> df <- data.frame(
+   x = c(as.Date("2001-01-01") + sort(sample(0:100, size = n))),
+   y = runif(n)
+   
+ )
> 
> df
           x          y
1 2001-01-31 0.24573309
2 2001-02-02 0.34251528
3 2001-03-19 0.07735324
4 2001-03-21 0.78062637
5 2001-03-26 0.97177559
> 
> df$x <- datetime_to_timestamp(df$x)
> 
> df
             x          y
1 980899200000 0.24573309
2 981072000000 0.34251528
3 984960000000 0.07735324
4 985132800000 0.78062637
5 985564800000 0.97177559
> 
> highchart() %>% 
+   hc_xAxis(type = "datetime") %>% 
+   hc_add_series(data = list_parse(df))
> 
```

Hope this helps! ;)

**Comment by Rustastra** [comment]
Thanks so much for your help and the package! 

My googling skills are not that great apparently :)

**Comment by Rustastra** [comment]
I thought I would paste an answer to my question in case anyone is looking for it too. If data frame has NAs in it, you can still connect the points using this option:
http://api.highcharts.com/highcharts/plotOptions.series.connectNulls

**Comment by jbkunst** [comment]
Thanks for the info @Rustastra
