### ISSUE TITLE
Spline with Symbols

### ISSUE THREAD

**Issue by TonyDIRL** [jbkunst/highcharter#22]
Hi,

Trying to incorporate a symbol into a spline as per 
http://www.highcharts.com/demo/spline-symbols
```
hc <- highchart()
hc <- hc_title(hc, text = "A nice chart")
hc <- hc_add_series(hc, data = c(7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2,list(y= 26.5, marker=list(symbol='square'))))
hc
```
Getting a ".. fully named list.." error, assuming its to do with the list(y= 26.5, segment.

Any ideas?

**Comment by jbkunst** [comment]
OMG 
  I tested and tested some hacks like:

```
data <- data_frame(
  y = c(1,2,3,4,5,4,5),
  marker = list(symbol = "square")
)

data$marker[[3]] <- list(symbol = 'url(https://www.highcharts.com/samples/graphics/sun.png)')

ds <- list.parse2(data)

ds

hc <- highchart()
hc <- hc_title(hc, text = "A nice chart")
hc_add_series(hc, data = ds)
```
Which works, so its nice, but then I change the `c` by `list` and it WORKS :relieved: 

```
hc <- highchart()
hc <- hc_title(hc, text = "A nice chart")
hc <- hc_add_series(hc, data = list(7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2,list(y= 26.5, marker=list(symbol='url(https://www.highcharts.com/samples/graphics/sun.png)'))))
hc
```

**Comment by TonyDIRL** [comment]
Thanks, actually I think the hc_add_series_flags might be more useful.
There seems to be a bug with using OHLC bars and the placement of the flag:
```
x <- getSymbols("AAPL", auto.assign = FALSE);
dates <- as.Date(c("2007-01-08", "2007-01-10"),format = "%Y-%m-%d")
highchart() %>%  
 hc_add_series_ohlc(x, id = "AAPL")%>%
  hc_add_series_flags(dates,title = c("E1", "E2"), id = "AAPL") 
```

Also, I imagine the dates parameter of hc_add_series_flags will not allow it work with an intraday OHLC xts object

**Comment by jbkunst** [comment]
This example works for you? http://jsfiddle.net/KDP87/14/

**Comment by TonyDIRL** [comment]
That would be cool.

Click response would also be cool but I imagine that would require crosstalk :)

**Comment by jbkunst** [comment]
What do you mean? Have you an example?

**Comment by TonyDIRL** [comment]
Sorry, I was referencing the crosstalk work rstudio is working on. Thats outside the scope of this issue on hc_add_series_flags
