### ISSUE TITLE
JavaScript export

### ISSUE THREAD

**Issue by misteliy** [jbkunst/highcharter#221]
hi,
since I can not use shiny as a way to share my charts I was wondering if I can directly export the charts from R to JavaScript format.

**Comment by jbkunst** [comment]
Hi @misteliy 

First of all, search help in stackoverflow or similar ;), Every day I check the [r] tags. This is section is mainly (I hope!) for features and bugs (https://github.com/jbkunst/highcharter/blob/master/CONTRIBUTING.md) 😉 

Not sure what is the format are you needing. There are two main ways.

1. Use `saveWidget` from the `htmlwidgets` package, This save html + (js & css) dependencies into a file.
2. In highcarter there is a `export_hc` function which write the js file as the __javascript__ in http://jsfiddle.net/gh/get/jquery/3.1.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/line-labels/.

Tell me if this help to you to close or not the issue.
