### ISSUE TITLE
hc_colorAxis with white space in the legend box

### ISSUE THREAD

**Issue by wlinInspire** [jbkunst/highcharter#222]
Dear Author,

Just found that when I use hc_colorAxis for the heatmap, the legend is not centered. When I plot the legend box board, I found that it has unnecessary white space in it. The following is the illustration code modified from hc_colorAxis example code

```{r}
nyears <- 5
df <- expand.grid(seq(12) - 1, seq(nyears) - 1)
df$value <- abs(seq(nrow(df)) + 10 * rnorm(nrow(df))) + 10
df$value <- round(df$value, 2)
ds <- list_parse2(df)
hc <- highchart() %>% 
    hc_chart(type = "heatmap") %>% 
    hc_title(text = "Simulated values by years and months") %>% 
    hc_xAxis(categories = month.abb) %>% 
    hc_yAxis(categories = 2016 - nyears + seq(nyears)) %>% 
    hc_add_series(name = "value", data = ds) %>% 
    hc_colorAxis(minColor = "#FFFFFF", maxColor = "#434348") %>% 
    hc_legend(borderWidth = 1)
```
![image](https://cloud.githubusercontent.com/assets/16128658/20647161/ae8c8eda-b441-11e6-8912-8bcd7a65ea77.png)

**Comment by jbkunst** [comment]
Hi @wlinInspire  

I will take a look! Thanks

**Comment by Elizemiku** [comment]
I changed the caption size manually using the width = 205, in the function : 
`hc_legend (borderWidth = 1, width = 205)`
by looking at the parameters of the hc_legend function on the api.highcharts.com/highcharts#legend

**Comment by Elizemiku** [comment]
I changed the caption size manually using the width = 205, in the function :
`hc_legend (borderWidth = 1, width = 205) `
by looking at the parameters of the hc_legend function on the api.highcharts.com/highcharts#legend. 
The legend remained centered.

**Comment by jbkunst** [comment]
Now, about the _unnecessary_ white space I think this is more @highcharts related than highcharter. @wlinInspire , if you are fine with this we can close the issue.

Regards to all.
