### ISSUE TITLE
Error : Time series highchart unable plot on html file.

### ISSUE THREAD

**Issue by englianhu** [jbkunst/highcharter#226]
By refer to http://jkunst.com/highcharter/highstock.html, I try to plot a **Time series** highchart. Its work when I run the chunk but not workable when knitted. Kindly look into this?

![2016-12-14 02 34 38](https://cloud.githubusercontent.com/assets/7227582/21151455/ed880a62-c1a5-11e6-8990-31793678a488.png)

Below is some sample while I faced same issue when ran it.
- http://stackoverflow.com/questions/28954836/highcharts-3d-with-rcharts
- http://jkunst.com/r/presenting-highcharter/

http://rpubs.com/englianhu/introduction-of-r-packages is my webpage with source codes.

**Comment by jbkunst** [comment]
Hi @englianhu 

My first guess is there is a conflict with the rest of librearies, can you try knit without formattable?

**Comment by englianhu** [comment]
I tested if it conflicts with others as you mentioned.

Finally its workable if I dissambled the `plotChart()`. Would you try to look at the issue?
http://rpubs.com/englianhu/highcharter-issue

**Comment by englianhu** [comment]
Solved, updated the link http://rpubs.com/englianhu/highcharter-issue, the return value of graph cannot in list format.
