### ISSUE TITLE
hc_colorAxis range not being mapped

### ISSUE THREAD

**Issue by daneel6672** [jbkunst/highcharter#228]
The colours are not affected by minColor and maxColor in this example:

library(highcharter)
library(reshape)

vaccines <- data.frame(year=seq(1970,2000),a=runif(31),b=runif(31),c=runif(31))
vaccines.melt <- melt(vaccines,id="year")

hchart(vaccines.melt, "heatmap", x = year, y = variable, value = value) %>% 
  hc_colorAxis(min=0,max=1,minColor="#000000",maxColor="#FFFFFF",type = "linear")

**Comment by jbkunst** [comment]
Hi @daneel6672 ,

Can you show the output? I'm using the development version so you need use `hcaes`:

```r
hchart(vaccines.melt, "heatmap", hcaes(x = year, y = variable, value = value)) %>%
  hc_colorAxis(min=0,max=1,minColor="#000000",maxColor="#FFFFFF",type = "linear")
```

![image](https://cloud.githubusercontent.com/assets/56481/21265579/dd092c3e-c380-11e6-93c5-754b1716084e.png)

**Comment by daneel6672** [comment]
![selection_140](https://cloud.githubusercontent.com/assets/20476435/21265906/9a9f7e32-c39b-11e6-8aa1-8ddd2b5c1ede.png)

**Comment by jbkunst** [comment]
Can you use the development version? Not sure what happend in the previous version, sorry.

**Comment by daneel6672** [comment]
Will do - amazing library by the way.

**Comment by jbkunst** [comment]
Thanks!
