### ISSUE TITLE
webshot

### ISSUE THREAD

**Issue by theyuish** [jbkunst/highcharter#229]
Hi Joshua,

I don't know if this is something that you have faced before. But when you have highchart output on rmarkdown (word_document) - something as below. The output is totally different in local machine and in shinyapps.io. On shinyapps.io, it seems the output will be zoomed in and become blur. Any idea how this happens.

Thank you so much.

```{r echo = FALSE, warning = FALSE, comment = NA, message = FALSE, screenshot.opts = list(delay = 2, zoom = 1)}
library(webshot)

hc = highchart(height = "235px", width = "235px") %>% 
  hc_chart(type = 'pie',
           spacingTop = 0,
           spacingBottom = 0,
           spacingLeft = 0,
           spacingRight = 0
           ) %>% 
      hc_plotOptions(
        pie = list(
          size = '100%',
          allowPointSelect = TRUE,
          cursor = 'pointer',
          dataLabels = list(
            enabled = TRUE,
            distance = -30,
            format = "{point.y:,.0f}"
          ),
          showInLegend = TRUE
        )
      )%>%
      hc_series(list(
        name = 'A ',
        data = dataList_
      ))
hc
```

**Comment by jbkunst** [comment]
I've never have use webshot package. If you use other htmlwidget like dygraph or plotly what happen?

**Comment by theyuish** [comment]
@jbkunst. I haven't tried other packages but perhpas it will be the same. Saw some discussion that the problem came from phantomjs due the the different setting for windows system and Linux. Have you came across for better way to put HTML output into a word document via knitr? 

Thanks.
