### ISSUE TITLE
Intraday hc_add_series_xts

### ISSUE THREAD

**Issue by TonyDIRL** [jbkunst/highcharter#23]
Sorry for all the notes but I think I found another small issue with hc_add_series_xts
This works as expected.
```
ProdData <- xts(runif(10000,0,1), seq(as.POSIXct("2016-01-04 08:00:00"), as.POSIXct("2016-01-06 08:11:00"), length = 10000),tz="GMT");
names(ProdData)<-"Price"
highchart() %>% 
  hc_add_series_xts(Cl(to.daily(ProdData)))
```

However, changed to intraday does not work
```
    hc_add_series_xts(Cl(to.period(ProdData,period = 'secs',k = 1)))
```

I imagine this is the same bug as hc_add_series_ohlc

**Comment by jbkunst** [comment]
Thanks, 

I thik I need to rework some function because not always ts objects are compatible with xts when I sue the `time`function. I need to check

**Comment by jbkunst** [comment]
@TonyDIRL 

I rewrite `hc_add_series_xts` function it works.

If you are not so busy. Can I ask you write a simple R script with all types chart/treatment what you use in this topic (time series) or what you think people use most? I dont work every day with this type of data so I don't know what people need.

This can help in:
- Make test to verify all is good after build package.
- Make a vignette for xts/quantmod package.  

Tell me if you can, or what you think.

Thanks

**Comment by TonyDIRL** [comment]
Absolutely, I'd be happy to do that
