### ISSUE TITLE
release v0.5.0

### ISSUE THREAD

**Issue by sagax85** [jbkunst/highcharter#231]
hey, 

i saw that you completed the milestone v0.5.0. Would it be possible to make a release for it? :) We'd like to use some features of that version.

thanks a lot!

**Comment by jbkunst** [comment]
Hey @sagax85,

Yep, I'm almost there to make a new release. I want to keep testing, in particular I want to rebuild all jkunst.com/highcharter/ to this new version first to be calm and ensure I'm not breaking anything.

Probably I will make the new release in mid of January.

**Comment by sagax85** [comment]
thanks @jbkunst for all the work 👍
