### ISSUE TITLE
hc_colorAxis option

### ISSUE THREAD

**Issue by ochees** [jbkunst/highcharter#232]
Hi,

Thanks for this package. Is it possible to use discrete scale (breaks and colour clearly defined) with the heatmap plot or map plot ?
I saw this page : [http://api.highcharts.com/highmaps/colorAxis.dataClasses](url) but i don't know how to use in the function `hc_colorAxis`

thanks a lot !

**Comment by ochees** [comment]
I found an answer here :  [https://github.com/jbkunst/highcharter/issues/120](url)
and `hc_colorAxis(hc,dataClasses=color_classes(breaks = breaks, colors =colors))`

thanks a lot !

**Comment by jbkunst** [comment]
You're welcome.

You forgot close the issue! :wink:
