### ISSUE TITLE
Creating a point data motion chart with worldmap as background

### ISSUE THREAD

**Issue by prateekjoshi565** [jbkunst/highcharter#233]
Hi,

I have a 40,000 rows dataset with **'year'**, **'latitude'**, **'longitude'**, **'id'**, and **'value'** as its columns. The 'year' values range from 1900 to 2013 and the 'id' is unique. 

I want to plot a motion point-chart on a worldmap. Please help me.

**Comment by jbkunst** [comment]
Hi @prateekjoshi565  

Have you some code of what ahve you done already? ;)

**Comment by prateekjoshi565** [comment]
This is what I am trying to do but no luck...

`library(dplyr)
library(geojsonio)
library(highcharter)

# sample data
met = data.frame(year = c(1999,1999,2001,2001,2003,2005,2005),
                 latitude = c(28,41,55,50,22,33,35),
                 longitude = c(77,28,37,4,43,18,139),
                 id = c(1,2,3,4,5,6,7),
                 value = c(100,80,200,170,130,60,150))

met_hc = geojson_list(met, lat = 'latitude', lon = 'longitude', group = 'year')

# Loading world map data
data("worldgeojson")

highchart(type = "map") %>% 
  hc_title(text = "Sample Data") %>%
  hc_add_series(mapData = worldgeojson, showInLegend = FALSE) %>%
  hc_add_series(data = met_hc, type = "mappoint", dataLabels = list(enabled = F)) %>%
  hc_legend(enabled = F)
`

**Comment by jbkunst** [comment]
@prateekjoshi565 

Do you want a point with moving across the map? Not sure what you want. Do you have a similar example to replicate?

**Comment by prateekjoshi565** [comment]
@jbkunst 

I want points of a particular year only to be displayed at a time. As the value of the year is changed, the corresponding points of that year should get displayed. I don't how to prepare my data for this and also how to put a slider to change year variable.

**Comment by jbkunst** [comment]
Hi @prateekjoshi565 

Sorry for late, you need to create a data frame with columns: lat, lon, z, and sequence, wich is a colum of numbers, The use the `hcmap` function to create the map, hc_add_series to add the data frame data, and then use `hc_motion` to set option to the pluging.

Example: http://rpubs.com/jbkunst/highcharter-issue-233
