### ISSUE TITLE
Error using hc_motion slider.

### ISSUE THREAD

**Issue by VPlazaM** [jbkunst/highcharter#235]
@jbkunst, 
I have been suffering problems with the slider created through hc_motion function. Basically, this slider is based on a years's sequence (10 of them) but the main problem is that it goes from 2005 to 2014 in the first third of the slider, and then continues empty and not changing anything to the end. It takes 10 seconds more or less so it's useless.

Thanks for your help!

**Comment by jbkunst** [comment]
Hi @VPlazaM 

Ok, what have you tried already?

**Comment by VPlazaM** [comment]
I have tried changing the updateinterval, the data structure and every option that hc_motion gives to me. I think that the problem is caused by the combination of tabsetpanels, mainpanels and absolutepanels that I'm currently using in my ui.R file that somehow is making the slider not work propertly.

**Comment by jbkunst** [comment]
I'm meant code. A reproducible example.

**Comment by VPlazaM** [comment]
It's complicated due to data's nature and confidentiality agreements, let's see if it's enough:

getMapHighCharts <- function(map_dataframe) {

  map_dataframe <- calculatePerc(map_dataframe)
    
  data_to_represent <- map_dataframe %>% 
    group_by(CODMUN) %>% 
    do(item = list(
      CODMUN = first(.$CODMUN),
      sequence = .$perc,
      value = first(.$perc))) %>% 
    .$item

  clases <- classIntervals(map_dataframe$perc, 10, style='kmeans')
  paleta <-c("#9ECFEF", "#49AEF1", "#9DEEB4", "#36DB65", "#FFFC95", "#FFF700", "#FFD282", "#FFB112", "#FF8989", "#FF0000")  
    
  map<-highchart(type = "map") %>%
    hc_title(text = "Porcentaje de incidentes por municipio frente al total de Canarias", x = -20) %>%
    hc_add_series(mapData = geojsondataframe, data = data_to_represent, name = "Incidentes por municipio",
                  value = "value", 
                  joinBy = "CODMUN") %>%
    hc_colorAxis(dataClasses = color_classes(clases[[2]], colors = paleta)) %>%
    hc_legend(layout = "horizontal", align = "left", verticalAlign = "bottom",
              floating = FALSE, valueDecimals = 2, Width = "auto", heigth = 600,
              itemWidth = 200, valueSuffix = ' %') %>%
   hc_tooltip(formatter = JS("function(){
return  (this.series.name + '<br><b>' + this.point.name + ': </b>' + this.point.value + ' %')}")) %>% 
    hc_exporting(enabled = TRUE) %>%
    hc_credits(enable = FALSE) %>%
    hc_mapNavigation(enabled = TRUE) %>%
    hc_motion(
    enabled = TRUE,
    axisLabel = "year",
    labels = 2005:2014,
      series = 0,
      updateIterval = 10,
      magnet = list(
        round = "floor",
        step = 0.02
      )
    )
  return(map)
  }
}

At the beginning:
![1](https://cloud.githubusercontent.com/assets/5502157/21518916/73399ff4-cce1-11e6-9439-0c03c4cb3625.PNG)

At the "end":
![2](https://cloud.githubusercontent.com/assets/5502157/21518912/6d511018-cce1-11e6-9c02-fba66196396e.PNG)

**Comment by jbkunst** [comment]
Not sure if this help. Can you chart the map correctly using with out shiny? If this is the case surely if an css issue as you said previously.

**Comment by jbkunst** [comment]
HI @VPlazaM. Any news in this issue?

**Comment by VPlazaM** [comment]
Sorry @jbkunst, I was on holidays without access to my work pc. I'm still struggled at the same point, I'm going to try solve it, I'll keep you updated but if it's something about the shiny's app I'm not sure how to fix it because I can't change the base of this project.

**Comment by VPlazaM** [comment]
Ok @jbkunst, I have fixed the problem, it was a NA value into the dataframe that was making the chart not working well. Thx for your help.

**Comment by jbkunst** [comment]
Nice!
