### ISSUE TITLE
Render static images for pdf/html output

### ISSUE THREAD

**Issue by reinholdsson** [jbkunst/highcharter#24]
Not sure if you have already looked into this, but one feature I would really appreciate is to be able to generate static chart images:

- http://www.highcharts.com/docs/export-module/render-charts-serverside
- https://github.com/highcharts/highcharts-export-server/tree/master/phantomjs

I think it would be really useful when creating different outputs (pdf or html) in rmarkdown. For example, when rendering a pdf document the package would automatically render a static image instead of an interactive javascript chart.

For an example, see: https://github.com/reinholdsson/test-highcharts-server-side-charts

What do you think about adding this feature to highcharter?

Keep up the good work! :)

**Comment by jbkunst** [comment]
Hi @reinholdsson. 

Interesting! Obviously this would be a really nice feature ;).

I'll check the link to see how it works and try to implement. I guess I'll ask some question if you dont mind :sweat_smile: 

Thanks

**Comment by reinholdsson** [comment]
@jbkunst Sounds great! Of course, I'm glad to help :)

**Comment by jbkunst** [comment]
Hi @reinholdsson ,

Doy you know if exists a function to check if you're are knitting to pdf or html? I want to do something like this:

```
knit_print.highchart <- function(...){

  if( I knitting a html ) {
    knit_print.htmlwidget(...)
  } else {
    create_highchart_image(...)
  }

}
```

**Comment by reinholdsson** [comment]
@jbkunst see https://trinkerrstuff.wordpress.com/2014/11/18/rmarkdown-alter-action-depending-on-document/, seems to work!

**Comment by jbkunst** [comment]
@reinholdsson tyvm! 

IT seem that your search skills are better than mine. 

Thanks again!

**Comment by jbkunst** [comment]
Hi @reinholdsson,

knitr (https://github.com/yihui/knitr/blob/master/NEWS.md) will have a feature to generate a static image in no html documents using the https://github.com/wch/webshot. So I will close this issue and we can open if this feature/solution dont work with highcharter.

Kind regards,

**Comment by Bryant-zhu** [comment]
@jbkunst  hey , what if I only what highcharter to be static on my html file ? thanks

**Comment by apuhegde** [comment]
Hello, I'm using the pdf() function to save my plots in a pdf file when I run my R script on the command line (this is why I can't use RMarkdown/knittr). Does highcharter allow saving the charts to a static pdf using the pdf() function?
