### ISSUE TITLE
Using hc_colorAxis on multi-level treemap

### ISSUE THREAD

**Issue by sy2816** [jbkunst/highcharter#240]
Hello, I've been trying to figure out how to get multi-level tree maps to display the color axis in the legend. 

For a reproducible example, I tried adding the color axis to one of the examples on the website. 

```
hc_tm <- highchart() %>% 
  hc_add_series_treemap(tm, allowDrillToNode = FALSE,
                        layoutAlgorithm = "squarified",
                        name = "tmdata") %>% 
  hc_title(text = "Gross National Income World Data") %>% 
  hc_tooltip(pointFormat = "<b>{point.name}</b>:<br>
             Pop: {point.value:,.0f}<br>
             GNI: {point.valuecolor:,.0f}")%>%
  hc_colorAxis()
```
But I just get this generic colorAxis legend and no matter what I set the min/max color values to, it never seems to map to the treemap.
![image](https://cloud.githubusercontent.com/assets/15570967/21904372/617082c8-d8d1-11e6-9b43-e20161101326.png)

I also get the same result when I use the hctreemap() function instead of hc_add_series_treemap(), which appears to be deprecated.

The only times I've been able to work have been with the hchart("treemap") method, but I can't figure out how I'd fill out the x/y parameters for that function because the dataframe that I'm making my treemap has multiple levels.

I'm fairly unfamiliar with the hc_colorAxis function, so any suggestions would be greatly appreciated.

**Comment by joh024** [comment]
It's because `hc_add_series_treemap` maps `vColor` to `valuecolor` instead of `colorValue` (per #98).

For it to work correctly, you need to modify the function so it maps to `colorValue`:

```R
hc_add_series_treemap2 = with(environment(hc_add_series_treemap),
   ## Modified `hc_add_series_treemap`
   ## names colorValue correctly for connection to `hc_colorAxis`
   function (hc, tm, ...)
   {
       assertthat::assert_that(.is_highchart(hc), is.list(tm))
       df <- tm$tm %>% tbl_df() %>% select_("-x0", "-y0", "-w", 
           "-h", "-stdErr", "-vColorValue") %>% rename_(value = "vSize", 
           colorValue = "vColor") %>% purrr::map_if(is.factor, as.character) %>% 
           data.frame(stringsAsFactors = FALSE) %>% tbl_df()
       ndepth <- which(names(df) == "value") - 1
       ds <- map_df(seq(ndepth), function(lvl) {
           df2 <- df %>% filter_(sprintf("level == %s", lvl)) %>% 
               rename_(name = names(df)[lvl]) %>% mutate_(id = "highcharter::str_to_id(name)")
           if (lvl > 1) {
               df2 <- df2 %>% mutate_(parent = names(df)[lvl - 1], 
                   parent = "highcharter::str_to_id(parent)")
           }
           else {
               df2 <- df2 %>% mutate_(parent = NA)
           }
           df2
       })
       ds <- list_parse(ds)
       ds <- map(ds, function(x) {
           if (is.na(x$parent)) 
               x$parent <- NULL
           x
       })
       hc %>% hc_add_series(data = ds, type = "treemap", ...)
   }
)
```

Afterwards, you attach `hc_colorAxis` with the correct min/max colours from `tm`:

```R
hc_colorAxis(minColor = tm$tm$color[which.min(tm$tm$vColorValue)],
             maxColor = tm$tm$color[which.max(tm$tm$vColorValue)])
```

**Comment by sy2816** [comment]
Got it working on my end. Thanks!

**Comment by jbkunst** [comment]
All the thanks to @joh024 !!!
