### ISSUE TITLE
Tooltip with map point series

### ISSUE THREAD

**Issue by KaterinaKou** [jbkunst/highcharter#243]
Hello! I have been using the tooltip option with no problems so far but I have a bit of trouble figuring out how I can use it when adding a mappoint type of series.
I have a data frame and I want to display more info on the tooltip (e.g. "ip" column) but I can't see how I can parse the dataframe accordingly in that case.  Map and points show up fine.

My code:

```
json_file <- "path to geojson file"
json_data <- fromJSON(file=json_file)
data <-read.csv("path to .csv file", encoding="UTF-8", header = TRUE)
data_geojson <- geojson_json(data, lat = "lat", lon = "lon")
class(data_geojson)

highchart(type = "map") %>%
  hc_add_series(mapData = json_data, showInLegend = FALSE) %>%
  hc_xAxis(crosshair = list(zIndex = 5, dashStyle = 'dot', snap = FALSE, color = '#8A8A8A')) %>%
  hc_yAxis(crosshair = list(zIndex = 5, dashStyle = 'dot', snap = FALSE, color = '#8A8A8A')) %>%
  hc_mapNavigation(enabled = TRUE)  %>%
  hc_add_series(data = data_geojson, type = "mappoint",  dataLabels = list(enabled = FALSE),  name = "Wifi Spots",   tooltip = list(pointFormat = "{point.ip}")) 

```
Thanks in advance!

**Comment by jbkunst** [comment]
Hi @KaterinaKou 

You can check this examples.

 - http://jkunst.com/highcharter/highmaps.html#advanced-maps, and
 - http://jkunst.com/highcharter/highmaps.html#adding-more-data

The first one use something like "{point.properties.ip}" is you use geojson. The second one uses only lat and long, maybe this can be a easier approach if your map live in https://code.highcharts.com/mapdata/.

Hope this helps. Tell me how it goes.

**Comment by KaterinaKou** [comment]
First approach worked fine. Thank you!
