### ISSUE TITLE
Learn crosstalk, why not?

### ISSUE THREAD

**Issue by jbkunst** [jbkunst/highcharter#245]

**Comment by jbkunst** [comment]
http://jsfiddle.net/gh/get/jquery/3.1.1/highcharts/highcharts/tree/master/samples/highcharts/chart/events-selection-points/

**Comment by smach** [comment]
It would be very cool if Highcharter supported crosstalk!

**Comment by prise6** [comment]
Hi,

Is the code in dev/crosstalk supposed to work ?
I don't really understant how the function hcct work right now. Any example ?

Thank you!
