### ISSUE TITLE
hc_add_series.xts X-axis not defaulting to stock type

### ISSUE THREAD

**Issue by doug-friedman** [jbkunst/highcharter#252]
I'm not entirely sure if this is by design, but the new hc_add_series.xts function that is replacing the now deprecated hc_add_xts function does not specify the X-axis is of "stock" type which results in a numeric version of the date timestamps.  #213 

Here's a simple example:

```r
library(highcharter)
library(xts)

x = sample(x=1:100, size=1000, replace = T, prob = NULL)
index_x = seq(from = as.Date("1980/1/1"), by=1, along.with = x)
my_xts = xts(x, index_x)

# Old hc_add_series_xts syntax
highchart() %>% 
  hc_add_series_xts(my_xts, name="Series") %>%
  hc_title(text="XTS Series Added with hc_add_series_xts")

# Using the new generic syntax yields a numeric x-axis
highchart() %>% 
  hc_add_series(data = my_xts, name="Series") %>%
  hc_title(text="XTS Series Added with hc_add_series")

# Need x-axis type as stock
h1 = highchart() %>% 
       hc_add_series(data = my_xts, name="Series") %>%
       hc_title(text="XTS Series Added with hc_add_series")
h1$x$type = "stock"
h1
```

@Schec

**Comment by jbkunst** [comment]
Hi @doug-friedman 

Yep, the old `hc_add_series_xts` changes the type of chart to stock. I decided the funcions `hc_add_series.*` add and only __add__ data , i.e. no modify other attributes of the chart.

Anyway you can do:

```r
highchart(type = "stock") %>% 
  hc_add_series(data = my_xts, name="Series") %>%
  hc_title(text="XTS Series Added with hc_add_series")
```

Hope this way looks natural to you.

**Comment by doug-friedman** [comment]
Hey @jbkunst,
Thanks so much for the quick answer on this! This is perfect.

Best,
Doug
