### ISSUE TITLE
Highcharter licensing for professional use

### ISSUE THREAD

**Issue by iclarke** [jbkunst/highcharter#254]
Good morning,

I have been experimenting with Highcharter over the past couple weeks with great satisfaction. I am conscious that Highcharts is not free for professional use, so I assume Highcharter is not free either. Would purchasing a Highchart license allow me to use Highcharter in R for professional use ? Or should we follow a different approach and deal with yourself directly ?

Again, congrats for this wonderful package.

Best regards

Samy

**Comment by jbkunst** [comment]
Good morning @iclarke Samy!

Happy to read that!

Highcharter is just a wrapper and the R code in the wrapper is open source. So, if you want to use for professional use you need a highcarts license. For highcharters users there is a discount http://announcements.highcharts.com/foss/ ;).

With that license highcharts offer you support 24/7 etc, but not sure if they offer the R support if you have some issues. So you need to come here and see we can solve it, but unlike highcharts, I'm not offering any priority, but obivously I want my package free of bugs, so eventually I will take some time to solve any problems with the package.

Hope I was clear ;).

Best regards,

**Comment by iclarke** [comment]
Thanks, very clear indeed, I'll get in touch with them and continue rocking some Highcharter code in my dashboards !

**Comment by iclarke** [comment]
Hi, 

Sorry to re-open. I've followed the link you've provided and was very pleased with the 50 % discount. Could you please indicate which license should I purchase to be able to use Highcharter within RStudio :  Highcharts/Highstocks/Highmaps or everyhthing ? 

Thanks for your help.

**Comment by jbkunst** [comment]
Hi, no problem.

Highcharter uses almost everithing, basically __highstock.js + maps.js + modules + plugins (by 3rs)__ (https://github.com/jbkunst/highcharter/tree/master/inst/htmlwidgets/lib/highcharts-5.0.6). I think it's a good alternative contact the highcharts people to know what you need ;)!

**Comment by airball2000** [comment]
Hello @jbkunst 

thanks for your work. Highcharter is so great !
the link with the licence discount doesn't work (http://announcements.highcharts.com/foss/)
Do you know if this discount is still available ?

Best regards
Arnaud

**Comment by jbkunst** [comment]
https://newsletter.highcharts.com/foss/

**Comment by Arizonagong** [comment]
Hi. I really appreciate for you to make this wonderful package allowing me to use Highcharts through R program. I have one question here. I installed your package but I haven't seen any message yet indicating I may need to insert my license key to use the professional Highchart. Then, when does it request my license?
