### ISSUE TITLE
hchart_aes fails to evaluate variables in parent environment

### ISSUE THREAD

**Issue by lissahyacinth** [jbkunst/highcharter#255]
When defining a local variable - date_variable - to select a column by, it is expected that by defining eval(date_variable), hchart will then use that column. 

Attached is an example of expected and actual behaviour. 

```
library(dplyr)
library(highcharter)
set.seed("1234")

data = data.frame("date" = seq(from = as.Date("2016-01-01"), to = as.Date("2016-01-14"), by = 1), 
                  "week" = c(rep(1,7), rep(2,7)),
                  "value" = runif(n = 14, min = 0.1, max = 1.0))

date_variable = "week"

data2 = data %>% group_by_(date_variable) %>% summarise("value" = sum(value))

#Expected Behaviour - No NSE

hchart(data2,
       "line",
       hcaes(
       x = "week",
       y = "value")
)

#Actual Behaviour - NSE

hchart(data2,
       "line",
       hcaes(
         x = eval(date_variable),
         y = "value")
)
```

**Comment by jbkunst** [comment]
Hi @lissahyacinth 

Thanks for this, but I'm new in this SE and NSE. So not sure if this can be solved using the `hcaes_` function:

Instead of:

```r
hchart(data2,
       "line",
       hcaes(
         x = week,
         y = value)
)

#  and
hchart(data2,
       "line",
       hcaes(
         x = eval(date_variable),
         y = "value")
)
```

You can use for SE:

```r
hchart(data2,
       "line",
       hcaes_(
         x = date_variable,
         y = "value")
)
```

Can you tell me if the issue can be solve using `hcaes_`?

**Comment by lissahyacinth** [comment]
It does fix that test, but it doesn't fix the issue I'm having in prod, so I guess I need to improve my example! 

So my prod is more similar to the below, where I'm using a NSE to evaluate between input options on a Shiny dashboard - hence the date_variable, and I'm then doing a manipulation on the Y variable similar to mean, and a grouping variable. 

I can create a failure without the group, so I think this is a MRE for the issue I'm having. 

```
hchart(data2,
       "line",
       hcaes_(
         x = eval(date_variable),
         y = mean("value")
)
```

**Comment by jbkunst** [comment]
Ok, in got it. Can you send a minimal reproducible shiny example? If we can't fix it with the actual version it will be sure add the PR to the master ;)! 

Thanks in advance.

**Comment by lissahyacinth** [comment]
Unfortunately, I think I've figured out how to do it. 

The below is the example, and the issue I was having was that hcaes_ wasn't accepting round(value, 2) as it wants to accept a text result, but it seems to be comfortable accepting a function if it's wrapped in text. 

I think it might be easier to mark this closed & add some documentation that includes shows this use, because this isn't typical behaviour for a NSE input. 

```
library(shiny)
library(highcharter)
ui <- fluidPage(
  titlePanel("Highcharter Example"),
      sidebarLayout(
      sidebarPanel(
        selectInput(inputId = "TimeSeriesSelector", 
                    label = "Group Data by Day or Week",
                    choices = c("Day" = "date", "Week" = "week"), 
                    selected = "date")
      ),
        mainPanel(
         highchartOutput("hPlot")
      )
   )
)
server <- function(input, output) {
   set.seed("1234")
   data = data.frame("date" = seq(from = as.Date("2016-01-01"), to = as.Date("2016-01-14"), by = 1), 
                    "week" = c(rep(1,7), rep(2,7)),
                    "value" = runif(n = 14, min = 0.1, max = 1.0))
   output$hPlot <- renderHighchart({
            hchart(data, 
            type = "line",
            hcaes_(
              x = eval(input$TimeSeriesSelector), 
              y = "round(value,2)"
            ))
   })
}
shinyApp(ui = ui, server = server)

```

**Comment by jbkunst** [comment]
Ok, as you wish, but I have some questions/recommendations

To test, I modified the app with:

```r
...
  output$hPlot <- renderHighchart({
    
    data <- data %>% 
      group_by_(.dots = input$TimeSeriesSelector) %>% 
      summarize(value = sum(value))
    
    hchart(data, 
           type = "line",
           hcaes_(
             x = input$TimeSeriesSelector, 
             y = "value"
           )) %>% 
      hc_tooltip(valueDecimals = 2)
  })
...
```

Qs:
- Why use `eval()` if `input$TimeSeriesSelector` is a character so it can be used with `hcaes_`

Rs
- You can put `hcaes_(..,  y = "value")` and control the print decimal using `hc_tooltip(valueDecimals = 2)`

Finally, YES! The package is lacking in documentation, thanks for remebering me ^^ to do that boring but needed part. 

Thanks again!

Best,
