### ISSUE TITLE
Issues with `data.table`

### ISSUE THREAD

**Issue by cmhh** [jbkunst/highcharter#263]
I've noticed I get errors when using `data.table` with functions such as `hc_add_series`.  I imagine this is because `hc_add_series.data.frame` is dispatched, and doesn't work quite right if the `data.table` package is loaded.  A simple fix is to always pass in `data.frame(dt)`, but I wonder if this could be handled explicitly within the package?  Perhaps by adding `hc_add_series.data.table`, for example.

**Comment by jbkunst** [comment]
Hi @cmhh 

Ooops. Thanks. I will fix this at home ;)!

**Comment by jbkunst** [comment]
I run: 
```r
library(data.table)
library(highcharter)

dt <- data.table(x=rep(c("b","a","c"),each=3), y=c(1,3,6), v=1:9)
head(dt)


hchart(dt, "scatter", hcaes(x = v, y))

highchart() %>% 
  hc_add_series(dt, "scatter", hcaes(x = v, y))
```

without problems: http://rpubs.com/jbkunst/highcharter-issue-263

Can we check your sessionInfo?

**Comment by jbkunst** [comment]
No problem

**Comment by cmhh** [comment]
Not sure what the protocol is regarding commenting on a closed issue...

It turns out it wasn't the `highcharter` version at all.  It seems that this happens when the `dtplyr` package is loaded:

```r
library(data.table)
library(highcharter)

dt <- data.table(x=rep(c("b","a","c"),each=3), y=c(1,3,6), v=1:9)

hchart(dt, "scatter", hcaes(x = v, y))

library(dtplyr)

hchart(dt, "scatter", hcaes(x = v, y))
```

After loading `dtplyr`, I get the following error:

```asis
Error in UseMethod("select_") : 
  no applicable method for 'select_' applied to an object of class "NULL"
```

I guess this is some sort of masking issue related to `dtplyr`?

Cheers

**Comment by jbkunst** [comment]
Don't worry,

I will look into it to see what happends ;).

**Comment by jbkunst** [comment]
Hi @cmhh 

Internally, I forced to be only a `data.frame` class, and in my test this work well. Please teste to check in your enviorment.

Thanks

**Comment by jbkunst** [comment]
I'll close the issue. If you still have problem we can reopen. 

Regards,
