### ISSUE TITLE
Checkbox-like option

### ISSUE THREAD

**Issue by ekstroem** [jbkunst/highcharter#265]
I'm trying to get my head around adding a way to add an option to choose between different sets of series to display. Right now I'm creating a nice plot with 7 lines with the following code.

```{r}
hchart(indata, "line", hcaes(x = range, y = hit, group = aim, be=be, aim=aim))
```

However, I'd like to choose between 4 different sets of series of lines either through checkboxes / radio buttons / something else. Should I be looking at crosstalk or a plugin to get that working?

[And I know I most likely will have to add the series manually instead of through `hchart` unless I can choose the series through one of the variables in `hcaes`]

**Comment by jbkunst** [comment]
Hi @ekstroem 

Sorry for the late response.

highcharts have  `id` and `linkedTo` parameters to help group series in _one_ legend. The easy way to use this adding the series separately as you said.

```r
library(tidyverse)
library(highcharter)

n <- 10

gen_data <- function(n) {
  cumsum(rnorm(n) + runif(1))
}
gen_data 

highchart() %>% 
  hc_chart(type = "line") %>% # set default type line 
  hc_add_series(data = gen_data(n), name = "Group I", id = "g1") %>% 
  hc_add_series(data = gen_data(n), linkedTo = "g1") %>% 
  hc_add_series(data = gen_data(n), linkedTo = "g1") %>% 
  hc_add_series(data = gen_data(n), name = "Group II", id = "g2") %>% 
  hc_add_series(data = gen_data(n), linkedTo = "g2") %>% 
  hc_add_series(data = gen_data(n), linkedTo = "g2") 
```
![image](https://cloud.githubusercontent.com/assets/56481/23095701/06ef7460-f5ed-11e6-9ad2-a72bdd999d08.png)



It's possible do this in a less code using `hc_add_series_list` but is needed know the structure of your data first . So, if you want, send your data to try how can do this, for example:

```r
data <- arrange(mtcars, hp)

series <- data %>% 
  group_by(cyl, am) %>% # the group and the series in the every group
  do(data = list_parse2(data_frame(.$hp, .$mpg))) %>% 
  arrange(cyl)

series

# A tibble: 6 × 3
    cyl    am        data
  <dbl> <dbl>      <list>
1     4     0  <list [3]>
2     4     1  <list [8]>
3     6     0  <list [4]>
4     6     1  <list [3]>
5     8     0 <list [12]>
6     8     1  <list [2]>
> 


series <- series %>% 
  mutate(id = ifelse(!duplicated(cyl), paste0("g", cyl), NA),
         linkedTo = ifelse(duplicated(cyl), paste0("g", cyl), NA),
         color = colorize(cyl))

series 


# A tibble: 6 × 6
    cyl    am        data    id linkedTo   color
  <dbl> <dbl>      <list> <chr>    <chr>   <chr>
1     4     0  <list [3]>    g4     <NA> #440154
2     4     1  <list [8]>  <NA>       g4 #440154
3     6     0  <list [4]>    g6     <NA> #21908C
4     6     1  <list [3]>  <NA>       g6 #21908C
5     8     0 <list [12]>    g8     <NA> #FDE725
6     8     1  <list [2]>  <NA>       g8 #FDE725

highchart() %>% 
  hc_add_series_list(series)
```

![image](https://cloud.githubusercontent.com/assets/56481/23095700/fb38bc4e-f5ec-11e6-9b1a-377bd7d863ee.png)

**Comment by ekstroem** [comment]
Wonderful! Almost got me to the end with very few lines of code.

I did look into the `linkedTo` argument and have decided to go that route even though I have 16 different series based on a combination of 4 binary variables which is why I originally thought of the checkboxes.

Is it possible to add extra information so I can tailor the tooltips? Here's a code piece of code where extra stuff is added to `hcaes` and the chart is generated using the amazing `hchart`

```{r}
hc2 <- hchart(indata, "line", 
              hcaes(x = range, y = hit, group = aim, be=be, aim=aim, id=status, linkedTo=status)) %>%
       hc_tooltip(table=TRUE, headerFormat = "", pointFormat = "<b>Aim {point.aim}, range {point.x}</b><br>Hit: {point.y}% (BE: {point.be}%)")
```

Is it possible to add that extra information as part of call to `do` or is that piece of information lost as part of `list_parse2` as in the example below.

```{r}
series <- data %>% 
  group_by(cyl, am) %>% # the group and the series in the every group
  do(data = list_parse2(data_frame(.$hp, .$mpg, .$carb, .$gear))) %>% 
  arrange(cyl)
```

I did try the code above (also with adding names for `.$carb` and `.$gear`) but I cannot reference them in the `hc_tooltip` call.

**Comment by jbkunst** [comment]
Fist see the difference between:
``` r
df <- data.frame(a = 1:2, type = c("A", "C"), stringsAsFactors = FALSE)
list_parse(df)
#> [[1]]
#> [[1]]$a
#> [1] 1
#> 
#> [[1]]$type
#> [1] "A"
#> 
#> 
#> [[2]]
#> [[2]]$a
#> [1] 2
#> 
#> [[2]]$type
#> [1] "C"
list_parse2(df)
#> [[1]]
#> [[1]][[1]]
#> [1] 1
#> 
#> [[1]][[2]]
#> [1] "A"
#> 
#> 
#> [[2]]
#> [[2]][[1]]
#> [1] 2
#> 
#> [[2]][[2]]
#> [1] "C"
```

The `list_parse2` dont preserve names so this can be used when we now the arguments order to every series in highcharts (for example in line, first one is for x and the second for y, etc). So in this case you need use `list_parse`:

```

series <- data %>% 
  group_by(cyl, am) %>% # the group and the series in the every group
  do(data = list_parse(data_frame(x = .$hp, y = .$mpg, disp = .$disp))) %>% 
  arrange(cyl)

series <- series %>% 
  mutate(id = ifelse(!duplicated(cyl), paste0("g", cyl), NA),
         linkedTo = ifelse(duplicated(cyl), paste0("g", cyl), NA),
         color = colorize(cyl))

series 


highchart() %>% 
  hc_add_series_list(series) %>% 
  hc_tooltip(table = TRUE, pointFormat = "<b>disp {point.disp} and hp: {point.x}")
```
![image](https://cloud.githubusercontent.com/assets/56481/23098526/4a926cae-f62e-11e6-9725-1e6019c04f8c.png)

**Comment by jbkunst** [comment]
I'll close this, but we can reopen if is needed ;).

**Comment by ekstroem** [comment]
Yup. Perfectly fine. I'll still tweaking things around trying not to get RStudio to crash, but it's certainly an issue on this side of the computer. Thanks for all your help.

**Comment by jbkunst** [comment]
You're welcome. If you need help don't hesitate to ask via stackoverflow or here.
