### ISSUE TITLE
hc_colorAxis on matrix not changing colors

### ISSUE THREAD

**Issue by tnederlof** [jbkunst/highcharter#266]
Hi there, first of all you have created a fantastic package that I am enjoying using. I hope to learn more about the highchart library and contribute someday as I come up the learning curve. I am having issues changing the color scheme of correlation (or any matrix for that matter) using hc_colorAxis. If this is intended to not work then please let me know and I will close this but incase this is a bug I wanted to give some examples...

Two examples that I would expect to have with the new color legends and data, however they dont change regardless of what options I put in hc_colorAxis.

```
test_data <- matrix(rexp(200, rate=.1), ncol=20)

hchart(cor(test_data)) %>% hc_colorAxis(stops = color_stops(8, c("#0000CD","#8ba9fe","#fee08b","#cc0000")))
hchart(volcano) %>% hc_colorAxis(stops = color_stops(8, c("#0000CD","#8ba9fe","#fee08b","#cc0000")))

```

Code below works properly (took from function documentation for hc_colorAxis)
```
highchart() %>% 
  hc_chart(type = "heatmap") %>% 
  hc_title(text = "Simulated values by years and months") %>% 
  hc_xAxis(categories = month.abb) %>% 
  hc_yAxis(categories = 2016 - nyears + seq(nyears)) %>% 
  hc_add_series(name = "value", data = ds) %>%
  hc_colorAxis(stops = color_stops(8, c("#0000CD","#8ba9fe","#fee08b","#cc0000")))
```
```

**Comment by jbkunst** [comment]
Hi @tnederlof ,

There are some issues with you want to replace some existing value (as the defaul color scales) with a new one because internally the code uses merge.list so the elements are combined instead of overwrite them. 

So, there are two way to get what you want meanwhile I see how I can avoid this behavior:

1. Remove the existing color scale and put yours.
```r
library(highcharter)
test_data <- matrix(rexp(200, rate=.1), ncol=20)

hc <- hchart(cor(test_data))
hc$x$hc_opts$colorAxis$stops <- NULL

hc %>%
  hc_colorAxis(stops = color_stops(8, c("#0000CD","#8ba9fe","#fee08b","#cc0000")))
```
2. Transform matrix  to data and put your color scale.
```r
library(tidyverse)


data <- cor(test_data) %>% 
  as.data.frame() %>% 
  mutate(row = paste0("V", seq(1, nrow(.)))) %>% 
  gather(column, value, -row)

hchart(data, "heatmap", hcaes(row, column, value = value)) %>% 
  hc_colorAxis(stops = color_stops(8, c("#0000CD","#8ba9fe","#fee08b","#cc0000"))) %>% 
  hc_xAxis(reversed = FALSE) %>% 
  hc_yAxis(reversed = TRUE)
```

Hope this help,

**Comment by tnederlof** [comment]
Very interesting, thank you for the prompt response and examples. It certainly works just setting the stops to NULL to clear out that list element then re-adding. I am happy to close or leave this open if its helpful for you to keep track. I imagine others will try what I tried and get confused why the stops dont change. Thanks again!

**Comment by jbkunst** [comment]
No problem.

Yeah, let's keep this open until I fix this thing.

**Comment by jbkunst** [comment]
I did'nt find a way to make this more simple. Until now the clearer way  to override the previous values is doing something like:

```r
hchart(cor(test_data)) %>%
  hc_colorAxis(stops = NULL) %>% 
  hc_colorAxis(stops = color_stops(8, c("#0000CD","#8ba9fe","#fee08b","#cc0000"))) 

hchart(volcano) %>%
  hc_colorAxis(stops = NULL) %>% 
  hc_colorAxis(stops = color_stops(8, c("#0000CD","#8ba9fe","#fee08b","#cc0000")))
```

I will close the issue due inactivity from my part but we can reopen :sweat_smile:
