### ISSUE TITLE
Dynamic data label values

### ISSUE THREAD

**Issue by bogdanrau** [jbkunst/highcharter#267]
I have the following data frame:

location  | estimate | flag
----------|-----------|-----
Loc1       | 30.2 | †
Loc2       | 18.4 | 
Loc3       | 15.5 | † 

The code on the bottom produces the following bar chart:

![image](https://cloud.githubusercontent.com/assets/7134642/22895965/30af0496-f1d3-11e6-9159-d87d92a26681.png)

What I am trying to accomplish is to add that flag (or whatever may be in that flag column or any additional column) into the bar chart, like so (notice the red crosses):

![image](https://cloud.githubusercontent.com/assets/7134642/22896165/e4c14c1e-f1d3-11e6-95cd-c76a1623d32d.png)

That cross represents an indication about whether the data label is reliable. Any insight on how this might be done? I'm assuming it's in the formatter option, but I can't seem to get it to work.

```
highchart(
        width = 450,
        height = 150
      ) %>%
        hc_chart(
          width = 450,
          height = 150,
          marginTop = 0,
          marginRight = 0,
          marginBottom = 0,
          marginLeft = 0
        ) %>%
        hc_add_series(
          data = data$estimate,
          categories = data$location,
          type = "bar",
          pointWidth = 24) %>%
        hc_legend(
          enabled = FALSE
        ) %>%
        hc_xAxis(
          categories = data$location,
          labels = list(
            x = 5,
            y = 4,
            align = "left",
            style = list(
              whiteSpace = "nowrap",
              color = "#FFFFFF"
            )
          ),
          lineWidth = 0,
          tickLength = 0
        ) %>%
        hc_yAxis(
          visible = FALSE
        ) %>%
        hc_plotOptions(bar = list(
          colorByPoint = TRUE,
          pointPadding = 0,
          groupPadding = 0.05,
          states = list(
            hover = list(
              enabled = FALSE
            )
          ),
          animation = FALSE,
          dataLabels = list(
            align = "left",
            enabled = TRUE,
            formatter = JS(paste0("function() {
                           var max = this.series.yAxis.max,
                           color = this.y / max < 0.89 ? '#0D538D' : '#FFFFFF';
                           return '<span style=\"color: ' + color + '\">' + this.y + '%</span>';
    }")),
          style = list(color = "#0D538D", textShadow = "0"),
          shadow = FALSE,
          x = 1,
          y = 1
            ))
        ) %>%
        hc_tooltip(
          enabled = FALSE
        ) %>%
        hc_colors(list(
          "#0D5AA5", "#8BB3DA", "#F07B39"
        ))
```

**Comment by jbkunst** [comment]
First of all, in this case I recommend use `hchart` function (or hc_add_series(data =  a_data_frame) instead because you send all the columns data. So you can use all this info (columns) in the `formatter` function argument among others (like tooltips, etc). 

So:

```r

hchart(data, "bar", hcaes(x = location, y = estimate)) %>% 
 ...
  hc_plotOptions(bar = list(
    colorByPoint = TRUE,
    pointPadding = 0,
    groupPadding = 0.05,
    states = list(
      hover = list(
        enabled = FALSE
      )
    ),
    animation = FALSE,
    dataLabels = list(
      align = "left",
      enabled = TRUE,
      formatter = JS(paste0("function() {
                           var max = this.series.yAxis.max,
                           color = this.y / max < 0.89 ? '#0D538D' : '#FFFFFF';
                           return '<span style=\"color: ' + color + '\">' + this.y + '%</span>' + '<span style=\"color: red\"> ' + this.point.flag + '</span>';
    }")),
      style = list(color = "#0D538D", textShadow = "0"),
      shadow = FALSE,
      x = 1,
      y = 1
    ))
  )
...
````

![image](https://cloud.githubusercontent.com/assets/56481/22897175/840e125c-f201-11e6-80e9-f1ae951e040a.png)

:wink:

__note__ this can't be seen in the rstudio viewer, you need to open in your browser.

**Comment by jbkunst** [comment]
I'll close the issue, but we can reopen if is needed ;).

**Comment by LuShuYangMing** [comment]
How to apply that to boxplot xaxis label color? Below is a small example, for example, if one group is statistically significant, the group label should be colored red (p value < 0.05).
Supppose I have already get a data frame, the first column is the group label, the second column is the significant (p value).

`dat <- data_to_boxplot(ToothGrowth,len,dose,supp)`
`highchart() %>%
  hc_add_series_list(dat)%>%hc_colors(c("green","red"))`
