### ISSUE TITLE
Feature request: error_bar series type

### ISSUE THREAD

**Issue by martinjhnhadley** [jbkunst/highcharter#270]
Thanks for highcharter, it's awesome!

I'd like to add a feature request - support for the `error_bar` plugin http://www.highcharts.com/plugin-registry/single/38/error_bar

**Comment by jbkunst** [comment]
Hi @martinjhnhadley ,

Thanks to you for try the package ;)!.

I tried to put the plugin but there some errors. I think is due the repo have 2 years without any commit and don't consider some (maybe) critical updates like highcharts 4 -> 5 among others.

Why do you need the pluging insead of use the built in error bar http://www.highcharts.com/demo/error-bar? What feature do you think is missed?


![image](https://cloud.githubusercontent.com/assets/56481/23136122/fae104ca-f779-11e6-90b9-372b39445b99.png)

![image](https://cloud.githubusercontent.com/assets/56481/23136099/e50e92d4-f779-11e6-9605-33adb171ee07.png)

**Comment by martinjhnhadley** [comment]
I might be totally wrong, but it appeared the built-in errorbar series
didn't support horizontal error bars.

That's what I'm interested in the error_bars plugin for. But didn't realise
it was that out of date :/

**Comment by jbkunst** [comment]
It's possible to put them horizontal if you change the type of chart to _bar_:

```r
library(dplyr)
library(highcharter)

n <- 5
set.seed(123)

df <- data.frame(x = seq_len(n) - 1) %>% 
  mutate(
    y = 10 + x + 10 * sin(x),
    y = round(y, 1),
    z = (x*y) - median(x*y),
    e = 10 * abs(rnorm(length(x))) + 2,
    e = round(e, 1),
    low = y - e,
    high = y + e
  )
df

highchart() %>% 
  hc_chart(type = "bar") %>% 
  hc_add_series(df, "errorbar", hcaes(x = x, low = low, high = high))
```
![image](https://cloud.githubusercontent.com/assets/56481/23137362/5a988e78-f780-11e6-848a-5785806100d6.png)

Another option would be chart the error bars manually using lines, but this will need more code to obtain the points of the whiskers, etc, but in 100% possible.

**Comment by martinjhnhadley** [comment]
Ahh! Thank you for providing support on Highchart.JS, very helpful! I
didn't feel this was well covered by the official documentation so you've
saved me a lot of bother.

This meets my current needs, don't know if you'd want to close this request
or see if others are interested.

Cheers,

Martin

**Comment by jbkunst** [comment]
Nice. 

Let's close. This will keep helping others even if this is closed.

Regards,

Joshua
