### ISSUE TITLE
Incorrect default value for hc_opts$plotOptions$bubble$maxSize

### ISSUE THREAD

**Issue by joh024** [jbkunst/highcharter#272]
The default per the [official highcharts API](http://api.highcharts.com/highcharts/plotOptions.bubble) is `"20%"` but currently `highcharter` has it set to `25`.

This fixed pixel maximum will frequently break large bubble charts with the user having no idea why until they discover the default is different in `highcharter` after trial and error.

**Comment by jbkunst** [comment]
Yeah, I abused and override the default with my taste. Maybe this is not a good options so I remove them ;)!

Thanks as always.

**Comment by jbkunst** [comment]
Don't you think they look too big? 

```r
hchart(cars, "point", hcaes(dist, speed, size = speed))
```

![image](https://cloud.githubusercontent.com/assets/56481/23215493/52143b7c-f8f1-11e6-9551-a4294b935446.png)


```r
hchart(cars, "point", hcaes(dist, speed, size = speed), maxSize = "10%")
```
![image](https://cloud.githubusercontent.com/assets/56481/23215547/96b56e72-f8f1-11e6-9107-b62fc09e684c.png)

**Comment by joh024** [comment]
That's why it's an argument, so if someone feels it's too big they can set a lower maximum. But I'd say the defaults should be consistent with `highcharts`.

**Comment by jbkunst** [comment]
Ok, sounds good. The change to defaults was made. Thanks again,
