### ISSUE TITLE
units in plotBands?

### ISSUE THREAD

**Issue by joelgombin** [jbkunst/highcharter#279]
I'm trying to create plotBands on the X axis, which is a time series (date). Therefore I need to pass Date values. However, I don't manage to do it; what format is expected?

**Comment by jbkunst** [comment]
Hi @joelgombin 

Transform the date using the datetime_to_timestamp. See http://stackoverflow.com/questions/41573626/highcharter-plotbands-plotlines-with-time-series-data

Cheers,

**Comment by joelgombin** [comment]
Great, thanks! (I guess it should probably be documented somewhere, though? Maube just add an example?)

**Comment by jbkunst** [comment]
Yep, you're right! I'll put this example somewhere in the website. Thanks for the recommendation ;)
