### ISSUE TITLE
Assign a global color theme

### ISSUE THREAD

**Issue by bogdanrau** [jbkunst/highcharter#282]
The link below shows a jsfiddle that uses `setOptions({colors:...})` to set a global color theme. Is this already reproducible in the current version of highcharter, or could this be added to the roadmap?

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/colors/

Ref: http://api.highcharts.com/highcharts/colors (see try it)

**Comment by jbkunst** [comment]
Hi @bogdanrau 

Have you tried?

**Comment by jbkunst** [comment]
http://jkunst.com/highcharter/highcharts-api.html#hc_colors

**Comment by bogdanrau** [comment]
I think I may not have explained the intent clearly. What I'd want to do is set the color (theme) globally for any and all charts produced. So removing the need to call hc_color every time a chart is rendered.

**Comment by jbkunst** [comment]
Sorry, my bad.

You need to use `highcharter.theme` in `options`:

```r
library(highcharter)

# standard theme
highcharts_demo()

# creting custom theme with new colors
newtheme <- hc_theme_merge(
  getOption("highcharter.theme"),  
  hc_theme(colors = c("#d35400", "#2980b9", "#2ecc71", "#f1c40f"))
)

# setting as default
options(highcharter.theme = newtheme)
highcharts_demo()        
hchart(mtcars, "point", hcaes(disp, hp, group =  cyl))
  
# changing the default
options(highcharter.theme = hc_theme_flatdark())
highcharts_demo()        
hchart(mtcars, "point", hcaes(disp, hp, group =  cyl))
```

**Comment by bogdanrau** [comment]
Excellent! Thank you sir!
