### ISSUE TITLE
Unwanted buttons in Shiny Server Hosted App

### ISSUE THREAD

**Issue by jjcole415** [jbkunst/highcharter#284]
I really love the ability to incorporate these charts.  However, I recently deployed a couple of our shiny apps to our own server running shiny server and I noticed that some buttons were showing up in our charts. Below is a photo of the buttons.  They seem to be buttons which a permit the user to add a text box or other features to the chart.  I could not find any documentation on these. 

![image](https://cloud.githubusercontent.com/assets/10905001/24053801/6a5446c4-0af7-11e7-8a0c-a809cc797818.png)

the code used to produce this chart is (I left this uncommented to preserve the look):

output$VAMI_chart <- renderHighchart({
    VAMI.Data <- round(VAMI(), 2)
      hc.opts <- list()
      hc.opts$title <- list(text = "Value of $1000 (VAMI)")
      hc.opts$subtitle <- list(text = paste("Showing data for", format.Date(index(VAMI.Data)[1], "%m/%d/%Y"),"to", format.Date(index(VAMI.Data)[nrow(VAMI.Data)], "%m/%d/%Y"), sep = " "))
      hc.opts$credits <- list(enabled = FALSE)
      hc.opts$xAxis <- list(categories = as.character.Date(index(VAMI.Data)))
      hc.opts$yAxis <- list(title = list(text = " VAMI in $"),
                            labels = list(format = "${value}"))
      hc.opts$tooltip <- list(crosshairs = TRUE, shared = TRUE)
      hc.opts$series <- lapply(colnames(VAMI.Data), function(x){
        return(list(name = x,
                    type = "spline",
                    data = VAMI.Data[,x]))
      })
      highchart(hc.opts)
  })

The data is a simple xts time series of the value of $1000 multiplied by the cumulative return of a given investment and its benchmarks.  It seems to affect both line and bar charts. IT does not occur on other charts that are coded using another method:

![image](https://cloud.githubusercontent.com/assets/10905001/24054105/49611af4-0af8-11e7-9fe3-7456cde969ca.png)

`output$longShortChart <- renderHighchart({
    mgrName <- input$managerSelect
    longShort <- exposureData[which(exposureData$`Manager Name` == mgrName), c(3,9:12)]
    longShort[,2:5] <- round(longShort[,2:5]*100, 1)
    
    highchart() %>% 
      hc_title(text = "Long/Short Exposure") %>% 
      hc_legend(enabled = TRUE) %>% 
      hc_xAxis(categories = longShort$`As of Date`) %>% 
      hc_yAxis_multiples(
        list(
          title = list(text = "Percent"),
          align = "right",
          showFirstLabel = FALSE,
          showLastLabel = FALSE,
          labels = list(format = "{value} %")
        )
      ) %>% 
      hc_plotOptions(
        column = list(
          stacking = "normal"
        )
      )%>%
      hc_add_series(name = "Long", type = "column",
                    data = longShort$`Long MV %`) %>% 
      hc_add_series(name = "Short", type = "column",
                    data = longShort$`Short MV %`) %>%
      hc_add_series(name = "Gross", type = "spline",
                    data = longShort$`Gross %`) %>%
      hc_add_series(name = "Net", type = "spline",
                    data = longShort$`Net %`) %>% 
      hc_colors(c("#7cb5ec","#f07f0c", "#4f4b47", "#f2b50f"))
  })
  `

I would prefer not to rewrite all the hc.opts style charts if possible.  It provides flexibility that I need to add multiple series dynamically.  Any advice would be greatly appreciated.  I had previously hosted these through shinyapps.io without any issue.

Best,
Jon

**Comment by jbkunst** [comment]
Hi @jjcole415 

You can use `hc_add_series_list( lapply(your stuff ))` ;). Tell me if this work for you ;)

**Comment by jjcole415** [comment]
Unfortunately not.  When I run the code with this change the chart does not render at all. Any other suggestions?

**Comment by jbkunst** [comment]
Not sure why `hc_add_series_list` dont work, are you sure you use correclty, IMO _this_ is the way to add multiples series at once:

```r
library(highcharter)

n <- 20
l <- 30

data <- lapply(seq(n), function(n){
  list(data = cumsum(rnorm(l)), name = paste("series", n), showInLegend = FALSE)
})

highchart() %>% 
  hc_add_series_list(data) %>% 
  hc_add_theme(hc_theme_smpl())
``` 
![image](https://cloud.githubusercontent.com/assets/56481/24068775/4b0eb874-0b76-11e7-9d1f-bc3750630e32.png)

**Comment by jbkunst** [comment]
The other way is download the development version using devtools, I recenlty remove the _annotations_ pluging so you will not see that buttons:

```r
data <- lapply(seq(n), function(n){
  list(data = cumsum(rnorm(l)), name = paste("series", n), showInLegend = FALSE)
})



hc.opts <- list()
hc.opts$title <- list(text = "Value of $1000 (VAMI)")
hc.opts$subtitle <- list(text = paste("Showing data for", format.Date(index(VAMI.Data)[1], "%m/%d/%Y"),"to", format.Date(index(VAMI.Data)[nrow(VAMI.Data)], "%m/%d/%Y"), sep = " "))
hc.opts$credits <- list(enabled = FALSE)
hc.opts$xAxis <- list(categories = as.character.Date(index(VAMI.Data)))
hc.opts$yAxis <- list(title = list(text = " VAMI in $"),
                      labels = list(format = "${value}"))
hc.opts$tooltip <- list(crosshairs = TRUE, shared = TRUE)
hc.opts$series <- data
highchart(hc.opts)
```

**Comment by jjcole415** [comment]
Great.  So I loaded the development version of the package and the annotation buttons went away.  Is the first version of the code more stable than the hc.opts version?  If you think it will be more reliable I will rewrite the code for those relevant charts.

Thank you again for your help and for producing such a wonderful package.  I love the highcharts graphs and charts, and I recently redid my whole app to make full use of your package.

**Comment by jbkunst** [comment]
I've developed the package thinking around the option 1. The 2nd option works too (at the end the highcharts object is a list) but you lose some features, for example in the `hc_tooltip` there are some options to put the tooltips as a table and be sorted as the value of each series, exist `hc_add_event_series` which is a shortcut to create events when the user click a point in a shiny app, obviously you can mix the sintaxis and the chart will work but will not be so elegant and clean imo.

At the end what matters is how you feel confortable using the package so you do what you want ;).
