### ISSUE TITLE
Error : object ‘dmap_if’ is not exported by 'namespace:purrr'

### ISSUE THREAD

**Issue by niheaven** [jbkunst/highcharter#285]
Hi,

When I install development version of highcharter, I met a error called "Error : object ‘dmap_if’ is not exported by 'namespace:purrr'", and my purrr version is 0.2.2.9000 from github tidyverse/purrr. What's wrong?

Hsiao-nan Cheung

**Comment by jbkunst** [comment]
Hi @niheaven 

From purrrly README:

> purrrlyr contains some functions that lie at the intersection of purrr and dplyr. They have been removed from purrr in order to make the package lighter and because they have been replaced by other solutions in the tidyverse.

See https://github.com/tidyverse/purrr/blob/aea1ce446f3e06b28b2e867a10efbaa29a7498cb/NEWS.md too.

So the simplest option is use the CRAN version of purrr. 

I will change the exports when purrrly reach CRAN.

**Comment by niheaven** [comment]
Thanks, @jbkunst. The packages dependencies from different authors at github are really confused and must be carefully tried...

**Comment by jbkunst** [comment]
Yep. In this case the author is the same ;), the issue is you've installed a developing version. Cheers

**Comment by crtahlin** [comment]
@jbkunst FYI, purrrlyr is now on CRAN.

**Comment by jbkunst** [comment]
@crtahlin 

Can you test `source("https://install-github.me/jbkunst/highcharter")` please? 

Thanks!

**Comment by dpprdan** [comment]
Seems to install fine, @jbkunst

**Comment by jbkunst** [comment]
Nice! Thanks for point this out.

**Comment by crtahlin** [comment]
@jbkunst 
`source("https://install-github.me/jbkunst/highcharter")` installs OK for me. Thank you, best.

**Comment by mexindian** [comment]
For what it's worth, `dmap_if` has a new more or less equivalent `modify_if`

**Comment by jbkunst** [comment]
`dmap_if` was used with `as_data_frame`, now we use `mutate_if` 😅. My rookie dplyr level is decreasing little by little
