### ISSUE TITLE
get only script

### ISSUE THREAD

**Issue by zone4182** [jbkunst/highcharter#288]
Hi, not sure if i'm doing this correctly as it is the first time i actually do something with/in Git.
I'm wondering if there also is a possibilty to only get the generated highchart script instead of actually generating the complete chart already.

**Comment by zone4182** [comment]
Sorry will close this. I found the export_hc function that probably does the trick for me. Guess you are awesome and I am somewhat less awesome ;-).

**Comment by jbkunst** [comment]
Hi @zone4182 

Haha, may be you're the awesome for find something undocumented in my less awesome documentation ;)
