### ISSUE TITLE
Unable to plot polar charts

### ISSUE THREAD

**Issue by earthlong** [jbkunst/highcharter#289]
It seems that the code for multicharts doesn't work (https://github.com/jbkunst/highcharter/blame/master/dev/types.R). Specifically polar charts are not plottable in 0.4.0

**Comment by jbkunst** [comment]
Hi @earthlong 

Sure is it. Have you tried with 0.5.0?

**Comment by earthlong** [comment]
Ok, they work with 0.5.0 but the multichart code still doesn't work.

**Comment by jbkunst** [comment]
Whe you said 'still doesn't work'? What this means? An error, a blank chart,

Did you run:

```
htmltools::browsable(htmltools::tagList(hcs))
```

**Comment by earthlong** [comment]
I was getting blank chart in RStudio Viewer. However running the tagList did the job.

**Comment by jbkunst** [comment]
Ok ;)

**Comment by earthlong** [comment]
Thanks :)
