### ISSUE TITLE
I have problem with multi-axis

### ISSUE THREAD

**Issue by pigkeeper** [jbkunst/highcharter#29]
I cannot set multi-axis with hc_yAxis or hc_xAxis
Please tell me how to solve that.
Thanks very much.

**Comment by jbkunst** [comment]
Hi @pigkeeper :smile: ,

This example can help you: http://jkunst.com/highcharter/#highcharts-home-page-example

Let me know if you solve your doubt.

Regards!

(If you have more doubts about how to use the package please use stackoverflow, highcharts.com, in last instance email ;). I want to keep the github issues with topics relatet to bugs or enhancements)

**Comment by pigkeeper** [comment]
@jbkunst     Thank you very much. I have just solved that~    ^-^

**Comment by jbkunst** [comment]
Nice \\(* *)//
