### ISSUE TITLE
hcaes for highstock charts?

### ISSUE THREAD

**Issue by sam-m-caldwell** [jbkunst/highcharter#291]
Hi there,

Thanks for such a great package!

I'm trying to reproduce something similar to the economics_long example below but through the highstocks chart type. 

`economics_long2 <- filter(economics_long, variable %in% c("pop", "uempmed", "unemploy"))
hchart(economics_long2, "line", hcaes(x = date, y = value01, group = variable)) %>% 
  hc_tooltip(sort = TRUE, table = TRUE)`

Simply changing the type argument to "stock" returns a blank chart. Is it possible to use the hcaes() function through the stocks chart type, given that the dataframe has a datetime column similar to the example above?

**Comment by sy2816** [comment]
Slightly different approach as it doesn't use the hchart function, but the following code puts it in a highstock chart.

```
highchart(type = "stock") %>%
hc_add_series(economics_long2, type = "line", hcaes(x = date, y = value01, group = variable))%>% 
  hc_tooltip(sort = TRUE, table = `TRUE)
```

**Comment by jbkunst** [comment]
Hi @sam-m-caldwell ,

Glad you find an answer by yourself. The "stock" it's a type of chart instead of type of series (like line, bar, etc).

If you want use `hchart` you can use `hc_navigator` or `hc_rangeSelector`  to add the "stock" features:

```r

hchart(economics_long2, "line", hcaes(x = date, y = value01, group = variable),
       showInLegend = FALSE) %>% 
  hc_tooltip(sort = TRUE, table = TRUE) %>% 
  hc_navigator(enabled = TRUE) %>% 
  hc_rangeSelector(enabled = TRUE)
```

**Comment by sam-m-caldwell** [comment]
Fantastic answers, thank you @jbkunst and @sy2816!!

**Comment by jbkunst** [comment]
Sorry @sy2816 , I was confused about who wrote the message! Thanks for help here :D.
