### ISSUE TITLE
Adding flags to series created within hcaes

### ISSUE THREAD

**Issue by sam-m-caldwell** [jbkunst/highcharter#292]
Hello again,

I'm trying to combine examples by adding flags to the line chart of the "economics_long" dataframe as per below:

`economics_long2 <- filter(economics_long, variable %in% c("pop", "uempmed", "unemploy")) 

df.flags = data_frame(
  date = sample(economics_long2$date, size = 5),
  title = sprintf("E #%s", seq_along(date)),
  text = sprintf("An interesting event #%s in %s", seq_along(date), date)
)

hchart(economics_long2, "line", hcaes(x = date, y = value01, group = variable),
       showInLegend = FALSE) %>% 
  hc_tooltip(sort = TRUE, table = TRUE) %>% 
  hc_navigator(enabled = TRUE) %>% 
  hc_rangeSelector(enabled = TRUE) %>%
  hc_add_series(df.flags, hcaes(x = date), type = "flags", onSeries = "pop")`

Unfortunately the "onSeries" reference doesn't seem to find the 'pop' group, as well as the title and text are dropped.

Thanks in advance!!

**Comment by jbkunst** [comment]
Hi @sam-m-caldwell ,

First, please _format_ your code, you need to use tripe: ``` to make code blocks.

`onSeries` need the _id_ of the series, so you need to give that in the `hchart` part:

```
hchart(economics_long2, "line", hcaes(x = date, y = value01, group = variable),
       showInLegend = FALSE, id = c("pop", "uempmed", "unemploy")) %>%
  ...
  hc_add_series(df.flags, hcaes(x = date), type = "flags", onSeries = "pop")
```

The github issues are mainly to discuss bug or new features, you can look answers in stackoverflow first, then use this section as final option ;).

**Comment by sam-m-caldwell** [comment]
Hey @jbkunst,

Thanks for your reply, that works ok but I still have the issue where the title and titles within the flags don't display on the hover (see image below). The hover information is as if it is an extra series with value 0 instead.

Also as a potential enhancement would it be an idea to be able to add the 'id' argument within the 'hcaes' to avoid hard coding in the ids as you have done here?

![image](https://cloud.githubusercontent.com/assets/22283098/24731321/5e3c577a-1abd-11e7-9c2d-a6ed1a0840cc.png)

Thanks again,
Sam
