### ISSUE TITLE
Problem with shape in annotations

### ISSUE THREAD

**Issue by Rhoboot** [jbkunst/highcharter#295]
Hello:

I'm trying to add a shape in an annotation, but I do not visualize anything, apparently it's all ok. 

Do you have any idea what may be happening?

`hc_annotations(list(
                title=list(text="hi!",style=list(color="blue")),
                anchorX= "left",
                anchorY= "top",
                allowDragX= TRUE,
                allowDragY= TRUE,
                x=100,
                y=100,
                shape=list(type="rect",params=list(x=0,y=0,width=55,height=40))
                ))`

**Comment by jbkunst** [comment]
Hi @Rhoboot ,

Sorry, I forgot read this issue, do you still have the problem? In that case can you send me a reproducible example to work with?

**Comment by Rhoboot** [comment]
Yes, now it works for me (draws the box), but notice another problem, since it is a draggable box, moving it leaves the text in the original position.

```
library(highcharter)
highchart() %>%
        hc_chart(renderTo="container") %>%
        hc_series(list(data=c(29.9, 71.5, 106.4, 129.2, 144.0, 176.0))) %>%
        hc_annotations(list(title=list(text="hello world!"),
                            anchorX= "left",
                            anchorY= "top",
                            allowDragX= TRUE,
                            allowDragY= TRUE,
                            x=100,
                            y=100,
                            shape=list(type="rect",
                                       params=list(x=0,y=0,width=75,height=40,fill='rgba(252,255,197,0.7)')
                                       )
                            )
                       )
```
<img width="875" alt="screenshot of rstudio 5-14-17 21-38-39" src="https://cloud.githubusercontent.com/assets/7344313/26039880/baa87b9e-38ed-11e7-82ba-3493507efcff.png">
