### ISSUE TITLE
How to add alternating colors to volume chart in highstock example

### ISSUE THREAD

**Issue by milindnirgun** [jbkunst/highcharter#296]
I want to add alternating colors for up and down days to the volume column graph in the last example in the highstock section. I have created the following version of the example as a function to pass in any object that I have already done a getSymbols() on.
`highplot <- function(d)  {
  names(d) <- c("Open", "High", "Low", "Close", "Volume", "Adjusted")

  barcols <- c()
  c <- as.numeric(d$Close)
  for (i in 1:length(c)) {

    if (i == 1) {barcols[i] <- "#F95959"}

    if (i > 1) {
      barcols[i] <- ifelse(c[i] > c[i - 1], "#F95959", "#595959")
    }
  }

  hc <- highchart(type = "stock") %>%
          hc_yAxis_multiples(create_yaxis(2, height = c(2, 1), turnopposite = TRUE)) %>%
          # series :D
          hc_add_series(d, yAxis = 0, name = "SPY") %>%
          hc_add_series(d$Volume, colors = barcols, yAxis = 1, name = "Volume", type = "column")

  return(hc)
}
`
I could not get the Volume bars to show in different colors. They are printed in gray only although the values are different in barcols vector. What am I doing wrong here?
Appreciate if someone can help. This problem has been bugging me for days.
Thanks.

**Comment by wildeyes** [comment]
@milindnirgun maybe this will help https://forum.highcharts.com/highstock-usage/set-volume-color-in-two-panes-candlestick-and-volume-t29671/
