### ISSUE TITLE
Tablet/Mobile usability - No scrolling possible - Highcharter capturing all touch events

### ISSUE THREAD

**Issue by jetzler** [jbkunst/highcharter#297]
Hi, we absolutly love highcharter and are using it for noumerous shiny based dashboard projects.
Our single problem: Usability on tablets. All touch events seem to be captured by tooltips.
When touching/clicking on the chart we can not scroll up/down. Only the tooltips are triggered.

We do not have this problem using Highcharts, only highcharter. The various Highcharts options: panning, followTouchMove etc. seem to have no effect here.

Hope you can give us a hint!

edit: 
If you need an example. Touch/scroll does also not work with the examples on the highcharter page.
http://jkunst.com/highcharter/hchart.html
e.g. in chrome open developemnt mode and toggle device toolbar

**Comment by jbkunst** [comment]
@jetzler 

I can't test yet, but I will look into this, looks very strange.

**Comment by kuzmenkov111** [comment]
+1

**Comment by wjsellers** [comment]
Running into same issue with highcharter on R Markdown html pages on iPhone with Safari, Firefox and Chrome and can confirm on hchart.html page mentioned above. Also love highcharter!

**Comment by nicholaelaw** [comment]
Same here. Tried looking in the dev console in Chrome, but found no obvious culprit. However I did notice that there's not a single event listener on `highcharts-container` from the Highcharts demo, while the chart generated through hightcharter has a number of them.
Perhaps the problem originates from the `htmlwidget` container?
