### ISSUE TITLE
shinydashboard integration

### ISSUE THREAD

**Issue by benalmer** [jbkunst/highcharter#298]
I am using highcharter with shinydashboard.
Already set chart width to '100%', but the chart doesn't resize when the sidebar panel is expanded/collapsed (unless in chrome DevTools) . Is there any way to fix it?

Thanks

**Comment by benalmer** [comment]
Just found out that the issue is from shinydashboard

**Comment by jbkunst** [comment]
Hi @benalmer , 

Sorry for don't reply. I remember made some hack with javascript when the sidebar change the width but I didn't find it.

Can you share your solution, may be can help others ;)!

**Comment by benalmer** [comment]
@jbkunst 

It can be solved by including this script on the shinyapp

`$(document).on("click", ".sidebar-toggle", function() {
     $(window).trigger("resize");
   });`

because the graph will react on window resizing

**Comment by chenx2018** [comment]
@jbkunst 

May I know if this problem is solved in the newest development version of highcharter? I still got this resizing problem in shinydashboard.
