### ISSUE TITLE
Inverted axes

### ISSUE THREAD

**Issue by benalmer** [jbkunst/highcharter#299]
In which function am I supposed to put `inverted` axes argument? Can't find a way to use it in highcharter

Thanks

**Comment by jbkunst** [comment]
@benalmer 

Usually, you need to find in highchart documentation **first**, then use the same argument in highcharter.

See: https://www.google.cl/search?q=highcharts+reverted+axis&oq=highcharts+reverted+axis&aqs=chrome..69i57j69i60l2j69i65l2j69i60.4625j0j4&sourceid=chrome&ie=UTF-8

Then (not sure what you want): 
- http://www.highcharts.com/demo/area-inverted, or
- http://www.highcharts.com/stock/demo/yaxis-reversed

And see the jsfiddles.

So:

```r
hc %>%
  hc_yAxis(reversed = TRUE) %>%
  hc_chart(inverted = TRUE)   
```
Finally, @ultinomics have a nice post showing how highcharts API and highcharter works http://ultinomics.org/2017/04/05/thinking-in-highcharter---how-to-build-any-highcharts-plot-in-r/#highcharts-api-and-highcharter-functions.

**Comment by benalmer** [comment]
@jbkunst 

This line doesn't give any effect:
` hc_chart(inverted = TRUE) `

it's supposed to switch the axes (e.g column chart is gonna look like a bar chart when inverted)

**Comment by jbkunst** [comment]
Can you try?:

![image](https://cloud.githubusercontent.com/assets/56481/25113638/236ed238-23cf-11e7-8590-7bd6017a061f.png)

**Comment by henry090** [comment]
@jbkunst Hi, how could you invert the following if you have multiple y_axis? I could not find it from official highcharts. Do you have any idea?
http://jkunst.com/highcharter/highstock#a-more-interesting-example

```
SPY <- getSymbols("SPY", from = Sys.Date() - lubridate::years(1), auto.assign = FALSE)
SPY <- adjustOHLC(SPY)

SPY.SMA.10 <- SMA(Cl(SPY), n = 5)
SPY.SMA.200 <- SMA(Cl(SPY), n = 100)
SPY.RSI.14 <- RSI(Cl(SPY))
SPY.RSI.SellLevel <- xts(rep(70, NROW(SPY)), index(SPY))
SPY.RSI.BuyLevel <- xts(rep(30, NROW(SPY)), index(SPY))


highchart(type = "stock") %>% 
  # create axis :)
  hc_yAxis_multiples(
    create_yaxis(3, height = c(2, 1, 1), turnopposite = TRUE)
  ) %>% 
  # series :D
  hc_add_series(SPY, yAxis = 0, name = "SPY") %>% 
  hc_add_series(SPY.SMA.10, yAxis = 0, name = "Fast MA") %>% 
  hc_add_series(SPY.SMA.200, yAxis = 0, name = "Slow MA") %>% 
  hc_add_series(SPY$SPY.Volume, color = "gray", yAxis = 1, name = "Volume", type = "column") %>% 
  hc_add_series(SPY.RSI.14, yAxis = 2, name = "Osciallator", color = hex_to_rgba("green", 0.7)) %>%
  hc_add_series(SPY.RSI.SellLevel, color = hex_to_rgba("red", 0.7),
                yAxis = 2, name = "Sell level") %>% 
  hc_add_series(SPY.RSI.BuyLevel, color = hex_to_rgba("blue", 0.7),
                yAxis = 2, name = "Buy level") 
```
