### ISSUE TITLE
rounded is not working in solidgauge 

### ISSUE THREAD

**Issue by cls3415** [jbkunst/highcharter#300]
Hi All, 
 I'm trying to reproduce active gauge as this: http://www.highcharts.com/demo/gauge-activity, but I couldn't get the bars rounded. The following is my code. Any thought?

hc<-highchart() %>% 
  hc_chart(type = "solidgauge" ,marginTop=50) %>% 
  hc_title(text = "Activity") %>% 
  hc_tooltip(borderWidth=0,
		backgroundColor = 'none', 
		shadow = FALSE,
		style = list(
			fontSize = '16px'
		),
		pointFormat = "{series.name}<br><span style='font-size:2em; color: {point.color}; font-weight: bold'>{point.y}%</span>"
		
  ) %>%
  hc_pane(
	startAngle = 0,
	endAngle = 360,
	background = list( # track for move
		list(
			outerRadius = '112%',
			innerRadius = '88%',
			backgroundColor = "rgba(19,19,245,.05)",
			borderWidth = 0
		),
		list( # track for exercise
			outerRadius = '87%',
			innerRadius = '63%',
			backgroundColor = "rgba(43, 175, 43, .05)",
			borderWidth = 0

		),
		list(
			outerRadius = '62%',
			innerRadius = '38%',
			backgroundColor = "rgba(0,128,128,.05)",
			borderWidth = 0

		)
	)
  ) %>%
 
  hc_yAxis(
		min = 0,
		max = 100,
		lineWidth = 0,
		tickPositions = list()
  ) %>% 

 hc_plotOptions(
	solidgauge = list(
		dataLabels = list(
			enabled = FALSE
		),
		rounded = TRUE,
		linecap = 'round',
		stickyTracking = FALSE
	)
  ) %>%

  hc_series(
	list(
		name= "Move",
		data =list( 
			list(
			color = "rgb(19,19,245)",
			
			radius= '112%',
			innerRadius= '88%',
			y=80
		)
		)
		
	),
	list(
		name= "Exercise",
		data =list( 
			list(
			y= 65,
			color = "rgb(43, 175, 43)", # green
			radius= '87%',
			innerRadius= '63%'
		)
		)
	),
	list(
      	name = "Stand",
      	data = list( 
			list(
			y=50,
			color="rgba(0,128,128,.5)", # teal
			radius= '62%',
			innerRadius= '38%'
		)
		)
    	)
  )

**Comment by jbkunst** [comment]
@cls3415 

I will look into it soon. 

Please, next time, try to format your code nicely so will be easier for me to help you.

**Comment by jbkunst** [comment]
Not sure, but I have a old example that works, try to see the differences:

```r
highchart(width = 400, height = 400) %>%
  hc_chart(
    type = "solidgauge",
    backgroundColor = "#F0F0F0",
    marginTop = 50
  ) %>%
  hc_title(
    text = "Holi",
    style = list(
      fontSize = "24px"
    )
  ) %>%
  hc_tooltip(
    borderWidth = 0,
    backgroundColor = 'none',
    shadow = FALSE,
    style = list(
      fontSize = '16px'
    ),
    pointFormat = '{series.name}<br><span style="font-size:2em; color: {point.color}; font-weight: bold">{point.y}%</span>',
    positioner = JS("function (labelWidth, labelHeight) {
                    return {
                    x: 200 - labelWidth / 2,
                    y: 180
                    };
                    }")
    ) %>%
  hc_pane(
    startAngle = 0,
    endAngle = 360,
    background = list(
      list(
        outerRadius = '112%',
        innerRadius = '88%',
        backgroundColor = JS("Highcharts.Color('#F62366').setOpacity(0.1).get()"),
        borderWidth =  0
      ),
      list(
        outerRadius = '87%',
        innerRadius = '63%',
        backgroundColor = JS("Highcharts.Color('#9DFF02').setOpacity(0.1).get()"),
        borderWidth = 0
      ),
      list(
        outerRadius = '62%',
        innerRadius =  '38%',
        backgroundColor = JS("Highcharts.Color('#0CCDD6').setOpacity(0.1).get()"),
        borderWidth = 0
      )
    )
  ) %>%
  hc_yAxis(
    min = 0,
    max = 100,
    lineWidth = 0,
    tickPositions = list()
  ) %>%
  hc_plotOptions(
    solidgauge = list(
      borderWidth = '34px',
      dataLabels = list(
        enabled = FALSE
      ),
      linecap = 'round',
      stickyTracking = FALSE
    )
  ) %>%
  hc_add_series(
    name = "Move",
    borderColor = JS("Highcharts.getOptions().colors[0]"),
    data = list(list(
      color = JS("Highcharts.getOptions().colors[0]"),
      radius = "100%",
      innerRadius = "100%",
      y = 80
    ))
  ) %>%
  hc_add_series(
    name = "Exercise",
    borderColor = JS("Highcharts.getOptions().colors[1]"),
    data = list(list(
      color = JS("Highcharts.getOptions().colors[1]"),
      radius = "75%",
      innerRadius = "75%",
      y = 65
    ))
  ) %>%
  hc_add_series(
    name = "Stand",
    borderColor = JS("Highcharts.getOptions().colors[2]"),
    data = list(list(
      color = JS("Highcharts.getOptions().colors[2]"),
      radius = "50%",
      innerRadius = "50%",
      y = 50
    ))
  )
```
![image](https://cloud.githubusercontent.com/assets/56481/25235214/e3f803d4-25ba-11e7-9d9a-555a15b2eed6.png)

**Comment by cls3415** [comment]
@jbkunst 
Thanks!! I'll format my code next time. Sorry about that. 
Looks like I can't use hc_series but hc_add_series instead. 
It works when I use hc_add_series. 

Thanks again for your help!!
