### ISSUE TITLE
Highcharter and includeHTML in Shiny do not work together

### ISSUE THREAD

**Issue by Eflores89** [jbkunst/highcharter#303]
Hi @jbkunst, thanks for a great library, it has been really useful! 

However, I think I might have found a small bug. The following shiny app works perfectly: 

```
#### server: 
library(shiny)
library(highcharter, quietly = T)

data(iris)

shinyServer(function(input, output) {
  output$hcontainer <- renderHighchart({
    hc <- highchart() %>% hc_add_series(data = iris$Sepal.Length)
    hc
  })
})

######  ui:
library(shiny)
library(highcharter, quietly = T)

navbarPage('App Expansión',
           tabPanel("Start",
                    sidebarLayout(
                      sidebarPanel(), 
                      mainPanel() 
                    )
           ), # end panel 
           tabPanel("Model",
                    sidebarLayout(
                      sidebarPanel(),
                      mainPanel(
                        tabsetPanel(
                          tabPanel('Start',
                                   highchartOutput("hcontainer",height = "500px")
                                   ),
                          tabPanel('Table'),
                          tabPanel('Others'),
                          tabPanel('Map')
                          )
                        ) 
                      ) # end sidebar layout 
                    )
           )
```

However, when I add (in any tab) [shiny::includeHTML](https://shiny.rstudio.com/reference/shiny/latest/include.html), the highcharter object does not appear. 

I found this out the hard way: built an entire app and then had to strip it down part by part to debug. I thought it was the tabset panel wrappers but it must be some wierd javascript or html functionality that "erases" one over the other exactly when the `includeHTML` is added. I have no experience with javascript but thought you might like to figure out the bug. 

Thanks again for the package!

**Comment by joh024** [comment]
Have you checked to make sure the problem isn't with improper syntax in the HTML you're including?

**Comment by Eflores89** [comment]
@joh024 yes, the HTML shows perfectly (but not the highchart) and vice-versa

**Comment by joh024** [comment]
I ask because `includeHTML` is literally just reading in the file, wrapping it in `HTML` (so the content isn't escaped) and returning it. There is nothing in the function itself that should interfere with anything else, which leads to the conclusion that the issue must be with the HTML code you're including.

But on the off-chance there's black magic involved (which sometimes happens), I took the app you posted above and modified it to include a basic html file using `includeHTML`. The code is below:

An html file, saved as `test.html` in the current working directory.

```html
<p>Hello</p>
```

Code to run the shiny app, same as posted above, but modified into a straight `runApp` call and with `includeHTML("test.html")` added to the Model side panel.

```R
library(shiny)
library(highcharter, quietly = T)
data(iris)

runApp(list(
server =
shinyServer(function(input, output) {
  output$hcontainer <- renderHighchart({
    hc <- highchart() %>% hc_add_series(data = iris$Sepal.Length)
    hc
  })
}),
ui =
navbarPage('App Expansión',
           tabPanel("Start",
                    sidebarLayout(
                      sidebarPanel(), 
                      mainPanel() 
                    )
           ), # end panel 
           tabPanel("Model",
                    sidebarLayout(
                      sidebarPanel(includeHTML("test.html")),
                      mainPanel(
                        tabsetPanel(
                          tabPanel('Start',
                                   highchartOutput("hcontainer",height = "500px")
                                   ),
                          tabPanel('Table'),
                          tabPanel('Others'),
                          tabPanel('Map')
                          )
                        ) 
                      ) # end sidebar layout 
                    )
           )
))
```

Screenshot displaying the text from the included html file, and the highcharter output, both displaying correctly.

![untitled](https://cloud.githubusercontent.com/assets/3042623/25562093/f2b4da38-2dcf-11e7-86b2-01b11eaa9b0e.png)

**Comment by Eflores89** [comment]
Thanks for your help. 

So i've traced the problem somewhat more. 

It will not work with an html **made from an rmarkdown with knitr**. I created a simple template with a `summary(cars)` and I get the html to show but *not* the highchart object: 
![not1](https://cloud.githubusercontent.com/assets/5789139/25566804/e2c55dec-2da6-11e7-98ba-59f66b7a2182.PNG)

I also tried taking out the code and R objects, to the same issue: 
![not2](https://cloud.githubusercontent.com/assets/5789139/25566809/f80beebe-2da6-11e7-9469-5997c899d760.PNG)

Alas, when I comment the `includeHTML` out:
![yes1](https://cloud.githubusercontent.com/assets/5789139/25566815/08d817ae-2da7-11e7-837e-a0ac21c8373a.PNG)

I further checked in the html file created from knitr and there does seem to be some javascript generated at the top which might be whats causing the problem, but again I don't know anything about javascript! 😭

**Comment by jbkunst** [comment]
Can you send a _reproducible_ example? Try to look the console message in the web browser (F12)

**Comment by Eflores89** [comment]
Yes, it's in the beginning of the issue. 

The html is the RStudio default, github doesn't let me upload html files.

**Comment by jbkunst** [comment]
Sorry ;). You need to knitr your Rmd using `output: html_fragment`, the output will be just html code, no javascript, no css so there will not be conflicts between shiny and rmarkdown js depedencies.

**Comment by Eflores89** [comment]
Ok let me try. Thanks

**Comment by Eflores89** [comment]
I see now. 

So when exporting as fragment you loose all the code CSS and other formatting, which means this document can't be *stand-alone*. However, when including into shiny, it appears to use the shiny's CSS, so it appears formatted. 

I guess it's a decent workable solution for now, thanks!

**Comment by jbkunst** [comment]
Why is not _the_ solution? What do you need? 

I guess _iframe_s is other possible solution: http://stackoverflow.com/questions/22177974/r-shiny-using-iframe-for-local-files

**Comment by Eflores89** [comment]
@jbkunst it *is* the solution!
