### ISSUE TITLE
How to set the color of bar border and filling for histogram plot

### ISSUE THREAD

**Issue by wenbostar** [jbkunst/highcharter#304]
Hi,
Does anyone know how to set the color of bar border and filling for histogram plot? In addition, how to remove the label "Series 1"?

Below is the code I used:

`hchist(x)`

![image](https://cloud.githubusercontent.com/assets/5302110/25567676/acd8a5ba-2db8-11e7-9775-855264709dac.png)

Best regards!
Bo

**Comment by jbkunst** [comment]
Bo @wenbostar ,

By instance you can use:

```r
hchist(x, showInLegend = FALSE, color = "navy")
```
Not sure how to add border color via `hchist`, may be it's easier if you _harcode_ the histogram.

**Comment by jbkunst** [comment]
Finally, read http://ultinomics.org/2017/04/05/thinking-in-highcharter---how-to-build-any-highcharts-plot-in-r/#highcharts-api-and-highcharter-functions and https://cran.rstudio.com/web/packages/highcharter/vignettes/replicating-highcharts-demos.html ;)!
