### ISSUE TITLE
Highcharts responsive feature

### ISSUE THREAD

**Issue by d-qn** [jbkunst/highcharter#305]
Since Highcharts 5.0, there are [additional options for responsive design](https://www.highcharts.com/docs/chart-concepts/responsive).

[highcharts API](http://api.highcharts.com/highcharts/responsive.rules.chartOptions)

I believe one cannot access this feature from R & highcharter.

**Comment by jbkunst** [comment]
Hi @d-qn ,

I'll do it now! Glad you try to use this nice features, I forgot added before ;).

**Comment by d-qn** [comment]
Awesome, cheers :-)

**Comment by jbkunst** [comment]
@d-qn ,

Try download the dev version (`source("https://install-github.me/jbkunst/highcharter")`) and run:

```r
leg_500_opts <- list(enabled = FALSE)
leg_900_opts <- list(align = "right", verticalAlign = "middle",  layout = "vertical")

highcharts_demo() %>%
  hc_responsive(
    rules = list(
      # remove legend if there is no much space
      list(
        condition = list(maxWidth  = 500),
        chartOptions = list(legend = leg_500_opts)
      ),
      # put legend on the right when there is much space
      list(
        condition = list(minWidth  = 900),
        chartOptions = list(legend = leg_900_opts)
      )
    )
  )
```

The legend will have different behavior depending of the width. Tell me please if this work for you.

**Comment by d-qn** [comment]
Sweet, that was quick :-). It seems to work perfectly, thank you

**Comment by jbkunst** [comment]
Nice. I'll close the issue ;)
