### ISSUE TITLE
highchart2 not working?

### ISSUE THREAD

**Issue by doug-friedman** [jbkunst/highcharter#306]
I'm trying to run [your simple example of `highchart2()`](https://github.com/jbkunst/highcharter/blob/434aedede8328d8722a0342a8d6e6609a6eafe65/dev/boots.src.R) and all I get is a blank page in the browser window.

Here's the code I used:
```R

n <- 50000

x <- sin(4*2*pi*seq(n)/n) + rnorm(n)/10

plot(x)

highchart2() %>%
  hc_chart(zoomType = "x") %>%
  hc_add_series(data = x)

```

If it helps, I'm attaching the resulting HTML generated by the above code.

[highchart2_example_html_and_files.zip](https://github.com/jbkunst/highcharter/files/976476/highchart2_example_html_and_files.zip)

**Comment by jbkunst** [comment]
Hi @doug-friedman 

It was my fault, not sure how I deleted the yaml file. Now it's working in the dev version. 

Tip: Remember make some `round(x, 4)` to make the file lightweiht and don't take some time in generate the html, see some discussion in #264

**Comment by jbkunst** [comment]
@doug-friedman  please tell me if this work now for close the issue.

**Comment by doug-friedman** [comment]
That worked! Thanks for the quick fix!
