### ISSUE TITLE
Font fallback on Edge because of missing MIME type

### ISSUE THREAD

**Issue by timsneath** [jbkunst/highcharter#308]
On Edge, the embedded fonts used for charts aren't rendering correctly, but are falling back to a default. This seems to be because the MIME type isn't specified for the stylesheet references in highchart.js and highchart2.js.

On Edge 40: 
![edge](https://cloud.githubusercontent.com/assets/2319867/25835669/7274f2ec-3435-11e7-8dd9-7acf25c5e0e5.png)

On Chrome 57:
![chrome](https://cloud.githubusercontent.com/assets/2319867/25835673/77d28ca4-3435-11e7-961a-acaf99b2c9d0.png)

Per the [HTML5 standard for the link element](http://www.w3.org/TR/html5/document-metadata.html#attr-link-type), a type is not required, but if it _is_ specified, "the value **must** be a valid MIME type".

**Comment by jbkunst** [comment]
@timsneath,

Oh, my fault! I forgot add the MIME type. Thank you very much for that PR!

**Comment by jbkunst** [comment]
closed by #309

**Comment by timsneath** [comment]
Thanks so much!

**Comment by jbkunst** [comment]
No! Thanks to YOU!
