### ISSUE TITLE
Dependency purrr::dmap_if deprecated

### ISSUE THREAD

**Issue by dpprdan** [jbkunst/highcharter#312]
The function `dmap_if` used in `hcparcords` is deprecated in `purrr` as of [version 0.2.2.1](https://cran.r-project.org/web/packages/purrr/news.html) and moved to the new package `purrrlyr`. (Why this "aggressive change" was release as a patch beats me, but that's not the issue here. )

This means that the github version of `highcharter` cannot be installed at the moment.

**Comment by jbkunst** [comment]
Hi @dpprdan 

I'm working on this now. I will close the issue due is duplicated of #285 

Cheers

**Comment by dpprdan** [comment]
Yes, sorry, I should have searched for this in the open issues before.

**Comment by jbkunst** [comment]
No problem! ;)
