### ISSUE TITLE
bug in hc_add_series_times_values: marker can not be set

### ISSUE THREAD

**Issue by MarkusBonsch** [jbkunst/highcharter#318]
In the function hc_add_series_times_values, the marker is hardcoded disabled.
I guess, this is not desired. I guess that the function should be changed as follows (just removed `marker = list(enabled = FALSE)`:

```hc_add_series_times_values
function (hc, dates, values, ...) 
{
    assertthat::assert_that(is.highchart(hc), is.numeric(values), 
        is.timepoint(dates))
    timestamps <- datetime_to_timestamp(dates)
    ds <- list_parse2(data.frame(timestamps, values))
    hc %>% hc_xAxis(type = "datetime") %>% hc_add_series(data = ds, ...)
}```

**Comment by jbkunst** [comment]
Hi @MarkusBonsch ,

`hc_add_series_times_values` is being deprecated, I can _fix_ the code, but I suggest you use:

```r
library(highcharter)

t <- Sys.Date() + 1:10
y <- rnorm(10)

df <- data.frame(t, y)

highchart() %>% 
  hc_xAxis(type = "datetime") %>% 
  hc_add_series(df, "line", hcaes(t, y))


# instead of
highchart() %>% 
  hc_add_series_times_values(t, x)
```

;)!

**Comment by MarkusBonsch** [comment]
Thank you very much for the clarification.

**Comment by jbrant** [comment]
Does hc_add_series with xAxis type of "datetime" only work for dates? I can't get it to work for POSIXct.

**Comment by jbrant** [comment]
Never mind, the "datetime_to_timestamp" function did the trick. Thanks!
