### ISSUE TITLE
How to modify `Highcharts.setOptions` in highcharter

### ISSUE THREAD

**Issue by changshun** [jbkunst/highcharter#321]
Dear jbkunst,

I want the change the default Date format into Chinese, which seems to need modifying `Highcharts.setOptions`  [lang](http://api.highcharts.com/highstock/lang). I do not know how to realize it in `highcharter`.  

Thank you!

**Comment by jbkunst** [comment]
Hi @changshun 

Thanks @sy2816 !

Yes, by now, that's the way you can do what you want. Let us know how it goes ;)!
