### ISSUE TITLE
Only first series of multi-series scatter/bubble charts displaying on latest development version

### ISSUE THREAD

**Issue by sy2816** [jbkunst/highcharter#322]
After installing the latest development version, I noticed some strange things going on with the scatter/bubble charts using hchart. Only the first series of a multi-series scatter/bubble plot is displaying for me by default, despite the fact that the other series are not hidden. I've found that you can eventually see the other series by hiding/unhiding the other series, but it takes a lot of work to get all of them to even show up.

Here's a minimal example:
```
a <- c("one","two", "three", "four")
b <- c(1:4)
d <- c("first group", "second group", "third group", "fourth group")

data <- data.frame(a,b,d)

hchart(data, "bubble", hcaes(x=a, y=b, group=d))
```
![image](https://user-images.githubusercontent.com/15570967/26977980-c0f8931c-4cf7-11e7-9e76-69ed09685b06.png)

And here's what that same code did before I installed a later development version:
![image](https://user-images.githubusercontent.com/15570967/26978045-fd5d8740-4cf7-11e7-9f3b-58bc1db432a9.png)

**Comment by jbkunst** [comment]
Hi @sy2816 

Sorry for the late reply, I run your code from the dev version and it worked, can you try again. Not sure what happend here.

**Comment by sy2816** [comment]
I installed the latest development version and no longer have the issue.

**Comment by jbkunst** [comment]
Thanks!
