### ISSUE TITLE
hcboxplot function error

### ISSUE THREAD

**Issue by chriswweibo** [jbkunst/highcharter#324]
I am running the official example, but an error reported.
```
data(diamonds, package = "ggplot2")
hcboxplot(x = diamonds$x, var = diamonds$color,
          name = "Length", color = "#2980b9")
```

error:
Error in mutate_impl(.data, dots) : 
  Column `data` must be length 1 (the group size), not 5

Confused!

**Comment by jbkunst** [comment]
Hi @chriswweibo,

Fixed in #323 ;)!
