### ISSUE TITLE
Define width by chart in hw_grid

### ISSUE THREAD

**Issue by S-UP** [jbkunst/highcharter#326]
Hi,

When using hw_grid() on e.g. a time series and a column chart, the column chart gets 50% of the width available of the combined object. I would like to do something like a 2:1 split. I've tried to set the chart width in the column chart, but this seems not to translate into the combined object in hw_grid().

Would be great to hear how you would suggest solving this, and whether we can expect some change in the hw_grid() feature in the near future.

Thanks!

**Comment by jbkunst** [comment]
Hi @S-UP 

Sorry for the late reply.

highcharter have inside its dependencies simple-grid.css. So you can use htmtools package and simple-grid.css to do whatever you want. For example:

```r
hc1 <- hchart(forecast::forecast(AirPassengers))
hc2 <- hchart(iris$Species)

library(htmltools)

# you can use col-2-3 or col-6-12
# same way col-1-3 and col-4-12
tags$div(
  class = "grid grid-pad",
  tags$div(class = "col-2-3", "chart1"),
  tags$div(class = "col-1-3", "chart2")
)

# So:
divs <- tags$div(
  class = "grid grid-pad",
  tags$div(class = "col-2-3", hc1),
  tags$div(class = "col-1-3", hc2)
)

browsable(divs)
```

![image](https://user-images.githubusercontent.com/56481/27608041-fa75fb88-5b53-11e7-894a-559163a430c0.png)

Note that simple grid have a responsive behaviour so if you window in small then you will see one chart above the other one.

I will close the issue, but we can reopen if is necessary.

Regards,

**Comment by S-UP** [comment]
Awesome. Thanks a lot!
