### ISSUE TITLE
Set dual yAxis and multiple yAxis in one plot

### ISSUE THREAD

**Issue by miluylin** [jbkunst/highcharter#328]
Hi jbkunst,
I would like set the multiple yAxis in sequence.
1. Dual yAxis (price (type = candlestick )and volume (type = column))
2. MACD
3. RSI
4. KD

Could you give an example that combining dual yAxis and multiple yAxis in chart?

Once I set the `hc_yAxis_multiple` in format list(), list(), list(), it shows in the first Dual yAxis only.
For dual yAxis, it can be done by below.
1. Dual yAxis (price (type = candlestick )and volume (type = column)), MACD

```R
 hc_yAxis_multiples(
    list(crosshair= list(snap = TRUE, zIndex = 6),
         labels   = list(style  = list(color = "#012d5a" )),
         title    = list(text  =  'Price',
                         style = list(color = "#012d5a" )), 
         offset   = 30,
         min = min(Lo(stockQry)),
         max = max(Hi(stockQry)),
         opposite = TRUE
    ),
    list(gridLineWidth = 0,
         labels        = list(style = list(color = "#cccccc")),
         title         = list(text  =  'Volume',
                              style = list(color = "#cccccc")),
         min = 0,
         opposite = FALSE
    )
)
```

For multiple yAxis, it can be done by below.
1. (price (type = candlestick )
2. MACD
3. RSI
4. KD
```R
hc_yAxis_multiples(#newaxis
      create_yaxis(
        naxis  = 4,
        height = c(2,0.8,0.5,0.5),
        offset = 30,
        sep    = 0.00,
        turnopposite = FALSE,
        title  = list(text = NULL)
        # lineWidth = 2
      )
    )
```

**Comment by wave-electron** [comment]
Is this the kind of stock chart UI your trying to build with highcharter?

<img width="2553" alt="screen shot 2017-06-21 at 1 17 23 pm" src="https://user-images.githubusercontent.com/16273780/27365617-530f56d8-5684-11e7-8d7e-af91a62a2f7e.png">

**Comment by wave-electron** [comment]
A small code chunk of how you format the chart above. 

```
 p <- p %>% hc_yAxis_multiples(
                    list(top = "0%", height = "40%", title = list(text = "VOLUME"),opposite=FALSE),
                    list(top = "0%", height = "40%", title = list(text = "OHLC") ,opposite=TRUE),
                    list(top = "40%", height = "40%", title = list(text = "CHANGE"),labels = list(format = "{value}%"), showFirstLabel = TRUE, showLastLabel = TRUE),  
                    list(top = "80%", height = "20%", title = list(text = "MFI"),labels = list(format = "{value}"),opposite=TRUE),
                    list(top = "80%", height = "20%", title = list(text = "RSI"),labels = list(format = "{value}"),opposite=FALSE), 
                    list(top = "80%", height = "20%", title = list(text = "Stoch"),labels = list(format = "{value}"),opposite=FALSE)
                  )

```

**Comment by wave-electron** [comment]
Example of the same chart UI with only Volume, OHLC and event flags selected.

<img width="2466" alt="screen shot 2017-06-21 at 1 39 07 pm" src="https://user-images.githubusercontent.com/16273780/27366076-2b40fbea-5687-11e7-982a-45a70705a30e.png">

**Comment by wave-electron** [comment]
code chunk for the one above
   
 ```
print("print the chart")
            
   
p <- highchart(type = "stock") %>%
              hc_rangeSelector(selected = 1) %>%
              hc_yAxis_multiples(list(title = list(text = "VOLUME"),opposite=FALSE),list(title = list(text = "OHLC"),opposite=TRUE)) %>% 
              hc_add_theme(eval(parse(text=input$themes))) %>% 
              hc_legend(enabled = TRUE,verticalAlign = "top") %>% 
              hc_add_series(dataInput()[[1]][,5], color = "#b3b3cc", yAxis = 0,  zIndex = 0, name = "VOLUME",type = "column") %>% 
              hc_add_series(round(dataInput()[[1]],2),name=  names(dataInput())[1],  zIndex = 2,  id = names(dataInput())[1], yAxis = 1 , type=input$chartType, fillOpacity= 0.1) %>%
              hc_plotOptions(series = list(groupPadding = 0,borderWidth=1))  
            
          }


```

**Comment by miluylin** [comment]
@wave-electron Thanks for this great example. I'm stuck here for few weeks.

 I saw your suggestion then I just change the quantmod chart to highcharter.

Thanks for your suggestion again.
<img width="684" alt="2017-06-21 11 57 10" src="https://user-images.githubusercontent.com/18286058/27366622-e90f02ec-5679-11e7-8a30-e1be15dc6659.png">

**Comment by jbkunst** [comment]
Thanks @wave-electron that is a _really good and complete_ example :D!

**Comment by miluylin** [comment]
Thanks @jbkunst  highcharter is very useful.

**Comment by wave-electron** [comment]
@miluylin 

Thanks @jbkunst highcharter is very useful.

You can say that again! Awesome package.
