### ISSUE TITLE
How can I convert a shapefile or geojson to a large list like "uscountygeojson" data?

### ISSUE THREAD

**Issue by JellisHeRo** [jbkunst/highcharter#329]
I've been very curious about this and never considered the possibility of a map taking the form of a "Large list" like some of the data from the `highcharter` package.

**Comment by jbkunst** [comment]
Hi @JellisHeRo ,

Sorry for the late reply.

Not sure about your question can you be more specific? Basically a geojson is a json with some specific format and a json is like a list or a nested diccionationatry, etc, so nothing weird there  :sweat_smile: 

Tell me if this convinces you

**Comment by aephidayatuloh** [comment]
Hi @jbkunst, I think this thread is the realted issue to my problem.

When I use `hcmap("countries/id/id-all)`, I found that there are missing region (should be 34 provinces, but only there 33). How can I update, or use shapefiles, for my map?

Best Regards

**Comment by jbkunst** [comment]
Hi @aephidayatuloh 

Try using geojson files:

- http://jkunst.com/highcharter/highmaps.html#geojsonio-package
- http://jkunst.com/highcharter/highmaps.html#advanced-maps

Regards,
