### ISSUE TITLE
Select option export in hc_exporting()

### ISSUE THREAD

**Issue by GiCollini** [jbkunst/highcharter#331]
Hi,

Is it possble to select which options are shown in the menu generated by hc_exporting() among "Print chart", "Download PNG image", "Download JPEG image", "Download SVG vector image", "Download PDF document", "Download CSV", "Download XLS" and "View data table"?

In particular I would like to not have "Print chart" and "View data table"

Thanks,

G.

**Comment by jbkunst** [comment]
Hi @GiCollini 

It possible, you need to see a hicharts(JS) example and then replicate in highcarter. 

For example look http://api.highcharts.com/highcharts/exporting.buttons.contextButton and the examples:

- http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/exporting/buttons-contextbutton-menuitems/
- http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/exporting/buttons-contextbutton-onclick/

And the examples in http://api.highcharts.com/highcharts/Chart.exportChart


Please, tell me your result when you try this approach ;)!

**Comment by nicholaelaw** [comment]
Hmm, @jbkunst, I just tried limiting export options to just PNG and SVG. I failed.

Here's the reference example from Highcharts: [jsfiddle](http://jsfiddle.net/gh/get/jquery/3.1.1/highslide-software/highcharts.com/tree/master/samples/highcharts/exporting/menuitemdefinitions/)

In the example, if you would ignore the `menuItemDefinition` part, is just an array of button names:

```js
buttons: {
  contextButton: {
    menuItems: ['downloadPNG', 'downloadSVG', 'separator', 'label']
  }
}
```

Here's what I did, (taking an example from [here](http://jkunst.com/highcharter/highcharts-api.html#hc_title-hc_subtitle-hc_credits-and-hc_legend-hc_tooltip-hc_exporting):

```r
data(citytemp)

hc <- highchart() %>%
  hc_xAxis(categories = citytemp$month) %>%
  hc_add_series(name = "Tokyo", data = citytemp$tokyo) %>%
  hc_add_series(name = "London", data = citytemp$london) %>%
  hc_add_series(name = "Other city",
                data = (citytemp$tokyo + citytemp$london)/2)

hc %>%
  hc_title(text = "This is a title with <i>margin</i> and <b>Strong or bold text</b>",
           margin = 20, align = "left",
           style = list(color = "#90ed7d", useHTML = TRUE)) %>%
  hc_subtitle(text = "And this is a subtitle with more information",
              align = "left",
              style = list(color = "#2b908f", fontWeight = "bold")) %>%
  hc_credits(enabled = TRUE, # add credits
             text = "www.lonk.tomy.site",
             href = "http://jkunst.com") %>%
  hc_legend(align = "left", verticalAlign = "top",
            layout = "vertical", x = 0, y = 100) %>%
  hc_tooltip(crosshairs = TRUE, backgroundColor = "#FCFFC5",
             shared = TRUE, borderWidth = 5) %>%
  hc_exporting(
    enabled = TRUE,
    menuItemDefinitions = list(
      label = list(
        onclick = JS('function() {
          this.renderer.label("You just clicked a custom menu item.", 100, 100)
          .attr({fill: "#a4edba", r: 5, padding: 10, zIndex: 10})
          .css({fontSize: "1.5em"})
          .add();
        }'),
        text = 'Show label'
      )
    ),
    buttons = list(
      contextButton = list(
        menuItems = list('downloadPNG', 'downloadSVG', 'separator', 'label')
    ))
  ) # enable exporting option
```

The menu items are just four 'undefined', nothing happens on click. What did I do wrong?

**Comment by samWieczorek** [comment]
Hi @nicholaelaw,
I have exactly the same question as yours. Did you find a solution for the 'undefined' items ?

**Comment by nicholaelaw** [comment]
@samWieczorek Nope. I had to adjust my expectations.

**Comment by samWieczorek** [comment]
I tried this short example. the menu is well displayed but nothing happens with the button click.

    library("highcharter")

    hc <- highchart() %>% 
      hc_chart(type = "line") %>% 
      hc_series(
        list(
            data = c(29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4)
        )) %>%
    hc_exporting(
        enabled=T,
                 
        buttons=list(
            contextButton=list(
                menuItems= list(
                    list(
                        text= 'Export to PNG',
                        onclick= 'function () {this.exportChart()}'
                    )
                )
            )
        )
    )
    hc

Where is the mistake ?

**Comment by samWieczorek** [comment]
@nicholaelaw : I have installed the dev version of highcharter and your code seems to work

**Comment by nicholaelaw** [comment]
@samWieczorek I'll give it a test then.

**Comment by upcnet-dmendez** [comment]
Hi @nicholaelaw & @samWieczorek, I tried your code but it didn't work to me. I had to do some modifications to get a good result:

```data(citytemp)

export <- list(
  list(text="PNG image",
       onclick=JS("function () { 
                  this.exportChart({ type: 'image/png' }); }")),
  list(text="JPEG image",
       onclick=JS("function () { 
                  this.exportChart({ type: 'image/jpeg' }); }")),
  list(text="SVG vector image",
       onclick=JS("function () { 
                  this.exportChart({ type: 'image/svg+xml' }); }")),
  list(text="PDF document",
       onclick=JS("function () { 
                  this.exportChart({ type: 'application/pdf' }); }")),
  list(separator=TRUE),
  list(text="CSV document",
       onclick=JS("function () { this.downloadCSV(); }")),
  list(text="XLS document",
       onclick=JS("function () { this.downloadXLS(); }")),
  list(text="Show label",
       onclick=JS('function() {
          this.renderer.label("You just clicked a custom menu item.", 100, 100)
          .attr({fill: "#a4edba", r: 5, padding: 10, zIndex: 10})
          .css({fontSize: "1.5em"})
          .add();
        }'))
)

hc <- highchart() %>%
  hc_xAxis(categories = citytemp$month) %>%
  hc_add_series(name = "Tokyo", data = citytemp$tokyo) %>%
  hc_add_series(name = "London", data = citytemp$london) %>%
  hc_add_series(name = "Other city",
                data = (citytemp$tokyo + citytemp$london)/2)

hc %>%
  hc_title(text = "This is a title with <i>margin</i> and <b>Strong or bold text</b>",
           margin = 20, align = "left",
           style = list(color = "#90ed7d", useHTML = TRUE)) %>%
  hc_subtitle(text = "And this is a subtitle with more information",
              align = "left",
              style = list(color = "#2b908f", fontWeight = "bold")) %>%
  hc_credits(enabled = TRUE, # add credits
             text = "www.lonk.tomy.site",
             href = "http://jkunst.com") %>%
  hc_legend(align = "left", verticalAlign = "top",
            layout = "vertical", x = 0, y = 100) %>%
  hc_tooltip(crosshairs = TRUE, backgroundColor = "#FCFFC5",
             shared = TRUE, borderWidth = 5) %>%
  hc_exporting(enabled=TRUE,
               formAttributes=list(target="_blank"),
               buttons=list(contextButton=list(
                 text="Export", theme=list(fill="transparent"),
                 menuItems=export)))```

**Comment by JBRINGLEY** [comment]
@upcnet-dmendez your solution works only for CSV for me. Did you ever get the PNG, PDF, etc options to work?

**Comment by upcnet-dmendez** [comment]
@JBRINGLEY Yes, all options work to me. Have you done any modification to the code that can change the result?

**Comment by NarendraSadhanala** [comment]
@upcnet-dmendez , your solution works, but how can I download the original data set (citytemp), not the modified one (not the plotted data)

**Comment by MirjamZengers** [comment]
@upcnet-dmendez your solution work verry wel fro this issue! I would like to have the option "View data table", how would I add that?

**Comment by MirjamZengers** [comment]
@upcnet-dmendez , your solutions works very well when I try to use it!
However, I would like to have the option "View data table", do you know how I would add this?

**Comment by oscarchang1226** [comment]
I get all the default menu items in the browser inspector console 

`Highcharts.getOptions().exporting.buttons.contextButton.menuItems` 

and get 

`["printChart", "separator", "downloadPNG", "downloadJPEG", "downloadPDF", "downloadSVG", "separator", "downloadCSV", "downloadXLS", "viewData", "openInCloud"]`.

Then create a vector of desired options and add it into `hc_exporting()` arguments.
```
myMenuItems -> c("downloadPNG", "downloadJPEG", "downloadPDF", "downloadCSV" )
hightchart() %>%
    hc_exporting(
        buttons = list(contextButton = list(menuItems = myMenuItems))
    )
```
