### ISSUE TITLE
"mapline" "mapbubbles" issue

### ISSUE THREAD

**Issue by CamilaAchury** [jbkunst/highcharter#332]
Hi! In the  previous version to 0.5.0.9999 when you added bubbles and lines in a map worked perfectly. But now hc_add_seres with type = "mapline" or "mapbubbles" doesn't add layers in a map, why?

**Comment by jbkunst** [comment]
Hi, @CamilaAchury 

Please, provide an example to work with. Thanks

**Comment by CamilaAchury** [comment]
Hi @jbkunst  I share with you the next example , which is in your page:  

cities <- data.frame(
  name = c("London", "Birmingham", "Glasgow", "Liverpool"),
  lat = c(51.507222, 52.483056,  55.858, 53.4),
  lon = c(-0.1275, -1.893611, -4.259, -3),
  z = c(1, 2, 3, 2)
)

hcmap("countries/gb/gb-all", showInLegend = FALSE) %>% 
  hc_add_series(data = cities, type = "mapbubble", name = "Cities", maxSize = '10%') %>% 
  hc_mapNavigation(enabled = TRUE)

**Comment by jbkunst** [comment]
Hola @CamilaAchury , que tal?

Can you install the dev version and try again (`source("https://install-github.me/jbkunst/highcharter")`)? 



(https://github.com/jbkunst/highcharter/commit/3f0c92e861331d54457b5b74aa342fc45e8c80dc)

**Comment by jbkunst** [comment]
I will close the issue but we can reopen if you keep with problems ;)!

**Comment by CamilaAchury** [comment]
Holaa! @jbkunst  ya funciona perfecto, muchas gracias!

**Comment by jbkunst** [comment]
Que bueno @CamilaAchury ! De nada, para eso estamos!
