### ISSUE TITLE
How to show the last data label only

### ISSUE THREAD

**Issue by miluylin** [jbkunst/highcharter#338]
I would like to show the last data label only in highcharter but the plot shown all data labels.

reference : http://jsfiddle.net/highcharts/mAJtj/

```javascript
plotOptions: {
        series: {
            dataLabels: {
                enabled: true,
                align: 'left',
                formatter: function() {
                      if (this.point.x == this.series.data.length - 1) {
              		    return this.y;
            	      }
            		    return "";
          	},
                crop: false,
                overflow: false
            }
        }
    }
```

```
 hc_plotOptions(
      series = list(
          showInLegend = FALSE,
        dataLabels = list(
          enabled = FALSE,
          align = 'center',
          verticalAlign = 'bottom',
          style = list(
            fontWeight = 'bold'
          ),
          overflow = FALSE, #'justify',
          crop = FALSE,
          formatter = JS( '
              function() {
                  if (this.point.x == this.series.data.length - 1) {
                          return this.y;
                    }
                          return "";
                }')
          )
      )
```

<img width="659" alt="2017-07-06 6 55 21" src="https://user-images.githubusercontent.com/18286058/27908144-010c4c88-627d-11e7-8b00-4288e66009a6.png">

**Comment by jbkunst** [comment]
Not sure why doesn't work for you.

```

hc <- highcharts_demo() %>%
  hc_plotOptions(
    series = list(
      showInLegend = FALSE,
      dataLabels = list(
        enabled = TRUE,
        align = 'center',
        verticalAlign = 'bottom',
        style = list(
          fontWeight = 'bold'
        ),
        overflow = FALSE, #'justify',
        crop = FALSE,
        formatter = JS( '
              function() {
                  if (this.point.x == this.series.data.length - 1) {
                          return this.y;
                    }
                          return "";
                }')
      )
    )
  )

hc

hc$x$type <- "stock"

hc
```
![image](https://user-images.githubusercontent.com/56481/28299141-5f653e68-6b45-11e7-9e56-3eab5b206b21.png)

![image](https://user-images.githubusercontent.com/56481/28299144-6ad1c1b8-6b45-11e7-9bf4-6f9d72d69d98.png)

Tell me why!!! 😅

**Comment by jbkunst** [comment]
I just set the `enabled = TRUE`

**Comment by miluylin** [comment]
It doesn't work. Thanks for your testing.
I will try to represent the format in another way.

**Comment by jbkunst** [comment]
Do you have a minimal reproducible example? Do you have the development version?

**Comment by miluylin** [comment]
Thanks for solve problems.  
I will try to re-install the development version later.

Here is the minimal reproducible example, I don't know why it still doesn't work
Data frame cc with colname "Data"
                     Data
2016-01-04 34.77
2016-01-05 34.91
2016-01-06 35.01
2016-01-07 35.33
2016-01-08 35.59
2016-01-11 35.92

```R
hh <- highchart(type = "stock") %>%
      hc_plotOptions(
          spline = list( 
              lineWidth = 2,
              dataLabels = list(
                  enabled = TRUE,
                  formatter = JS( '
                      function() {
                          if (this.point.x == this.series.data.length - 1) {
                              return this.y;
                          }
                          return "";
                }')
                                  
      ))) %>%
      hc_yAxis_multiples(
          list(top = "0%" , height = "100%", title = list(text = "test"))
      ) %>%  
      hc_add_series(
          cc$Data, type = "spline", yAxis = 0, 
          dataLabels = list(format = '{y}%')
      )
  hh
```
<img width="581" alt="2017-07-19 11 13 13" src="https://user-images.githubusercontent.com/18286058/28374616-e5f9f642-6cd7-11e7-9a9e-9fb92dfd7c7d.png">

**Comment by miluylin** [comment]
After re-install the dev version. Test result is the same.
It will be great if this problem can be found. I'd appreciate your help.

**Comment by jbkunst** [comment]
@miluylin :sweat_smile: 

It seems `format` and `formatter` override each other. So remove the `dataLabels = list(format = '{y}%')` and put that "%" inside the formatter function.

**Comment by miluylin** [comment]
@jbkunst 
I remove the format, but no data label shows in the plot.  :(

```R
hh <- highchart(type = "stock") %>%
      hc_plotOptions(
          spline = list( 
              lineWidth = 2,
              dataLabels = list(
                  enabled = TRUE,
                  formatter = JS( '
                      function() {
                          if (this.point.x == this.series.data.length - 1) {
                              return this.y + "%";
                          }
                          return "";
                }')
                                  
      ))) %>%
      hc_yAxis_multiples(
          list(top = "0%" , height = "100%", title = list(text = "test"))
      ) %>%  
      hc_add_series(
          cc$Data, type = "spline", yAxis = 0
      )
  hh
```

<img width="665" alt="2017-07-20 7 13 16" src="https://user-images.githubusercontent.com/18286058/28393742-1779ba7a-6d1b-11e7-8c6a-13849c8e2773.png">

**Comment by jbkunst** [comment]
Hi @miluylin ,

Take a look, try to copy/paste if this didn't work you can try with a simple `formatter` function to try to debug the problem. I don't have more information to help you. You can try changing the browser,  etc.

**Comment by miluylin** [comment]
Hi @jbkunst,

Thank you again, it works, I will try to figure out why previous config still show nothing.

**Comment by miluylin** [comment]
I think that I found the problem,  while the data class is data.frame, it works.
The original data class was xts,zoo, the last data label will not show in the plot.

Again, Thank you and this powerful package.
