### ISSUE TITLE
where is "hc_add_series_map"

### ISSUE THREAD

**Issue by vhp1360** [jbkunst/highcharter#34]
I installed highcharter package.
all functions are OK! but there is not "hc_add_series_map".

**Comment by jbkunst** [comment]
Hi @vhp1360!

(The function si here: https://github.com/jbkunst/highcharter/blob/daa4e7192e9402aec6903ae86355a2377fdc7f52/R/shortcuts.R#L295)

Maybe you install/have the CRAN version which is 0.1.0. The `hc_add_series_map` function is not released yet in CRAN so if you want to use you need install the package from github `devtools::install_github("jbkunst/highcharter")` (devtools packag is needed).

If you have problems let me know! ;)

**Comment by vhp1360** [comment]
Hi
so many thanks for your feedback.
No, I installed in with devtools,
but I tried to update your package and I faced treble error
I tried `devtools::install_github("jbkunst/highcharter")`
and got

> Error : .onLoad failed in loadNamespace() for 'seasonal', details:<br/>
>  call: x13binary::checkX13binary(verbose = FALSE)<br/>
>  error: X-13 has run but has not produced Testairline.html<br/>
> Error: loading failed<br/>
 maybe it is not your business but could you please help me.

**Comment by jbkunst** [comment]
What R version you have?

May be this is related to https://github.com/x13org/x13binary/issues/32. I will be more accurate if you gime your R version, ands `sessionInfo()`

I think I'll remove seasonal dependency for now. Ok, Give me 10 minutes to remove. 

![](http://bloximages.newyork1.vip.townnews.com/stltoday.com/content/tncms/assets/v3/editorial/3/44/344a8f80-d44a-11e2-81ba-0019bb30f31a/51b9fa6a33362.preview-620.png)

**Comment by jbkunst** [comment]
Please check ;)!

**Comment by vhp1360** [comment]
sorry for late

> platform       x86_64-redhat-linux-gnu     
>arch           x86_64                      
>os             linux-gnu                   
>system         x86_64, linux-gnu           
>status                                     
>major          3                           
>minor          2.3                         
>year           2015                        
>month          12                          
>day            10                          
>svn rev        69752                       
>language       R                           
>version.string R version 3.2.3 (2015-12-10)
>nickname       Wooden Christmas-Tree

**Comment by jbkunst** [comment]
Thanks, 

Please don't copy paste only, add ``` in the start and bottom of what you copy paste to add code style to the block of text ;)!!

**Comment by vhp1360** [comment]
I really appreciate for your kind support.
Package installed and "hc_add_serie_map" and "hc_add_series_map" are coming.
we can close it.

**Comment by jbkunst** [comment]
Ok, thank you too.
