### ISSUE TITLE
Scatter + Regression Lines

### ISSUE THREAD

**Issue by S-UP** [jbkunst/highcharter#340]
Dear all,

ggplot2 allows to include regression lines in scatters. It would be great to have this feature available also in highcharter.

Ideally, one could e.g. scatter over a group like Males and Females combined while giving the user the option to deselect one gender. Then, the chart would automatically update with a corresponding regression line.

Many thanks for your consideration!

**Comment by jbkunst** [comment]
Hi @S-UP ,

There are some alternatives to do what you want.

1. There is a plugin for highcharts include in highcharter, but you need add the dependency to your widget (highcharter object):

```
library(ggplot2)
library(highcharter)
library(dplyr)

data(mpg, diamonds, package = "ggplot2")

hchart(mpg, "point", hcaes(displ, hwy, group = drv), regression = TRUE) %>% 
  hc_colors(c("#d35400", "#2980b9", "#2ecc71")) %>% 
  hc_add_dependency("plugins/highcharts-regression.js")
```

![image](https://user-images.githubusercontent.com/56481/29895897-36dab610-8db1-11e7-891a-9f4dcc0679b7.png)

2. The second way is use `broom` in a `lm` object and plot that data frame, obviously it's not that automatic but you have more control in what you want to show.

There are other options in https://github.com/streamlinesocial/highcharts-regression

Hope ti helps.
