### ISSUE TITLE
Custom Tooltip 

### ISSUE THREAD

**Issue by saifkabirasif** [jbkunst/highcharter#342]
Hi,

I'm trying to add a custom tooltip but it is not working.
What I am trying to achieve is to have tooltip of each point to show Region and Target.
Example for for first case :
Region: Ab
Target: 2

Need your help in this regard.

`
df<-data.frame(c(2011,2012,2013,2014,2015),
               c('Ab','Bc','Cd','De','Ef'),
               c(2,4,3,5,10)
               )

colnames(df)<-c('Yr','Region','Target')

highchart()%>%
  hc_xAxis(categories=df$Yr)%>%
  hc_add_series(df$Target,type="scatter",name="Target",marker = list(radius = 3))%>%
  hc_tooltip(table=TRUE,sort=TRUE,pointFormat='Region: {point.df$Region} <br> Target: {point.df$Target}')

`

**Comment by jbkunst** [comment]
Hi @saifkabirasif !

First of all, try to format your code, you need to use ``` (3 ` ) please ;)!

Secondly, see http://api.highcharts.com/highcharts/tooltip.pointFormat and its example http://api.highcharts.com/highcharts/tooltip.pointFormat, then try something like `{point.Target}`.

Please, tell me if this work for you.

**Comment by jbkunst** [comment]
```
highchart()%>%
  hc_xAxis(categories=df$Yr)%>%
  hc_add_series(df,type="scatter", hcaes(Yr, Target), name="Target",marker = list(radius = 3))%>%
  hc_tooltip(table=TRUE,sort=TRUE,pointFormat='Region: {point.Region} 
             Target: {point.Target}')

```

**Comment by saifkabirasif** [comment]
THANK YOU.
That worked man. "hcaes" is the key. I was also wondering if I pass data.frame to add_series, how does it know which is x-axis and which is y-axis. This also solved that issue.
