### ISSUE TITLE
Heatmap with hierarchical clustering results

### ISSUE THREAD

**Issue by jpzhangvincent** [jbkunst/highcharter#344]
I really like the highcharter package. I wonder whether it's possible for the heatmap to show the hierarchical clustering result and make the labels in the corresponding order, like the "d3heatmap" and "heatmaply" packages.

**Comment by jbkunst** [comment]
Hi @jpzhangvincent 

Sadly there is no way to make it in one chart. But obviously you can compose charts to make a similiar result. It's not that easy but I think is 100% possible.

I will close the issue but we can keep the discussion if you want ;)!
