### ISSUE TITLE
Feature request/ bug: Preserve order of series labels

### ISSUE THREAD

**Issue by S-UP** [jbkunst/highcharter#348]
Hi,

When running a stacked column chart with a categorical variable on the x-axis and a grouping over another categorical variable, then highcharts preserves the order of the x-axis variables, i.e. it displays the values in the order in which they were present in the initial data frame.

However, the series labels are always sorted alphabetically. This is an issue when e.g. grouping like '1x', '2x', '3x', '4-10x', '10-20x', '>20'. The labels will show '>20' first, followed by '10x' and '1x'.

If you could default to label in the order of appearance in the data frame, then I could sort accordingly.

![image](https://user-images.githubusercontent.com/25745787/29187607-a5a09b88-7e10-11e7-9f84-d8d305d44de2.png)

**Comment by jbkunst** [comment]
Hi @S-UP ,

Please provide alway a reproducible example :)!

**Comment by S-UP** [comment]
Hi again,

Sorry for the delay. Below is a reproducible example.

I guess I would prefer a solution that simply keeps the sorting of groups in accordance with the sequence they appear in the data set. This seems simple and, generally, consistent with expectations. Alternatively, an option to sort by defined variables would do the trick as well. 

For instance, what I did in my charting script (not shown) is to store the sorting order of the categorical variable, then do some data aggregation that typically messes with the order of observations, and then merge the sorting table with the modified data table to reestablish the sorting order. The final table then gets plotted. This works fine for the column charts but not for below examples. Also, boxplot charts do not respect the sorting either.

Examples:

`

  # === DATA === #

value <- c(165, 5020, 127, 204, 506, 809, 1039, 3094)
category <- c('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H')
group <- c('G1', 'G1', 'G2', 'G2', 'G3', 'G3', 'G4', 'G4')
group_alt <- c('biggest', 'biggest', 'smallest', 'smallest', 'small', 'small', 'big', 'big')

chartData <- data_frame( category = category, value = value, group = group, group_alt = group_alt)

chartData <- chartData %>% group_by(group) %>% summarise(groupValue=sum(value)) %>% 
  right_join(chartData) %>% arrange(groupValue)


  # ====  COLUMN === #

  # NOTE: INPUT SORTING **IS** RESPECTE

  # ASCENDING
chartData <- chartData %>% arrange(value)

highchart() %>% 
  hc_add_series(chartData, type = 'column', colorByPoint = T, hcaes(category, value)) %>% 
  hc_xAxis( type = 'category' )

  # DESCENDING
chartData <- chartData %>% arrange(desc(value))

highchart() %>% 
  hc_add_series(chartData, type = 'column', colorByPoint = T, hcaes(category, value)) %>% 
  hc_xAxis( type = 'category' )



# ====  COLUMN - GROUPED === #

  # NOTE: INPUT SORTING IS NOT RESPECTED

  # ASCENDING
chartData <- chartData %>% arrange(groupValue, value)

highchart() %>% 
  hc_add_series(chartData, type = 'column', colorByPoint = T, hcaes(category, value, group=group)) %>% 
  hc_xAxis( type = 'category' ) %>% 
  hc_plotOptions(column = list(stacking = 'normal'))

  # DESCENDING
chartData <- chartData %>% arrange(desc(groupValue), desc(value))

highchart() %>% 
  hc_add_series(chartData, type = 'column', colorByPoint = T, hcaes(category, value, group=group)) %>% 
  hc_xAxis( type = 'category' ) %>% 
  hc_plotOptions(column = list(stacking = 'normal'))
  


# === COLUMN - GROUPED - BAD FIX === #

  # NOTE: SENSIBLE ORDER DUE TO RENAMING BUT NOT RESPECTING INPUT SORTING

  # ASCENDING
chartData <- chartData %>% arrange(groupValue, value)

highchart() %>% 
  hc_add_series(chartData, type = 'column', colorByPoint = T, hcaes(category, value, group=group_alt)) %>% 
  hc_xAxis( type = 'category' ) %>% 
  hc_plotOptions(column = list(stacking = 'normal'))

  # DESCENDING
chartData <- chartData %>% arrange(desc(groupValue), desc(value))

highchart() %>% 
  hc_add_series(chartData, type = 'column', colorByPoint = T, hcaes(category, value, group=group_alt)) %>% 
  hc_xAxis( type = 'category' ) %>% 
  hc_plotOptions(column = list(stacking = 'normal'))


# === BOXPLOT === #

  # NOTE: AGAIN, INPUT SORTING IS NOT RESPECTED

chartData <- chartData %>% arrange(groupValue)

hcboxplot(chartData$value, chartData$group)
`

**Comment by jbkunst** [comment]
I'll take a look

**Comment by S-UP** [comment]
That'd be awesome!

Thank you so much for the great support!

**Comment by S-UP** [comment]
Not to rush, but in case you already have some good news to share. I'd be very happy to hear about progress on this end. I have developed a nice Shiny application. But not being able to order the data makes it difficult for others to use (it is a self-help tool).

Thanks a ton for your great support and efforts! Much appreciated indeed.

**Comment by jbkunst** [comment]
Hi @S-UP ,

I just find this https://stackoverflow.com/questions/17997717/highcharts-change-legend-index-order
This is not implemented yet but you can do in the meantime:

```r
chartData <- chartData %>% arrange(groupValue, value)

idex <- chartData$group %>% 
  unique() %>% 
  order()
highchart() %>% 
  hc_add_series(chartData, type = 'column', colorByPoint = T, hcaes(category, value, group=group),
                legendIndex = idex - 1) %>% 
  hc_xAxis( type = 'category' ) %>% 
  hc_plotOptions(column = list(stacking = 'normal'))
```

![image](https://user-images.githubusercontent.com/56481/32246961-83e6253c-be5f-11e7-8198-3c63a12c9727.png)

**Comment by S-UP** [comment]
Thanks for sharing! Will have a look at this.
