### ISSUE TITLE
Fonts : Need R's default font, and Relative Sizing text and Labels

### ISSUE THREAD

**Issue by anz000** [jbkunst/highcharter#353]
Hi, 

Is there a way to create the look of the plots from Highcharter same/similar to the R default's plots? I tried with font changes and all, but the relative sizing (according to the width and height of the plot) of the fonts is a huge hassle. I'm using "em" for font sizes, which displays correctly in Rstudio, but is not exporting correctly in vector formats (pdf and svg), while working fine for other formats.

I'ld love to create uniform look throughout my plots, as i'm using highcharts as well as default R plot. 

I'ld love to be able to do something like this.
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/css/em/

Thanks.

**Comment by jbkunst** [comment]
Hi @anz000 

What have you tried?

**Comment by anz000** [comment]
I was using something like this to deal with all the wholesale font changes
`hc_chart(backgroundColor="#FFFFFF", style=list(fontSize = "2em")) %>% `

But it didn't changed the axis labels, so I have to do something like this:
`hc_yAxis(style=list( fontSize = "1em"),labels = list(style=list( fontSize = "1em"))) %>%`

The js example implements a slider that is so easy to manage the zoom label for all the fonts. I wonder if something like that is possible? As for the vector exports, it might be some problem with my SVG viewer (default Ubuntu 16.10), as the browser is showing fine. Thanks.

And if there is a simple R theme for highcharter, that would be so handy as well. I see a lot fancier themes, a simple R wrapper for plots visualization would be a great addition, I believe.
