### ISSUE TITLE
French Characters

### ISSUE THREAD

**Issue by juansecal** [jbkunst/highcharter#359]
Hello, I wanted to plot a map of french departments.

The problem is that the names are not dowloaded properly, is there an option to fix this?

```

library(readr)
library(name)
mapdata <- read_delim("J:/PRORS/CALDERON/Etude GAV/mapdata.csv",";", escape_double = FALSE, trim_ws = TRUE)


mapdata <- get_data_from_map(download_map_data("countries/fr/fr-all-all"))
glimpse(mapdata)


set.seed(1234)

data_fake <- mapdata %>% 
  select(code = `hc-a2`) %>% 
  mutate(frequence = 0.5 * abs(rt(nrow(.), df = 10)))

glimpse(data_fake)

hcmap("countries/fr/fr-all-all", by = "iso3",data = data_fake, value = "frequence",
      joinBy = c("hc-a2", "code"), name = "Fake data",
      dataLabels = list(enabled = TRUE, `format` = '{point.name}'),
      borderColor = "#FAFAFA", borderWidth = 0.1,
      tooltip = list(valueDecimals = 2, valuePrefix = "$", valueSuffix = " USD")) %>% 
  hc_mapNavigation(enabled = TRUE) 

```

Also is there a way to obtain the postal code of the department corresponding to each key?

**Comment by jbkunst** [comment]
Hi @juansecal 

I forgot read the json files with `utf-8` encondig. Thanks! Try to download the development version and try again.

![image](https://user-images.githubusercontent.com/56481/29791770-80a2b962-8c14-11e7-93b7-3b564e5dbf17.png)

**Comment by juansecal** [comment]
Thank you very much

Le 28 août 2017 10:17 PM, "Joshua Kunst" <notifications@github.com> a
écrit :

**Comment by juansecal** [comment]
Allthough I was completely unable to install the dev version, tried
everything but the master zipfile on github seems to be differently
structured than CRAN files.

**Comment by jbkunst** [comment]
What did you tried? Did you tried https://github.com/jbkunst/highcharter#installation?

**Comment by juansecal** [comment]
Yes I tried that.

`devtools::install_github("jbkunst/highcharter")`

gives me error :

```
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Couldn't resolve host name
```

`source("https://install-github.me/jbkunst/highcharter")
`

Gives me error 

```
In utils::install.packages(...) :
  installation of package ‘C:/Users/JUAN~1.CAL/AppData/Local/Temp/RtmpITMhVG/remotes3d981fef148a/jbkunst-highcharter-722f69a’ had non-zero exit status
```

I'm trying to install it manually but it seems that one needs to install Rtools first.

**Comment by jbkunst** [comment]
Mmm... not sure what's going on, I had 0 problem to download using devtools :/
