### ISSUE TITLE
Problems with using highcharts2() boost

### ISSUE THREAD

**Issue by SvenGuthe** [jbkunst/highcharter#361]
Hi,
i've got a problem with the boost version of highcharts(). I developed a dashboard with shiny and some modules with many highcharts objects. Now i've got the problem, that i have to plot around 6000 points in a scatterplot. highcharts is to slow, so i've tried highcharts2. There is no output ("No data to display") and it is not faster. I read something about the fact, that I can only use only a single version of highcharts in the whole R application.

So I am right that i have to change all highcharts code in the whole app to use highcharts2 with boost and the app still works without changing parameters in hc_options or some other parameters?

I wanna change this:

```
 output$XXX<- renderHighchart({
   highchart() %>%
     hc_add_series(XXX, "point", hcaes(x = XXX, y = XXX), name = "XXX") %>%
     hc_title(text = "XXX") %>%
     hc_credits(enabled = TRUE, text = "XXX") %>%
     hc_xAxis(title = list(text = "XXX")) %>%
     hc_yAxis(title = list(text = "XXX"))
   })
```

to this:

```
 output$XXX<- renderHighchart2({
   highchart2() %>%
     hc_add_series(XXX, "point", hcaes(x = XXX, y = XXX), name = "XXX") %>%
     hc_title(text = "XXX") %>%
     hc_credits(enabled = TRUE, text = "XXX") %>%
     hc_xAxis(title = list(text = "XXX")) %>%
     hc_yAxis(title = list(text = "XXX"))
   })
```
...maybe it's a stupid question but I've been using it only recently

**Comment by jbkunst** [comment]
Hi @SvenGuthe ,

Yes, that would be (if I'm correct) enough. 

Anyway you need to be clear that boost plugin it's for have a good performance in zoom/tooltips/etc whe the **data is loaded**, so if you send a lot of data from R to browser that would take some time. 

Please see https://github.com/jbkunst/highcharter/issues/264#issuecomment-278848430 for more details.

I'll wait for you response before close the issue ;)!

**Comment by SvenGuthe** [comment]
Hi @jbkunst,

thx for that answer. My problem was what you marked as big "data is loaded". I used a large data.frame and sended thousands of useless data to the browser. Now i fixed it and the highcharts2 works perfectly. Also in combination with the normal highcharts graphs. There is no problem to combine them in seperate shiny modules. 

Thank you. Issue can be closed.
