### ISSUE TITLE
highchartOutput2 - Failed to load resource

### ISSUE THREAD

**Issue by SvenGuthe** [jbkunst/highcharter#362]
Hi again,

my shiny app works fine but now i get an error i can't handle with. I want to change all highchartOutput() to highchartOutput2() so i modified:

`highcharter::highchart() -> highcharter::highchart2()
highcharter::renderHighchart() -> highcharter::renderHighchart2()
highcharter::highchartOutput() -> highcharter::highchartOutput2()`

Now i got a `ERROR: [on_request_read] connection reset by peer`-Error and when i open the Google Chrome Console der are some Errors like: 
`Failed to load resource: the server responded with a status of 404 (Not Found) - boost.src.js`
`Failed to load resource: the server responded with a status of 404 (Not Found) - reset.js`
`Uncaught ReferenceError: ResetHighchartsOptions is not defined`
`Uncaught TypeError: Cannot read property 'renderTo' of undefined`

With the normal highcharts the plots are ok, but if i change to highcharts2 errors are incoming.

**Comment by jbkunst** [comment]
@SvenGuthe 

That's **not** the way you rename functions. Try something like:

```r
hcoutput <- highcharter::highchartOutput()
# hcoutput <- highcharter::highchartOutput2()
```
And then use the function according what you want.

Not sure what is the reason of the message, you should send me a minimal reproducible example to work with to discuss about the possible solutions.

**Comment by SvenGuthe** [comment]
Oh sorry. I wrote this functions like this `hcoutput <- highcharter::highchartOutput2()`

But i transform the `highcharter::highchartOutput()` to `highcharter::highchartOutput2()`. That's why i use the arrows. That is what a get [https://i.stack.imgur.com/l2uwO.png](url) in the Google Chrome console.

**Comment by jbkunst** [comment]
With a minimal reproducible example of what are you doing will be easier to solve the problem.

**Comment by bocs2993** [comment]
I'm getting the exact same thing. App renders beautifully with highchart functions but not highchart2 with the same errors upon inspection...

**Comment by bocs2993** [comment]
You can use these to reproduce the error.

[exampleFail.xlsx](https://github.com/jbkunst/highcharter/files/1817081/exampleFail.xlsx)
[app copy.R.txt](https://github.com/jbkunst/highcharter/files/1817082/app.copy.R.txt)
