### ISSUE TITLE
multiple plots in a loop in shiny app

### ISSUE THREAD

**Issue by jbkunst** [jbkunst/highcharter#37]
@royfrancis ask about how have multiples chart in one output.

The code is based in @royfrancis demo app https://roymf.shinyapps.io/highchartrtest/ (using rCharts)

```r
library("shiny")
library("highcharter")

ui <- fluidPage(
  selectInput("nplots", "Choose", multiple = TRUE, width = "100%",
              choices = c("cars", "mtcars", "iris",
                          "Puromycin", "ChickWeight")),
  fluidRow(
    column(12, htmlOutput("hcontainer")),
    highchartOutput("hcontainer2", height = "0", width = "0")
    # the previous output is hide. This is needed load highcharts/highcharter
    # javascript in the app
  )
)

server <- function(input, output) {
    
  gethc <- function(dfname = "cars") {
    # function to return the chart in a column div
    df <- get(dfname)
    
    hc <- highchart(height = 300) %>% 
      hc_title(text = dfname) %>% 
      hc_xAxis(title = list(text = names(df)[1])) %>% 
      hc_yAxis(title = list(text = names(df)[2])) %>% 
      hc_add_serie_scatter(df[,1], df[, 2]) %>% 
      hc_add_theme(
        list(hc_theme_538(), hc_theme_economist(), hc_theme_darkunica())[sample(1:3, size = 1)][[1]]
        )
    
    column(width = 6, hc)
    
  }
  
  output$hcontainer <- renderUI({
    # input <- list(nplots = c("cars", "mtcars"))
    charts <- lapply(input$nplots, gethc)
    do.call(tagList, charts)
    
  })  
  
}

shinyApp(ui = ui, server = server)
```

**Comment by royfrancis** [comment]
Good example. Thanks a lot. The demo app link is just temporary and will be removed.

**Comment by jbkunst** [comment]
Ok, thanks!

**Comment by royfrancis** [comment]
Here is an example that I have been trying and it doesn't entirely work. I can't seem to figure out what is wrong. The data is correctly injected into the highcharts object.

```
#ui.R
library("shiny")
library("highcharter")

ui <- fluidPage(
  selectInput("nplots", "Choose", multiple = TRUE, width = "100%",
              choices = c("A","B")),
  fluidRow(
    column(12, htmlOutput("hcontainer")),
    highchartOutput("hcontainer2", height = "0", width = "0")
    # the previous output is hide. This is needed load highcharts/highcharter
    # javascript in the app
  )
)

#server.R
library(rlist)
server <- function(input, output) {
  
  gethc <- function(dfname) {
    # function to return the chart in a column div
    A <- data.frame(x=c(1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10),
                    y=c(0.7,0.8,0.7,0.3,0.5,0.2,0.4,0.4,0.5,0.5,
                        0.3,0.2,0.3,0.7,0.5,0.8,0.6,0.6,0.5,0.7),
                    group=factor(c("A","A","A","A","A","A","A","A","A","A","B","B","B","B","B","B","B","B","B","B")),
                    pop=c("Group 1","Group 1","Group 1","Group 1","Group 1","Group 1","Group 2","Group 2","Group 2","Group 2",
                          "Group 1","Group 1","Group 1","Group 1","Group 1","Group 1","Group 2","Group 2","Group 2","Group 2"))
    
    B <- data.frame(x=c(1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10),
                    y=c(0.6,0.7,0.2,0.3,0.2,0.1,0.4,0.5,0.2,0.1,
                        0.3,0.2,0.3,0.3,0.2,0.1,0.1,0.2,0.1,0.3,
                        0.1,0.1,0.5,0.4,0.6,0.8,0.5,0.3,0.7,0.6),
                    group=factor(c("A","A","A","A","A","A","A","A","A","A","B","B","B","B","B","B","B","B","B","B","C","C","C","C","C","C","C","C","C","C")),
                    pop=c("Group 1","Group 1","Group 1","Group 1","Group 1","Group 1","Group 2","Group 2","Group 2","Group 2",
                          "Group 1","Group 1","Group 1","Group 1","Group 1","Group 1","Group 2","Group 2","Group 2","Group 2",
                          "Group 1","Group 1","Group 1","Group 1","Group 1","Group 1","Group 2","Group 2","Group 2","Group 2"))
    
    df <- get(dfname)
    
    hc <- highchart(height=300)
    hc <- hc_xAxis(hc,title=list(text=NULL),allowDecimals=FALSE)
    
    dlev <- levels(df$group)
    for(i in 1:length(dlev))
    {
      #hc <- hc_add_serie(hc,data = rCharts::toJSONArray2(d[d$type==dlev[i],,drop=F], json = F,names=T), name = dlev[i],type = c("column"), marker = list(radius = 3))
      da <- list.parse(df[df$group==dlev[i],])
      names(da) <- NULL
      hc <- hc_add_series(hc, data = da, name = dlev[i],type = "column")
    }
    
    hc <- hc_yAxis(hc,title=list(text=NULL),max=1)
    hc <- hc_chart(hc,zoomType='x',panKey="shift",panning=TRUE)
    hc <- hc_credits(hc, enabled = TRUE, text = dfname)
    hc <- hc_legend(hc,
                    enabled = TRUE,
                    align = 'right',
                    verticalAlign = 'top',
                    layout = 'horizontal',
                    floating = FALSE)
    hc <- hc_tooltip(hc,borderWidth=0, followPointer=TRUE, followTouchMove=TRUE, shared = FALSE,
                     pointFormat = "y: {point.y} <br> type: {point.type} <br> group: {point.pop}")
    hc <- hc_exporting(hc,enabled=TRUE,
                       url = "https://export.highcharts.com",
                       fallbackToExportServer=FALSE,
                       buttons=list(
                         contextButton = list(
                           align = 'left',
                           verticalAlign = 'top'
                         )
                       )
    )
    hc <- hc_plotOptions(hc,column = list(stacking = "normal", pointPadding = 0, groupPadding = 0, borderWidth = 0))
   #check data structure
    print(str(hc))
    column(width = 12, hc)
  }
  
  output$hcontainer <- renderUI({
    charts <- lapply(input$nplots, gethc)
    do.call(tagList, charts)
    
  })  
}
```

**Comment by jbkunst** [comment]
@royfrancis 

Yep, the data is right, the problem is the "column" type chart doesnt understand data when you add other named values. If you change:

```
da <- list.parse(df[df$group==dlev[i], ])
```
by 
```
da <- list.parse(df[df$group==dlev[i], c("x", "y")])
```
it works.

I'm not sure why this happens.

Some references:
- http://api.highcharts.com/highcharts#series<column>.data
- http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/series/data-array-of-objects/

**Comment by jbkunst** [comment]
May be it's the order :/

**Comment by royfrancis** [comment]
It works now. that's fantastic! thanks again!

**Comment by royfrancis** [comment]
ah. but then it's not possible to add the extra variables as tooltip anymore? As that breaks the plot.

**Comment by royfrancis** [comment]
Do you think this should be a new issue? Because this no longer about multiple plots and loop.

**Comment by jbkunst** [comment]
Ok ☺, but try put a minimal example instead of the all app 😆

**Comment by TJ66** [comment]
Hi there! I know that it might be an old topic, but I recently faced some issues regarding the code posted above. Consider an example with the code above, where it is  used in a loop and plots are redrawn lets say every second. In such case I noticed a claiming memory usages in Chorme Task-manager what after a period of time leads to "Aw Snap something went wrong while displaying this web page".
For a minimal example I didn't change much of the code just included invalidatlate into the renderUI function.
`
library("shiny")
library("highcharter")

ui <- fluidPage(
  selectInput("nplots", "Choose", multiple = TRUE, width = "100%",
              choices = c("cars", "mtcars", "iris",
                          "Puromycin", "ChickWeight")),
  fluidRow(
    column(12, htmlOutput("hcontainer")),
    highchartOutput("hcontainer2", height = "0", width = "0")
    # the previous output is hide. This is needed load highcharts/highcharter
    # javascript in the app
  )
)

server <- function(input, output) {
  
  gethc <- function(dfname = "cars") {
    # function to return the chart in a column div
    df <- get(dfname)
    
    hc <- highchart(height = 300) %>% 
      hc_title(text = dfname) %>% 
      hc_xAxis(title = list(text = names(df)[1])) %>% 
      hc_yAxis(title = list(text = names(df)[2])) %>% 
      hc_add_series_scatter(df[,1], df[, 2]) %>% 
      hc_add_theme(
        list(hc_theme_538(), hc_theme_economist(), hc_theme_darkunica())[sample(1:3, size = 1)][[1]]
      )
    
    column(width = 6, hc)
    
  }
  
  output$hcontainer <- renderUI({
    invalidateLater(1000)
     input <- list(nplots =  c("cars", "mtcars", "iris",
                               "Puromycin", "ChickWeight"))
    charts <- lapply(input$nplots, gethc)
    do.call(tagList, charts)
    
  })  
  
}

shinyApp(ui = ui, server = server)
`

Please Let me know if you are able to replicate the issue and off course have suggestions how to get rid of this nasty problem.
Greetings!
