### ISSUE TITLE
Word Reports

### ISSUE THREAD

**Issue by quantransform** [jbkunst/highcharter#370]
I have using highcharter for my shiny dashboard but I am asked to gather all the charts into Word documents. I am currently using webshot to do so but sometimes the resolution is not ideal. I've came across a library called rvg (https://github.com/davidgohel/rvg) and I wondered if this is possible to do similar tasks. Like somehow api to download svg chart and use the same technique to get those svg charts onto word and becomes a downloadable report on shiny app? 

Thank you in advance,
Jeremy

**Comment by emillykkejensen** [comment]
Highcharts has a build in function for downloading png, pdf, jpg and svg files. You can see it in action here: https://www.highcharts.com/demo/line-basic

To use it with in the highcharter package simply run hc_exporting() - like so:
```
highcharts_demo() %>% 
hc_exporting(enabled = TRUE)
```

There even is an example using the package here: http://jkunst.com/highcharter/plugins.html#exporting-csv

Hope that helped,
Emil
