### ISSUE TITLE
"No data to display" when adding flags on an intraday candlestick chart

### ISSUE THREAD

**Issue by tstoyc** [jbkunst/highcharter#372]
Hi,
I am trying to add flags to an intraday candlestick chart and I get "No data to display".
I tried to replicate a slimmed down version of the highstock candlestick jsfiddle: 
https://jsfiddle.net/qotyn2rv/1 
using the following R code:
require(jsonlite)
require(highcharter)
require(xts)
require(dplyr)

data<-fromJSON('[
               [1317888000000,372.5101,375,372.2,372.52],
               [1317888060000,372.4,373,372.01,372.16],
               [1317888120000,372.16,372.4,371.39,371.62],
               [1317888180000,371.62,372.16,371.55,371.75],
               [1317888240000,371.75,372.4,371.57,372],
               [1317888300000,372,372.3,371.8,372.24],
               [1317888360000,372.22,372.45,372.22,372.3],
               [1317888420000,372.3,373.25,372.3,373.15],
               [1317888480000,373.01,373.5,373,373.24]
               ]
               ')
data<-as.data.frame(data)
colnames(data) <- c("Index", "Open", "High", "Low", "Close")
data[,1]<-as.POSIXct(data[,1]/1000, origin="1970-01-01")
data<-xts(data[,-1], order.by = data[,1])

data_flags <- data_frame(
  date = index(data)[c(2,4)],
  title = sprintf("E #%s", seq_along(date)),
  text = sprintf("An interesting event #%s in %s", seq_along(date), date)
)

hc <- highchart(type = "stock") %>%  
  hc_add_series(data, id="ES") %>%
  hc_add_series(data_flags, hcaes(x = date), type = "flags", onSeries="ES")
hc

**Comment by jflycn** [comment]
I had the same problem when I was trying to add flags to the chart. It seems when the time index has time (not just the date), it will show "no data to display".

**Comment by jbkunst** [comment]
Hi @tstoyc and @jflycn 

In this case I think it's better work with data frames to make give explicit the data to highcharts.

``` r
require(jsonlite)
require(highcharter)
require(dplyr)

data <- fromJSON("[
[1317888000000,372.5101,375,372.2,372.52],
[1317888060000,372.4,373,372.01,372.16],
[1317888120000,372.16,372.4,371.39,371.62],
[1317888180000,371.62,372.16,371.55,371.75],
[1317888240000,371.75,372.4,371.57,372],
[1317888300000,372,372.3,371.8,372.24],
[1317888360000,372.22,372.45,372.22,372.3],
[1317888420000,372.3,373.25,372.3,373.15],
[1317888480000,373.01,373.5,373,373.24]
]
")
data <- as.data.frame(data)
colnames(data) <- c("Index", "Open", "High", "Low", "Close")

head(data)
#>          Index     Open   High    Low  Close
#> 1 1.317888e+12 372.5101 375.00 372.20 372.52
#> 2 1.317888e+12 372.4000 373.00 372.01 372.16
#> 3 1.317888e+12 372.1600 372.40 371.39 371.62
#> 4 1.317888e+12 371.6200 372.16 371.55 371.75
#> 5 1.317888e+12 371.7500 372.40 371.57 372.00
#> 6 1.317888e+12 372.0000 372.30 371.80 372.24

data_flags <- data_frame(date = data$Index[c(2, 4)], ttl = sprintf("E #%s", 
  seq_along(date)), txt = sprintf("An interesting event #%s in %s", seq_along(date), 
  date))

data_flags
#> # A tibble: 2 x 3
#>            date ttl   txt                                     
#>           <dbl> <chr> <chr>                                   
#> 1 1317888060000 E #1  An interesting event #1 in 1317888060000
#> 2 1317888180000 E #2  An interesting event #2 in 1317888180000

highchart(type = "stock") %>% 
  hc_add_series(data, "candlestick", hcaes(x = Index, open = Open, high = High, low = Low, close = Close), id = "ES") %>% 
  hc_add_series(data_flags, hcaes(x = date, title = ttl, text = txt), type = "flags", onSeries="ES")
```
![image](https://user-images.githubusercontent.com/56481/36219400-fb748b0a-1195-11e8-919d-c4bb84afd083.png)

Next time you can post this type of question in stackoverflow rather than here where I prefer keep topics like features or bugs :)!
