### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by nicholaelaw** [jbkunst/highcharter#375]
Couldn't load the [website](http://jkunst.com/highcharter/showcase.html) properly. It seems that bootswatch has changed the URL of their stylesheet, breaking the webpage.

![image](https://user-images.githubusercontent.com/10719482/32773562-8749c48a-c964-11e7-931b-36e0e79ff9df.png)

**Comment by jbkunst** [comment]
Thanks for notice that! 

Fixed  in 2c2f70a
