### ISSUE TITLE
Upgrade to Highcharts 6

### ISSUE THREAD

**Issue by nuno-agostinho** [jbkunst/highcharter#376]
Hey, @jbkunst!

With the release of the [new version of Highcharts](https://www.highcharts.com/blog/news/announcing-highcharts-6/) (with a lot of new charts!), I would like to know when are you thinking about upgrading the library?

Cheers!

**Comment by jbkunst** [comment]
Hi @nuno-agostinho  how have you been?

Yeah! I know! A lot of great upgrades in this new version. I think I will work on this at the end of this month and then make a new cran release.

**Comment by jbkunst** [comment]
closed in 9505a2cbe7dbf86ee7cb38ff5203cd9c06ec114a
