### ISSUE TITLE
Synchronization

### ISSUE THREAD

**Issue by mviertel** [jbkunst/highcharter#379]
Hi - first of all, awesome library.

My question: is there a feature for synchronization planned?

See: https://www.highcharts.com/demo/synchronized-charts

Best
Michael

**Comment by jbkunst** [comment]
There is no plan to add that feature (anyway I think is possible to be implemented from R using JS). 

As alternative you can create a chart adding more than one yAxis like http://jkunst.com/highcharter/highstock#a-more-interesting-example special the next part:

```r
 hc_yAxis_multiples(
    create_yaxis(3, height = c(2, 1, 1), turnopposite = TRUE)
  )
```
Other example of this alternative is:

```r
hchart(stl(AirPassengers, s.window = 12))
```

![image](https://user-images.githubusercontent.com/56481/34108058-545bd890-e3dd-11e7-959f-244736e980f9.png)
