### ISSUE TITLE
Color line with alpha (transparency/opacity)

### ISSUE THREAD

**Issue by samuelhuerga** [jbkunst/highcharter#386]
Hi!

I want to add transparency to a linechart. In Highcharts api, there is nothing related, and in some stackoverflow question it shows that you can use a rgba color, as follows:

```
Highcharts.chart('container', {
    xAxis: {
        categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    },
    plotOptions: {
        series: {
            color: '#FF000022'
        }
    },

    series: [{
        data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
    }]
});
```
Giving the following result:
![image](https://user-images.githubusercontent.com/12885915/34145578-feedfac2-e496-11e7-8023-69e66d28c575.png)

However, when I try it on highcharter, it seems it doesn't recognise rgba colors:

```
highchart() %>% hc_add_series(data = 1:10, color = "#FF000022")
```
![image](https://user-images.githubusercontent.com/12885915/34145617-2c048788-e497-11e7-915d-cedfc8232a96.png)

How can I use alpha in line charts?

Thank you!

**Comment by jbkunst** [comment]
Hi @samuelhuerga 

Yep, it's seems there is no info in the API but there are some link with useful information about highcharts colors. In particular https://www.highcharts.com/docs/chart-design-and-style/colors.

You can use the `hex_to_rgba` helper function.

```r
 hex_to_rgba("#FF0000", alpha = 0.4)

highchart() %>%
  hc_add_series(data = 1:5, color = hex_to_rgba("#FF0000", alpha = 0.4))
```r
