### ISSUE TITLE
Spline color in hchart function

### ISSUE THREAD

**Issue by samuelhuerga** [jbkunst/highcharter#389]
Hi!

I have a grouped dataframe and I want to plot a spline chart, but with custom colors. If I use color argument in hcaes function, it only applies to markers, not splines:

```
data_frame(x=rep(1:3,2),
           group = c(rep("A",3),rep("B",3)),
           y = c(1:3,2:4),
           color = c(rep("#FF0000",3),rep("#00FF00",3))) %>% 
  hchart("spline",hcaes(x=x,y=y,group=group,color= color),
         marker = list(enabled = TRUE))
```
![image](https://user-images.githubusercontent.com/12885915/34938560-136752ac-f9e9-11e7-80c6-f8cb86e4eb4d.png)

How can I do it the same way I do it in ggplot?
```
data_frame(x=rep(1:3,2),
           group = c(rep("A",3),rep("B",3)),
           y = c(1:3,2:4),
           color = c(rep("#FF0000",3),rep("#00FF00",3))) %>% 
  ggplot(aes(x=x,y=y,group=group,color = color)) +
  geom_line()
```
Thank you!

**Comment by jbkunst** [comment]
Hi @samuelhuerga 

Soooorrryyy for my late reponse!.

Two alternatives:

```r
data_frame(x = rep(1:3, 2), group = c(rep("A", 3), rep("B", 3)), y = c(1:3, 2:4)) %>%
  hchart("spline", hcaes(x = x, y = y, group = group), marker = list(enabled = TRUE),
         color =  c("#FF0000", "#00FF00")) %>%


data_frame(x = rep(1:3, 2), group = c(rep("A", 3), rep("B", 3)), y = c(1:3, 2:4)) %>%
  hchart("spline", hcaes(x = x, y = y, group = group), marker = list(enabled = TRUE)) %>%
  hc_colors(colors =  c("#FF0000", "#00FF00"))
```
![image](https://user-images.githubusercontent.com/56481/36168916-7544beb8-10d9-11e8-9045-4e0f36f4da7c.png)

Next time you can post your question in stackoverflow, I prefer use this space for requests/bugs topics ;)!
