### ISSUE TITLE
turnopposite parameter bug?

### ISSUE THREAD

**Issue by lalas** [jbkunst/highcharter#390]
Hello

First and foremost, thanks for an excellent package.. 
In the "A More Interesting Example" you provided for [Highstock](http://jkunst.com/highcharter/highstock.html),  the _turnopposite_ parameter is set to TRUE, yet the y-axis on the second plot (corresponding to volume), appears on the wrong side (as if _turnopposite_ was set to FALSE.

Is this a bug?

Thanks

**Comment by jbkunst** [comment]
Hi @lalas .

Not a but but a naming problem and a very lack of documentation in this parameter/function :disappointed: .

The `turnopposite ` parameter put the even axis (1, 3, 5, ...) in the left side and the odds (2, 4, 6, ...) axis in the right side

**Comment by lalas** [comment]
Hi jbkunst,

Thank you for the clarification.... make sense! :)
