### ISSUE TITLE
vertical scroll highcharter object on mobile device of flexdashboard 

### ISSUE THREAD

**Issue by Bryant-zhu** [jbkunst/highcharter#394]
hi there 
 I made a demo dashboard originally to send on mobile device .
it was worked all good , but on mobile device , it is extremely  to scroll down vertically.

it there any way to improve this ? or I could just use all the static image instead of interactive charting for highchart . thanks

**Comment by jbkunst** [comment]
Hi @Bryant-zhu 

Please, provide a simple reproducible example to try to see what happens

**Comment by jbkunst** [comment]
Fixed with #722
