### ISSUE TITLE
highcharter Shiny demo not working

### ISSUE THREAD

**Issue by smach** [jbkunst/highcharter#40]
FYI 

    demo("shiny-ex")

triggers this error message:

    Error in force(ui) : object 'ui' not found

for the package version on CRAN. (Version I tried downloading from GitHub worked OK).

**Comment by jbkunst** [comment]
@smach  :smile: 

Yep! I forgot to write the `ui`. Sorry for the problems ;)!. 

Anyway thank you for the advice and for use the package.
