### ISSUE TITLE
Shiny,  hc_add_series dynamically and multiple

### ISSUE THREAD

**Issue by TitovAV** [jbkunst/highcharter#400]
Dear Joshua,
Thanks for very nice and useful package
I've a question about following feature in highcharter package for Shiny projects
I made checkboxGroupInput in my Shiny project. User may select multiple boxes. I want create plot in Highcharter package, which will be show selection series (many lines in one plot). By "hchart" function (data, type, hcaes(x, y, group)) it's easy, but this function doesn't work in Shiny project.
I must use "renderHighchart" and "hc_add_series", but I don't know as I can add dynamically (connect with checkboxGroupInput selection) and multiple series?

My Dataset
```
str(Crude_Oil_Production)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	1440 obs. of  4 variables:
 $ Index     : chr  "US Crude Production" "US Crude Production" "US Crude Production"...
 $ Date      : POSIXct, format: "2014-01-01" "2014-02-01" "2014-03-01" ...
 $ STEO_Issue: chr  "STEO, Jan.16" "STEO, Jan.16" "STEO, Jan.16" "STEO, Jan.16" ...
 $ Data      : num  8 8.09 8.24 8.57 8.58 ...
```
User choose different "STEO Issue" by checkboxGroupInput

```
ui<-fluidPage(
  titlePanel("US Crude Oil Production in different STEO"),
    sidebarLayout(sidebarPanel(      
      checkboxGroupInput("STEO",
                    "Choose STEO Issues:",
                     choices = c(unique(
                  as.character(Crude_Oil_Production$STEO_Issue)
                )), selected ="STEO, Jan.16"),
        ),
  mainPanel(highchartOutput("hcSTEO",height = "500px")))
)
```
Plot depends on user select (must show Data only for selected STEO_Issue)
```
server <- function(input, output) {
   output$hcSTEO <- renderHighchart({
      Crude_Oil_Production <- Crude_Oil_Production %>%      
      dplyr::filter(STEO_Issue %in% c(input$STEO))

      hc <- highchart() %>%
      hc_add_series(Crude_Oil_Production$Data) %>%
      hc_yAxis(title = list(text = "mbd"), allowDecimals = FALSE) %>%
      hc_xAxis(categories = Crude_Oil_Production$Date, type = "datetime", dateTimeLabelFormats = list(year = '%y')) %>%
      hc_title(text = "US Crude Oil Production in different STEO")%>%
      hc_add_theme(hc_theme_flat())
   hc
  })
}
shinyApp(ui = ui, server = server)

```
For one select (for example "STEO, Jan.16" only) it works correct. But for two and more selections isn't work (don't show two and more lines).
I think, that my mistake in "hc_add_series(Crude_Oil_Production$Data)", but I don't know about correction

Thank you very much in advance!

**Comment by jbkunst** [comment]
Hi @TitovAV!

Mmm.. may be the question need to be why hchart don't work :/. Please, ensure you're using the development version of highcharter.

Read https://cran.r-project.org/web/packages/highcharter/vignettes/charting-data-frames.html can help too.

Finally you can do something like this:  
```r
dchoices <- Crude_Oil_Production %>% dplyr::filter(STEO_Issue %in% c(input$STEO))

hc <- highchart() %>%
  hc_add_series(dchoices, "line", hcaes(x = Date, y = Data, group = STEO_Issue))

hc
```

Finally, to this type question I recommend you use stackoverflow. I prefer use github for requests/bugs related questions ;)!

Regards,
