### ISSUE TITLE
Survival plots via highcharter

### ISSUE THREAD

**Issue by HRAnalytics** [jbkunst/highcharter#401]
I just tried to make some survival plots via highcharter and have no result - just white screen.
Can't even replicate examples in documentation. 
Highcharter version: 0.5.0.9999

Example:
lsurv2 <- survfit(Surv(time, status) ~ x, aml, type='fleming') 
hchart(lsurv2, fun="cumhaz")

Can somebody replicate this example on this highcharter version?

**Comment by jbkunst** [comment]
Hi @HRAnalytics 

http://rpubs.com/jbkunst/highcharter-issues-401

Be sure you have the last development version.

**Comment by HRAnalytics** [comment]
Doesn't work, highcharter version the same, but R version is 3.4.3.

> devtools::session_info()
Session info ---------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, mingw32             
 ui       RStudio (1.1.383)           
 language (EN)                        
 collate  Russian_Ukraine.1251        
 tz       Europe/Helsinki             
 date     2018-02-18                  

Packages -------------------------------------------------------------------------------------------------------------------
 package      * version    date       source                              
 assertthat     0.2.0      2017-04-11 CRAN (R 3.4.3)                      
 backports      1.1.2      2017-12-13 CRAN (R 3.4.3)                      
 base         * 3.4.3      2017-12-06 local                               
 BBmisc         1.11       2017-03-10 CRAN (R 3.4.3)                      
 bindr          0.1        2016-11-13 CRAN (R 3.4.3)                      
 bindrcpp       0.2        2017-06-17 CRAN (R 3.4.3)                      
 bitops         1.0-6      2013-08-17 CRAN (R 3.4.1)                      
 broom          0.4.3      2017-11-20 CRAN (R 3.4.3)                      
 caTools        1.17.1     2014-09-10 CRAN (R 3.4.3)                      
 checkmate      1.8.5      2017-10-24 CRAN (R 3.4.3)                      
 cmprsk         2.2-7      2014-06-17 CRAN (R 3.4.3)                      
 colorspace     1.3-2      2016-12-14 CRAN (R 3.4.3)                      
 compiler       3.4.3      2017-12-06 local                               
 curl           3.1        2017-12-12 CRAN (R 3.4.3)                      
 data.table     1.10.4-3   2017-10-27 CRAN (R 3.4.3)                      
 datasets     * 3.4.3      2017-12-06 local                               
 devtools       1.13.4     2017-11-09 CRAN (R 3.4.3)                      
 digest         0.6.15     2018-01-28 CRAN (R 3.4.3)                      
 dplyr          0.7.4      2017-09-28 CRAN (R 3.4.3)                      
 foreign        0.8-69     2017-06-22 CRAN (R 3.4.3)                      
 gdata          2.18.0     2017-06-06 CRAN (R 3.4.3)                      
 ggplot2        2.2.1      2016-12-30 CRAN (R 3.4.3)                      
 ggpubr         0.1.6      2017-11-14 CRAN (R 3.4.3)                      
 glue           1.2.0      2017-10-29 CRAN (R 3.4.3)                      
 gplots       * 3.0.1      2016-03-30 CRAN (R 3.4.3)                      
 graphics     * 3.4.3      2017-12-06 local                               
 grDevices    * 3.4.3      2017-12-06 local                               
 grid           3.4.3      2017-12-06 local                               
 gridExtra      2.3        2017-09-09 CRAN (R 3.4.3)                      
 gtable         0.2.0      2016-02-26 CRAN (R 3.4.3)                      
 gtools         3.5.0      2015-05-29 CRAN (R 3.4.1)                      
 highcharter  * 0.5.0.9999 2018-02-18 Github (jbkunst/highcharter@90715ad)
 htmltools      0.3.6      2017-04-28 CRAN (R 3.4.3)                      
 htmlwidgets    1.0        2018-01-20 CRAN (R 3.4.3)                      
 igraph         1.1.2      2017-07-21 CRAN (R 3.4.3)                      
 jsonlite       1.5        2017-06-01 CRAN (R 3.4.3)                      
 KernSmooth     2.23-15    2015-06-29 CRAN (R 3.4.3)                      
 km.ci          0.5-2      2009-08-30 CRAN (R 3.4.3)                      
 KMsurv         0.1-5      2012-12-03 CRAN (R 3.4.1)                      
 knitr          1.19       2018-01-29 CRAN (R 3.4.3)                      
 lattice        0.20-35    2017-03-25 CRAN (R 3.4.3)                      
 lazyeval       0.2.1      2017-10-29 CRAN (R 3.4.3)                      
 lubridate      1.7.2      2018-02-06 CRAN (R 3.4.3)                      
 magrittr       1.5        2014-11-22 CRAN (R 3.4.3)                      
 Matrix         1.2-12     2017-11-20 CRAN (R 3.4.3)                      
 memoise        1.1.0      2017-04-21 CRAN (R 3.4.3)                      
 methods      * 3.4.3      2017-12-06 local                               
 mlr            2.11       2017-03-15 CRAN (R 3.4.3)                      
 mnormt         1.5-5      2016-10-15 CRAN (R 3.4.1)                      
 munsell        0.4.3      2016-02-13 CRAN (R 3.4.3)                      
 nlme           3.1-131    2017-02-06 CRAN (R 3.4.3)                      
 parallel       3.4.3      2017-12-06 local                               
 parallelMap    1.3        2015-06-10 CRAN (R 3.4.3)                      
 ParamHelpers   1.10       2017-01-05 CRAN (R 3.4.3)                      
 pillar         1.1.0      2018-01-14 CRAN (R 3.4.3)                      
 pkgconfig      2.0.1      2017-03-21 CRAN (R 3.4.3)                      
 plyr           1.8.4      2016-06-08 CRAN (R 3.4.3)                      
 psych          1.7.8      2017-09-09 CRAN (R 3.4.3)                      
 purrr          0.2.4      2017-10-18 CRAN (R 3.4.3)                      
 quantmod       0.4-12     2017-12-10 CRAN (R 3.4.3)                      
 R6             2.2.2      2017-06-17 CRAN (R 3.4.3)                      
 Rcpp           0.12.15    2018-01-20 CRAN (R 3.4.3)                      
 reshape2       1.4.3      2017-12-11 CRAN (R 3.4.3)                      
 rlang          0.1.6      2017-12-21 CRAN (R 3.4.3)                      
 rlist          0.4.6.1    2016-04-04 CRAN (R 3.4.3)                      
 ROCR         * 1.0-7      2015-03-26 CRAN (R 3.4.3)                      
 scales         0.5.0.9000 2018-02-18 Github (hadley/scales@d767915)      
 splines        3.4.3      2017-12-06 local                               
 stats        * 3.4.3      2017-12-06 local                               
 stringi        1.1.6      2017-11-17 CRAN (R 3.4.2)                      
 stringr        1.2.0      2017-02-18 CRAN (R 3.4.3)                      
 survival     * 2.41-3     2017-04-04 CRAN (R 3.4.3)                      
 survminer      0.4.2      2018-01-31 CRAN (R 3.4.3)                      
 survMisc       0.5.4      2016-11-23 CRAN (R 3.4.3)                      
 tibble         1.4.2      2018-01-22 CRAN (R 3.4.3)                      
 tidyr          0.8.0      2018-01-29 CRAN (R 3.4.3)                      
 tools          3.4.3      2017-12-06 local                               
 TTR            0.23-3     2018-01-24 CRAN (R 3.4.3)                      
 utils        * 3.4.3      2017-12-06 local                               
 whisker        0.3-2      2013-04-28 CRAN (R 3.4.3)                      
 withr          2.1.1.9000 2018-02-18 Github (jimhester/withr@df18523)    
 xtable         1.8-2      2016-02-05 CRAN (R 3.4.3)                      
 xts            0.10-1     2017-12-20 CRAN (R 3.4.3)                      
 yaml           2.1.16     2017-12-12 CRAN (R 3.4.3)                      
 zoo            1.8-1      2018-01-08 CRAN (R 3.4.3)

**Comment by HRAnalytics** [comment]
Still have problem:
![scr2](https://user-images.githubusercontent.com/28641624/36430202-4185d0f6-165d-11e8-9aa5-f9f57edfe9bf.png)
![scr1](https://user-images.githubusercontent.com/28641624/36430204-41aeb1e2-165d-11e8-942d-298406e1cd53.png)

Some simple plots not rendering too

**Comment by jbkunst** [comment]
Hi @HRAnalytics 

Please can you download the development version and try again? 

(You have the  #399 related version and we did a mistake)

**Comment by HRAnalytics** [comment]
Thank you! its ok now after updating package
