### ISSUE TITLE
color lost with data over 5000 rows

### ISSUE THREAD

**Issue by samWieczorek** [jbkunst/highcharter#406]
Hi, 
I have a strange behaviour with a little piece of code. I want to plot n points with a specific color.
The code is  : 
n <- 5000
ds <- data.frame(x=abs(rnorm(n)),y=abs(rnorm(n)), color=rep("orange",n))

highchart() %>%
 hc_add_series(data=ds, type="scatter")

from n=1 to 4999, the plot is ok with orange points, but over 5000, they became blue ....
I have this issue on one machine but on another machine (same R version and same packages versions), the points are all orange.

It seems that it is the configuration of the first machine but I do not find what is wrong.

If anyone has an idea...

Best

Sam

**Comment by jbkunst** [comment]
Hi @samWieczorek !

Really strange the behaviour. Not sure what is going on. My suspect is highchartsJS and not highcharter.

Any way. You need all the points with one color? If this is the case is better yo set the color to the series (as the next example) instead of giving the color to each point (your code). This will result in a ligthweight widget due you don't send the "orange" value 5000 times.

```r
n <- 5001
ds <- data.frame(x=abs(rnorm(n)),y=abs(rnorm(n)))

highchart() %>%
  hc_add_series(data=ds, type="scatter", color = "orange")
````

![image](https://user-images.githubusercontent.com/56481/36795560-1cd76578-1c82-11e8-8b26-6338f52b686b.png)

Next time, try to format your code ;)!

**Comment by samWieczorek** [comment]
Hi
and thank you for your quick answer.
In fact, my code is a bit more complicated than the example I have given. My goal is to be able to draw different regions in the scatter plot (defined by two thresholds). The color of the points differ from a region to another

My real code is the following : 
```
h1 <-  highchart() %>% 
hc_add_series(data = ds, type="scatter") %>%
        hc_add_series(data = data.frame(
            x=c(-threshold_logFC, -threshold_logFC), 
            y=c(0,max(df$y))), type="line", color="lightgrey") %>%
        hc_add_series(data = data.frame(
            x=c(threshold_logFC, threshold_logFC), 
            y=c(0,max(df$y))), type="line", color="lightgrey") %>%
        hc_add_series(data = data.frame(
        x=c(-max(max(df$x), abs(min(df$x))),max(max(df$x), abs(min(df$x)))), 
                                        y=c(threshold_pVal,threshold_pVal)), 
            type="line", color="lightgrey", marker=list(enabled = FALSE)) %>%
        my_hc_chart(zoomType = "xy",chartType="scatter") %>%
        hc_legend(enabled = FALSE) %>%
        hc_xAxis(title = list(text="logFC")) %>%
        hc_yAxis(title = list(text = "-log10(pValue)")) %>%
        hc_tooltip(headerFormat= '',
                   pointFormat = txt_tooltip) %>%
        hc_plotOptions( series = list( animation=list(duration = 100),
                                cursor = "pointer", 
                                       point = list( events = list( 
                                           click = clickFunction ) ) ) ) %>%
      my_hc_ExportMenu(filename = "volcanoplot")
```
        

where df contains three slots : x, y and color

Maybe instead of using only one serie, I can build two different series : one for the grey points and one for the orange one ?

![image](https://user-images.githubusercontent.com/2912670/36835040-26a6e37c-1d35-11e8-9819-25a1f41d76d3.png)

**Comment by jbkunst** [comment]
> Maybe instead of using only one serie, I can build two different series : one for the grey points and one for the orange one ?

Yes, I think that is a _clearer_ approach. 

A suggestion: You can use ´plotLines´ to draw the treshold to draw the lines. I think is easy (you don't need to calculate max) and clearer and you have a lot of options https://api.highcharts.com/highcharts/xAxis.plotLines

```r
library(highcharter)
library(tidyverse)

n <- 5000

ds <- data_frame(
  x = rnorm(n),
  y = rnorm(n),
  g = ifelse(y > 1 & abs(x) > 1, "g1", "g2")
  )

hchart(ds, "scatter", hcaes(x, y, group = g)) %>% 
  hc_colors(c("orange", "lightgrey")) %>% 
  hc_yAxis(
    plotLines = list(list(color = "red", width = 2, value = 1, zIndex = 5))
  ) %>% 
  hc_xAxis(
    plotLines = list(
      list(color = "red", width = 2, value = 1, zIndex = 5),
      list(color = "red", width = 2, value = -1, zIndex = 5)
      )
  ) 
```

![image](https://user-images.githubusercontent.com/56481/36847148-1a367bc8-1d3c-11e8-8ea2-fc7cef53d9f8.png)

**Comment by samWieczorek** [comment]
I have resolved my problem by upgrading R to the devel version. But still interesting by the reason that made if failed

**Comment by samWieczorek** [comment]
Thanks for the tip !!
