### ISSUE TITLE
Can not add mathematical expression, superscript, subscript to highcharter axis or legend

### ISSUE THREAD

**Issue by tungmilan** [jbkunst/highcharter#409]
Great package! Thank you very much for developing this!

I was wondering how I can add mathematical expression, superscript, subscript to highcharter axis or legend? I tried to use `expression` but it didn't work. 

``` r

library(magrittr)
library(highcharter)

data(citytemp)

highchart() %>% 
  # hc_yAxis(title = list(text = "Temperature")) %>% 
  hc_yAxis(title = list(text = expression("Temperature"~(degree*C)))) %>%
  hc_xAxis(categories = citytemp$month) %>% 
  hc_add_series(name = expression("Tokyo temperature"~(degree*C)), data = citytemp$tokyo) %>% 
  hc_add_series(name = expression("London temperature"~(degree*C)), data = citytemp$london) %>%
  hc_legend(align = "center", verticalAlign = "bottom",
            layout = "horizontal", x = 0, y = 0) 
```

![rplot](https://user-images.githubusercontent.com/6590141/36913758-d0e41eca-1dff-11e8-9cc1-09d1aa3cc880.png)

**Comment by tungmilan** [comment]
Thanks @jbkunst for the prompt reply! This is what I got after the change you suggested

```
highchart() %>% 
  hc_yAxis(title = list(text = '"Temperature"~(degree*C)')) %>%
  hc_xAxis(categories = citytemp$month) %>% 
  hc_add_series(name = 'Tokyo temperature~(degree*C)', data = citytemp$tokyo) %>% 
  hc_add_series(name = 'London temperature~(degree*C)', data = citytemp$london) %>%
  hc_legend(align = "center", verticalAlign = "bottom",
            layout = "horizontal", x = 0, y = 0) 
```

![rplot02](https://user-images.githubusercontent.com/6590141/36914815-67e596fc-1e03-11e8-87ff-b5b997d2e3cb.png)

**Comment by jbkunst** [comment]
@tungmilan , Is that what you want?

**Comment by tungmilan** [comment]
@jbkunst : No what I want is similar to [this](https://stackoverflow.com/questions/37554118/ggplot-inserting-space-before-degree-symbol-on-axis-label). Thanks!

![rplot02](https://i.stack.imgur.com/SILdo.jpg)

**Comment by jbkunst** [comment]
Ok,

You need to change to html world. So you need:

- See how "tags" works. like sup, sub https://www.w3schools.com/tags/tag_sup.asp 
- Enabled the use of html in highcharts text (usually with `useHTML = TRUE`) https://stackoverflow.com/questions/28963286/using-image-tag-as-series-name-in-highcharts
- Use the _mathematical_ symbols with  their hexadecimal form https://www.w3schools.com/charsets/ref_utf_math.asp

Example:

```r
library(highcharter)

data(citytemp)

highchart() %>% 
  hc_title(text = "This is a <sup>Sup</sup>title I will display &#8738;", useHTML = TRUE) %>% 
  hc_subtitle(text = "This is a <sub>sub</sub>title", useHTML = TRUE) %>% 
  hc_xAxis(title = list(text = "hola<sub>subtag</sub>", useHTML = TRUE)) %>%
  hc_yAxis(title = list(text = "Temperature celcius (°C)")) %>%
  hc_xAxis(categories = citytemp$month) %>% 
  
  # the next options will enable html in the name of legendd
  hc_legend(useHTML = TRUE) %>% 
  
  # add series with names with html tags and unicodes
  hc_add_series(name = "hey! im a X<sup>2</sup> wich &#8712 to real <b>R</b><sup>+</sup>", data = citytemp$tokyo) %>% 
  hc_add_series(name = "look! an integral &#8755", data = citytemp$london)

```

![image](https://user-images.githubusercontent.com/56481/36920818-b71a181e-1e40-11e8-8b61-3773dc37736e.png)

Hope this helps! ;)!

**Comment by tungmilan** [comment]
Good to know! Thanks @jbkunst !

**Comment by jbkunst** [comment]
@tungmilan I edited the code. I forgot to add `hc_tooltip(useHTML = TRUE, shared = TRUE) %>% `

**Comment by tungmilan** [comment]
@jbkunst Thanks again! One last question: how can I modify the limit on the y-axis e.g. `ylim = c(5, 35)`? I couldn't find such information anywhere in the documentation

**Comment by jbkunst** [comment]
Please, read:

- https://dantonnoriega.github.io/ultinomics.org/post/2017-04-05-highcharter-explainer.html 
- https://api.highcharts.com/highcharts/yAxis
- Then https://api.highcharts.com/highcharts/yAxis.min

**Comment by brooklyOPC** [comment]
I know this was closed... but how do you do this within the categories option of the xaxis? I have the following code

`chart1<- highchart() %>%
    hc_chart(type = 'bar') %>%
    hc_xAxis(type="category", title = list(text = 'Age at Review'), useHTML = T, 
             categories = c('85+', '75-84', '65-74', '55-64','45-54',"35-44", '&#8804; 34')) %>%
    hc_plotOptions(series = list(groupPadding = 0.2, pointPadding = -.4)) %>%
    hc_add_series(name = "Database", data = ageDist_opc, useHTML = T,
              color = '#9EB9D4') %>% 
    hc_add_series(name = practice_name, data =  ageDist, useHTML = T,
                  color = '#0D5295') %>%
hc_yAxis(labels = list(format = "{value}%"), tickInterval = 5)`

As you can see, I've tried adding the `useHTML` option to the series itself and the hc_xAxis function, but no matter what I do, the less than or equal to symbol doesn't show up and the plain text "&#8804;" does instead
