### ISSUE TITLE
Sankey in highcharter using R

### ISSUE THREAD

**Issue by meetshah31094** [jbkunst/highcharter#412]
How do we create sankey in highcharter using R? Are there any sample codes? What is the format of the input?

**Comment by jbkunst** [comment]
Hi @meetshah31094 

You can look in the meantime this file https://github.com/jbkunst/highcharter/blob/master/dev/highcharts-v6.R#L43

In the next release I will put that examples in the highcharter website.

Regards,

**Comment by meetshah31094** [comment]
Hi @jbkunst 
I saw this file. However, i am not getting any output when I run the code snippet of sankey even though i copy pasted the code as it is

**Comment by jbkunst** [comment]
Did you update to the _development_ version?

**Comment by meetshah31094** [comment]
How do we do that?

**Comment by meetshah31094** [comment]
ERROR: dependencies 'igraph', 'lubridate', 'yaml' are not available for package 'highcharter'
* removing 'C:/Users/Meet.Shah/Documents/R/win-library/3.4/highcharter'
Installation failed: Command failed (1)

**Comment by meetshah31094** [comment]
ERROR: dependencies 'igraph', 'lubridate', 'yaml' are not available for package 'highcharter'
Installation failed: Command failed (1)

**Comment by meetshah31094** [comment]
Getting this error

**Comment by jbkunst** [comment]
Update/install those packages and try again.

**Comment by meetshah31094** [comment]
ERROR: lazy loading failed for package 'highcharter'

Getting this now

**Comment by meetshah31094** [comment]
@jbkunst  can hcharts be used to render the sankey in rshiny?

**Comment by jbkunst** [comment]
@meetshah31094  Yes. Every highcharter chart can work in shiny ;)!

**Comment by meetshah31094** [comment]
@jbkunst can we create custom tooltip in R using hchart? I want to specify a different tooltip for nodes and links. Is that possible?

**Comment by meetshah31094** [comment]
??

**Comment by meetshah31094** [comment]
nodeFormatter doesn't seem to work. I want to display additional data at nodes but it is displaying undefined in the tooltip
