### ISSUE TITLE
Codes for your Highcharter examples

### ISSUE THREAD

**Issue by MarkusLang1987** [jbkunst/highcharter#426]
Hello, 

i really tried to find this out on my own for some hours, but i could not find an answer :-(.

http://jkunst.com/highcharter/highcharts.html

Here is the link to some charts. How do is actually find the codes of these examples? They seem not to be available on the page. I would need a columrange chart for a dashboard, but when I add series to my chart, nothing is displayed. Where can i find ALL of the codes of the examples?

Thank you :-)

Best regards
Markus

**Comment by jbkunst** [comment]
Every page in that site comes from a R script, in this repo there is _gh_pages_ branch which contains the site. In https://github.com/jbkunst/highcharter/tree/gh-pages/_scripts you can see all the scripts ;)

Good luck!

**Comment by MarkusLang1987** [comment]
Thannk you very much. In general I wanted to thank you for your awesome work. What you did with this library is just amazing!

**Comment by jbkunst** [comment]
Oh! Thank so much for say it. Iitmakes me feel happy! :smile:
