### ISSUE TITLE
create a separate htmlwidget with boost module

### ISSUE THREAD

**Issue by jbkunst** [jbkunst/highcharter#43]
This include highcharts, exporting, and boost (no more, no less)

hcboost()?  highcharterboost()?

**Comment by shrektan** [comment]
Ha, what is _boost_?

**Comment by jbkunst** [comment]
Hi @shrektan 

http://www.highcharts.com/articles/2-news/175-highcharts-performance-boost  :+1:  :wink: 

There are some conflicts with highstock and maps with this plugin (according my tests) so I need to have another htmlwidget to implement this plugin. Besides this will help to get a lightweight highchart widget beacuse right now `highchart()` (maps + stocks + 3d + plugins + etc) is getting a little heavy.

**Comment by shrektan** [comment]
Thanks for the quick respond. 

Great. I'm a fan of beautiful charts, so I really love this package. It's easy to use and very powerful.

Thanks again! Good work!

**Comment by jbkunst** [comment]
Thank you for your kind words and for use the package.
