### ISSUE TITLE
Sankey digaram implementation in R

### ISSUE THREAD

**Issue by semco-jahanbin-mpf** [jbkunst/highcharter#437]
I have been trying to use Sankey diagram in R, but it seems like it hasn't implemented, For example in the below dataset is 'test', which has two categorical variables PRODUCT_NAME_N and DATEPART and numerical variable Expenditure:

hchart(object = test, type = "sankey", 
       hcaes(from = PRODUCT_NAME, to = DATEPART, weight = Expenditure ))

The above doesn't return any outpots in R.

**Comment by jbkunst** [comment]
Hi @semco-jahanbin-mpf  Semco,

Try to download the development version first, and then try something like https://github.com/jbkunst/highcharter/blob/master/dev/highcharts-v6.R#L43

**Comment by heider-c** [comment]
> Hi @semco-jahanbin-mpf Semco,
> 
> Try to download the development version first, and then try something like https://github.com/jbkunst/highcharter/blob/master/dev/highcharts-v6.R#L43

This website is no longer alive. Can you post a working example?
I have a clean dataset (tibble) and want to generate a sankey diagram. 

Thanks a lot.
