### ISSUE TITLE
How change time frame in hc_xAxis - month in quartal

### ISSUE THREAD

**Issue by VoVDm** [jbkunst/highcharter#439]
Hi.
I have this time series(change quarter GDP):
QQRGDPts
   

Year  Qtr1  Qtr2  Qtr3  Qtr4
1948  2.84  4.64  5.33  3.80
1949  0.90 -1.04 -0.51 -1.50
1950  3.84  7.34 10.26 13.40
1951 10.55  9.17  7.28  5.49
1952  5.16  3.58  2.23  5.35
1953  6.19  6.79  5.43  0.53
1954 -1.76 -2.42 -0.76  2.74
1955  6.16  7.78  8.00  6.57
1956  3.21  2.40  0.96  1.99
1957  3.05  1.98  3.06  0.36
1958 -2.87 -2.01 -0.71  2.67
1959  7.35  9.25  6.57  4.54
1960  4.93  2.04  2.50  0.86
1961 -0.67  1.56  3.00  6.37
1962  7.56  6.73  5.98  4.28
1963  3.58  3.81  4.84  5.18
1964  6.27  6.15  5.53  5.15
1965  5.47  5.65  6.35  8.48
1966  8.48  7.45  6.07  4.51
1967  2.93  2.60  2.75  2.70
1968  3.83  5.49  5.34  4.97
1969  4.48  3.07  2.97  2.07
1970  0.33  0.18  0.45 -0.15
1971  2.70  3.11  3.00  4.38
1972  3.48  5.27  5.42  6.86
1973  7.56  6.31  4.77  4.02
1974  0.68 -0.19 -0.61 -1.93
1975 -2.30 -1.81  0.79  2.56
1976  6.16  6.15  4.95  4.33
1977  3.22  4.45  5.76  4.98
1978  4.14  6.11  5.28  6.68
1979  6.52  2.66  2.40  1.30
1980  1.43 -0.75 -1.61 -0.04
1981  1.70  3.05  4.39  1.29
1982 -2.42 -1.17 -2.64 -1.40
1983  1.59  3.35  5.75  7.83
1984  8.55  7.99  6.96  5.63
1985  4.61  3.74  4.33  4.28
1986  4.21  3.74  3.18  2.94
1987  2.71  3.39  3.28  4.45
1988  4.31  4.51  4.17  3.84
1989  4.30  3.75  3.92  2.78
1990  2.87  2.46  1.73  0.65
1991 -0.91 -0.53 -0.07  1.22
1992  2.90  3.24  3.74  4.33
1993  3.30  2.78  2.29  2.63
1994  3.44  4.23  4.34  4.13
1995  3.47  2.44  2.71  2.28
1996  2.60  4.02  4.09  4.45
1997  4.56  4.32  4.68  4.39
1998  4.62  4.07  4.10  5.00
1999  4.80  4.65  4.60  4.69
2000  4.17  5.27  4.08  2.89
2001  2.30  0.94  0.49  0.21
2002  1.42  1.44  2.25  2.04
2003  1.63  2.01  3.22  4.36
2004  4.41  4.21  3.43  3.12
2005  3.62  3.40  3.33  3.03
2006  3.17  2.94  2.17  2.39
2007  1.24  1.71  2.30  1.87
2008  1.11  0.84 -0.31 -2.77
2009 -3.46 -4.06 -3.28 -0.24
2010  1.60  2.72  3.08  2.73
2011  1.89  1.65  1.18  1.68
2012  2.75  2.49  2.39  1.28
2013  1.31  1.04  1.69  2.66
2014  1.72  2.67  3.19  2.70
2015  3.76  3.30  2.40  2.02
2016  1.36  1.23  1.52  1.84
2017  2.00  2.21  2.30  2.58
2018  2.86

I want plot this time series

QQRGDP <- highchart(type = "stock") %>% 
  hc_title(text = "Annual U.S. GDP ") %>% 
  hc_subtitle(text = "Source: U.S. Bureau of Economic Analysis",  align = "left") %>%
  hc_add_series(QQRGDPts,type="column", name="GDP")
QQRGDP

![rplot](https://user-images.githubusercontent.com/38957510/39592683-320d7dc2-4f10-11e8-9775-e3f8a6c7a122.jpeg)
but on X-axis I have only mounly data. How convert month on quartal data?
TimeLabelFormats in xAxis.date - does not work!
If I change data on X-axis  and type chart- not = "stock" - in navigation - error
In chart 2 - hc_xAxis(type = "category")%>%
![rplot2](https://user-images.githubusercontent.com/38957510/39602372-a558023a-4f2d-11e8-8da2-e1e47f4f15c1.jpeg)
I find answer on my question in this post [https://stackoverflow.com/questions/16543896/highcharts-time-based-quarterly-data-xaxis-label-issue](url) but I don't know how realisation this in R.
Thank.

**Comment by ameneguetti** [comment]
In R, I tried this on my chart:
 ```
 hc_xAxis(
    alternateGridColor = '#FAFAFA',
    labels= list(
       style=list(
         fontSize= '9px',
         width= '175px'
       ),
      formatter= JS("function() {
        var s;
        if (Highcharts.dateFormat('%b', this.value) == 'Jan') {
          s = s + \"Q1\"
        };
        if (Highcharts.dateFormat('%b', this.value) == 'Apr') {
          s = s + \"Q2\"
        };
        if (Highcharts.dateFormat('%b', this.value) == 'Jul') {
          s = s + \"Q3\"
        };
        if (Highcharts.dateFormat('%b', this.value) == 'Oct') {
          s = s + \"Q4\"
        };
        s = s + \" \" + Highcharts.dateFormat('%Y', this.value);
        return s;
      }")
    ),
    tickInterval = 31536000000,
    type = 'datetime'
  ) %>%
```

But I didn't succeed, see:
![plot hc](https://user-images.githubusercontent.com/51303505/61840085-68396580-ae66-11e9-97e1-668c3eb774bd.png)

Does anyone have any suggestions or solutions, please?

**Comment by GregorDeCillia** [comment]
I just had the exact same problem and solved it with `htmlwidgets::prependContent()`. This functions allows to add `js` and `css` definitions to `htmlwidgets` objects. First, you define a custom `dateFormat`.

```js
// file: formatQuarter.js
// source: https://jsfiddle.net/0nqkywLv/
Highcharts.dateFormats = {
    q: function (timestamp) {
        var date = new Date(timestamp),
        quarter = (Math.floor(date.getUTCMonth() / 3) + 1);
        return quarter;
    }
};
```

Then, you prepend the content of the script to the widget object. This allows you to use `%q` in format definitions. In this case,  the formatting of the tooltip as well as the xAxis is changed.

```R
# file: make_graph.R
library(highcharter)

js_script <- readLines("formatQuarter.js") %>%
  paste(collapse = "\n") %>%
  htmltools::tag("script", .)

highchart(type = "stock") %>% 
  hc_add_series(QQRGDPts, type = "column") %>%
  hc_xAxis(labels = list(format = '{value:Q%q\'%y}')) %>% 
  hc_tooltip(xDateFormat =  'Q%q\'%y') %>%
  htmlwidgets::prependContent(js_script)
```
