### ISSUE TITLE
Streamgraph in Highcharts

### ISSUE THREAD

**Issue by MargaFields** [jbkunst/highcharter#441]
Hi, I was trying to make a streamgraph in Highcharts in R, but it seems to require a javascript module. Is there any way to do this?
Thank you!

**Comment by Ettouhami** [comment]
Hello I am experiencing the same issue, how do we add a streamgraph using highcharter in R?

**Comment by jbkunst** [comment]
Hi, by the moment you need to install the development version https://github.com/jbkunst/highcharter#installation and then test https://github.com/jbkunst/highcharter/blob/master/dev/highcharts-v6.R#L29

Regards,
