### ISSUE TITLE
Images in Tooltip 

### ISSUE THREAD

**Issue by systats** [jbkunst/highcharter#442]
Hi jbkunst,

i try to show images for certain points in the tooltip of a linegraph. But only got that far ...

```
dat <- tibble(x = 1:10, y = rnorm(10))
dat$image <- NA
dat$image[3] <- "https://cloud.githubusercontent.com/assets/56481/13571107/70cabbd2-e451-11e5-9b93-636e6da5f05e.png"

dat %>%
  hchart("line", hcaes(x = x, y = y)) %>%
    hc_tooltip(
      pointFormat = 
      "{point.image}
      <img src = {point.image}>",
    useHTML = T
  )
```

I found this [Highcharts stackoverflow issue](https://stackoverflow.com/questions/8474375/highcharts-tooltip-image) but can not translate it. If at all possible I need a quick solution for a presentation tomorrow ... 

As always, thanks in advance!
Best, 
Simon

**Comment by jbkunst** [comment]
Not sure what is the problem. I can show the image:

![image](https://user-images.githubusercontent.com/56481/39793131-700ebd76-531a-11e8-9204-43100854e7a5.png)

with:

```r
dat %>%
  hchart("line", hcaes(x = x, y = y)) %>%
  hc_tooltip(
    pointFormat = "{point.x} <img src ='{point.image}' width = '100px'>",
    useHTML = T
  )
```

Do you have the development version installed?

**Comment by systats** [comment]
Great! This will be adopted immediately. Thanks jbkunst for your quick response.
