### ISSUE TITLE
Getting Error in dirname(to) : path too long

### ISSUE THREAD

**Issue by fsiola** [jbkunst/highcharter#445]
`Error in dirname(to) : path too long` when running. 

`
highchart(type = "stock") %>%  hc_title(text = "Total de ligações") %>%  hc_add_series_times_values(serieTT$DIA, total$PREVISTO, id = "previsto")
`

Any help?

**Comment by fsiola** [comment]
Changed project to smaller path and it worked.

**Comment by MMJansen** [comment]
Hi @fsiola , you closed this topic. Does this mean you found a solution? I would love to hear it, since I am running into the same error message.
