### ISSUE TITLE
hcaes(group=x) changes data sorting

### ISSUE THREAD

**Issue by jslul** [jbkunst/highcharter#449]
Hello

Whenever i use grouping in my stacked column chart, the sorting goes bad. Is there a fix for this, or an option? See example below.

**Without the use of group:**
![image](https://user-images.githubusercontent.com/26651906/40488816-ea24649a-5f67-11e8-97dc-bf46c923faeb.png)

**With group:**
![image](https://user-images.githubusercontent.com/26651906/40488956-3db610e0-5f68-11e8-87e8-70ef4d98eb76.png)

**Example:**
```
library(highcharter)
library(dplyr)

hej <- mtcars
hej$car <- rownames(mtcars)
hej$sub <- substr(hej$car,1,3)

hejmax <- hej %>% group_by(sub) %>% summarise(maxmpg=sum(mpg)) %>% arrange(desc(maxmpg))

hej <- hej %>% group_by(car,sub) %>% summarise(mpg = sum(mpg)) %>% ungroup() %>% mutate(., group = group_indices(., sub)) %>% arrange(group, desc(mpg))

hej <- left_join(hejmax, hej) %>% arrange(desc(maxmpg),desc(group))

#with grouping
highchart() %>% hc_add_series(type = "column", data = hej, hcaes(group=car, y = mpg, x=sub)) %>% hc_xAxis(type = 'category') %>% hc_plotOptions(column = list(stacking='normal'))

#without grouping
highchart() %>% hc_add_series(type = "column", data = hej, hcaes(y = mpg, x=sub)) %>% hc_xAxis(type = 'category') %>% hc_plotOptions(column = list(stacking='normal'))
```

**Comment by edavidaja** [comment]
See #363, #373 

I use `tidyr::complete()` to add zero values for missing group elements and then the sort order is preserved.
