### ISSUE TITLE
How to change display message when there is no data?

### ISSUE THREAD

**Issue by peeyooshc** [jbkunst/highcharter#451]
Recently upgraded to highcharter 0.6 and the default behaviour of showing "No data to display". That isn't working anymore and I can't figure out how to enable it.

Can you please advise how to turn it back on?

**Comment by peeyooshc** [comment]
in `htmlwidgets > highchart.yaml` the call to `modules/no-data-to-display.js` has been commented out. Uncommenting this line shows the "No data to display" message.

**Comment by ashbaldry** [comment]
Now that 0.7.0 is out on CRAN, is there any way to enable this module without editing the yaml (as unable to write to that file)? I've tried the following and just brings up a blank plot:
`highcharter::hc_add_dependency(highcharter::highchart(), "modules/no-data-to-display.js")`

**Comment by jbkunst** [comment]
Hi @ashbaldry 

You can do in the meantime: 

```r
library(highcharter)


opts <- getOption("highcharter.chart") 
opts$noData <- list(useHTML = TRUE)
options(highcharter.chart = opts) 

highchart() 

highchart() %>% 
  hc_add_dependency("modules/no-data-to-display.js")

highchart() %>% 
  hc_add_series(data = 1:10) %>% 
  hc_add_dependency("modules/no-data-to-display.js")
```

I don't know why the text is not centered. I'll check.

I'm thinking to put this module as default, not sure yet. 

Let me know if this example works for you.

**Comment by ashbaldry** [comment]
Thanks so much @jbkunst, works for me!

To get it in the center of the plot I just added an extra argument to opts$noData:
```
opts$noData <- list(useHTML = TRUE, position = list(align = "center", verticalAlign = "middle"))
```

**Comment by jbkunst** [comment]
@ashbaldry 

Perfect!  Thanks for the reply!
