### ISSUE TITLE
Empty data frame breaks chart

### ISSUE THREAD

**Issue by bogdanrau** [jbkunst/highcharter#456]
```
test <- data.frame(x_var = character(), y_var = integer())

highchart() %>%
   hc_add_series(data = test, type = 'column', hcaes(x = x_var, y = y_var))
```
Will result in:
`replacement has 1 row, data has 0`

This is impacting charts created with both `hchart()`, as well as `highchart()`.
I'm running highcharter 0.6.0 (https://github.com/jbkunst/highcharter/commit/ae311b16d620f382b7f45ddf6316ccab362c6794).

**Comment by tonyk7440** [comment]
@bogdanrau Is there an expectation that it wouldn't cause an error?
