### ISSUE TITLE
local build failed due to failing querying a csv file in vignettes

### ISSUE THREAD

**Issue by wwwjk366** [jbkunst/highcharter#459]
Warning in file(file, "rt") :
  cannot open URL 'https://commondatastorage.googleapis.com/ckannet-storage/2012-07-09T214020/global_airports.csv': HTTP status was '403 Forbidden'
Quitting from lines 98-111 (charting-maps.Rmd) 
Error: processing vignette 'charting-maps.Rmd' failed with diagnostics:
cannot open the connection to 'https://commondatastorage.googleapis.com/ckannet-storage/2012-07-09T214020/global_airports.csv'
Execution halted
Error: Command failed (1)

**Comment by jbkunst** [comment]
Fixed due no more vignettes to CRAN!
