### ISSUE TITLE
Add brush point functionality

### ISSUE THREAD

**Issue by csese** [jbkunst/highcharter#46]
Hello, 

First of all, thank you for your package. It is very useful and you made an incredible work. 
I would like to know if you are thinking of integrating a brush point functionality. Similar to the one available for base and ggplot2 plots. 

I know it is not available in the highchart.js library but it seems like it could be possible to implement it. 

Thanks

**Comment by jbkunst** [comment]
Hi @csese,

In highcharts.js you can create select and drop events so then you can update an input in shiny. With that you can implement brush funcionality (sadly you need to know a little js and the highcharts api) to extract the points and send as an input to shiny. 

For example, using http://jkunst.com/highcharter/plugins.html#draggable-points you can implement intercativity between the chart and user as here https://jbkunst.shinyapps.io/highcharter/  (issue #28). So, i think this is relative similar to recreate brush point using as start point this http://jsfiddle.net/tznwoc09/  and this  http://jsfiddle.net/highcharts/nsuA6/ (issue #41).

I plan to add examples, create addins or gadgets after the next realease of the package :smile: and try to make some javascript script to send updates to shiny automatically to avoid the user know (or type) js.

Hope it helps. Have you any ideas or you want to do something in specific? Glad to hear. 

Thanks for use the package!
