### ISSUE TITLE
Version 0.6.0 release date?

### ISSUE THREAD

**Issue by pwildenhain** [jbkunst/highcharter#460]
Since `ggplot2` `3.0` has been released to CRAN, the fix that addressed #420 now applies to the current version of `ggplot2` instead of the development version.

Do you have an estimated timeline for when you plan to send version `0.6.0` to CRAN?

**Comment by haohua** [comment]
@jbkunst Hi guys, do you have the estimate when to release the 0.6.0 to Cran? Thank you

**Comment by jbkunst** [comment]
@pwildenhain @haohua 

The time has come, the v0.7.0 is out.

https://cran.r-project.org/web/packages/highcharter/index.html
