### ISSUE TITLE
How to draw "Bar with negative stack" in R

### ISSUE THREAD

**Issue by ZENG-David** [jbkunst/highcharter#463]
How to transform the function in highcharts to R code, please help me work out the "Bar with negative stack". the web is

 https://www.highcharts.com/demo/bar-negative-stack

**Comment by edavidaja** [comment]
Assuming you had some data frame `data`, make sure your series X is stored as negative numbers:

```
      highchart() %>%
        hc_add_series(data$x, type = "bar", name = "series x") %>%
        hc_add_series(data$y, type = "bar", name = "series y") %>%
        hc_xAxis(categories = data$categories) %>%
        hc_plotOptions(series = list(stacking = "normal")) %>%
        hc_yAxis(
          labels = list(
            formatter = JS("function(){return Math.abs(this.value);}")
          )
        ) %>%
        hc_tooltip(
          shared = FALSE,
          formatter = JS("function () {
            return this.point.category + '<br/>' + 
            '<b>' + this.series.name + '</b> ' + 
            Highcharts.numberFormat(Math.abs(this.point.y), 1);}")
        )
```

**Comment by ZENG-David** [comment]
Dear Bro.  Appreciate your kindness and sharing. It help me a lot. especially the code` formatter = JS("function(){return Math.abs(this.value);}")` inspired me a lot. again, Thanks a lot, I wish we have more conversation in the future, and the code I transfer from the web [https://www.highcharts.com/demo/bar-negative-stack](url):
`library(highcharter)


categories = c(
  '0-4', '5-9', '10-14', '15-19',
  '20-24', '25-29', '30-34', '35-39', '40-44',
  '45-49', '50-54', '55-59', '60-64', '65-69',
  '70-74', '75-79', '80-84', '85-89', '90-94',
  '95-99', '100 + ')

hc<-highchart()%>%
  hc_chart(type= 'bar')%>%
  hc_title(text= 'Population pyramid for Germany, 2018')%>%
  hc_subtitle(text= 'Source: <a href="http://populationpyramid.net/germany/2018/">Population Pyramids of the World from 1950 to 2100</a>')%>%

  hc_xAxis(
    list(categories=categories,reversed=FALSE,labels=list(step= 1)),
    list(categories= categories,opposite= TRUE,reversed= FALSE,linkedTo= 0,labels=list(step= 1)))%>%

  hc_tooltip(
    shared = FALSE,
    formatter = JS("function () {
                   return this.point.category + '<br/>' +
                   '<b>' + this.series.name + '</b> ' +
                   Highcharts.numberFormat(Math.abs(this.point.y), 1);}")
    )%>%

  hc_yAxis(title= list(text= NULL),
           labels=list(formatter=JS("function () {
               return Math.abs(this.value) + '%';
             }")))%>%

  hc_plotOptions(series=list(stacking= 'normal'))%>%

  hc_series(
    list(name= 'Male',
         data= c(
           -2.2, -2.1, -2.2, -2.4,
           -2.7, -3.0, -3.3, -3.2,
           -2.9, -3.5, -4.4, -4.1,
           -3.4, -2.7, -2.3, -2.2,
           -1.6, -0.6, -0.3, -0.0,
           -0.0)),

    list(name= 'Female',
         data= c(
           2.1, 2.0, 2.1, 2.3, 2.6,
           2.9, 3.2, 3.1, 2.9, 3.4,
           4.3, 4.0, 3.5, 2.9, 2.5,
           2.7, 2.2, 1.1, 0.6, 0.2,
           0.0)))
hc`
