### ISSUE TITLE
R Jupyter Notebook

### ISSUE THREAD

**Issue by jadaliha** [jbkunst/highcharter#468]
I have trouble in using this package in R Jupyter environment.

I copied one of the examples into Rstudio and it did work, and then I copied that into R Jupyter and it returns an error. Most probably this is an incompatibility issue, and I'm wondering if anyone dealt with this issue before:

![image](https://user-images.githubusercontent.com/5852992/45179908-709d9900-b1df-11e8-9f0d-a6f25aaf0565.png)

**Comment by jbkunst** [comment]
Hi @jadaliha 

Mmm... have you tried with other htmlwidgets?

**Comment by jadaliha** [comment]
Hi @jbkunst 
I tried a few. most of them return this error: `HTML widgets cannot be represented in plain text (need html)`.

This one is not htmlwidget, but it is partially working with highchart plot. I'm saying partialy because it is opening another window with highchart plot inside.

```r
require(rCharts)
h1 <- Highcharts$new()
h1$chart(type = "spline")
h1$series(data = c(1, 3, 2, 4, 5, 4, 6, 2, 3, 5, NA), dashStyle = "longdash")
h1$series(data = c(NA, 4, 1, 3, 4, 2, 9, 1, 2, 3, 4), dashStyle = "shortdot")
h1$legend(symbolWidth = 80)
h1
```

**Comment by jadaliha** [comment]
I tried again with iframe.
some of the plots are working and some other does not work

Here is an example that works:
```r
library(htmlwidgets)
library(IRdisplay)
library(highcharter)
data(diamonds, package = "ggplot2")

m = hcboxplot(x = diamonds$x, var = diamonds$color,
          name = "Length", color = "#2980b9") 
saveWidget(m, 'demo.html', selfcontained = FALSE)
display_html('<iframe src="demo.html" width="800" height="600"></iframe>')
```
![image](https://user-images.githubusercontent.com/5852992/45182882-2240c800-b1e8-11e8-8ccd-401cd3955abf.png)

**Comment by pwildenhain** [comment]
Are you sure that you're using the same version of `higcharter` in both environments? That error message looks an awful lot like one I've encountered before, that can be solved by downloading the current version from Github.
