### ISSUE TITLE
WordCloud

### ISSUE THREAD

**Issue by robertogilsaura** [jbkunst/highcharter#472]
I'm trying a wordcloud when d2 is a dataframe, word is a string an weight is a number (frequency)

highchart() %>%
          hc_chart(type="wordcloud") %>% 
          hc_title(text="Wordcloud") %>% 
          hc_add_series(name=d2$word, data=d2$weight)

Impossible to obtain an output ... is it possible?

Thanks

**Comment by jbkunst** [comment]
Hi @robertogilsaura 

You can do: 

```r
hchart(data, "wordcloud", hcaes(name = word, weight = log(n)))
```

![image](https://user-images.githubusercontent.com/56481/45853094-b1d29480-bd19-11e8-8d55-61db71bc6f4b.png)

You need the development version

Example from https://github.com/jbkunst/highcharter/blob/master/dev/highcharts-v6.R

**Comment by robertogilsaura** [comment]
A lot of tahnks, I will try with this version ...

**Comment by robertogilsaura** [comment]
Hi, it **runs properly** with 0.6.0 ...

Thanks
