### ISSUE TITLE
implement hc_drop hc_select functions/events

### ISSUE THREAD

**Issue by jbkunst** [jbkunst/highcharter#48]
This is a vey inmature idea. The goal is define function to implement in an easy way events without write javascript.

This will be usefull with shiny app, addin etc.

**Comment by jbkunst** [comment]
http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/plotoptions/series-point-events-click-column/

```
$(function () {
    $('#container').highcharts({
        chart: {
            type: 'scatter'
        },
        xAxis: {
            categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
        },

        plotOptions: {
            series: {
                cursor: 'pointer',
                point: {
                    events: {
                        click: function () {
                            alert('Category: ' + this.category + ', value: ' + this.y + ', series: ' + this.series.name);
                        }
                    }
                }
            }
        },

        series: [{
            data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
        },{
            data: [135.6, 148.5, 216.4, 194.1, 95.6, 54.4, 29.9, 71.5, 106.4, 129.2, 144.0, 176.0]
        }]
    });
});
```

**Comment by adymimos** [comment]
good to have this.
With current package, below code will work
hc_plotOptions(
        series = list(
          cursor = 'pointer',
          point = list(events = list(
            click = JS("function() {  
              if (typeof Shiny != 'undefined') {
              Shiny.onInputChange('bar_select',this.category); }
              }")
                  ))))

**Comment by davidmanero** [comment]
This function will be great.

I've problems with the drilldown event in a 3Dpie chart.

I've try this:

hc_plotOptions(pie = list(depth = 40,
                                cursor = "pointer",
                                point = list(events = list(
                                    click = JS("function() {Shiny.onInputChange('pie', name: this.point.name);}")
                          ))))

I've try it with "drilldown" instead of "click" and nothing works.

Could you help me?

**Comment by jbkunst** [comment]
See your browse console. 

I think you need other set of brackets:

`Shiny.onInputChange('pie', **{** name: this.point.name **}** ) `

Next time, try format your code using ``` ;)!

**Comment by davidmanero** [comment]
Thanks you, it works!!!
