### ISSUE TITLE
highcharter integration in R Shiny “html template”-based application

### ISSUE THREAD

**Issue by cho7tom** [jbkunst/highcharter#481]
Hello,
First of all, thank you very much for this great package!

I have an issue leveraging highcharter in 'advanced' "html-template"-based R Shiny applications.
By 'advanced' I mean using bootstrap dashboard themes such as [SB Admin 2](https://startbootstrap.com/template-overviews/sb-admin-2/) or [Gentelella](https://colorlib.com/polygon/gentelella/index.html)

I've asked for community support on stakoverflow (see question [here](https://stackoverflow.com/questions/52703549/highcharter-integration-in-r-shiny-html-template-based-application)). Reproducible example is however difficult to share as one would need all css, js, html files from the theme I'm using. I've still tried to explain the issue...

Did you already observe this issue? Any idea on how to solve it?
Thank you very much in advance and best regards!

**Comment by cho7tom** [comment]
Dear @jbkunst, I've investigated a bit further, and it seems like the highcharter package is somehow **conflicting with other js components** used in the bootstrap theme I use (SB Admin 2).
In particular, I believe the following line from index.html is causing the issue (jquery js): 

    <script src="../vendor/jquery/jquery.min.js"></script>

I guess the issue is not 100% highcharter-related but I was not able to find similar (solved) topics among the community. How would you recommend to proceed?

So far I tried the following :  

  1. **keep <script src="../vendor/jquery/jquery.min.js"></script>** => highchart charts do not appear in the application
  2. **remove <script src="../vendor/jquery/jquery.min.js"></script>** => other 'interactivities' are disabled, so not a good option either.
 3. **keep <script src="../vendor/jquery/jquery.min.js"></script> and add {{ suppressDependencies("jquery") }} in my index.html header** => same observation as 1.

Thank you very much in advance for your views on this. I really hope to be able to crack this issue, so as to "reach the next level" in terms of building R Shiny application!

**Comment by jbkunst** [comment]
Hi @cho7tom 

Sorry for the late response. Do you still have the issue?

**Comment by cho7tom** [comment]
Hi Joshua,

yes! Thank you for coming back to me.
I could fix my issue for the SB Admin 2 template. I'm planning to soon
retest on another html template, hoping this will confirm my approach is
indeed correct and independent from the chosen template.

Thank you again for your email and for your great work on highcharter!

Regards,

Thomas

*Thomas Filaire*

*t.filaire@gmail.com <t.filaire@gmail.com>*
