### ISSUE TITLE
Plots not fully rendered in pdf documents using Rmarkdown

### ISSUE THREAD

**Issue by christinabrady** [jbkunst/highcharter#488]
This is a great package. Thank you all of your hard work!

I am having a problem when trying to use Highcharter in combination with Rmarkdown to create a pdf document. The charts do not scale properly. 

The following code produces the data frame and graph below when using knitr and Rmarkdown to render to a pdf document:

`tmp <- data.frame(a = sample(1:1000, 10, replace = F), b = 2010:2019)
`
`tmp %>%
  hchart("bar", 
    hcaes(x = b, 
          y = a)
        ) %>%
    hc_xAxis(allowDecimals = F)
`

     a    b
1  372 2010
2  156 2011
3  883 2012
4  608 2013
5  439 2014
6  211 2015
7   62 2016
8  907 2017
9  386 2018
10 821 2019

![no resizing](https://user-images.githubusercontent.com/7213806/49035390-9c973d80-f182-11e8-9aae-efea6077415d.PNG)

As you can see, most values are greater than 200, but the graph shows them all less than 200. 

Resizing using hc_size does not help. The second was created with the following code:
`tmp %>%
  hchart("bar", 
    hcaes(x = b, 
          y = a)
        ) %>%
    hc_xAxis(allowDecimals = F) %>%
    hc_size(600, 600)
`
![using hc_size](https://user-images.githubusercontent.com/7213806/49035408-a5880f00-f182-11e8-923c-fe846dda6041.PNG)

OS information:
Windows 7 Enterprise
R version 3.4.2
highcharter 0.6.0
Rmarkdown 1.8
knitr 1.17

**Comment by jbkunst** [comment]
Hi @christinabrady!

This is because highcharts have animation as default so the image from the widget is not the final chart.

Please, try to use the last line to remove the animation effect:

```r
tmp %>% 
  hchart("bar", hcaes(x = b, y = a)) %>% 
  hc_plotOptions(series = list(animation = FALSE)))
```

**Comment by christinabrady** [comment]
That worked. Thank you! That saves me a lot of messily trying to turn html files into pdfs!

**Comment by ReyashOPC** [comment]
This was helpful, thank you for sharing!
