### ISSUE TITLE
Highcharts "rich data" example on R

### ISSUE THREAD

**Issue by nutle** [jbkunst/highcharter#490]
Any examples on how to implement this (or similar) example [from highcharts website](https://www.highcharts.com/maps/demo/rich-info) so that additional graphs or other functionality could be realized based on selected values on the map? 
I'm interested not necessarily in a standalone example like here, but also something with ``shiny`` capability would also be useful. For example, triggering certain plots or views based on the selected values, like ``DT`` does?

NB: When saying ``DT``, I mean, i.e., [this functionality](https://stackoverflow.com/questions/43263879/creating-drill-down-report-in-r-shiny), that is, the ability to extract and reactively reuse ``input$summary_rows_selected`` based on the selected rows.

**Comment by jbkunst** [comment]
Howdy @nutle,

Yep, implement that example is hard beacuse have a lot of custom javascript.

There are implemented some helpers to use events in highcarts/shiny apps. You can see these examples:

https://github.com/jbkunst/highcharter/blob/master/dev/events.R

and

https://github.com/jbkunst/highcharter/blob/master/dev/events2-shiny.R

And finally see this example http://104.140.247.162:3838/shiny-apps-highcharter/piramid-census/ code here https://github.com/jbkunst/shiny-apps-highcharter

Hope this helps!

**Comment by nutle** [comment]
Excellent, I'll definitely have a look! Thanks!
