### ISSUE TITLE
Error: All arguments must be named list

### ISSUE THREAD

**Issue by Anairam1995** [jbkunst/highcharter#491]
I'm trying to create a textbox, but its doesn't work. 
This is the entire code and this is the error msg given: Error: All arguments must be named list

hc.venda <-
highchart(type = "stock")                                %>%
hc_title(text = 'Histórico de Vendas (Boleto + Cartão)') %>%
hc_subtitle(text = paste(mensagem, "<br>", mensagem2, "<br>", mensagem3),
color = '#333333') %>%
hc_add_series(as.xts(serie.vendas, dateFormat = "Date"), name = "Vendas") %>%
hc_add_series(as.xts(serie.previsao, dateFormat = "Date"), name = "Previsão") 

hc.venda <- hc.venda %>% hc_annotations(
list( 
       labelOptions = list(
       backgroundColor = 'rgba(255,255,255,0.5)',
       verticalAlign = 'top',
       y = 50
     ),
     labels = list(
       list(
         point = list(
           xAxis = 0,
           yAxis = 0,
           x = highcharter::datetime_to_timestamp(as.Date("2018-01-29")),
           y = 750
         ),
         text = "Mudança de Oferta"
       )
     )
   )
 )
 

I tried this too, but the textbox does not appear

hc.venda <-
highchart(type = "stock")                                %>%
hc_title(text = 'Histórico de Vendas (Boleto + Cartão)') %>%
hc_subtitle(text = paste(mensagem, "<br>", mensagem2, "<br>", mensagem3),
color = '#333333') %>%
hc_add_series(as.xts(serie.vendas, dateFormat = "Date"), name = "Vendas") %>%
hc_add_series(as.xts(serie.previsao, dateFormat = "Date"), name = "Previsão") %>% 
hc_add_annotation(
    list(list( 
      labelOptions = list(
      backgroundColor = 'rgba(255,255,255,0.5)',
      verticalAlign = 'top',
      y = 50
    ),
    labels = list(
      list(
        point = list(
          xAxis = 0,
          yAxis = 0,
          x = highcharter::datetime_to_timestamp(as.Date("2018-01-29")),
          y = 750
        ),
        text = "Some annotation"
      )
    )
  )
)
)

Sorry about my English. I'm Brazilian.

**Comment by jbkunst** [comment]
Hi @Anairam1995 

> Sorry about my English. I'm Brazilian.

No problem ;).

Please, If you can format your code, using  it would be great: https://help.github.com/articles/creating-and-highlighting-code-blocks/
