### ISSUE TITLE
plotLines label does not render

### ISSUE THREAD

**Issue by dStudio-git** [jbkunst/highcharter#492]
I've just noticed that all plotLines labels disappeared from my graphs.
Simple code to reproduce this issue:

`highchart() %>%
 hc_add_series(data = c(7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2,
                        26.5, 23.3, 18.3, 13.9, 9.6),
               type = "spline") %>%
 hc_xAxis(plotLines = list(
           list(label = list(text = "This is a plotLine"),
                color = "red",
                width = 2,
                value = 5.5))
          )`

giving me such result:

![image](https://user-images.githubusercontent.com/20369864/50220633-26f24c00-0393-11e9-834f-7361dadb6882.png)

Higcharter ver: 0.5.0

**Comment by dStudio-git** [comment]
update: seems that it's a browser issue:
the issue appears in Chrome version: Version 70.0.3538.110 (Official Build) (64-bit).
IE 11.0.9600.19129

**Comment by nteetor** [comment]
I have a similar problem using Firefox 64. Specifically, if a scatter series is combined with any other series then the points do not seem to detect mouse events. Thus, a tooltip is not shown. 

Dishearteningly, updating to the development of highcharter, version 6, which uses Highcharts 6, resolved the issue. I say dishearteningly because based on #460 there is no indication vesion 6 will get to CRAN anytime soon. 

@dStudio-git, is there any chance you could check if the development version of highcharter resolves your problem? Thank you in advance if you can. 

```R
remotes::install_github("jbkunst/highcharter")
```

**Comment by dStudio-git** [comment]
Hi @nteetor,
unfortunately upgrading to dev. version does not resolve the issue. Please refer to below prtscr. (Chrome (up) vs. RStudio Window mode (down)).
![image](https://user-images.githubusercontent.com/20369864/50244773-119c1280-03d1-11e9-990d-9b3eef69b1e9.png)

**Comment by nteetor** [comment]
Ah, our problems are more dissimilar than I thought. However, I am fairly certain I ran into your issue a couple months ago. If you are incorporating highcharter into a shiny app, try adding the following snippet to the beginning of your application.

```R
tags$script(HTML(paste0(
  collapse = "\n",
  "$(function() {",
  "Highcharts.wrap(Highcharts.Axis.prototype, 'getPlotLinePath', function(proceed) {",
  "  var path = proceed.apply(this, Array.prototype.slice.call(arguments, 1));",
  "  if (path) {",
  "    path.flat = false;",
  "  }",
  "  return path;",
  "});",
  "});"
)))
```

**Comment by dStudio-git** [comment]
@nteetor Your solution works like a charm.
On CRAN 0.5.0 version too. Thank you very much!

**Comment by nteetor** [comment]
You are welcome! I am glad it worked out.

**Comment by jbkunst** [comment]
Hi @dStudio-git @nteetor 

I will close this issue. You can reopen when you want! 

Regards
