### ISSUE TITLE
Combining tooltip_table and tooltip_chart

### ISSUE THREAD

**Issue by pranavpandya84** [jbkunst/highcharter#502]
First of all, thanks for the latest release with new features. I really liked the `minichart` (chart inside chart) function. However I would like to display `tooltip_table` and `tooltip_chart` both at the same time on hover. 

**I am able to get them individually but not together**. :(  

#### Reprex below: 

```
data(iris)
iris <- tbl_df(iris)
iris <- mutate(iris, id = seq_along(Species))

irismini <- iris %>%
  select(-Species) %>% 
  gather(x, y, -id) %>% 
  mutate(x = str_replace(x, "\\.", "_"),
         x = str_to_lower(x)) %>% 
  group_by(id) %>% 
  do(tooltipdata = list_parse2(select(., -id))) 

iristot <- left_join(iris, irismini)

# hover tooltip chart
pfmc <- tooltip_chart(
  accesor = "tooltipdata",
  hc_opts = list(
    xAxis = list(type = "category")
  )
)

#hover tooltip table
vars <- c("Species", "id")
tt <- tooltip_table(x = vars, y = sprintf("{point.%s}", vars))
```

### chart with tooltip table
```
hchart(iristot, "point", hcaes(x = Sepal.Length, y = Sepal.Width, group = Species)) %>% 
  hc_tooltip(useHTML = TRUE, pointFormat = tt)
```
![capture1](https://user-images.githubusercontent.com/22565727/52349481-f344b180-2a26-11e9-9961-5caa76a3e49e.PNG)

### chart with minichart
```
hchart(iristot, "point", hcaes(x = Sepal.Length, y = Sepal.Width, group = Species)) %>% 
  hc_tooltip(useHTML = TRUE, pointFormatter = pfmc)
```
![capture2](https://user-images.githubusercontent.com/22565727/52349490-f770cf00-2a26-11e9-8872-fba0762f81e1.PNG)

How do I combine `tooltip_table` and `tooltip_chart`? Any suggestions?

**Comment by jbkunst** [comment]
Hi @pranavpandya84 

It's possible, a way (not the most elegant imho but functional)  is write the text (the table) for each point. You can use the `tt` as a template, and then use the `str_glue_data` to generate the needed text, in the example is named as `tttext`. Then use that accesor in the `tooltip_chart` in the title option adding  `useHMTL = TRUE`.

![image](https://user-images.githubusercontent.com/56481/52352015-963b0280-2a0a-11e9-9a5c-aabea272271b.png)


```r
library(tidyverse)
library(highcharter)

data(iris)
iris <- tbl_df(iris)
iris <- mutate(iris, id = seq_along(Species))

irismini <- iris %>%
  select(-Species) %>% 
  gather(x, y, -id) %>% 
  mutate(x = str_replace(x, "\\.", "_"),
         x = str_to_lower(x)) %>% 
  group_by(id) %>% 
  do(tooltipdata = list_parse2(select(., -id))) 

iristot <- left_join(iris, irismini)



# hover tooltip table
vars <- c("Species", "id")
tt <- tooltip_table(x = vars, y = sprintf("{point.%s}", vars))

ttt <- tt %>% 
  str_remove_all("point\\.") %>% 
  str_remove_all("\\s+")
ttt

iristot <- iristot %>% 
  mutate(
    tttext = str_glue_data(iristot, ttt)
    )

# hover tooltip chart
pfmc <- tooltip_chart(
  width = 500,
  height = 300,
  accesor = "tooltipdata",
  hc_opts = list(
    title = list(text = "point.tttext", useHTML = TRUE),
    xAxis = list(type = "category")
  )
)

cat(pfmc)

hchart(iristot, "point", hcaes(x = Sepal.Length, y = Sepal.Width, group = Species)) %>% 
  hc_tooltip(useHTML = TRUE, pointFormatter = pfmc)
```

**Comment by jbkunst** [comment]
And thanks for your reprex, very **tidy** 😄

**Comment by pranavpandya84** [comment]
Thanks a lot @jbkunst. Excellent!

**Comment by steve-liang** [comment]
Sorry for re-open this. My question will be similar. Can we produce 2+ charts (and different types) in one tooltip window? 

I am trying to digest the 1 table + 1 chart code here while waiting for your response. 

Thanks!
