### ISSUE TITLE
How to specify zoom and RangeSelector

### ISSUE THREAD

**Issue by Fooourche** [jbkunst/highcharter#51]
Hi Joshua

I'm building my highchart from scratch (with hichart() method) to specify each serie the option and i don't find the way to add a zoom and a rangeselector

     hc.pap <- highchart() %>% 
          hc_xAxis(categories = don.pap.sp$date) %>%
          hc_add_series(name = names(don.pap.sp)[2], data = don.pap.sp[,2],marker=list(enabled = FALSE),color='#CCCCCC') %>%
          hc_zoom ?
          hc RangeSelector ?
         
Thanks 
Fabien

**Comment by jbkunst** [comment]
Hi @Fooourche Fabien,

1. The zoom is defined via `hc_chart(...)` 
2. There is a `hc_rangeSelector`function ;) (http://api.highcharts.com/highstock#rangeSelector)

Regards!

**Comment by Fooourche** [comment]
Ho Joshua

Thanks for the answear.
The hc_rangeSelector function only works for highstock type chart ? Doesn't
work for highchart type on my side

Regards

Fabien

2016-03-03 14:17 GMT+01:00 Joshua Kunst <notifications@github.com>:

**Comment by jbkunst** [comment]
@Fooourche Yep, only for highstock :|.

**Comment by englianhu** [comment]
I tried to plot a [Real Time Forex Graph](https://beta.rstudioconnect.com/content/3143/), may I know how do I set a default `hc_RangeSelector` to zoom into 1 week graph?

By the way, is it possible made the real time graph to change only latest bar compare to whole graph?
