### ISSUE TITLE
highchartOutput and highchartOutput2 cannot use together in shinydashboard

### ISSUE THREAD

**Issue by chenx2018** [jbkunst/highcharter#510]
I try to render correlation matrix using highcharter in Shinydashboard. It does not work if I use highchartOutput2. It only works if there is no highchartOutput2 in body part. However, I have to use highchartOutput2 for other reason. Any suggestion?

**Comment by Vicroline** [comment]
Without a code example it is difficult to understand your problem, but in principle to render more than one output you would do something like this: 
```
# UI
ui <- dashboardPage(
  fluidRow(
    box(highchartOutput("first_plot")),
    box(highchartOutput("second_plot"))
  )
)
# Server logic
server <- function(input, output) {
  output$first_plot <- renderHighchart({
    hc1 <- hchart(data1, "heatmap", hcaes(.....))
    return(hc1)
    })
  output$second_plot <- renderHighchart({
    hc2 <- hchart(data2, "heatmap", hcaes(.....))
    return(hc2)
    })
  }
```

**Comment by jbkunst** [comment]
Hi @chenx2018 

There's no need to use `highchartOutput2`. In fact I need to remove them 😅 

Regards,
