### ISSUE TITLE
Rebase starting values of yAxis

### ISSUE THREAD

**Issue by nitingupta2** [jbkunst/highcharter#512]
Hi @jbkunst ,

I started tinkering with `highcharter` just a couple of days back. Congratulations on the fantastic work!

In my [Shiny app](https://nitingupta2.shinyapps.io/stockReturns/) I show, among other things, how a dollar invested has compounded over time in different stocks/ETFs, This means the starting value of y-axis in the Cumulative Return plot should rebase to 1, whenever the starting date on x-axis is changed. I used `dygraphs` package for my plot before, in which this could be easily achieved by `my_dygraphs_plot %>% dyRebase(value = 1)`

Is there some way to do this in highcharts? I looked up the docs and Closed Issues but couldn't find anything related. 
You could observe this functionality in **Plot** tab which shows `dygraphs` plots. I've tried to replicate the same functionality in a `highcharter` plot in **Plot2**.

Thank you!

**Comment by jbkunst** [comment]
Hi @nitingupta2 

Not sure if the `compare` option can help you:

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/plotoptions/series-comparebase/

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/plotoptions/series-compare-percent/

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/plotoptions/series-compare-value/

Searching in the web I found some discussion: https://www.highcharts.com/forum/viewtopic.php?t=12180

**Comment by nitingupta2** [comment]
Thanks for the pointers!! @jbkunst 

In principle, the series-compare option should work by setting `hc_plotOptions(series = list(compare = "value", compareBase = 1.0)`

It leads to 2 problems:
1. I have dual y-axes in the plot. The Cumulative Return axis is `type = "logarithmic"` and the Drawdown axis is `type = "line"`. Seems like the logarithmic axis prevents the plot from rendering when I add hc_plotOptions - the RStudio Viewer pane goes blank.

2. When I change the Cumulative Return axis to `type = "line"`, the plot renders, but since the options are set at the top level of the plot, they affect the Drawdown axis as well.

I tried many different ways to set the series-compare options only for the Cumulative Return y-axis but couldn't get it to work. Please let me know if you have any ideas.

**Comment by jbkunst** [comment]
@nitingupta2 

I thinks this is a highcharts limitation/issue so you maybe can open the issue in the highcharts repository. It could help if you have an example in jsfiddle.

**Comment by nitingupta2** [comment]
Thanks, @jbkunst 

I'll open this issue in the highcharts repo. But I don't know how to create a JS example in jsfiddle.

**Comment by nitingupta2** [comment]
Hi @jbkunst 

I figured out why the plot was not rendering with a logarithmic axis, and essentially solved my problems with a workaround. The issue is mentioned in the highcharts repo [here](https://github.com/highcharts/highcharts/issues/4276).

The plot doesn't render with `compare = "value", compareBase = 1.0` if the y-axis is logarithmic, But it renders without any problem with `compare = "percent", compareBase = 100` for each series with logarithmic y-axis.

So, instead of showing how $1 compounds over time, the plot in my [Shiny app](https://nitingupta2.shinyapps.io/stockReturns/) now shows how $100 invested at the beginning of the period, compounds over time. In the tooltip I show the change in % from the beginning of the time period.

Many thanks for following up and sharing your ideas!
Nitin
