### ISSUE TITLE
Errrobar does not vary by group

### ISSUE THREAD

**Issue by favstats** [jbkunst/highcharter#513]
Hi! I am having some trouble creating a `type = "column` chart with an errorbar that varies by group. I can create the column chart that varies by group without any problem but I would like to add an errorbar for each individual bar.

This is what I would like my plot to look like (in ggplot2)

![00000b](https://user-images.githubusercontent.com/12173862/54245109-cdcc2b80-452f-11e9-9961-413208315f0b.png)

And this is how my plot actually looks like:

![image](https://user-images.githubusercontent.com/12173862/54245169-05d36e80-4530-11e9-9e7c-e49635e3a538.png)

The error bars are oddly off and I don't really understand why.

Here is the mock data that I created and the highcharter syntax for the graph above:

```
example_dat <- tibble(Type = c("Human", "High-Elf", "Orc"), 
       key = c("World1", "World2", "World3")) %>% 
  expand.grid() %>% 
  mutate(mean = runif(9, 5, 7)) %>% 
  mutate(sd = runif(9, 0, 2)) 

hchart(example_dat, "column", hcaes(x = key, y = mean, group = Type)) %>%
  hc_add_series(example_dat, "errorbar", 
       hcaes(y = mean, x = key, low = mean - sd, high = mean + sd, group = Type),
             enableMouseTracking = FALSE,
             showInLegend = FALSE) %>% 
    hc_plotOptions(
    errorbar = list(
     color = "black", 
     stemWidth = 1, 
     whiskerLength = 1
    ) 
) 
```

Thank you so much for your help!

**Comment by parker-howell** [comment]
Following

**Comment by raf18seb** [comment]
I am not sure why the above errorbars look strange (only one vertical line), but I know why they are positioned incorrectly. Highcharter wrapper adds series in a wrong order (at least for errorbars). Errorbars must be connected to series and, by default, they are connected to the previous series.
In short: if you want to have 2 column series and 2 errorbars, you should add your series in order: column -> errorbar -> column -> errorbar.
Highcharter adds them in order: column -> column -> errorbar -> errorbar (the last errorbar is connected to the previous series which is... errorbar, not column).

Either Highcharter ordering should be fixed for this type of series, you the user should define series.id for column series and series.linkedTo for errorbar series:
https://api.highcharts.com/highcharts/series.column.id
https://api.highcharts.com/highcharts/series.errorbar.linkedTo

I don't know how to define it in the chart's options (in hc_add_series), but I know how to update the series properties with a simple JavaScript:
```
hc_chart(events = list(load = JS("function () {
    this.series[0].update({
      id: 'firstColumnSeries'
    }, false);
    this.series[1].update({
      id: 'secondColumnSeries'
    }, false);
    this.series[2].update({
      linkedTo: 'secondColumnSeries'
    }, false);
    this.series[3].update({
      linkedTo: 'firstColumnSeries'
    });
  }"))) %>%
```

A working R example can be found here: https://stackoverflow.com/a/63847912/8618934

**Comment by jbkunst** [comment]
@favstats 

Sorry for the LATE. A solution around @raf18seb  solution would be use `id` parameter in the first group of series and then use `linkedTo` in the errorbar series.

```r
hchart(
  example_dat, 
  "column",
  hcaes(x = key, y = mean, group = Type),
  id = c("a", "b", "c")
  ) %>%
  
  hc_add_series(
    example_dat,
    "errorbar", 
    hcaes(y = mean, x = key, low = mean - sd, high = mean + sd, group = Type),
    linkedTo = c("a", "b", "c"),
    enableMouseTracking = TRUE,
    showInLegend = FALSE
    ) %>% 
  
  hc_plotOptions(
    errorbar = list(
      color = "black", 
      # whiskerLength = 1,
      stemWidth = 1
    ) 
  ) 
```

![image](https://user-images.githubusercontent.com/56481/146600771-595d91ce-5496-49e5-8868-bc0719bb1cc9.png)


References:
- https://www.highcharts.com/forum/viewtopic.php?t=32588
- http://jsfiddle.net/1wjsrr1x/3/
