### ISSUE TITLE
Format individual axis labels

### ISSUE THREAD

**Issue by floriangehrig** [jbkunst/highcharter#529]
Hi @jbkunst,

First thanks for this awesome package i loved highchart but i love it even more that i can use it in R !

I was wondering if it is able to change the colors of the individual axis labels?

Thanks!

**Comment by jbkunst** [comment]
Hi @floriangehrig 

Sorry for the late response.

Like this example http://jsfiddle.net/508jej83/?

**Comment by floriangehrig** [comment]
@jbkunst exactly!

**Comment by jbkunst** [comment]
Can you share your specific use? Because idk if the example can work if your needs are more complex.
