### ISSUE TITLE
Upgrading to highcharts 7.1.0

### ISSUE THREAD

**Issue by jenswirf** [jbkunst/highcharter#530]
Any chance of upgrading to [**7.1.0**](https://www.highcharts.com/blog/changelog/#highcharts-v7.1.0) in order to get the lovely `inactive state` feature?

**Comment by jbkunst** [comment]
Hi @jenswirf

Oh! I missed that nice feature. I will try to update highcharter soon!  Thanks for noticed that.

**Comment by nklepeis** [comment]
Is it possible to just drop in the new highcharts js library into the highcharter R package directory?  Or would that break something?
