### ISSUE TITLE
how to export the graphs created by highcharter in a .svg format?

### ISSUE THREAD

**Issue by ZENG-David** [jbkunst/highcharter#532]

**Comment by boehmchen** [comment]
Hi,

I think this might help you: http://jkunst.com/highcharter/plugins.html#exporting-csv

I use highcharter in RStudio and export my highcharts as follows:

- add `%>%hc_exporting(enabled = TRUE)` to my hc pipeline
- open html notebook output in web browser
- click on the new hamburger icon in the upper right corner
- click download PNG/SVG/PDF/etc.

If you know a faster solution, let me know :)
