### ISSUE TITLE
renderHighchart inside Shiny Module

### ISSUE THREAD

**Issue by guaribr** [jbkunst/highcharter#535]
First of all, I am new to highcharts and Shiny.
I am building a shiny app which is going to be quite complex in terms of size, so I decided to build it using modules. Inside a couple of modules I will need to add a graph and I am using highcharter. 
The idea is that the user uses a dropdown list (selectInput) to select a value. Once this is done a line in a dataset will be filtered and a graph is updated. I am trying to pass a reactive dataset to a module but I keep on getting a error saying that Highcharts does not work with reactive datasets (yet) This is the error: `Warning: Error in : Objects of class/type reactiveExpr/reactive are not supported by hchart (yet).`
 Will you include this feature? I am copying the code:

```
library(shiny)
library(highcharter)
library(tidyverse)

df <- data.frame(label = c('A','B', 'EU'), value = c(10,25,48))

myModuleUI <- function(id) {
  ns <- NS(id)
  tagList(
    textOutput(ns("title")),
    textOutput(ns("text")),
    highchartOutput(ns("graph")),
    plotOutput(ns('plot')))}

myModuleServer <- function(input, output, session, action, dataset) {
  
  dfReactive <- reactive({dataset()})
  
  output$title <- renderText({paste0("You selected letter: ",action())})
  output$text <- renderText({paste0("In the dataset the letter selected corresponds to number: ", dataset()$value)})
  output$graph <- renderHighchart({hchart(dfReactive, 'bar', hcaes(x=dfReactive$label, y=dfReactive$value))})
  output$plot <- renderPlot({barplot(dataset()$value)})
  }  


ui <- fluidPage(
  fluidRow(
    column(width = 3, wellPanel(selectInput('dummy', 'Select a letter', choices = c('A', 'B')))),
    column(width = 6, myModuleUI("module1")))
  )

server <- function(input, output, session) {
  
  reactiveData <- reactive({input$dummy})
  reactiveDataSet <- reactive({df %>% filter(label %in% c('EU',input$dummy))})
  
  callModule(myModuleServer, 'module1', action = reactiveData, dataset = reactiveDataSet)
}

shinyApp(ui, server)
```

**Comment by nteetor** [comment]
There are a couple other problems I ran into, specifically the usage of `hcaes()`. I will those problems up to you. 

In general, you want to refer to `dataset()` or `dfReactive()`. The `hchart()` is looking for a list or data frame, but what you are passing `dfReactive`, a reactive object. To get the list or data frame from the reactive object use `dfReactive()` instead (note the parentheses). 

Additionally, `dfReactive()` is not needed in this case. You could instead use `dataset()` as you have on other lines. 

I hope this helps.
