### ISSUE TITLE
Example for hctreemap2 now fails to render

### ISSUE THREAD

**Issue by mkrasmus** [jbkunst/highcharter#536]
> R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
> Copyright (C) 2019 The R Foundation for Statistical Computing
> Platform: x86_64-apple-darwin15.6.0 (64-bit)

The following example code breaks

`library(tidyverse)
library(highcharter)
library(RColorBrewer)

data_frame(
  index1 = sample(LETTERS[1:5], 500, replace = T),
  index2 = sample(LETTERS[6:10], 500, replace = T),
  index3 = sample(LETTERS[11:15], 500, replace = T),
  value = rpois(500, 5),
  color_value = rpois(500, 5)
) %>%
  hctreemap2(
    group_vars = c("index1", "index2", "index3"),
    size_var = "value",
    color_var = "color_value",
    layoutAlgorithm = "squarified",
    levelIsConstant = FALSE,
    levels = list(
      list(level = 1, dataLabels = list(enabled = TRUE)),
      list(level = 2, dataLabels = list(enabled = FALSE)),
      list(level = 3, dataLabels = list(enabled = FALSE))
    )
  ) %>% 
  hc_colorAxis(minColor = brewer.pal(7, "Greens")[1],
               maxColor = brewer.pal(7, "Greens")[7]) %>% 
  hc_tooltip(pointFormat = "<b>{point.name}</b>:<br>
             Value: {point.value:,.0f}<br>
             Color Value: {point.colorValue:,.0f}")`

With response:

> library(RColorBrewer)
> > data_frame(
> +   index1 = sample(LETTERS[1:5], 500, replace = T),
> +   index2 = sample(LETTERS[6:10], 500, replace = T),
> +   index3 = sample(LETTERS[1 .... [TRUNCATED] 
> Error: Unknown column `index2` 
> Call `rlang::last_error()` to see a backtrace
> In addition: Warning message:
> `data_frame()` is deprecated, use `tibble()`.
> This warning is displayed once per session.

**Comment by boxuancui** [comment]
```R
> rlang::last_error()
<error>
message: Unknown column `country` 
class:   `rlang_error`
backtrace:
  1. `%>%`(...)
  4. highcharter::hctreemap2(...)
  5. 1:length(group_vars)
 12. purrr::map(., data_at_depth)
 13. highcharter:::.f(.x[[i]], ...)
 14. dplyr::group_by(., !!!group_syms[1:depth])
 21. dplyr::summarise(., value = sum(!!size_sym), colorValue = sum(!!color_sym))
 22. dplyr::ungroup(.)
 23. dplyr::mutate(., name = !!group_syms[[depth]], level = depth)
 24. dplyr::mutate_at(., group_vars, as.character())
 25. dplyr:::manip_at(...)
 26. dplyr:::tbl_at_syms(.tbl, .vars, .include_group_vars = .include_group_vars)
 27. dplyr:::tbl_at_vars(tbl, vars, .include_group_vars = .include_group_vars)
 28. tidyselect::vars_select(tibble_vars, !!!vars)
 29. tidyselect:::vars_select_eval(.vars, quos)
 30. purrr::map_if(ind_list, is_character, match_strings, names = TRUE)
  1. purrr::map(.x[sel], .f, ...)
  4. tidyselect:::.f(.x[[i]], ...)
  5. tidyselect:::bad_unknown_vars(vars, unknown)
Call `rlang::last_trace()` to see the full backtrace
```

**Comment by Ljupch0** [comment]
+1

**Comment by pachamaltese** [comment]
this works

```r
library(tidyverse)
library(highcharter)
library(RColorBrewer)

data_frame(
  index1 = sample(LETTERS[1:5], 500, replace = T),
  index2 = sample(LETTERS[6:10], 500, replace = T),
  index3 = sample(LETTERS[11:15], 500, replace = T),
  value = rpois(500, 5),
  color_value = rpois(500, 5)
) %>%
  hctreemap2(
    group_vars = c("index1"),
    size_var = "value",
    color_var = "color_value",
    layoutAlgorithm = "squarified",
    levelIsConstant = FALSE,
    levels = list(
      list(level = 1, dataLabels = list(enabled = TRUE)),
      list(level = 2, dataLabels = list(enabled = FALSE)),
      list(level = 3, dataLabels = list(enabled = FALSE))
    )
  )
```

change `group_vars` to `group_vars = c("index1", "index2", "index3")` and this function fails:

https://github.com/jbkunst/highcharter/blob/master/R/hchart-shorcuts.R#L410

**Comment by pachamaltese** [comment]
@Ljupch0 @boxuancui @mkrasmus please run `devtools::install_github("jbkunst/highcharter", ref = "720")`
the example works with the changes I uploaded there, please let me know how it works from your side

**Comment by LapsedPacifistROU** [comment]
> @Ljupch0 @boxuancui @mkrasmus please run `devtools::install_github("jbkunst/highcharter", ref = "720")`
> the example works with the changes I uploaded there, please let me know how it works from your side
I am facing the same issue as well and I am not able to download the solution that is recommended I get this error

`Downloading GitHub repo jbkunst/highcharter@720
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/jbkunst/highcharter/tarball/720'`

**Comment by mjfrigaard** [comment]
Also getting error when trying to load the `ref = "720`

```r
devtools::install_github("jbkunst/highcharter", ref = "720")
Downloading GitHub repo jbkunst/highcharter@720
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/jbkunst/highcharter/tarball/720'
```

My session info: 

```r
devtools::session_info()
─ Session info ───────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.2 (2019-12-12)
 os       macOS Catalina 10.15.3      
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/Los_Angeles         
 date     2020-03-19                  

─ Packages ───────────────────────────────────────────────────────────────────────
 package      * version date       lib source        
 assertthat     0.2.1   2019-03-21 [1] CRAN (R 3.6.0)
 backports      1.1.5   2019-10-02 [1] CRAN (R 3.6.0)
 base64enc      0.1-3   2015-07-28 [1] CRAN (R 3.6.0)
 broom          0.5.5   2020-02-29 [1] CRAN (R 3.6.0)
 callr          3.4.2   2020-02-12 [1] CRAN (R 3.6.0)
 cellranger     1.1.0   2016-07-27 [1] CRAN (R 3.6.0)
 cli            2.0.2   2020-02-28 [1] CRAN (R 3.6.0)
 colorspace     1.4-1   2019-03-18 [1] CRAN (R 3.6.0)
 crayon         1.3.4   2017-09-16 [1] CRAN (R 3.6.0)
 curl           4.3     2019-12-02 [1] CRAN (R 3.6.0)
 data.table     1.12.8  2019-12-09 [1] CRAN (R 3.6.0)
 DBI            1.1.0   2019-12-15 [1] CRAN (R 3.6.0)
 dbplyr         1.4.2   2019-06-17 [1] CRAN (R 3.6.0)
 desc           1.2.0   2018-05-01 [1] CRAN (R 3.6.0)
 devtools       2.2.2   2020-02-17 [1] CRAN (R 3.6.0)
 digest         0.6.25  2020-02-23 [1] CRAN (R 3.6.2)
 dplyr        * 0.8.5   2020-03-07 [1] CRAN (R 3.6.2)
 ellipsis       0.3.0   2019-09-20 [1] CRAN (R 3.6.0)
 evaluate       0.14    2019-05-28 [1] CRAN (R 3.6.0)
 extrafont      0.17    2014-12-08 [1] CRAN (R 3.6.0)
 extrafontdb    1.0     2012-06-11 [1] CRAN (R 3.6.0)
 fansi          0.4.1   2020-01-08 [1] CRAN (R 3.6.0)
 forcats      * 0.5.0   2020-03-01 [1] CRAN (R 3.6.0)
 fs             1.3.2   2020-03-05 [1] CRAN (R 3.6.0)
 gdtools        0.2.1   2019-10-14 [1] CRAN (R 3.6.0)
 generics       0.0.2   2018-11-29 [1] CRAN (R 3.6.0)
 ggfittext      0.8.1   2019-07-18 [1] CRAN (R 3.6.0)
 ggplot2      * 3.3.0   2020-03-05 [1] CRAN (R 3.6.0)
 glue           1.3.2   2020-03-12 [1] CRAN (R 3.6.0)
 gtable         0.3.0   2019-03-25 [1] CRAN (R 3.6.0)
 haven          2.2.0   2019-11-08 [1] CRAN (R 3.6.0)
 highcharter  * 0.7.0   2019-01-15 [1] CRAN (R 3.6.0)
 hms            0.5.3   2020-01-08 [1] CRAN (R 3.6.0)
 hrbrthemes     0.8.0   2020-03-06 [1] CRAN (R 3.6.2)
 htmltools      0.4.0   2019-10-04 [1] CRAN (R 3.6.0)
 htmlwidgets    1.5.1   2019-10-08 [1] CRAN (R 3.6.0)
 httr           1.4.1   2019-08-05 [1] CRAN (R 3.6.0)
 igraph         1.2.4.2 2019-11-27 [1] CRAN (R 3.6.0)
 inspectdf      0.0.7   2019-11-05 [1] CRAN (R 3.6.0)
 janitor        1.2.1   2020-01-22 [1] CRAN (R 3.6.0)
 jsonlite       1.6.1   2020-02-02 [1] CRAN (R 3.6.0)
 knitr          1.28    2020-02-06 [1] CRAN (R 3.6.0)
 lattice        0.20-40 2020-02-19 [1] CRAN (R 3.6.0)
 lifecycle      0.2.0   2020-03-06 [1] CRAN (R 3.6.2)
 lubridate      1.7.4   2018-04-11 [1] CRAN (R 3.6.0)
 magrittr       1.5     2014-11-22 [1] CRAN (R 3.6.0)
 memoise        1.1.0   2017-04-21 [1] CRAN (R 3.6.0)
 modelr         0.1.6   2020-02-22 [1] CRAN (R 3.6.0)
 munsell        0.5.0   2018-06-12 [1] CRAN (R 3.6.0)
 nlme           3.1-145 2020-03-04 [1] CRAN (R 3.6.0)
 pillar         1.4.3   2019-12-20 [1] CRAN (R 3.6.0)
 pkgbuild       1.0.6   2019-10-09 [1] CRAN (R 3.6.0)
 pkgconfig      2.0.3   2019-09-22 [1] CRAN (R 3.6.0)
 pkgload        1.0.2   2018-10-29 [1] CRAN (R 3.6.0)
 prettyunits    1.1.1   2020-01-24 [1] CRAN (R 3.6.0)
 processx       3.4.2   2020-02-09 [1] CRAN (R 3.6.0)
 progress       1.2.2   2019-05-16 [1] CRAN (R 3.6.0)
 ps             1.3.2   2020-02-13 [1] CRAN (R 3.6.0)
 purrr        * 0.3.3   2019-10-18 [1] CRAN (R 3.6.0)
 quantmod       0.4-16  2020-03-08 [1] CRAN (R 3.6.0)
 R6             2.4.1   2019-11-12 [1] CRAN (R 3.6.0)
 RColorBrewer * 1.1-2   2014-12-07 [1] CRAN (R 3.6.0)
 Rcpp           1.0.4   2020-03-17 [1] CRAN (R 3.6.0)
 readr        * 1.3.1   2018-12-21 [1] CRAN (R 3.6.0)
 readxl         1.3.1   2019-03-13 [1] CRAN (R 3.6.0)
 remotes        2.1.1   2020-02-15 [1] CRAN (R 3.6.2)
 repr           1.1.0   2020-01-28 [1] CRAN (R 3.6.0)
 reprex         0.3.0   2019-05-16 [1] CRAN (R 3.6.0)
 rlang          0.4.5   2020-03-01 [1] CRAN (R 3.6.0)
 rlist          0.4.6.1 2016-04-04 [1] CRAN (R 3.6.0)
 rmarkdown      2.1     2020-01-20 [1] CRAN (R 3.6.0)
 rprojroot      1.3-2   2018-01-03 [1] CRAN (R 3.6.0)
 rstudioapi     0.11    2020-02-07 [1] CRAN (R 3.6.0)
 Rttf2pt1       1.3.8   2020-01-10 [1] CRAN (R 3.6.0)
 rvest          0.3.5   2019-11-08 [1] CRAN (R 3.6.0)
 scales         1.1.0   2019-11-18 [1] CRAN (R 3.6.0)
 sessioninfo    1.1.1   2018-11-05 [1] CRAN (R 3.6.0)
 skimr          2.1     2020-02-01 [1] CRAN (R 3.6.0)
 stringi        1.4.6   2020-02-17 [1] CRAN (R 3.6.2)
 stringr      * 1.4.0   2019-02-10 [1] CRAN (R 3.6.0)
 systemfonts    0.1.1   2019-07-01 [1] CRAN (R 3.6.0)
 testthat       2.3.2   2020-03-02 [1] CRAN (R 3.6.2)
 tibble       * 2.1.3   2019-06-06 [1] CRAN (R 3.6.0)
 tidyr        * 1.0.2   2020-01-24 [1] CRAN (R 3.6.0)
 tidyselect     1.0.0   2020-01-27 [1] CRAN (R 3.6.0)
 tidyverse    * 1.3.0   2019-11-21 [1] CRAN (R 3.6.0)
 TTR            0.23-6  2019-12-15 [1] CRAN (R 3.6.0)
 usethis        1.5.1   2019-07-04 [1] CRAN (R 3.6.0)
 utf8           1.1.4   2018-05-24 [1] CRAN (R 3.6.0)
 vctrs          0.2.4   2020-03-10 [1] CRAN (R 3.6.2)
 whisker        0.4     2019-08-28 [1] CRAN (R 3.6.0)
 withr          2.1.2   2018-03-15 [1] CRAN (R 3.6.0)
 xfun           0.12    2020-01-13 [1] CRAN (R 3.6.0)
 xml2           1.2.5   2020-03-11 [1] CRAN (R 3.6.2)
 xts            0.12-0  2020-01-19 [1] CRAN (R 3.6.0)
 yaml           2.2.1   2020-02-01 [1] CRAN (R 3.6.0)
 zoo            1.8-7   2020-01-10 [1] CRAN (R 3.6.0)

[1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library
```

**Comment by 240db** [comment]
Perhaps we could trace back when this issue started ? I mean, the highcharter treemaps used to work, there are even some online examples that work, but if you use their source code and compile with something like R version 4, it looks like the group_vars is broken; the groups are not structured, they repeat and so on. 

At the moment, the alternatives to hctreemap and hctreemap2 functions seem to be d3tree2 from d3treeR. They work similarly but the Highcharter viz is a little more robust given the automatic legend that is also interactive with the cursor hover (so awesome indeed!). 

[pachadotdev](https://github.com/pachadotdev) I really appreciate your initiative to sketch a solution, I wonder if this was ever consolidated as a pull request and implemented? Did anybody test this successfully? I was not able to pull your changes from  `(devtools::install_github("jbkunst/highcharter", ref = "720")) ` but I could probably investigate the source of the highcharter functions and make the changes manually. 

I also plan to investigate what version of R had the functions hctreemap and hctreemap2 "bug-free", for specific visualization purposes, a custom environment with an older version of R and highcharter is probably one other solution. 

For now, I will stick with d3tree::d3tree2() but it might not work for everyone. Plotly also has an interactive treemap function but I am not sure you can use the treemap() as an input like you can do with d3tree, for hctreemap , one can simply get the treemap() arguments and paste it as a function for the first argument of hctreemap. I have not tried this with plotly but it does not seem to yield comparable results.

**Comment by 240db** [comment]
One other thing worth trying is the data_to_hierarchical() function. From the references, hctreemap is technically a shortcut, so it might be a convoluted function under the hood very sensitive to dependencies' changes, so do something like   data_to_hierarchical() then try running the treemap functions. I am sure going to use data_to_hierarchical() for other purposes like BumpCharts, RibbonCharts... but treemaps are another obvious candidate, even if that does not work, im sure the data frame will be fine to use in any other treemap function once structure in hierarchical form factor, even plotly might work without major bloat code.
