### ISSUE TITLE
Allow exclusion of JavaScript highcharts dependencies/modules

### ISSUE THREAD

**Issue by nteetor** [jbkunst/highcharter#539]
Currently all highcharts modules are included even if the generated chart in question does not require the module. In certain projects, this has lead to slow chart generation as each resource must be loaded. I would love to alternatively ignore or blacklist certain resources I know I will not need, thus speeding up the initial chart generation. 

If there is already a way to accomplish this I could not find the relevant documentation. My current, hacky approach is to overwrite the `highchart.yaml` file included in the package.

**Comment by nteetor** [comment]
Any thoughts or comments? The slow initial load time is quite unpopular with clients and I would love to bring them some good news.

**Comment by analytichealth** [comment]
Hi @nteetor, based on another issue in this repo (https://github.com/jbkunst/highcharter/issues/546)) you can prevent certain scripts from loading by commenting out lines from the yaml file. “open highchart.yaml file under highcharter library (example path on windows machine: R\win-library\3.6\highcharter\htmlwidgets\highchart.yaml)”. I do not know if this is best practice and I would be very not to exclude any dependencies.
