### ISSUE TITLE
Displaying extra variables in tooltips

### ISSUE THREAD

**Issue by royfrancis** [jbkunst/highcharter#54]
I have this working example of a situation where one or more datasets are selected from a dropdown to plot. The plots are plotted in a loop and displayed one below the other. There are 4 variables: _x_, _y_, _group_ and _cluster_. _x_ and _y_ are plotted by _group_ while _cluster_ is not used. I would like all variables to be shown in the mouse-over tooltip. But, it doesn't seem to work.

The issue is with the line marked `#issue line`. When using `da <- list.parse(df[df$group==dlev[i],c("x", "y")])`, the plot is drawn correctly, but extra variables are not passed on to display tooltips. When using `da <- list.parse(df[df$group==dlev[i],])`, all variables are passed to the highcharts object, but the plot doesn't draw correctly.

```{r}
#---------------------------------------------------------------------------------
#ui.R
library("shiny")
library("highcharter")

ui <- fluidPage(
  selectInput("nplots", "Choose", multiple = TRUE, width = "100%", choices = c("A","B")),
  fluidRow(
    column(12, htmlOutput("hcontainer")),
    highchartOutput("hcontainer2", height = "0", width = "0")
  )
)
#---------------------------------------------------------------------------------
#server.R
library(rlist)

server <- function(input, output) {
  
  gethc <- function(dfname) {
    A <- data.frame(x=c(1,2,3,1,2,3),
                    y=c(0.7,0.8,0.7,0.3,0.2,0.3),
                    group=factor(c("A","A","A","B","B","B")),
                    cluster=c("Cluster 1","Cluster 1","Cluster 2","Cluster 1","Cluster 1","Cluster 2"))
    
    B <- data.frame(x=c(1,2,3,4,1,2,3,4,1,2,3,4),
                    y=c(0.6,0.7,0.2,0.3,0.3,0.2,0.3,0.3,0.1,0.1,0.5,0.4),
                    group=factor(c("A","A","A","A","B","B","B","B","C","C","C","C")),
                    cluster=c("Cluster 1","Cluster 1","Cluster 2","Cluster 2",
                              "Cluster 1","Cluster 1","Cluster 2","Cluster 2",
                              "Cluster 1","Cluster 1","Cluster 2","Cluster 2"))
    
    df <- get(dfname)
    hc <- highchart(height=300)
    hc <- hc_xAxis(hc,title=list(text=NULL),allowDecimals=FALSE)
    
    dlev <- levels(df$group)
    for(i in 1:length(dlev))
    {
      #issue line
      da <- list.parse(df[df$group==dlev[i],c("x", "y")])
      names(da) <- NULL
      hc <- hc_add_series(hc, data = da, name = dlev[i],type = "column")
    }
    
    hc <- hc_yAxis(hc,title=list(text=NULL),max=1)
    hc <- hc_tooltip(pointFormat = "y: {point.y} <br> group: {point.group} <br> cluster: {point.cluster}")
    hc <- hc_plotOptions(hc,column = list(stacking = "normal", pointPadding = 0, groupPadding = 0, borderWidth = 0))
    #check highcharts object
    print(str(hc))
    column(width = 12, hc)
  }
  
  output$hcontainer <- renderUI({
    charts <- lapply(input$nplots, gethc)
    do.call(tagList, charts)
  })  
}

```

**Comment by jbkunst** [comment]
@royfrancis 

I found a solution I hope this work for you ;)

```
hc <- highchart(height=300)

# here I pre-define the categories, for each bar 
hc <- hc_xAxis(hc,title=list(text=NULL),allowDecimals=FALSE, categories = unique(sort(df$x)))

# this avoid put `type colum` in each hc_add_series
hc <- hc_chart(hc, type = "column")

for(lvl in levels(df$group)) # its more cleaner.
{
  # dplyr its used to select only y and cluster.
  # And use list.parse3 (shorcut to list.parse, and remove names)
  da <- list.parse3(df %>% filter(group==lvl) %>% select(y, name = cluster)) 
  hc <- hc_add_series(hc, data = da, name = lvl)
}

hc <- hc_yAxis(hc,title=list(text=NULL),max=1)

# here I changed the data tooltip group: {series.name} and  cluster: {point.name}
hc <- hc_tooltip(hc, pointFormat = "y: {point.y} <br> group: {series.name} <br> cluster: {point.name}")
hc <- hc_plotOptions(hc,column = list(stacking = "normal", pointPadding = 0, groupPadding = 0, borderWidth = 0))
```

![screenshot_1](https://cloud.githubusercontent.com/assets/56481/13571107/70cabbd2-e451-11e5-9b93-636e6da5f05e.png)

**Comment by smach** [comment]
Based on this StackOverflow answer about adding extra data to Highcharts tooltips [http://stackoverflow.com/a/8515679/718150](http://stackoverflow.com/a/8515679/718150) it seems that this should work

    highchart() %>% 
      hc_title(text = "Scatter chart with size and color") %>% 
      hc_add_series_scatter(mtcars$wt, mtcars$mpg,
                        mtcars$drat, mtcars$hp, numgears=mtcars$gear) %>%
    hc_tooltip(formatter = JS("function(){
                          return ('y: ' + this.y + ' <br> Number of gears: ' + this.point.numgears)
                          }")
    )



But it doesn't, this.point.numgears is undefined in the tooltip. Is that format not supported? Or is it supported and I'm doing something wrong? Thanks.

**Comment by jbkunst** [comment]
@smach 

If you do:

```
library(highcharter)

hc <- highchart() %>% 
  hc_title(text = "Scatter chart with size and color") %>% 
  hc_add_series_scatter(mtcars$wt, mtcars$mpg,
                        mtcars$drat, mtcars$hp, numgears=mtcars$gear) %>%
  hc_tooltip(formatter = JS("function(){
                            return ('y: ' + this.y + ' <br> Number of gears: ' + this.point.numgears)
                            }")
             )

hc$x$hc_opts$series[[1]]$data[[1]]
```

You'll see:
```
$x
[1] 2.62

$y
[1] 21

$z
[1] 3.9

$valuecolor
[1] 110

$color
[1] "#26828EFF"
```

The optional parameters in `hc_add_series_scatter`  (`...`) are used in the `hc_add_series` function (inside de of   `hc_add_series_scatter`) as arguments and are not passed to the data frame. So the argument `numgears=mtcars$gear` is not used. May be we can do it in the future .

You can do "manually":

```
library(viridisLite)
library(dplyr)

colorvar <- mtcars$hp
cols <- viridis(1000)[round(ecdf(colorvar)(colorvar)*1000)]
cols <- substr(cols, 0, 7)

dt <- mtcars %>% 
  mutate(x = wt, y = mpg, z = drat, color =  cols)

ds <- list.parse3(dt)

hc2 <- highchart() %>% 
  hc_title(text = "Scatter chart with size and color") %>% 
  hc_add_series(data = ds, type = "bubble") %>%
  hc_tooltip(formatter = JS("function(){
                            return ('y: ' + this.y + ' <br> Number of gears: ' + this.point.gear)
                            }")
  )

hc2
```
![screenshot_2](https://cloud.githubusercontent.com/assets/56481/13582603/0a130602-e48c-11e5-9e85-f416cdd99835.png)

Finally check;:

```
hc$x$hc_opts$series[[1]]$data[[1]]

$mpg
[1] 21

$cyl
[1] 6

$disp
[1] 160

$hp
[1] 110

$drat
[1] 3.9

$wt
[1] 2.62

$qsec
[1] 16.46

$vs
[1] 0

$am
[1] 1

$gear
[1] 4

$carb
[1] 4

$x
[1] 2.62

$y
[1] 21

$z
[1] 3.9

$color
[1] "#26828E"

```

**Comment by smach** [comment]
Thank you. I will have to look more carefully at the code to try to understand what's happening there. 

It would be a very useful feature someday to be able to use the `hc_add_series_scatter(mtcars$wt, mtcars$mpg, mtcars$drat, mtcars$hp, numgears=mtcars$gear)` format to do this!

**Comment by jbkunst** [comment]
The `hc_add_series_scatter`is just a shotcut. I'll try to implement your idea to make this function more flexible and general. By now I think the best option is do it "manually". If you have more questions just open a issue. The discussions probably will make more funcionalities to highcharter ;).

**Comment by kamalkishorebss** [comment]
- 

- [ ] 1.
