### ISSUE TITLE
Only 5 distinct colors in themes

### ISSUE THREAD

**Issue by DrRoad** [jbkunst/highcharter#540]
Hi, appreciate if you can help to look at why there are only 5 different colors when I use themes with hc_add_theme as shown in the chart below

![rut-trend (2)](https://user-images.githubusercontent.com/8111532/62185464-bdb9c900-b3b6-11e9-85c5-b5cd0ce6010e.jpeg)

**Comment by DrRoad** [comment]
![rut-trend (1)](https://user-images.githubusercontent.com/8111532/62185531-f22d8500-b3b6-11e9-94c4-2ed1a09c8f4a.jpeg)
![rut-trend](https://user-images.githubusercontent.com/8111532/62185551-02ddfb00-b3b7-11e9-9c93-691977c0b9fe.jpeg)

**Comment by jbkunst** [comment]
Hi,

Every theme have its own colors, usually they are 5.  You can choose whatever you want and many as you want with:

```r
hc %>%
  hc_colors(c("red", "black", ...))
```
