### ISSUE TITLE
Draggable points not working after deploying the app on shinyapps.io

### ISSUE THREAD

**Issue by pranavpandya84** [jbkunst/highcharter#546]
### Explanation of issue:

Draggable points feature works perfectly fine locally after implementing suggestions from [this issue](https://github.com/jbkunst/highcharter/issues/485). However, **it's not working after deploying it on shinyapps.io**. 

### Steps to replicate the issue:

To enable `draggable-point.js` plugin, 

- open `highchart.yaml` file under highcharter libarary (example path on windows machine: `R\win-library\3.6\highcharter\htmlwidgets\highchart.yaml`)
- Add this line `- plugins/draggable-points.js` (instead of uncommenting `- modules/draggable-points.js` line)

or simply add following in highchart() with pipe

```
highchart() %>%
  ("plugins/draggable-points.js")
```
Now run the following code to get the output in shiny locally. 

```
library(shiny)
library("highcharter")
data("citytemp")

shinyApp(
    ui <- fluidPage(highchartOutput("draggable")), 
    server <- function(input, output) {
        output$draggable <- renderHighchart({
            highchart() %>% 
                hc_title(text = "draggable points demo") %>% 
                hc_xAxis(categories = month.abb) %>% 
                hc_plotOptions(
                    series = list(stickyTracking = FALSE),
                    column = list(stacking = "normal"),
                    line = list(cursor = "ns-resize")) %>% 
                hc_add_series(data = sample(1:12), type = "column") %>% 
                hc_add_series(data = citytemp$new_york, type = "column") %>% 
                hc_add_series(data = citytemp$berlin, draggableY = TRUE)
        })
    }
)
```
At this point, draggable feature works fine locally. 

![Capture](https://user-images.githubusercontent.com/22565727/63434670-d18ca400-c425-11e9-9137-504ecbef658e.PNG)

### Problematic part: 

The app is then deployed to shinyapps.io with exact same code as above and the output can be viewed [here](https://pranavp.shinyapps.io/hc_draggable_example/). Unfortunately, this feature is not working. :( 

Any suggestions on how to fix this issue?

**Comment by cjvanlissa** [comment]
Has this been fixed yet? I run into the same problem!
