### ISSUE TITLE
htmlwdgtgrid influence in all col classes

### ISSUE THREAD

**Issue by HarrisonHenri** [jbkunst/highcharter#549]
Dear @jbkunst, thank you for this great package!

I am a developer on a Shiny system where CSS is suffering unwanted effects because the line below in htmlwdgtgrid.css:

`[class*='col-'] {
	float: left;
}
`

Is there any possibility to solve or reverse that?

**Comment by nteetor** [comment]
I have run into this on a few occasions and would love to have a way to suppress the style altogether.

**Comment by HarrisonHenri** [comment]
Yeah @nteetor , this effect is really unpleasure boring sometimes!

**Comment by jbkunst** [comment]
Hi @HarrisonHenri  @nteetor ,

I will remove that depedency and add a function to add this css if is requiered due is not used so much (I think!)

**Comment by jbkunst** [comment]
Hi @HarrisonHenri @nteetor 

The dependency of *htmlwdgtgrid.css* was removed as default.

If is needed its possible to do:

```r
hchart(rnorm(10000)) %>%
  hc_add_dependency("css/htmlwdgtgrid.css")
```

**Comment by nteetor** [comment]
Excellent, thank you for this adjustment.
