### ISSUE TITLE
depedency problem

### ISSUE THREAD

**Issue by harryprince** [jbkunst/highcharter#55]
ERROR: dependencies ‘purrr’, ‘viridisLite’ are not available for package ‘highcharter’

**Comment by jbkunst** [comment]
Hi @harryprince :smile: 

Next time, can you tell more details insteand of a simple output :wink: ?

Try install the package first:

```
install.packages(c("purrr", "viridisLite"))
```

Then run:

```
install.packages("highcarter")
```

Tell me if it helps

**Comment by jbkunst** [comment]
I'm closing this issue due the non activity. No problem if this need to be reopen ;)!
