### ISSUE TITLE
 Configurations options from Highcharter 

### ISSUE THREAD

**Issue by NahuelBargas** [jbkunst/highcharter#554]
Hello!

How can the configuration options be edited directly from the Highcharter commands in R?.

I want to modify the lang settings like weekdays, months, shortMonths and drillUpText.

It is a bit tedious to change the Highcharts.Options from the final version of HTML every time.

Thanks!

**Comment by jbkunst** [comment]
Hola, 

Hay algunos issues en los cuales se han ejemplificados el como poder hacer lo que requieres ;):

https://github.com/jbkunst/highcharter/issues/69
https://github.com/jbkunst/highcharter/issues/321

Espero te sea de ayuda,

**Comment by NahuelBargas** [comment]
Muchas Gracias por la pronta respuesta! Voy a mirarlos en este momento.
