### ISSUE TITLE
Autorotation doesn't work

### ISSUE THREAD

**Issue by kuzmenkov111** [jbkunst/highcharter#563]
In dev version of highcharter autorotation doesn't work. It just trimmed categories on X axis. But the current CRAN version makes appropriate autorotation. 
See below
```
remotes::install_github('jbkunst/highcharter')
library(highcharter)
data(citytemp)
citytemp$month <- paste0(citytemp$month, citytemp$month, citytemp$month )
highchart() %>% 
  hc_xAxis(categories = citytemp$month) %>% 
  hc_add_series(name = "Tokyo", data = citytemp$tokyo) %>% 
  hc_add_series(name = "London", data = citytemp$london) %>% 
  hc_exporting(enabled = TRUE) %>%
  hc_add_series(name = "Other city",
                data = (citytemp$tokyo + citytemp$london)/2)
```

![Снимок_экрана_101819_122952_AM](https://user-images.githubusercontent.com/13810479/67049236-6d910e00-f13e-11e9-9c0c-e7f2f7b8a704.jpg)

And with CRAN
```
install.packages("highcharter", repos = "https://cran.r-project.org/")
library(highcharter)
data(citytemp)
citytemp$month <- paste0(citytemp$month, citytemp$month, citytemp$month )
highchart() %>% 
  hc_xAxis(categories = citytemp$month) %>% 
  hc_add_series(name = "Tokyo", data = citytemp$tokyo) %>% 
  hc_add_series(name = "London", data = citytemp$london) %>% 
  hc_exporting(enabled = TRUE) %>%
  hc_add_series(name = "Other city",
                data = (citytemp$tokyo + citytemp$london)/2)
```
![Снимок_экрана_101819_123337_AM](https://user-images.githubusercontent.com/13810479/67049459-f740db80-f13e-11e9-8ab3-b127f4253b92.jpg)

By default autorotation should works (https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/xaxis/labels-autorotation-0-90/)

Moreover on github master version `rotation` argument has broken padding of X axis labels
```
library(highcharter)
data(citytemp)
citytemp$month <- paste0(citytemp$month, citytemp$month, citytemp$month )
highchart() %>% 
  hc_xAxis(categories = citytemp$month, labels= list(rotation = -45)) %>% 
  hc_add_series(name = "Tokyo", data = citytemp$tokyo) %>% 
  hc_add_series(name = "London", data = citytemp$london) %>% 
  hc_exporting(enabled = TRUE) %>%
  hc_add_series(name = "Other city",
                data = (citytemp$tokyo + citytemp$london)/2)
```
![Снимок_экрана_101819_124133_AM](https://user-images.githubusercontent.com/13810479/67049924-08d6b300-f140-11e9-89bb-5cbef34c523f.jpg)

**Comment by kuzmenkov111** [comment]
The same problem exists on 0.5 CRAN version

**Comment by jbkunst** [comment]
Hi @kuzmenkov111 

The problem was the grouped categories plugin which I removed from the default.

Thanks.

Next time, try use highcharts2() which is a minified version in terms of dependencies:

![image](https://user-images.githubusercontent.com/56481/69882210-3e79ca80-12ae-11ea-81ad-95698f3b1d19.png)

**Comment by kuzmenkov111** [comment]
Many thanks!
