### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Stephonomon** [jbkunst/highcharter#564]
The ability to click on somewhere like a chart title and to have it hyperlink to a defined URL

**Comment by jbkunst** [comment]
Hi @Stephonomon 

You can do it. See http://jsfiddle.net/fen9eLn4/

So, you need to do:

```r
hc_title(
  useHTML = TRUE,
  text = '<a href="http://www.highcharts.com"><u>My title</u></a>'
)
```

In your R script.
