### ISSUE TITLE
Warning "`cols` is now required" after last tidyr update

### ISSUE THREAD

**Issue by wrprates** [jbkunst/highcharter#566]
Hi. 

After the latest update in tidyr (1.0.0 version) some warning messages started appearing when using some highcharter functions.  The versions of my packages are:

`packageVersion("tidyr")`
[1] ‘1.0.0’

`packageVersion("highcharter")`
[1] ‘0.7.0’

One example happens when I use the function `hcboxplot()`, like this:

`hcboxplot(mtcars$hp)`
<code> 
Warning message:
`cols` is now required.
Please use `cols = c(data)` 
</code>

I saw that this specific issue happens because the function `unnest()` of `tidyr`. 

Specifically in the function hcboxplot, when I replaced (inside the function) "unnest()" by "unnest(cols = c(data))" the warning stopped appearing.

It happens all the time when highcharter uses `unnest()` function after this update in `tidyr`.

Thanks in advance.
Best.

**Comment by jbkunst** [comment]
Thanks @wrprates 

Clossing this issue due the deprecation of `hcboxplot` in favor to `data_to_boxplot`.
