### ISSUE TITLE
How to add new Highcharts module to 7.2.0 version from GitHub?

### ISSUE THREAD

**Issue by raf18seb** [jbkunst/highcharter#567]
The Highcharter is using Highcharts 7.0.1 now, but I would like to use 7.2.0 from GitHub to use the Organization series which was added to Highcharts in 7.2.0.

I am pulling the GitHub Highcharter 7.2.0 and defining organization series using this code:
```
devtools::install_github("jbkunst/highcharter")
library(highcharter)

highchart() %>%
  hc_chart(type = 'organization') %>%
  hc_add_series(
    data = list(
      list(from = 'Brazil', to = 'Portugal'),
      list(from = 'Brazil', to = 'Spain'),
      list(from = 'Poland', to = 'England'))
  )
```

But I get Highcharts error 17 which says that Organization series doesn't exist - the common reason why this error occurs is the missing organization.js module.

The question is - how can I load this module to Highcharter? Maybe it's already loaded? How to run organization chart in Highcharter 7.2.0?

Best regards,
Rafał,
Highcharts Developer

ps. below code is working fine for Sankey series 
```
library(highcharter)

highchart() %>%
  hc_chart(type = 'sankey') %>%
  hc_add_series(
    data = list(
      list(from = 'Brazil', to = 'Portugal', weight = 5),
      list(from = 'Brazil', to = 'Spain', weight = 2),
      list(from = 'Poland', to = 'England', weight = 2))
  )
```

Original question: https://stackoverflow.com/questions/58540244/how-to-build-an-organization-chart-with-highcharter

**Comment by pachamaltese** [comment]
@raf18seb Hi! Thanks for reporting this, I created a development branch that allows this.

Please re-install highcharter by running `devtools::install_github("jbkunst/highcharter", ref = "720")`

Here I added the example above and it works: https://github.com/jbkunst/highcharter/blob/720/dev/stackoverflow/58540244.R

**Comment by mnist91** [comment]
Thanks and I appreciate that you solved this issue

**Comment by FlyImagi** [comment]
The command devtools::install_github("jbkunst/highcharter", ref = "720") to get to the development branch is now no longer available, can it be updated again?

```
Downloading GitHub repo jbkunst/highcharter@720
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/jbkunst/highcharter/tarball/720'
```
