### ISSUE TITLE
Warning message: `parse_quosure()` is deprecated as of rlang 0.2.0.

### ISSUE THREAD

**Issue by wrprates** [jbkunst/highcharter#569]
When using `hchart()`, the following warning appeared:

Warning message:
`parse_quosure()` is deprecated as of rlang 0.2.0.
Please use `parse_quo()` instead.

The code to replicate the warning is:

<pre>
hchart(
  as_tibble(rownames_to_column(mtcars, var = "car")),
  "column",
  hcaes(x = car, y = mpg)
) 
</pre>

Session info:
R version 3.6.1 (2019-07-05)
tidyverse_1.2.1
highcharter_0.7.0

Thanks!

**Comment by jbkunst** [comment]
Fixed in #570, thanks to @pachamaltese
