### ISSUE TITLE
Custom colors

### ISSUE THREAD

**Issue by royfrancis** [jbkunst/highcharter#57]
If I have a bunch of custom colours `c("#0000FF","#FF3300")`, how can I use them in the plot? I can see that highcharts have a config option called [colors](http://api.highcharts.com/highmaps#colors), but I am not sure how to access it. Is there something like `hc_colors()`?

**Comment by jbkunst** [comment]
@royfrancis 

I forgot implement `hc_colors` sorry, I'm adding rght now.

Meanwhile you can add creating a theme:

```
library(highcharter)
library(viridisLite)


cols <- viridis(3)
cols <- substr(cols, 0, 7)

thm <- hc_theme(
  colors = cols,
  chart = list(
    backgroundColor = NULL
    )
  )  

hc_demo() %>% 
  hc_chart(type = "column", stack) %>% 
  hc_add_theme(thm)
```  
![rplot](https://cloud.githubusercontent.com/assets/56481/13745225/b870caec-e9cb-11e5-9893-2c297363db12.png)


Kind regards!

**Comment by royfrancis** [comment]
You are fantastic! Thanks a lot :-)

**Comment by jbkunst** [comment]
56566cd
