### ISSUE TITLE
next steps for highcharter

### ISSUE THREAD

**Issue by pachamaltese** [jbkunst/highcharter#572]
# documentation

- [ ] integrate Danton Noriega examples
- [x] pkgdown site

# contribs

- [ ] https://github.com/edwindj #550 
- [ ] https://github.com/sgrubsmyon #537

# tests

- [ ] test on OSX
- [x] add test suite
- [ ] update obsolete funcions (see #574)

**Comment by jbkunst** [comment]
Closes in v0.8.2
