### ISSUE TITLE
Highcharter doexn't work in shiy

### ISSUE THREAD

**Issue by MislavSag** [jbkunst/highcharter#576]
I tried to implement highcharter in shiny, but without success.

I also wanted to try your implementation from this site http://jkunst.com/highcharter/shiny.html
but links don't work. The code for shiny app doesn't work either. It returns:
```
Warning: Error in hc_demo: could not find function "hc_demo"
  [No stack trace available]
```

In my case, it doesn't return an error, but the graph doesn't appear on site. It works outside shiny app.

**Comment by jbkunst** [comment]
Hi @MislavSag 

Try to use `highcharts_demo()` instaed of `hc_demo()`.
