### ISSUE TITLE
Labels for z axis in 3D column chart

### ISSUE THREAD

**Issue by sab-d** [jbkunst/highcharter#580]
Hey there.

I think there's a problem with setting labels for the z axis in a 3D column chart. When I specify min, max and categories for the z axis via hc_zAxis() only zeros get printed as labels instead of the specified ones. I observed this behaviour for versions 0.5.0, 0.7.0, and the current dev version (0.7.0.9001).

I've included a fiddle, as well as a reproducible example in R.

https://jsfiddle.net/4qkfw619/

    library(shiny)
    library(highcharter)
    
    shinyApp(
      
      ui <- fluidPage(
        fluidRow(
          highchartOutput('chart')
        )
      ),
      
      server <- function(input, output, session) {
        
        df <- data.frame(
          Z1 = c(1, 2, 1, 4),
          Z2 = c(2, 3, 2, 7),
          Z3 = c(6, 3, 7, 4),
          Z4 = c(3, 4, 1, 5)
        )
        
        dta <- lapply(seq(ncol(df)), function(x) {
          list(
            name = colnames(df)[x], 
            data = df[, x]
          ) 
        })
        
        output$chart <- renderHighchart({
          
          highchart() %>%
            hc_chart(
              type = "column", 
              options3d = list(
                enabled = TRUE,
                beta = 20,
                alpha = 30,
                depth = 400,
                viewDistance = 10
              )
            ) %>%
            hc_xAxis(categories = paste0("X", 1:4)) %>%
            hc_zAxis(
              min = 0,
              max = 3,
              categories = colnames(df)
            ) %>%
            hc_plotOptions(
              series = list(
                depth = 100,
                grouping = FALSE,
                groupZpadding = 10
              )
            ) %>%
            hc_add_series_list(dta)
        })
      })

Keep up the good work and thanks in advance!

**Comment by jbkunst** [comment]
Replicated in 0.8.2 without problems:

![image](https://user-images.githubusercontent.com/56481/89005965-ae27d580-d2d3-11ea-8dd6-16a92542685a.png)

**Comment by akshaybholee** [comment]
Hello jbkunst,

That's an impressive way of shaowing 3d barchart. Thank you for this.

I have one question if you can help me with it. 

I tried your code and it is working fine. But when i have only 1 row in the data.frame the chart is not rendering. 
Is there something additional to do when dealing with 1 row?

see the reproducible example with 1 row below:

library(shiny)
library(highcharter)

shinyApp(
  
  ui <- fluidPage(
    fluidRow(
      highchartOutput('chart')
    )
  ),
  
  server <- function(input, output, session) {
    
    df <- data.frame(
      Z1 = c(1, 2, 1, 4),
      Z2 = c(2, 3, 2, 7),
      Z3 = c(6, 3, 7, 4),
      Z4 = c(3, 4, 1, 5)
    )
    
    df <- df[-(1:3),] #reduced dataframe to 1 row
    
    
    dta <- lapply(seq(ncol(df)), function(x) {
      list(
        name = colnames(df)[x], 
        data = df[, x]
      ) 
    })
    
    output$chart <- renderHighchart({
      
      highchart() %>%
        hc_chart(
          type = "column", 
          options3d = list(
            enabled = TRUE,
            beta = 20,
            alpha = 30,
            depth = 400,
            viewDistance = 10
          )
        ) %>%
        hc_xAxis(categories = row.names(df[1:nrow(df)-1,])) %>%
        hc_zAxis(
          min = 0,
          max = 3,
          categories = colnames(df)
        ) %>%
        hc_plotOptions(
          series = list(
            depth = 100,
            grouping = FALSE,
            groupZpadding = 10
          )
        ) %>%
        hc_add_series_list(dta)
    })
  })
