### ISSUE TITLE
SimpleGrid CSS clashes with Bootstrap classes

### ISSUE THREAD

**Issue by cpsievert** [jbkunst/highcharter#582]
This line of Highcharter's simplegrid CSS dependency clashes with some Bootstrap classes, [like `.col-form-label`](https://getbootstrap.com/docs/4.0/components/forms/#readonly-plain-text)

https://github.com/jbkunst/highcharter/blob/ffa58136374aabf3d3d2585943ce91542cb380da/inst/htmlwidgets/lib/highcharts-7.2.1/css/htmlwdgtgrid.css#L18-L22

You can see an example of that by `rmarkdown::run()` ing the Rmd in this repo -- https://github.com/walkerke/neighborhood_diversity (notice how the positioning of the slider label is wrong)

**Comment by jbkunst** [comment]
Hi Carson @cpsievert ,

That dependency was removed for the highchart htmlwidget in the development version. More details in #549,

**Comment by cpsievert** [comment]
Oh, great, feel free to close then!
