### ISSUE TITLE
are innerSize and dataLabels' distance parameter incompatible?

### ISSUE THREAD

**Issue by SeungminHeo** [jbkunst/highcharter#585]
Hi,

I made donut pie chart for visualization and my chart seems like error.

This is my code.

```
data = data.frame(
        name = c('a', 'b', 'c', 'd', 'e', 'f'),
        y = c(4668, 3152, 1530, 452, 103, 104)
    )

hc <- highchart() %>%
    hc_chart(type="pie") %>%
    hc_add_series(
      data = list_parse(data),
      innerSize = '50%'
    ) %>%
    hc_plotOptions(
      pie = list(
        dataLabels =
          list(enabled = TRUE,
               distance = '-25%',
               allowOverlap = FALSE)
      )
    )
  
hc
```

This is my result. The dataLabel is located far from chart.

![image](https://user-images.githubusercontent.com/46894313/71453664-b4028900-27cf-11ea-9c8a-b13fdb8a6271.png)

I tested same chart in JS Fiddle with Highcharts.js(refer to this link : https://jsfiddle.net/wzr8q7ac/2/#). This works fine.

Is this R wrapper's problem?

Thank you

**Comment by jbkunst** [comment]
Maybe was a highcharter problem. Now in 0.8.2 looks ok.

![image](https://user-images.githubusercontent.com/56481/89006298-68b7d800-d2d4-11ea-926a-d6c1e6acc61d.png)
