### ISSUE TITLE
disable legendItemClick in highmaps is not working

### ISSUE THREAD

**Issue by rwaaijman** [jbkunst/highcharter#589]
The example below does not work, while in other charts I'm able to disable the legendItemClick in the same manner. Also in highcharts itself it is working (https://codepen.io/hanswesterbeek/pen/oNgMXdg):  

highchart(type = 'map') %>%
    hc_plotOptions(
      series = list(joinBy = c("a", "b"))
      , map = list(events = list(legendItemClick = JS("function(){return false}")))
    ) %>%
    hc_add_series(mapData = map, data = data, name = seriesName) %>% 
    hc_colorAxis(dataClasses = dataClasses)

**Comment by nordicgit70** [comment]
I could not reproduce the sample, but could be related to known [Highcharts legendItemClick issue](https://stackoverflow.com/questions/59063357/highmaps-legenditemclick-doesnt-work-when-there-are-dataclasses-in-coloraxis).
