### ISSUE TITLE
Add support for cross talk

### ISSUE THREAD

**Issue by bjungbogati** [jbkunst/highcharter#590]
Plot.ly has already supported Cross talk.

https://rstudio.github.io/crosstalk/

**Comment by bjungbogati** [comment]
@jbkunst can you please look into this.

**Comment by jbkunst** [comment]
Hi @bjungbogati 

I will not add crosstalk support any time soon. 😞

**Comment by patarol** [comment]
@jbkunst if you want I can work on it and create a PR. Let me know if you're open to it

**Comment by abourdea** [comment]
@jbkunst any updates on this? I would also love to see crosstalk functionality added to highcharter!
