### ISSUE TITLE
How to add a dependency wheel in Highcharter?

### ISSUE THREAD

**Issue by Sissi91** [jbkunst/highcharter#592]
I tried to make a dependency wheel plot. But found out that probably the module: "dependency-wheel.js" is missing. Would be great if you could add it like you did in issue #567 .

`highchart() %>%`
  `hc_chart(type = 'dependencywheel') %>%`
 ` hc_add_series(`
   ` data = list(`
      `list(from = 'Brazil', to = 'Portugal', weight = 1),`
      `list(from = 'Portugal', to = 'England', weight = 1),`
     ` list(from = 'England', to = 'Brazil', weight = 1))`
`  )`

If I could use it in a developer version, that would be amazing!

I asked the question originaly in:
[https://stackoverflow.com/questions/59794724/highcharts-dependency-wheel-in-r]

**Comment by nordicgit70** [comment]
"dependencywheel" module is disabled in the yaml and not loaded by Highcharter. There are lots of modules in Highcharts so makes sense to be selective to avoid loading "too much" Javascript. 

It could be a feature request to enable additional dependencies to be loaded using `htmlwidgets::createWidget()` with argument dependencies.

**Comment by jbkunst** [comment]
@Sissi91 

The module is included. Was a bug due the order of the dependencies and it was fixed.
