### ISSUE TITLE
Line Chart Losing its hover and other properties when number of series exceeds 49

### ISSUE THREAD

**Issue by tusharmajhi9** [jbkunst/highcharter#596]
Hi @jbkunst ,

I am using Highcharter package 0.7.0.9001. I have attached the RData for your reference.

I am facing an issue while plotting a line chart. When the number of series in the chart exceeds 49, the chart is losing some of its hover properties. 

There are 2 data frames in the RData attached:
1. df - master dataframe containing more than 50 series
2. df_new - filtered dataset containing 49 series

Below is the code to produce the chart:

highchart() %>%
  hc_add_series(df_new, type = "line",
                hcaes(x = properties_ts_hour, y = hourly_cv, group = l2_story))%>%
  hc_tooltip(pointFormat = '<span style="color:{series.color}">{series.name}</span><br/> Value: {point.y}<br/> Story: {point.title}',
             valueDecimals = 1)%>%
  hc_chart(zoomType = "xy")%>%
  hc_exporting(enabled = TRUE)

The chart with df_new is working fine, but not with df. 

df_new is a subset of df.

df_new<-df%>%filter(!l2_story %in% c("story_11","story_15","story_87",
                                                       "story_54","story_61"))

Thanks,
Tushar
[data.zip](https://github.com/jbkunst/highcharter/files/4127387/data.zip)

**Comment by andybega** [comment]
This conversely also affects how "forecast" objects are plotted. 

```r
library(highcharter)
library(forecast)
k_ts <- structure(c(113.9, 121.97, NA, NA, 127.25, 165.36, 213.68, 235.07, 
  244.14, NA, 217.11, 181.27, 147.93, 105.13, 101.52, 99.19, 106.22, 
  169.61, 178.28, 226.09, 304.47, 248.83, 169.17, 136.87, 110.87, 
  100.64, 101.81, 98.34, 107.3, 161.45, 186.78, 185.93, 205.1, 
  198.68, NA, 163.6, 143.66, 105.97, 107.5, 100.84, 115.78, 160.56, 
  174.96, 188.61, 202.04, 225.44, 210.46, 154.47, 109.4, 100.33, 
  101.83, 106.2, 116.2, 158.84, 183.12, 223.79, 240.16, 194.63, 
  194.78, 154.36, 160.93, 110.7, 136.58, 140.85, 124.75, 168.93, 
  203.85, 193.44, 206.2, 195.7, NA), .Tsp = c(2014.33333333333, 
  2020.16666666667, 12), class = "ts") 
fcast <- forecast(auto.arima(k_ts), h = 12)
# only show last 3 years data
fcast$x <- tail(fcast$x, 36)
hc <- hchart(fcast)
# fix hist series name
hc$x$hc_opts$series[[1]]$name <- "Total"
hc
```

<img width="685" alt="Screen Shot 2020-03-19 at 16 23 24" src="https://user-images.githubusercontent.com/1353756/77077524-008be800-69fe-11ea-9ec9-94388ddd0bd6.png">

**Comment by andybega** [comment]
Hey @tusharmajhi9, the markers are showing for me with df and df_new. I found how to enable and disable the markers, maybe try that?

```r
highchart() %>%
  hc_add_series(
    df_new, type = "line",
    hcaes(x = properties_ts_hour, y = hourly_cv, group = l2_story),
    # the new bit
    marker = list(enabled = TRUE)
  ) %>%
  hc_tooltip(
    pointFormat = '{series.name}\nValue: {point.y}\nStory: {point.title}',
    valueDecimals = 1)%>%
  hc_chart(zoomType = "xy")%>%
  hc_exporting(enabled = TRUE)
```

<img width="686" alt="Screen Shot 2020-03-19 at 16 37 54" src="https://user-images.githubusercontent.com/1353756/77078973-ff5bba80-69ff-11ea-92b0-3d524ca40629.png">

**Comment by andybega** [comment]
For the "forecast" example from my comment above, explicitly turning the markers off works as a hacky fix:

```r
library(highcharter)
library(forecast)
k_ts <- structure(c(113.9, 121.97, NA, NA, 127.25, 165.36, 213.68, 235.07, 
  244.14, NA, 217.11, 181.27, 147.93, 105.13, 101.52, 99.19, 106.22, 
  169.61, 178.28, 226.09, 304.47, 248.83, 169.17, 136.87, 110.87, 
  100.64, 101.81, 98.34, 107.3, 161.45, 186.78, 185.93, 205.1, 
  198.68, NA, 163.6, 143.66, 105.97, 107.5, 100.84, 115.78, 160.56, 
  174.96, 188.61, 202.04, 225.44, 210.46, 154.47, 109.4, 100.33, 
  101.83, 106.2, 116.2, 158.84, 183.12, 223.79, 240.16, 194.63, 
  194.78, 154.36, 160.93, 110.7, 136.58, 140.85, 124.75, 168.93, 
  203.85, 193.44, 206.2, 195.7, NA), .Tsp = c(2014.33333333333, 
  2020.16666666667, 12), class = "ts") 
fcast <- forecast(auto.arima(k_ts), h = 12)
# only show last 3 years data
fcast$x <- tail(fcast$x, 36)
hc <- hchart(fcast)
# fix hist series name
hc$x$hc_opts$series[[1]]$name <- "Total"
# turn off markers
for (i in 1:length(hc$x$hc_opts$series)) {
  hc$x$hc_opts$series[[i]]$marker <- FALSE
}
hc
```

<img width="678" alt="Screen Shot 2020-03-19 at 16 44 20" src="https://user-images.githubusercontent.com/1353756/77079543-e43d7a80-6a00-11ea-9017-a94c67a22129.png">

**Comment by jbkunst** [comment]
Hi @tusharmajhi9 

Can you test with the dev version?
