### ISSUE TITLE
Series name with series color at the end of line series

### ISSUE THREAD

**Issue by deepanshu88** [jbkunst/highcharter#597]
I want series name at the end of line series with color of series. I am looking for similar output present here - Highcharts Line Chart, display series name at the end of line series

I am able to include series name at the end of line series but fails to show it as color of series. This is the solution I am unable to include it in highcharter in R as it has both single and double quotes. R is unable to recognise it.

```
 formatter: function() {
    return '<span style="color:'+this.series.color+'">'+this.series.name+'</span>';
  }
```
My Code is shown below -
```

highchart() %>% 
  hc_chart(type = "spline") %>% 
  hc_title(text = "Demo",
           align = "center",
           style = list(
             fontFamily = "Roboto",
             color = "#444",
             fontWeight = "bold"
           )) %>% 
  hc_xAxis(categories = iris$Species) %>% 
  hc_yAxis(labels = list(format = "{value}M")) %>% 
  hc_add_series(name   = "Sepal.Length", 
                data   = iris$Sepal.Length,
                marker = list(enabled= FALSE),
                color='red',
                lineWidth=4, 
                lineColor='red') %>% 
  hc_add_series(name   = "Petal.Length", 
                data   = iris$Petal.Length,
                marker = list(enabled= FALSE),
                type = "area", 
                color='#f6f3ef',
                lineWidth=3, 
                lineColor='#e4dcd2',
                dashStyle = "ShortDot") %>% 
  hc_plotOptions(
    series = list(
      dataLabels = list(
        enabled = TRUE,
        allowOverlap = TRUE,
        align = 'center',
        verticalAlign = 'bottom',
        style = list(fontSize = '14px', color = '#666'),
        formatter = JS("
              function() {
                  if (this.point.x == this.series.data.length - 1) {
                          return this.series.name;
                    }
                          return '';
                }")))) %>% 
  hc_tooltip(pointFormat="{point.series.name}:  €<b>{point.y:,.2f}M</b><br/>", shared= TRUE) %>% 
  hc_add_theme(anacap_theme(palettes = "lightbluegolden")) %>% 
  hc_exporting(enabled = TRUE)

```

**Comment by raf18seb** [comment]
I suppose this issues repo is tracking bugs only or special requests. You got your answer on StackOverflow: https://stackoverflow.com/questions/59968029/series-name-with-series-color-at-the-end-of-line-series

The question should rather be: is _series-label.js_ module supported in Highcharter?
https://code.highcharts.com/modules/series-label.src.js
API: https://api.highcharts.com/highcharts/plotOptions.series.label

**Comment by PaulC91** [comment]
an easier way to do this is to use the proximate legend label position feature as demonstrated here: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/legend/layout-proximate

You can add this in highcharter with:
```
%>% hc_legend(layout = "proximate", align = "right")
```
