### ISSUE TITLE
Value variable

### ISSUE THREAD

**Issue by natjerm** [jbkunst/highcharter#600]
Hi, 

Let's say I have a map, for example: 
hc <- highchart(type="map") %>%
hc_xAxis(type = "category") %>%
  hc_add_series(mapData = map_data,
                tooltip = list(pointFormat = "{point.name}: {point.value}"),
                showInLegend = TRUE, 
                states = list(
                  select= list(
                    color='#EFFFEF')),
                data = df,
                value="value", joinBy = "name", name = " ")

Is there a way to name a value differently than "value"? When I'd changed the name of the column "value", my variable wasn't placed correctly, e.g. "joinBy" function wasn't split colors by values. 

Thanks in advance

**Comment by jbkunst** [comment]
Highcharts uses the `value` name for color the map.  Do you have a reprex?
