### ISSUE TITLE
How to make sure the chart exported  is perfect that  like the chart exported from Highcharts official website? 

### ISSUE THREAD

**Issue by ZENG-David** [jbkunst/highcharter#604]
For example, the scatter chart exported from official website (https://www.highcharts.com/demo/scatter) which looks quite 
perfect，but mine (all elements) is  always changing with the 
change of browser window. 

please help me out of the issue, thanks, bro.

**Comment by nordicgit70** [comment]
The resulting chart is the same as in Highcharts since the rendering is done by Highcharts Javascript. To make perfect looking charts it is worth to study the available options, this is really a great charting library that takes some time to learn.
