### ISSUE TITLE
toJSON is very slow compared to using rjson's

### ISSUE THREAD

**Issue by nordicgit70** [jbkunst/highcharter#613]
The default Shiny toJSON (jsonlite) is very slow compared to rjson's toJSON, which is approximately 25x faster in microbench tests (*highcharter object with AAPL YTD quotes*). 

<img width="369" alt="json-benchmark" src="https://user-images.githubusercontent.com/22841797/78658104-0b81bc00-78ca-11ea-9b97-c9f413b8ddff.PNG">

In my test I found that rjson::toJSON converts NA's to strings, which cannot be plotted by Highcharts (*Javascript error 14 in browser console*). After removing NA's my charts plot without problems; including OHLC stock, line, stacked bars and scatter.

Suggest to add option to use rjson::toJSON to improve performance.

**Comment by nordicgit70** [comment]
Closed after merge into master.

**Comment by hongyuanjia** [comment]
@nordicgit70 https://github.com/jbkunst/highcharter/issues/457 guided me here. Thanks for this. I wonder if you could try https://github.com/eddelbuettel/rcppsimdjson, which is I believe the fastest json serialization library for R.
