### ISSUE TITLE
[BUG] scatter plot loss it's color with large size dataset

### ISSUE THREAD

**Issue by jhk0530** [jbkunst/highcharter#615]
Hi, I'm trying to build single cell data analysis package, which usually contains large size (more than 10k) datasets.

and I plotted `t-SNE` / `UMAP` result with this `highcharter`.

Here's code I used.

```R
 hchart(dfobj, type = 'scatter', hcaes(x = x, y = y, color = col) )
```

`dfobj` is dataframe with 6162*3 size.

![image](https://user-images.githubusercontent.com/6457691/79099275-bef12180-7d9e-11ea-8d8a-f729381e7f8f.png)

------

If I plot all points of `dfobj` their color doesn't work.

![image](https://user-images.githubusercontent.com/6457691/79099204-9f59f900-7d9e-11ea-9bce-a99ce3931ad7.png)

and If I plot part of them, it will work as expected.

![image](https://user-images.githubusercontent.com/6457691/79099175-8cdfbf80-7d9e-11ea-8692-1c9e6b62cff4.png)

I used `DEV` version of highcharter. not `CRAN` version.

I believe as size is larger than 5000, this error happened.

Bests.

**Comment by nordicgit70** [comment]
Hi, did you find a resolution or is this still an open issue? If so do you have any errors in the browser console?

**Comment by jbkunst** [comment]
Hi @jhk0530 ,

Can you try again reinstalling the github version? 

``` r
# 20K
N <- 20000

library(tidyverse)
library(highcharter)
#> Registered S3 method overwritten by 'quantmod':
#>   method            from
#>   as.zoo.data.frame zoo
#> Highcharts (www.highcharts.com) is a Highsoft software product which is
#> not free for commercial and Governmental use

df <- tibble::tibble(
  x = round(rnorm(N), 2),
  y = round(rnorm(N), 2),
  col = colorize(x + y)
)

glimpse(df)
#> Rows: 20,000
#> Columns: 3
#> $ x   <dbl> 2.15, -0.39, -0.48, -0.23, 0.66, 1.33, -0.16, 1.02, -0.85, -0.8...
#> $ y   <dbl> -0.64, -1.04, -0.46, 1.40, -0.71, -0.56, -0.49, -0.34, -1.66, 1...
#> $ col <chr> "#C0CE41", "#392D65", "#324A70", "#A5C44D", "#218E8B", "#7FB55F...
```

<sup>Created on 2020-07-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

```

hchart(df, "scatter", hcaes(x, y, color = col))
```
![image](https://user-images.githubusercontent.com/56481/88087330-b73bd880-cb56-11ea-8b38-7ad00b1fd739.png)
