### ISSUE TITLE
Pattern fill sample code deprecated

### ISSUE THREAD

**Issue by parker-howell** [jbkunst/highcharter#617]
jbkunst's tutorial here: http://jkunst.com/highcharter/plugins.html shows a pattern fill (sub-heading "Pattern fill"), but the code he provides (copied below) doesn't add the pattern anymore (using R version 3.6--both the CRAN and development versions of highcharter fail to add the pattern fill). It looks like the problem might be with the hc_defs function.

Here is the plot on jbkunst's tutorial:
![image](https://user-images.githubusercontent.com/29580215/79251133-fe6e4b00-7e3c-11ea-8eb4-df5ffd961141.png)

CRAN version of highcharter returns the error "could not find function "hc_defs" and development version of highcharter just returns a plot without the pattern fill.

Here is the highcharts documentation on pattern fills: https://www.highcharts.com/blog/tutorials/pattern-fills/

```
library(highcharter)
highchart() %>% 
  hc_title(text = "I'm a pirate looking chart") %>% 
  hc_xAxis(categories = month.abb) %>% 
  hc_defs(patterns = list(
    list(id = 'custom-pattern',
         path = list(d = 'M 0 0 L 10 10 M 9 -1 L 11 1 M -1 9 L 1 11',
                     stroke = "black",
                     strokeWidth = 1
         )
    )
  )) %>% 
  hc_add_series(data = c(7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2,
                         26.5, 23.3, 18.3, 13.9, 9.6),
                type = "area",
                fillColor = 'url(#custom-pattern)') %>% 
  hc_add_theme(hc_theme_handdrawn())
```

**Comment by nordicgit70** [comment]
Dependency `modules/pattern-fill.js` is disabled in the yaml (see also #276 for possible solution).

**Comment by jbkunst** [comment]
Hi @parker-howell 

As @nordicgit70  said, the module is disable but you can add using `hc_add_dependency`.

Examples in https://jkunst.com/highcharter/articles/modules.html#pattern-fills-1

Kind regards.

![image](https://user-images.githubusercontent.com/56481/89104807-1ec11600-d3ea-11ea-9be6-cb2f173e959c.png)
![image](https://user-images.githubusercontent.com/56481/89104810-241e6080-d3ea-11ea-8c0f-a1ff1e057e31.png)
![image](https://user-images.githubusercontent.com/56481/89104812-297bab00-d3ea-11ea-8b9e-c975142cf18a.png)
