### ISSUE TITLE
hc_add_series throws error for tibble package >2.0.0 

### ISSUE THREAD

**Issue by Anna-DB** [jbkunst/highcharter#618]
Hi we use the R Package highcharter in Version 0.7.0 and the package tibble in version 3.0.0. 

The following example shows, that the highcharter Version is not fully compatible with this tibble version. It uses a deprecated function. 

In our project we use mainly the tibble package and the highcharter package. 
It would be awesome if this could be fixed, otherwise we will run into major problems if the next update of the tibble package comes around. 

```
library(highcharter)
library(tibble)
hc <- highchart()
dataset <- tibble(
  name = c("5", "1", "1", "1", "3", "2"),
  y = c(1, 2, 1, 3, NA, 10)
)

hc <- hc %>% 
  hc_add_series(
    name = 'Titel',
    type = 'spline',
    data = dataset,
    yAxis = 1,
    dataLabels = list(enabled = FALSE) # NOTE if the Numbers on the Line are  supposed to be shown, set this to True 
  ) 
```

This gives us the following error message: 

```
 Warning message:
  `as_data_frame()` is deprecated as of tibble 2.0.0.
 Please use `as_tibble()` instead.
 The signature and semantics have changed, see `?as_tibble`.
 This warning is displayed once every 8 hours.
 Call `lifecycle::last_warnings()` to see where this warning was generated. 
```

And last but not least: The Package version we have installed: 

```
pkgs <- as.data.frame(installed.packages(), stringsAsFactors = FALSE, row.names = FALSE)

# > pkgs[c(131, 48) , c("Package", "Version", "Built")]
# Package Version Built
# 131      tibble   3.0.0 3.6.3
# 48  highcharter   0.7.0 3.6.3
```

**Comment by jbkunst** [comment]
Hi @Anna-DB 

I see the a *warning* message, not an *error* one.

The deprected funcion were removed. The CRAN release will be soon.

Thanks and regards.
