### ISSUE TITLE
`hw_grid()` no longer working in 0.7

### ISSUE THREAD

**Issue by uvedhe** [jbkunst/highcharter#622]
I just discovered that code using `hw_grid()` no longer works since upgrading my `highcharter` version to `0.7.0.9001`

When running the code below, all plots are rendered in 1 column, seemingly ignoring the input for `ncol`:

```
library(highcharter)
library(htmltools)

x <- hchart(data.table::data.table(a=c(1:5),b=c(1:5)), type='column', hcaes(x=a,y=b))
lst <- list(x,x,x,x)
hw_grid(lst, rowheight = 300, ncol = 2) %>% browsable()
```

Is this indeed a bug?

Full specs:
- highcharter_0.7.0.9001 / htmltools_0.4.0
- R 3.5.3
- RStudio 1.2.5033
- macOS 10.15.4

**Comment by uvedhe** [comment]
Hi @jbkunst , would you know what causes this in `highcharter 0.7.0`? Is it linked to the bug in "Grouped Categories" ([https://github.com/jbkunst/highcharter/issues/620](url))?

**Comment by nordicgit70** [comment]
With above sample code it generates HTML including div for each widget with class ´class="col-1-2 mobile-col-1-1"`, but the page source is missing the styles to layout the grid.

![image](https://user-images.githubusercontent.com/22841797/86812189-037b1900-c07f-11ea-949d-9bae55ecd0b0.png)

**Comment by hdrab127** [comment]
Hey see this thread (https://github.com/jbkunst/highcharter/issues/549#issuecomment-549363361) you can get the old functionality by chaing `hc_add_dependency("css/htmlwdgtgrid.css")` to your hchart declaration

**Comment by uvedhe** [comment]
Thanks @hdrab127 for your response! Unfortunately I cannot seem to get that to work, I think because I'm looping over a list to create multiple graphs (hence the use of `hw_grid`). Here's a truncated version of my code:

```
# Loop over all factors to create a plot for each
list_of_graphs <- lapply(factors, function(this_factor){
  # do some data wrangling
  highchart() %>%
          hc_add_series( ...data stuff etc. the graphs plot fine so the problem shouldn't be here... )
}

# Render graphs
output$gridPlots <- renderUI({
      # Put all plots in a grid
      hw_grid(list_of_graphs, 
              rowheight = 300, ncol = 2) %>% 
                browsable()
})
```

I've tried adding `hc_add_dependency("css/htmlwdgtgrid.css")` in various places, all to no avail: 

- chained after `hc_add_series` (result: no graphs show up, no error thrown)
- chained after the trailing `}` of `list_of_graphs` (result: `Error in hw_grid: All parameters must be htmlwidget objects`)
- chained after `hw_grid()` (result: graphs are plotted but like before, in 1 column)

Not sure how else to get this to work? Or should I adapt the path to the `css` file somehow?

Thanks so much for your help!!

**Comment by hdrab127** [comment]
Ahh you're right sorry!

Something might have changed with the `htmltools` package and the `src` arg to `htmlDependency` no longer accepts css so we now have to use `stylesheet`?

You can get around this for now by overwriting the `hc_add_dependency` function with this version (will work on a pull request to add it later):

```
hc_add_dependency <- function (hc, name = "plugins/annotations.js"){
  stopifnot(!is.null(name))
  yml <- system.file("htmlwidgets/highchart.yaml", package = "highcharter")
  yml <- yaml::yaml.load_file(yml)[[1]]
  hc_ver <- purrr::map_chr(yml, c("version"))[purrr::map_chr(yml, c("name")) == "highcharts"]
  name_src <- c(file = system.file(sprintf("htmlwidgets/lib/highcharts-%s/%s", 
                                           hc_ver, 
                                           dirname(name)), 
                                   package = "highcharter"))
  if (grepl('\\.css$', basename(name))) {
    dep <- htmlDependency(name = basename(name), 
                          version = hc_ver, 
                          src = name_src,
                          stylesheet = basename(name))
  } else {
    dep <- htmlDependency(name = basename(name), 
                          version = hc_ver, 
                          src = name_src,
                          script = basename(name))
  }
  hc$dependencies <- c(hc$dependencies, list(dep))
  hc
}
```

And yep, it should be option 1 - chained after the `hc_add_series`

**Comment by jbkunst** [comment]
Hi @uvedhe  @nordicgit70 @hdrab127 

Yeah,  as @hdrab127  says, I made a big mistake trying using the `hc_add_dependency ` function because only works with js script and no css files. Sorry about that.

In  a088dfd , the function was modify  to add the `htmlwdwtgrid.css` automatically so you don't need use the `hc_add_dependency ` function. Additionally `hw_grid` gain a new parameter `browsable` -set as TRUE the default value- so now there is no need to use `htmltools::browsable` 

```r
library(highcharter)
x <- hchart(data.table::data.table(a=c(1:5),b=c(1:5)), type='column', hcaes(x=a,y=b))
lst <- list(x,x,x,x)
hw_grid(lst, rowheight = 300, ncol = 2)
```

![image](https://user-images.githubusercontent.com/56481/87614209-69018200-c6dd-11ea-898e-87fbd4d03374.png)
