### ISSUE TITLE
dateTimeLabelFormats not working as expected with R

### ISSUE THREAD

**Issue by MERE55** [jbkunst/highcharter#624]
Was trying to format dates on x axis and expected the dates being displayed like 20.04.2020 but 20. Apr is displayed instead.
See attached data, R code and resuting html file
[MERE55.zip](https://github.com/jbkunst/highcharter/files/4641137/MERE55.zip)

**Comment by nordicgit70** [comment]
TB's [Cookbook](https://www.tmbish.me/lab/highcharter-cookbook/) has a good example on how to use `dateTimeLabelFormats`.

**Comment by MERE55** [comment]
> TB's [Cookbook](https://www.tmbish.me/lab/highcharter-cookbook/) has a good example on how to use `dateTimeLabelFormats`.

Thx a lot for this advise - this cookbook looks great and I certainly will have to go through it !!!

**Comment by nordicgit70** [comment]
Please close the issue if it has been answered/resolved.

**Comment by MERE55** [comment]
> Please close the issue if it has been answered/resolved.

Looks, like this is still not what I was looking for : 
using hc_tooltip(xDateFormat = "%d.%m.%Y") the date is displayed like I wanted it, e.g. 20.04.2020
using hc_xAxis(type = "datetime", dateTimeLabelFormats = list(day = "%d.%m.%Y")) for the x axis it is displayed as 20. Apr
I would rather also display the date as in the tooltip.
Besides that when displaying the month in character format I would rather display the German name of the month

Therefore - unfortunately - my issue is still not solved

**Comment by nordicgit70** [comment]
Adding your date format to the Highcharts [fiddle ](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/xaxis/datetimelabelformats/) generates the correct date format. So it could be a bug in Highcharter. I will look into it.

@jbkunst, do you know languages can be set?

**Comment by nordicgit70** [comment]
The `dateTimeLabelFormats` is correctly added to the xAxis. It requires that the format is specified for the correct scale. In the sample i used the weather data and setting format for `day` has no effect as the chart displays labels for `month`.

```
weather %>% hchart("line", hcaes(x = date, y = mean_temperaturec)) %>% hc_xAxis(type = "datetime", dateTimeLabelFormats = list(month = "%d.%m.%Y"))
```

![image](https://user-images.githubusercontent.com/22841797/87127757-bec5cc80-c28e-11ea-97aa-b6bc9f934313.png)

**Comment by MERE55** [comment]
> The `dateTimeLabelFormats` is correctly added to the xAxis. It requires that the format is specified for the correct scale. In the sample i used the weather data and setting format for `day` has no effect as the chart displays labels for `month`.
> 
> ```
> weather %>% hchart("line", hcaes(x = date, y = mean_temperaturec)) %>% hc_xAxis(type = "datetime", dateTimeLabelFormats = list(month = "%d.%m.%Y"))
> ```
> 
> ![image](https://user-images.githubusercontent.com/22841797/87127757-bec5cc80-c28e-11ea-97aa-b6bc9f934313.png)

changing dateTimeLabelFormat to list(month = "%d.%m.%Y) instead of list(day = "%d.%m.%Y) doesn't change the date displayed on the x axis. It still doesn´t show the date in the format dd.mm.YYYY

**Comment by nordicgit70** [comment]
On your date set with COVID data the scale should be `week`. As I explained the format must be set for the scale used by the chart. Check the Highcharts API for more details.

![image](https://user-images.githubusercontent.com/22841797/87241414-2dd42a00-c423-11ea-94ad-49f4282a7140.png)

BTW to use your data the date and numeric formats have to be adjusted.
```
r0$Date <- as.Date(r0$Date, format = "%d.%m.%Y")
r0$R <- as.numeric(sub(",", ".", r0$R, fixed = TRUE))
```

**Comment by MERE55** [comment]
> On your date set with COVID data the scale should be `week`. As I explained the format must be set for the scale used by the chart. Check the Highcharts API for more details.
> 
> ![image](https://user-images.githubusercontent.com/22841797/87241414-2dd42a00-c423-11ea-94ad-49f4282a7140.png)
> 
> BTW to use your data the date and numeric formats have to be adjusted.
> 
> ```
> r0$Date <- as.Date(r0$Date, format = "%d.%m.%Y")
> r0$R <- as.numeric(sub(",", ".", r0$R, fixed = TRUE))
> ```

I already use the date and numeric formatting like you suggested - but thx for that advise !!
When using 'week' the date is finally displayed in the format I wanted :-)
But how could I achieve to display the labels only once or twice a month to have it more readable ?
And : why does the 'week' parameter accept the format but not the 'month' parameter ?

**Comment by MERE55** [comment]
Perhaps another interesting input (formatting of date labels for me not quite logical) 
See the 3 attached screenshots, one after viewing the html-File fullscreen in the browser, one after shrinking browser window and one after fullscreen right after the shrinking one.
![20200712_R0_FullscreenAfterSmallerScreen](https://user-images.githubusercontent.com/62344783/87244835-8fef5800-c440-11ea-904c-86a63b4bc642.png)
![20200712_R0_SmallerScreen](https://user-images.githubusercontent.com/62344783/87244836-91208500-c440-11ea-83e0-1322a3bdd974.png)
![20200712_R0_FullscreenAfterCall](https://user-images.githubusercontent.com/62344783/87244837-91208500-c440-11ea-8a72-37a34fc16082.png)

**Comment by nordicgit70** [comment]
The behavior is as expected. Highcharts Javascript adjusts the scale on the axis depending on the size of the data and the size of the chart. As can be seen in the samples you created. it can be required that multiple formats should be set to control different scales.

Highcharts API is well documented, and a valuable source of information for more control over the layout of charts.

**Comment by MERE55** [comment]
> The behavior is as expected. Highcharts Javascript adjusts the scale on the axis depending on the size of the data and the size of the chart. As can be seen in the samples you created. it can be required that multiple formats should be set to control different scales.
> 
> Highcharts API is well documented, and a valuable source of information for more control over the layout of charts.

Thx a lot for our explanations -in that case I will close this item now :-)
