### ISSUE TITLE
Highcharter not picking up category or datetime axes properly

### ISSUE THREAD

**Issue by elbamos** [jbkunst/highcharter#638]
I'm not sure whether this is caused by a change in a dependency or what, but highcharter, at least with heatmaps, is not picking up axis types properly. 

Here is an example:

```
tstframe <- expand_grid(state = state.name, dt = seq(from=ymd("2020/1/1"), to=ymd("2020/3/30"), by=1)) %>% 
  mutate(val = runif(n = n(), min=0, max=100))

highchart() %>% 
  hc_xAxis(type="datetime") %>%
  hc_yAxis(type="category") %>% 
  hc_add_series(data=tstframe, 
                type="heatmap", 
                hcaes(x=dt, y=state, color=val))
```

Instead of the expectation - the x axis should  show datetimes from 1/1/2020 to 3/30/2020, the y-axis should show the names of states, I get numeric labels on the y axis, and the x axis seems to think days are miliseconds:

![image](https://user-images.githubusercontent.com/10103420/85650921-72a64580-b65b-11ea-996d-56aed463c041.png)

**Comment by nordicgit70** [comment]
The heatmap can be correctly generated with: `hchart(tstframe, "heatmap", hcaes(x = dt, y = state, color = val))` (see also sample [showcase](http://jkunst.com/highcharter/showcase.html)).

The difference that `hchart` calls a function `data_to_options` to add chart options for the axes. This function is not called by `hc_add_series`.  Categories can be added with the below code.

```
highchart() %>% 
   hc_xAxis(type="datetime", categories = levels(as.factor(tstframe$dt))) %>%
   hc_yAxis(type="category", categories = levels(as.factor(tstframe$state))) %>% 
   hc_add_series(data=tstframe, 
      type="heatmap", 
      hcaes(x=dt, y=state, color=val))
```
