### ISSUE TITLE
Highcharts module 7.2.0 version are no longer available

### ISSUE THREAD

**Issue by FlyImagi** [jbkunst/highcharter#639]
This is an Open issue continue from this issue (https://github.com/jbkunst/highcharter/issues/567), that The command `devtools::install_github("jbkunst/highcharter", ref = "720")` to get to the development branch is now no longer available, can it be updated again?

```
Downloading GitHub repo jbkunst/highcharter@720
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/jbkunst/highcharter/tarball/720'
```

Cannot display Dependency Wheel chart correctly by now.

I posted this issue also in https://stackoverflow.com/questions/62512552/highcharter-dependency-wheel-not-showing-up/62518590?noredirect=1#comment110585636_62518590

**Comment by nordicgit70** [comment]
The [readme ](https://github.com/jbkunst/highcharter/blob/master/dev/readme.md) in the development folder explains how to use a custom version of Highcharts.
