### ISSUE TITLE
Highcharter not picking datetime axes properly

### ISSUE THREAD

**Issue by mostafaRifi** [jbkunst/highcharter#640]
I'm developping a shiny application with some highcharter graphics but I'm facimg some issues ...
I created a a stackoverflow question here : https://stackoverflow.com/questions/62451813/why-highcharter-give-random-plot-date-x-axis
Thanks for help

**Comment by nordicgit70** [comment]
Commented on stackoverflow. IMO, not a bug. Can this be closed?
