### ISSUE TITLE
Use zones independently of series

### ISSUE THREAD

**Issue by AGrosserHH** [jbkunst/highcharter#647]
HI all,

I am trying to create a chart with two series and combine it with the plotOptions zones command. However, I want to apply the zones coloring only to one series (with the name 'Change'). Is there already an option to use it as intended? Here would be my code which I am using.

    highchart() %>%
        hc_chart(type = "bar") %>%
        hc_plotOptions(column = list(zones = list(list(value = 0,
                                                   color = ('#f30020')),
                                              list(color = ('#17b003'))))) %>%
        hc_xAxis(categories = factors_df$`Factor Group`) %>%
        hc_yAxis( visible = FALSE ) %>%
        hc_add_series(name ="OriginalScore", factors_df, "column", hcaes(x = `Factor Group`, y = `Original Score`),
                  color = color_main) %>%    
        hc_add_series(name ="Change", factors_df, "column", hcaes(x = `Factor Group`, y = `+/-`, naming = `Factor Group` ),    
                  dataLabels = list(enabled = TRUE,
                                    inside = TRUE,
                                    align = "right",
                                    format= '{point.y:,.2f}',
                                    style = list(fontSize = '.7em',color = '#fff')) ) %>%
         hc_legend(enabled = FALSE)

**Comment by nordicgit70** [comment]
Implemented according the [Highcharts API fiddle ](https://api.highcharts.com/highstock/plotOptions.series.zones) zones work.

```
highcharter::highchart() %>% hc_add_series(data = list(-10, -5, 0, 5, 10, 15, 10, 10, 5, 0, -5), zones = list(list(value = 0, color = '#f7a35c'), list(value = 10, color = '#7cb5ec'), list(color = '#90ed7d')))
```
![image](https://user-images.githubusercontent.com/22841797/88415406-bc12bd80-cdde-11ea-93ed-295f0c20b25d.png)
