### ISSUE TITLE
Bug in Heatmap if grouped categories in use

### ISSUE THREAD

**Issue by Dave-stat** [jbkunst/highcharter#648]
First of all a big thanks for this package. You made life easy for R programmers who want to design beautiful web app. 

I am trying to create heatmap with grouped categories in X axis. Code works partially but it returns the labels of x axis in wrong position. **For example : Egypt 1952 should have 1418 but the code posted here returns 2444 which is a value of Bulgaria.** It always take X axis in ascending order of text and then map coordinates in X and Y axis. Coordinates should change when grouped categories in effect.

```
library(gapminder)
library(highcharter)
library(dplyr)
set.seed(100)
x_country = sample(gapminder$country,20)

dat<- select(gapminder, continent, country, year, gdpPercap) %>%
  filter(country %in% x_country)
dat=droplevels(dat)

categories_grouped <- dat %>%
  distinct(continent,country) %>% 
  rename( name =continent) %>%
  group_by(name) %>%
  do(categories = .$country) %>% 
  list_parse()

highchart() %>%
  hc_yAxis(categories = dat$year) %>%
  hc_xAxis(categories = categories_grouped) %>%
  hc_add_series(data = dat,type = 'heatmap',hcaes(x=country,y=factor(year),value=gdpPercap)) %>% 
  hc_colorAxis(minColor = "#FFFFFF", maxColor = "#434348")

It can be seen in JSON
`toJSON(hc$x$hc_opts, auto_unbox = TRUE, pretty = TRUE)
`
```

**Comment by jbkunst** [comment]
Hi  @Dave-stat !

Grouped categories plugin is not included by deafult. So:

```r
highchart() %>%
  hc_yAxis(categories = dat$year) %>%
  hc_xAxis(categories = categories_grouped) %>%
  hc_add_series(data = dat,type = 'heatmap',hcaes(x=country,y=factor(year),value=gdpPercap)) %>% 
  hc_colorAxis(minColor = "#FFFFFF", maxColor = "#434348") %>% 
  hc_add_dependency("plugins/grouped-categories.js")
```
![image](https://user-images.githubusercontent.com/56481/87835430-18179800-c85b-11ea-8574-ada1c3d7c537.png)

Kind regards.

**Comment by Dave-stat** [comment]
Thanks. I am getting the similar output. I think I didn't explain the issue properly. Values (i.e. gpdPercap) are being shown against wrong countries. For example - Egypt in year 1952 should have value gpdPercap 1418 but the code returns 2444 which is a gpdPercap of Bulgaria. I added data labels in the code for your reference.

```
highchart() %>%
  hc_yAxis(categories = dat$year) %>%
  hc_xAxis(categories = categories_grouped) %>%
  hc_add_series(data = dat,type = 'heatmap',hcaes(x=country,y=factor(year),value=round(gdpPercap,0)),
                dataLabels = list(enabled = TRUE)) %>% 
  hc_colorAxis(minColor = "#FFFFFF", maxColor = "#434348") %>% 
  hc_add_dependency("plugins/grouped-categories.js")

```

**Comment by Dave-stat** [comment]
Got it. It's important to sort and factor before using grouped category.
```
dat <- dat %>% arrange(continent) %>% 
  mutate(country = as.character(country),
         country = factor(country, levels = unique(country)))
```
