### ISSUE TITLE
HighChart: Different Data source in Hc_ToolTip than what is used in X and Y Axis

### ISSUE THREAD

**Issue by munishkgitbub** [jbkunst/highcharter#649]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

Brief description of the problem
I want to use different data source while building hc_tooltip in my Line type Highchart. Its a custom tool tip. So just to summarize in case I am using **dataSource1** in my hc_add_series like this highchart() %>% hc_add_series(**dataSource1** ), I would like to bring data from dataSource2 during  hc_tooltip. Is it possible even? Will really appreciate a response.

```r
# insert reprex here
```

**Comment by jbkunst** [comment]
> Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on https://stackoverflow.com/ or https://community.rstudio.com/.

You can pre join the dataSource1 and dataSource2 adding the info for your custom tooltip.
