### ISSUE TITLE
Coloredarea charts not working

### ISSUE THREAD

**Issue by SreejaSN** [jbkunst/highcharter#651]
Hi, 

I'm having issues making a coloredarea chart using the new version of highcharter. I downgraded to 0.7.0 and this code works. Is this an issue with the HighchartsJS itself? Thanks!

```r
colors <- c("#000004", "#3B0F70", "#8C2981", "#DE4968", "#FE9F6D", "#FCFDBF")

df <- tibble(
  x = 1:6,
  y = x*3,
  segmentColor = colors
)

hchart(df, type = "coloredarea", hcaes(x = x, y = y, segmentColor = segmentColor))
```

**Comment by jbkunst** [comment]
Hi @SreejaSN,
 
In 0.8.2 you need add the module/plugin to enable this feature because doesn't come by default. More details in https://jkunst.com/highcharter/articles/modules.html#colored-area-and-colored-line-1 

```r
hchart(df, type = "coloredarea", hcaes(x = x, y = y, segmentColor = segmentColor)) %>% 
  hc_add_dependency("plugins/multicolor_series.js")
```

Kind regards,
