### ISSUE TITLE
`hc_tooltip(shared = TRUE)` not working

### ISSUE THREAD

**Issue by wolfeclw** [jbkunst/highcharter#652]
I just downloaded the new CRAN version, and `hc_tooltip(shared = TRUE)` yields the same results when set to `FALSE`. I would expect that when the argument is set to `TRUE`, the different groups (year) would not highlight when hovering over a point in that series.  I was using the old CRAN version previously, so it is possible I missed something between all the development versions.

I am currently using R 4.0.0.

```r
library(tidyverse)

#same results
hchart(mpg, "point", hcaes(x = displ, y = cty, group = year)) %>% hc_tooltip(shared = FALSE)

hchart(mpg, "point", hcaes(x = displ, y = cty, group = year)) %>% hc_tooltip(shared = TRUE)

```

**Comment by jbkunst** [comment]
Hi @wolfeclw 

According to the official docs https://api.highcharts.com/highcharts/tooltip.shared

> When the tooltip is shared, the entire plot area will capture mouse movement or touch events. Tooltip texts for series types with ordered data (**not pie, scatter, flag**s etc) will be shown in a single bubble. This is recommended for single series charts and for tablet/mobile optimized charts.

```r
highcharts_demo()

# different result
highcharts_demo() %>% 
  hc_tooltip(shared = TRUE)
```

**Comment by wolfeclw** [comment]
Thanks @jbkunst for the quick reply.  After some digging, I found a solution for what I actually needed.  I was trying to stop the other series from fading when hovering on a specific series in the scatterplot (i.e. disabling the inactive state).  The following code achieves that:

```r
hchart(mpg, "point", hcaes(x = displ, y = cty, group = year)) %>%
     hc_plotOptions(series = list(states = list(inactive = list(opacity = 1))))
```
