### ISSUE TITLE
hc_size function note work at render time properly

### ISSUE THREAD

**Issue by MilindShingote** [jbkunst/highcharter#654]
i Want to reduce size of funnel in plotoutput because labels of funnel not showing properly. i have attached output window.

file:///C:/Users/Selectigence/AppData/Local/Temp/RtmpwBK56v/reprex186872ed18b5/reprex_reprex.html
![Funnel](https://user-images.githubusercontent.com/57298505/89098034-bd0ca600-d401-11ea-84fc-b0dc993e73d8.jpg)

**Comment by jbkunst** [comment]
Hi @MilindShingote 

The hc_size control the size of the widget. Not the series (funnel, a line, etc) you can use the `width` argument o try control the lables.

Could you share a reprex?

You can check an example and how parameters work in  https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/funnel/ . Try modify the `width` value to  '50%' and click the _play_ button.

Thanks
