### ISSUE TITLE
hcaes - 'stack' option

### ISSUE THREAD

**Issue by DavidPatShuiFong** [jbkunst/highcharter#655]
Would like to reproduce the [multiple stacked bar chart example on stackoverlow](https://stackoverflow.com/questions/54651243/r-highcharts-multiple-stacked-bar-chart/54657354) using 'long' data rather than 'wide' data

(using `highcharter` 0.7.0 or 0.8.2)

The desired result looks like 
![image](https://user-images.githubusercontent.com/8335820/89470068-37507800-d7be-11ea-954f-8438b5e0a229.png)

An example of 'long' data to reproduce this with `hchart` and `hcaes` might look like:

```r
bs.frame <- data.frame(
  data = c(13637344, 14075507, 14578093, 10911628, 10680998,
           13078654, 12772388, 14226181, 10205708, 10950779,
           9376243, 8895126, 9715914, 9810157, 13493110,
           5075985, 4963856, 5992229, 8859263, 4094183),
  date = rep(as.Date(c("2013/12/1", "2014/12/1", "2015/12/1", "2016/12/1", "2017/12/1")), 4),
  group = c(rep("Non Current Assets", 5), rep("Current Assets", 5),
            rep("Non Current Liabilities", 5), rep("Liabilities", 5)),
  stack = c(rep("Assets", 10), rep("Liabilities", 10))
)

hchart(bs.frame, type = "bar", hcaes(x = date, y = data, group = group, stack = stack )) %>%
  hc_plotOptions(bar = list(stacking = "normal"))
```

... but the `stack` option does not work.

I *can* convert this 'long' data to 'wide' data with code like ...

```r
new.frame <- bs.frame %>% 
  dplyr::select(date) %>% 
  dplyr::distinct() %>% 
  dplyr::arrange(date)
stacks.list <- list()
for (i in unique(bs.frame$stack)) {
  partial <- bs.frame %>% 
    dplyr::filter(stack == i) %>% 
    dplyr::select(data, date, group)
  new.frame <- new.frame %>% 
    dplyr::left_join(
      tidyr::pivot_wider(partial, values_from = data, names_from = group))
  for (j in unique(partial$group)) {
    stacks.list[[j]] <- i
  }
}
``` 

... and then plot with ...

```r
x <- highchart() %>%
  hc_chart(type = "bar") %>%
  hc_plotOptions(bar = list(stacking = "normal")) %>%
  hc_xAxis(categories = new.frame$date)

for (i in names(stacks.list)) {
  x <- x %>%
    hc_add_series(name = i, data = new.frame[[i]], stack = stacks.list[[i]])
}

x
```

... but since it was easier to create and manipulate the data 'long', I'd rather keep it that way!

**Comment by jbkunst** [comment]
Hi @DavidPatShuiFong
 
Thanks for the reprex. 

`stack` is a series argument, no a "point" one. So, this argument goes outside `hcaes`.

```r
hchart(
  bs.frame, 
  type = "bar", 
  hcaes(x = date, y = data, group = group),
  stack = dplyr::distinct(bs.frame, group, stack)$stack
) %>%
  hc_plotOptions(
    bar = list(stacking = "normal")
  )
```

Maybe you'll need some order in the `dplyr::distinct(bs.frame, group, stack)$stack` due the levels/factor but that is the idea.

Hope it helps.

See this comment https://github.com/jbkunst/highcharter/issues/627#issuecomment-665044279 for a little more detailed information.

**Comment by DavidPatShuiFong** [comment]
Thanks, you are so awesome!

I think this modification gets the `stack` in the same order as in the original data.frame (which is factorized...)

```r
hchart(
  bs.frame, 
  type = "bar", 
  hcaes(x = date, y = data, group = group),
  stack = (dplyr::distinct(bs.frame, group, stack) %>%
             dplyr::arrange(group) %>%
             dplyr::pull(stack))
) %>%
  hc_plotOptions(
    bar = list(stacking = "normal")
  )
```
