### ISSUE TITLE
How to change bar color (one group only has one term)?

### ISSUE THREAD

**Issue by wangshisheng** [jbkunst/highcharter#656]
This is my first time to use highcharter package. Could someone tell me how to change the bar color? I have googled this question, but not find the answer. Thanks a lot.

```r
df <- data.frame(dose=c("D0.5", "D1", "D2"),
                len=c(4.2, 10, 29.5))
df %>% 
  hchart(
  'bar', hcaes(x = dose, y = len, color = dose)
  )
```

Because one group only has one term here, if I add color as below:

```r
df <- data.frame(dose=c("D0.5", "D1", "D2"),
                len=c(4.2, 10, 29.5))
df %>% 
  hchart(
  'bar', hcaes(x = dose, y = len, color = dose),
  color=c("blue","green","red")
  )
```

It displays three same items in one group. So strange!

Bests,
Shisheng

**Comment by jbkunst** [comment]
Hi @wangshisheng 

Try with the next code and tell me if this what you need.

```
df %>% 
  hchart(
    'column', 
    hcaes(x = dose, y = len, group = dose)
  ) %>% 
  hc_colors(c("blue","green","red"))

```

**Comment by wangshisheng** [comment]
Hi @jbkunst

Thanks a lot. It works! But the new question comes that the bars are not in the middle position, as below:
![image](https://user-images.githubusercontent.com/19953005/90327414-e9a9eb80-dfc5-11ea-9490-e3c6b6f5f7a3.png)
