### ISSUE TITLE
Remotes installation failed

### ISSUE THREAD

**Issue by AGrosserHH** [jbkunst/highcharter#659]
HI all, 
I am using R 3.4.3 and I am trying to install the latest highcharter version but my system is constantly fail and I do not know why.

Here is my code

     remotes::install_github("jbkunst/highcharter")
     Downloading GitHub repo jbkunst/highcharter@master
     Skipping 4 packages ahead of CRAN: data.table, dplyr, igraph, R6
     Installing package into ‘C:/Users/.../Documents/R/win-library/3.4’
     (as ‘lib’ is unspecified)
     * installing *source* package 'highcharter' ...
     ** R
     ** data
     *** moving datasets to lazyload DB
     ** inst
     ** preparing package for lazy loading
     Error : object 'all_of' is not exported by 'namespace:dplyr'
     ERROR: lazy loading failed for package 'highcharter'
     * removing 'C:/Users/.../Documents/R/win-library/3.4/highcharter'
     * restoring previous 'C:/Users/.../Documents/R/win-library/3.4/highcharter'
     In R CMD INSTALL
     Warning messages:
     1: running command '"C:/PROGRA~1/MIE74D~1/ROPEN~1/R-34~1.3/bin/x64/R" CMD INSTALL -l     "C :\Users\...\Documents\R\win-library\3.4" "C:/Users/.../AppData/Local/Temp/RtmpUhPbEY/remotes115c76501dd8/jbkunst-    highcharter-3060b3c"' had status 1 
     2: In i.p(...) :
       installation of package ‘C:/Users/.../AppData/Local/Temp/RtmpUhPbEY/remotes115c76501dd8/jbkunst-highcharter-    3060b3c’ had non-zero exit status

What do I make wrong?

Thanks!

**Comment by jbkunst** [comment]
Hi @AGrosserHH  

Can you update dplyr package and then try again please?
