### ISSUE TITLE
Facet grid layout

### ISSUE THREAD

**Issue by Yang-Tang** [jbkunst/highcharter#66]
Is there any way to show multiple highcharts in facet grid layout?

**Comment by jbkunst** [comment]
Hi @Yang-Tang , 

Sadly highcharts dont have a facet implementation like [taucharts](http://rpubs.com/hrbrmstr/taucharts) or plotly.

You can implement kind of facet for y axis like http://jkunst.com/highcharter/hchart.html#seasonal-decomposition-of-time-series-by-loess, but there no way to create more x axis.

If you're ok, we can close this issue.

Thanks ;)

**Comment by haozhu233** [comment]
Hi @jbkunst,

In fact, I find myself have some difficulties on understanding the underline mechanism when you use `hchart()` to draw the seasonal decomposition of time series. I want to build some similar facets of time series data but they are not coming from the  `stl()` function. Is there a way to get around that?

Thanks!

**Comment by jbkunst** [comment]
Hi @haozhu233 

Basically, the code from `hchart.stl()` was based on the [candlestick-volume](http://www.highcharts.com/stock/demo/candlestick-and-volume) example from highcharts.

You have to work/play with the yAxis to create many xAxis as you need taking care of the `top`and `height` arguments:
```
yAxis: [{
	height: '60%'
}, {
	top: '65%',
	height: '35%',
	offset: 0
}]
```

Then add each (ts) series to each yaxis. 

Hope I was clear :D.

**Comment by haozhu233** [comment]
Excellent! @jbkunst , thank you for this short but right-to-the-point instruction! I will play around with it. :)

**Comment by jbkunst** [comment]
@Yang-Tang , @haozhu233 ,

Im just implemented a grid function `hc_grid` to display highchart like faceting. Take a look please: http://rpubs.com/jbkunst/higcharter-grid-test

**Comment by haozhu233** [comment]
Excellent! Thanks!! @jbkunst

**Comment by Yang-Tang** [comment]
That's great! Thanks! @jbkunst

**Comment by svarn27** [comment]
How is this incorporated into a shiny app? My test app below. I know the issue lies with the browsable function converting the object to HTML but if I remove, still does not work.

```
library(purrr)
library(highcharter)
library(htmltools)
library(shiny)

data(diamonds, package = "ggplot2")
diamonds <- diamonds[-6]

ui <- fluidPage(highchartOutput('hchart'))

server <- function(input,output,session){

output$renderHighchart({

map(names(diamonds), function(x){
  diamonds[[x]] %>% 
    hchart(showInLegend = FALSE) %>% 
    hc_add_theme(hc_theme_smpl()) %>% 
    hc_title(text = x) %>% 
    hc_yAxis(title = list(text = ""))
  }) %>% 
  hw_grid(rowheight = 225, ncol = 3)  %>% browsable()

})
}

shinyApp(ui=ui,server=server)
```

**Comment by jbkunst** [comment]
Hi @svarn27 ,

Use `htmlOutput` and `renderUI` works for me.

```
ui <- fluidPage(htmlOutput('hchart'))

server <- function(input,output,session){
  
  output$hchart <- renderUI({
    
    map(names(diamonds), function(x){
      diamonds[[x]] %>% 
        hchart(showInLegend = FALSE) %>% 
        hc_add_theme(hc_theme_smpl()) %>% 
        hc_title(text = x) %>% 
        hc_yAxis(title = list(text = ""))
    }) %>% 
      hw_grid(rowheight = 225, ncol = 3) 
    
  })
}

shinyApp(ui=ui,server=server)
```

**Comment by svarn27** [comment]
OK great, I'll see how I can incorporate it in that fashion. Thanks a ton, this package is amazing. By far the most powerful/flexible I've come across. Your hard work is much appreciated!

**Comment by charlie86** [comment]
@jbkunst you are the man!

**Comment by rfarouni** [comment]
@jbkunst Can the output be directed to RStudio viewer instead of Shiny?  Can the multiplot  be embedded in a knittr document? 
Thanks

**Comment by jbkunst** [comment]
@rfarouni ,

Yep! It's possible.

In console/rstudio viewer you need to use `browseable` from the `htmltools` package, see https://github.com/jbkunst/highcharter/blob/master/devscripts/hc_grid2.R

In knitr/rmarkdown documents you just use `hw_grid` alone. https://github.com/jbkunst/highcharter/blob/master/devscripts/hc_grid.R

Let me if this work for you ;)!

**Comment by rfarouni** [comment]
Yes it works! Thank you!

**Comment by mcandar** [comment]
Is it possible to use hw_grid function nested? I want to locate my plots in a layout like this

```
1 3 3 3
2 3 3 3
```

two graphs at left and one bigger at right-hand side. Also, I want this pattern to repeat several times as rows. I tried to use hw_grid function in nested forms, but did not make it work.

**Comment by jbkunst** [comment]
@mcandar 

Not sure, but you can try https://github.com/FrancoisGuillem/combineWidgets It supposed to do what you want :sweat_smile:

**Comment by mcandar** [comment]
@jbkunst  thanks! combineWidgets function is also included in manipulateWidget package. They work properly but now I have problems with sizing and adding slider when exporting them as html ... 😄

**Comment by vinoth4stat** [comment]
@jbkunst....

Below page is not found.. Please help..
https://github.com/jbkunst/highcharter/blob/master/devscripts/hc_grid2.R
https://github.com/jbkunst/highcharter/blob/master/devscripts/hc_grid.R

(This is pasted from message "jbkunst commented on Aug 19, 2016" to @rfarouni ....)

Thank You!!!

**Comment by patarol** [comment]
I've found the link your're looking for @vinoth4stat 
In this [link](https://github.com/jbkunst/highcharter/search?q=hw_grid&unscoped_q=hw_grid) you can find the mentioned example!

Plus, if you search for `hw_grid` in the `highcharter` repo you can find a bunch of exaples!

To put side by side `hicharter` graphs you can do something like that:

`htmltools::browsable(hw_grid(h1, h2, ncol = 2, rowheight = 300))` 
where `h1` and `h2` are `hicharter` graphs!
