### ISSUE TITLE
Default minimum value of colour axis in `hc_add_series_map()`

### ISSUE THREAD

**Issue by long39ng** [jbkunst/highcharter#664]
The default minimum value of colour axis in `hc_add_series_map()` is set to `min = 0`:

https://github.com/jbkunst/highcharter/blob/d47a7792577588d0891dfd87a14a60914371e8c3/R/highmaps.R#L76

I think `min = NULL` would be a more appropriate setting, as it would allow for negative values to be displayed correctly on the colour scale as well.

**Comment by jbkunst** [comment]
I think your're right! I'll change that. Thanks!
