### ISSUE TITLE
Question: manual aesthetics scaling 

### ISSUE THREAD

**Issue by JrmFRL** [jbkunst/highcharter#665]
Hi Joshua,
first of all a lot of thanks for this fantastic package. 
I've been deeply in it for 24 hours now and have a small question about the grammar "spirit": 

With ggplot, one principle is that you can define your layers, and then _after that_ adjust aesthetics (e.g. color) values thanks to the `scale_aesthetics_()` family functions. 

Very short example. The values over 0.5 must be red, the values below must be green.
```r
require(ggplot2)
ggplot(data.frame(x = 1:10, y = runif(10)),
       aes(x = x, y = y)) + 
  geom_point(aes(color = (y > 0.5))) + 
  scale_color_manual(values = c("green", "red"))
```
![hc](https://user-images.githubusercontent.com/70572729/91831132-fa07ca80-ec43-11ea-8083-7d99590abbc4.PNG)

With `highcharter`, it seems from my understanding that the colors that we will use must be defined _before_ the layer constructions, like this: 

```r
data.frame(x = 1:10, y = runif(10)) %>%
  mutate(color = colorize(y > 0.5, c("green", "red"))) %>% # the colors are ready before we plot
  hchart("scatter", hcaes(x = x, y = y, color = color))
```

My question is: isn't there any option to adjust the colors after the layer construction with an equivalent of `ggplot2::scale_color_manual()` ? Like :
```r
data.frame(x = 1:10, y = runif(10)) %>%
  hchart("scatter", hcaes(x = x, y = y, color = y > 0.5)) %>%
  # here some hc "scale" function ?
```
It seems not, but I would like to be sure. My researches on the topic on stackoverflow did not help. 

Again, thank you for this package!
Jerome

**Comment by royfrancis** [comment]
Since your colour groups are categorical, I think `hc_colors()` would work.

```
data.frame(x = 1:10, y = runif(10)) %>%
  mutate(grp = ifelse(y > 0.5, T,F)) %>% 
  hchart("scatter", hcaes(x = x, y = y, group=grp)) %>%
  hc_colors(colors=c("green","red"))
```

This doesn't seem to work for continuous variables though.
