### ISSUE TITLE
Error: package or namespace load failed for ‘highcharter’

### ISSUE THREAD

**Issue by wangb08** [jbkunst/highcharter#667]
An error occurred while I library this package. The error message is that：

Error: package or namespace load failed for ‘highcharter’:
 object ‘all_of’ is not exported by 'namespace:dplyr'

How to solve this problem？
Thanks ！

**Comment by jbkunst** [comment]
Hi @wangb08 

Same as #659. Please try updating packages (dplyr).

Thanks

**Comment by wangb08** [comment]
Hi @jbkunst 

Perfect! It can work normally.
Thanks so much!

**Comment by jbkunst** [comment]
@wangb08 

Please, don't forget close the issue!
