### ISSUE TITLE
Missing random_id function!

### ISSUE THREAD

**Issue by SESjo** [jbkunst/highcharter#669]
Hi there,

It seems that on the last version the `random_id` function has simply disappeared whereas still found within the help of the package.

```r
# can get help
?highcharter::random_id()

# cannot run the function
highcharter::random_id()
```
Am I the only one?

**Comment by nordicgit70** [comment]
Hi, the function `random_id()` is an internal function that is not exported.
It can be called with triple-colon `highcharter:::random_id()` (but that is not recommended).
