### ISSUE TITLE
networkgraph without igraph

### ISSUE THREAD

**Issue by robertogilsaura** [jbkunst/highcharter#675]
I'm trying to replicate a simple `networkgraph` directly without igraph, but I don't get my graph ...

highchart() %>%
   hc_chart(type = "networkgraph") %>%
   hc_title(text = 'Title') %>%
   hc_subtitle(text = 'Subtitle') %>%
   hc_plotOptions(networkgraph=list(keys = c('from', 'to'), layoutAlgorithm = list(enableSimulation = TRUE, friction = -0.9))) %>%
   hc_series(dataLabels=list(enabled = TRUE, linkFormat = ''), id = 'tree', data = list(c(1,1), c(1,2), c(2,3), c(1,3)))

Any  suggestion?

Thanks in advance...

**Comment by raf18seb** [comment]
+1

I am getting error 17 (missing networkgraph.js module)
Is the `https://code.highcharts.com/modules/networkgraph.js` module included in Highcharter?

**Comment by madepiet** [comment]
+1

**Comment by federicoamadei** [comment]
Same issue!
I wanted to avoid using igraph and work directly with highcharter.
This is my code:
library(highcharter)

hc <- highchart()%>%
hc_chart(type='networkgraph',marginTop=80)%>%
hc_title(text="Prova")%>%
hc_subtitle(text="Prova2")%>%
hc_plotOptions(
networkgraph = list(
keys = list(
'from','to'
)
)
)%>%
hc_series(
marker=list(
radius=30
),
dataLabels = list(
enabled = TRUE,
linkFormat = '',
allowOverlap = TRUE
),
data = list(
list('Node 1','Node 2'),
list('Node 1', 'Node 3')
)
)
hc

Nothing is displayed afterwards except the graph's title and subtitle

**Comment by cy-james-lee** [comment]
Just to add here that I'm also getting this error. 

I'm on R 4.0.3 and highcharter 0.8.2

Also tried hc_add_dependency("modules/networkgraph.js") but still didn't get any visual except title and subtitle texts.

**Comment by raf18seb** [comment]
FYI @jbkunst (no rush, just calling in case you missed this ticket)

**Comment by jbkunst** [comment]
Hi @robertogilsaura , @cy-james-lee @federicoamadei and @raf18seb 

I'm just added and example of  networkgraph here https://github.com/jbkunst/highcharter/blob/master/dev/examples-charts/networkgraph.R  (https://github.com/jbkunst/highcharter/commit/26bd8a45c0dc858dc0a48652514019c16edd967a)

Sadly, this does not work with `highchart()` / `hchart()` but `highchartzero()` instead. This is beacuse there some conflict with the networkgraph module and the other modules I use by default with highcharter. So you need use the lite version (highchartzero only load highcharts.js) and then add the networkgraph.js module.

```r
data(package = "igraphdata")

data(karate, package = "igraphdata")

df <- igraph::as_data_frame(karate, what = "edges")

str(df)

highchartzero() %>% 
  hc_add_series(
    df, 
    "networkgraph",
    hcaes(from = from, to = to, weight = weight),
    layoutAlgorithm = list(enableSimulation = TRUE)
  ) %>% 
  hc_add_dependency("modules/networkgraph.js")
```
![image](https://user-images.githubusercontent.com/56481/105948488-c5107000-6049-11eb-9be3-f1a8f85530ec.png)

I noticed this plugin have some performances issues, when I tested with over 100 edges the movement is not that smooth as you see in other js libraries. 

Hope it helps.

**Comment by federicoamadei** [comment]
Dear @jbkunst thank you so much for providing this example!
I have tried to implement exactly the same but still i cannot see anything.
do you know what else could cause the problem?

```
 highchartzero() %>% 
      hc_add_series(
        synergy_df, 
        "networkgraph",
        hcaes(from = from, to = to, weight = weight),
        layoutAlgorithm = list(enableSimulation = TRUE)
      ) %>% 
      hc_add_dependency(name = "plugins/networkgraph.js")
```
Again, I see only "Graph title" and the rest is blank :(

best regards,

Federico

**Comment by jbkunst** [comment]
Hi @federicoamadei  

Did you try the development version?

Other thing you can do is check the console. In your web browser press F12. Sometimes the messages give some information about what is going on.

![image](https://user-images.githubusercontent.com/56481/106001241-7802bd00-608e-11eb-9dda-2eae6f1f75cf.png)

**Comment by cy-james-lee** [comment]
@federicoamadei 
Could you try the 2 samples that @jbkunst posted? Do they run okay on your computer?

@jbkunst I'm using CRAN version and your code works.

**Comment by cy-james-lee** [comment]
> Dear @jbkunst thank you so much for providing this example!
> I have tried to implement exactly the same but still i cannot see anything.
> do you know what else could cause the problem?
> 
> ```
>  highchartzero() %>% 
>       hc_add_series(
>         synergy_df, 
>         "networkgraph",
>         hcaes(from = from, to = to, weight = weight),
>         layoutAlgorithm = list(enableSimulation = TRUE)
>       ) %>% 
>       hc_add_dependency(name = "plugins/networkgraph.js")
> ```
> 
> Again, I see only "Graph title" and the rest is blank :(
> 
> best regards,
> 
> Federico

Can you try removing `names =` and just try `hc_add_dependency("modules/networkgraph.js")` ? When I use  `names =`, I get an error.

**Comment by robertogilsaura** [comment]
Hi @federicoamadei @cy-james-lee @jbkunst 
I had same error, not showed anything; I've changed highcharter version to dev version and I get it the chart.

Regards
