### ISSUE TITLE
hc_add_series.list

### ISSUE THREAD

**Issue by jbkunst** [jbkunst/highcharter#68]
Usually I have a data frame which generate various series. So I do something like:
```
dss <- df %>% 
  arrange(name, year) %>% 
  group_by(name) %>% 
  do(dss = list(
    name = first(.$name),
    id = first(.$state),
    data = .[[sprintf("%s_per_100k", varname)]],
    color = ifelse(first(.$name) == "District of Columbia", "red", NA)
  )) %>% 
  .$dss

hc_tms <- highchart() %>%
  hc_chart(...) %>% 
  hc_colors(...) %>% 

hc_tms$x$hc_opts$series <- dss # NO!
hc_tms
```
I will be something like:

```
hc_tms %>% 
   hc_add_series(dss)
```
**where dss is a list of lists**.

**Comment by AKLLaursen** [comment]
I've been doing the same, when writing function wrappers of highcharter plots, where I want the number of series in the plot to be dynamic. Making `hc_add_series()` take a list as an argument would be a very elegant solution.

**Comment by jbkunst** [comment]
Ok, finally I implemented the `hc_add_series_list`. Examples here: http://rpubs.com/jbkunst/hc_add_series_list

Hope it helps.

I was expecting make a method `hc_add_series` (hc_add_series.list, hc_add_series.ts, hc_add_series.string, hc_add_series.numeric), but the problem the **first** argument is the highcarts object and not the type of the data. In the future I'll think how to do this more elegant ;).

**Comment by AKLLaursen** [comment]
Awesome! Thanks a lot for all the good work. Your package is awesome :)
