### ISSUE TITLE
tooltip_chart doesn't recognize date xaxis even when specified

### ISSUE THREAD

**Issue by zac-garland** [jbkunst/highcharter#683]
The below tooltip doesn't render, though I can't think of any reason why. The chart renders properly if you wrap year around date, or convert the date to a numeric, but when you try to specify datetime it doesn't. 

Is this expected? Is there a workaround?

```r
library(tidyverse)
library(gapminder)
library(highcharter)

gapminder <- gapminder::gapminder %>%
  mutate(
    date = paste0(year, "-01-01") %>% lubridate::ymd()
  ) %>%
  select(-year) %>%
  filter(country %in% c("Australia", "Brazil", "Canada", "Italy", "United Kingdom", "United States"))


df <- gapminder %>%
  group_by(country, continent) %>%
  filter(date == max(date, na.rm = TRUE)) %>%
  left_join(
    gapminder %>%
      nest(-country) %>%
      mutate(
        data = map(data, mutate_mapping, hcaes(x = date, y = pop)),
        data = map(data, list_parse)
      ) %>%
      rename(ttdata = data)
  )

df %>%
  hchart("bar", hcaes(country, pop, name = country)) %>%
  hc_tooltip(
    useHTML = TRUE,
    headerFormat = "<b>{point.key}</b>",
    pointFormatter = tooltip_chart(accesor = "ttdata", hc_opts = list(chart = list(type = "line", xAxis = list(type = "datetime"))))
  )



```

**Comment by johnsnow09** [comment]
even I have faced a similar issue:
https://stackoverflow.com/questions/65618347/how-to-create-a-tooltip-chart-in-r-using-highcharter

**Comment by jbkunst** [comment]
Hi @zac-garland 

In your code 

```
head(df$ttdata[[1]], 1)
```

Show that x is coded as text. So you need to transform to a numeric value that represent a date, for this you can use the `highcharter::datetime_to_timestamp` function:

```r
gapminder <- gapminder::gapminder %>%
  mutate(
    date = paste0(year, "-01-01") %>% lubridate::ymd() %>% highcharter::datetime_to_timestamp()
  ) %>%
...
```

Then be careful with the structre of hc_opts argument. `xAxis` is defined outside of `chart` element:

```
df %>%
  hchart("bar", hcaes(country, pop, name = country)) %>%
  hc_tooltip(
    useHTML = TRUE,
    headerFormat = "<b>{point.key}</b>",
    pointFormatter = tooltip_chart(
      accesor = "ttdata",
      hc_opts = list(
        chart = list(type = "line"),
        xAxis = list(type = "datetime")
        )
      )
    )
``` 

With this: 

![image](https://user-images.githubusercontent.com/56481/145665281-fc7d6e0f-13cc-45a6-b16a-5bc9b11c6d04.png)

Obviously in this case would be easy to treat year as a integer value due the data is yearly.

**Comment by zac-garland** [comment]
@jbkunst apologies for the delay! I should have closed this earlier as I found this fix :) but thank you for documenting here and closing.

**Comment by jbkunst** [comment]
@zac-garland  apologies for _my_ delay too!
