### ISSUE TITLE
vignettes not included when installed from CRAN or GitHub

### ISSUE THREAD

**Issue by twkrygowski** [jbkunst/highcharter#689]
This issue was closed in 2016, but installs from both CRAN and GitHub still aren't showing vignettes.  Are there pdf's somewhere or are they shown on a site?  I didn't see them on https://jkunst.com/highcharter/.  Thanks, Tom

**Comment by jbkunst** [comment]
Hi Tom,

Yes. Highcharter don't have CRAN vignettes. All this type of content/examples are on https://jkunst.com/highcharter/articles/, the source files in https://github.com/jbkunst/highcharter/tree/master/vignettes due https://github.com/r-lib/pkgdown search in this folder to make the articles section.

**Comment by twkrygowski** [comment]
Excellent – thanks Joshua.
Regards,
Tom


Thomas W. Krygowski, Ph.D., CFA
Managing Director, Analyst & Portfolio Manager
1919 Investment Counsel, LLC
Office:         (410) 454-3162
