### ISSUE TITLE
Error: package or namespace load failed for ‘highcharter’:  object ‘all_of’ is not exported by 'namespace:dplyr'

### ISSUE THREAD

**Issue by jgabalos** [jbkunst/highcharter#694]
I am seeing this error when loading the highcharter package:

> install.packages("highcharter")
Installing package into ‘C:/Users/jojo/R/win-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/highcharter_0.8.2.zip'
Content type 'application/zip' length 1548972 bytes (1.5 MB)
downloaded 1.5 MB

package ‘highcharter’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\jojo\AppData\Local\Temp\RtmpqY66A0\downloaded_packages
> library(highcharter)
Error: package or namespace load failed for ‘highcharter’:
 object ‘all_of’ is not exported by 'namespace:dplyr'

Tried updating dplyr but still having the same issue.

Thanks.

**Comment by mienaikoe** [comment]
+1 Having the same issue. with R 3.6, dplyr 0.8.3, highcharter 0.8.2

**Comment by daroczig** [comment]
possible duplicate of #680
