### ISSUE TITLE
Chart background turns black when viewing in fullscreen

### ISSUE THREAD

**Issue by jenfly** [jbkunst/highcharter#706]
Hello! I'm using Highcharter (v 0.8.2) to create charts in a Shiny app, and when I use the export menu to view a chart in fullscreen, the background turns black (instead of staying white as expected) which makes the title, axis labels, etc. almost illegible. I haven't been able to find any settings which fix this problem, so I'm wondering if it's a bug?

The expected behaviour I'm trying to achieve is shown [here](https://codepen.io/jenfly/pen/ZEeWyPO) -- when I click the context menu and select "View in full screen", the background stays white when it goes into fullscreen.

Whereas in [this example Shiny app](https://jenfly.shinyapps.io/app-highcharts-test/), when I select "View in full screen", the background turns black. The code for this example is below.

```r
# app.R

library(highcharter)
library(shiny)

ui <- fluidPage(
  h1("Highcharts Test"),  
  highchartOutput("fruits")
)

server <- function(input, output, session){
  
  data <- data.frame(
    fruit = c("apple", "banana", "orange", "pear"),
    count = c(2, 3, 5, 4)
  )
  
  hc_opts <- list(   
    exporting = list(
      enabled = TRUE
    )
  )
  
  output$fruits <- renderHighchart({    
    highchart(hc_opts) %>%
      hc_xAxis(categories = data$fruit) %>% 
      hc_add_series(
        type = "column",
        name = "Count", 
        data = data$count
      ) %>%
      hc_title(text = "Fruits")
  })
}

shinyApp(ui = ui, server = server)
```

Thank you!

**Comment by jbkunst** [comment]
Hi @jenfly !

A possible solution is set the background color to white.

```r
  hc_opts <- list(   
    exporting = list(
      enabled = TRUE
    ),
    chart = list(
      backgroundColor = "white"
    )
  )
```

Kind regards,

**Comment by jenfly** [comment]
Yes, that fixed it for me. @jbkunst thanks so much!
