### ISSUE TITLE
Keyboard navigation (accessibility setting) not working

### ISSUE THREAD

**Issue by jenfly** [jbkunst/highcharter#707]
Hello! I'm using Highcharter (v 0.8.2) to create charts in a Shiny app, and I'm trying to enable the keyboard navigation option for accessibility, but I can't seem to get it working and am wondering if it's a bug?

The expected behaviour I'm trying to achieve is shown [here](https://codepen.io/jenfly/pen/ZEeWyPO) -- when I use the Tab key in the Codepen output, the focus ring goes first to the "something focusable" link, then to the first bar in the chart, where I can use the right arrow to navigate through the bars (allowing a screen reader to read each one, for example), and if I press tab again, it goes to the legend, then to the context menu button, and finally to the generic "Button" I included at the bottom of the page.

Whereas in [this example Shiny app](https://jenfly.shinyapps.io/app-highcharts-test/), when I tab through the page, the keyboard focus goes to the "something focusable" link and then skips the chart entirely and goes to the generic "Button" at the bottom of the page. The code for this example is below:

```r
# app.R

library(highcharter)
library(shiny)

ui <- fluidPage(
  h1("Highcharts Test"), 
  p("Here is ", a(href="#", "something focusable")), 
  highchartOutput("fruits"),
  actionButton("button1", "Button")
)

server <- function(input, output, session){
  
  data <- data.frame(
    fruit = c("apple", "banana", "orange", "pear"),
    count = c(2, 3, 5, 4)
  )
  
  hc_opts <- list( 
    accessibility = list(
      enabled = TRUE,
      keyboardNavigation = list(enabled = TRUE)
    ),  
    exporting = list(
      enabled = TRUE
    )
  )
  
  output$fruits <- renderHighchart({    
    highchart(hc_opts) %>%
      hc_xAxis(categories = data$fruit) %>% 
      hc_add_series(
        type = "column",
        name = "Count", 
        data = data$count
      ) %>%
      hc_title(text = "Fruits")
  })
}

shinyApp(ui = ui, server = server)
```

I also tried modifying the above example by adding `%>% hc_add_dependency("modules/accessibility.js")` to the highchart object, and it caused the bars in the bar chart to disappear (and the keyboard focus still wouldn't go onto the chart at all).

Thank you!

**Comment by batpigandme** [comment]
And here's your example (albeit outside of shiny) working https://rpubs.com/maraaverick/highcharter-fruits-example

**Comment by jenfly** [comment]
Thank you @batpigandme! This does indeed seem to be an issue with Shiny interaction.

**Comment by Tilskot** [comment]
This still seems to be an issue. Has anyone found a solution here? Would be highly appreciated.

**Comment by humoroussmile** [comment]
I recommend checking the following issues and forks:

[https://github.com/jbkunst/highcharter/pull/780](https://github.com/jbkunst/highcharter/pull/780)
[https://github.com/jbkunst/highcharter/issues/755](https://github.com/jbkunst/highcharter/issues/755)
