### ISSUE TITLE
rror: All arguments must be named list

### ISSUE THREAD

**Issue by dawitt11** [jbkunst/highcharter#708]
### VISUALIZING ASSET RETURNS
highchart(type = "stock")%>%
hc_title("Monthly Log Return")%>%
  hc_add_series(asset_Returns[, symbols[1]],
                name = symbols[1])%>%
  hc_add_series(asset_Returns[, symbols[2]],
                name = symbols[2])%>%
  hc_add_series(asset_Returns[, symbols[3]],
                name = symbols[3])%>%
  hc_add_series(asset_Returns[, symbols[4]],
                name = symbols[4])%>%
  hc_add_series(asset_Returns[, symbols[5]],
                name = symbols[5])%>%
  hc_add_theme(hc_theme_flat())%>%
  hc_navigator(enabled = FALSE)%>%
  hc_scrollbar(enabled = FALSE)%>%
  hc_exporting(enabled = TRUE)%>%
  hc_legend(enabled = TRUE)

**Comment by jbkunst** [comment]
hc_title(text = "Monthly Log Return")

**Comment by dawitt11** [comment]
Thank you jbkunst.
