### ISSUE TITLE
date format after using `list_parse` with highcharter

### ISSUE THREAD

**Issue by sdaza** [jbkunst/highcharter#709]
I am trying to create a line plot with a custom tooltip, where the y-axis is a numeric variable, and the x-axis consists of dates. The function `list_parse`  seems to mess up the dates, and I am not able to plot the lines. I know that I can specify all the variables using `hcaes`, but because I am creating plots dynamically (the number of variables and their names change depending on the dataset used), I found the list_parseruseful for that purpose.

Any ideas or suggestions?

```r
library(highcharter)
library(data.table)

df = data.table(
  x = as.Date(c("2021-03-01", "2021-03-02", "2021-03-03", "2021-03-04")),
  y = c(2,4,3,2),
  z = c(4,5,6,3),
  text=c("A","A","A","B"), stringsAsFactors = FALSE)

setorder(df, x)
ds = list_parse(df)

highchart() %>% 
  hc_add_series(data = ds, 
    name = "data.frame data",
    type = "line") %>% 
    hc_xAxis(title = list(text = ''),
        type = 'datetime') %>%
    hc_tooltip(headerFormat = "<b>This is a custom tooltip</b><br>",
             pointFormat = "x: {point.x} <br> y: {point.y} <br> text: {point.text}")
```

**Comment by jbkunst** [comment]
Try 

```r
df$x <- datetime_to_timestamp(df$x)
```

**Comment by sdaza** [comment]
Thanks @jbkunst !
