### ISSUE TITLE
Calling hc_add_series with single value passed to data parameter

### ISSUE THREAD

**Issue by jeromefroe** [jbkunst/highcharter#71]
Hi! Just wanted to start off by saying this is an amazing package! I recently noticed though that when I pass a single value to the `data` parameter in `hc_add_series` the chart does not render that value. I think an example would best demonstrate what I mean. When I call

```
foo <- c(1, 2)
highchart() %>% 
  hc_chart(type = "column") %>%
  hc_add_series(name = "Foo", data = foo)
```
I see the following result:
![image](https://cloud.githubusercontent.com/assets/7217598/14503934/5a747444-0180-11e6-9830-a362ec4c9d3f.png)

If I change foo to contain only one value, as in:
```
foo <- c(2)
highchart() %>% 
  hc_chart(type = "column") %>%
  hc_add_series(name = "Foo", data = foo)
```
The resulting chart does not display any columns:
![image](https://cloud.githubusercontent.com/assets/7217598/14504039/fa6ed908-0180-11e6-919a-6dbdf77929d6.png)

If I wrap foo in a call to `as.list`:
```
highchart() %>% 
  hc_chart(type = "column") %>%
  hc_add_series(name = "Foo", data = as.list(foo))
```
I get a chart with a single column as expected:
![image](https://cloud.githubusercontent.com/assets/7217598/14504043/066ba592-0181-11e6-9825-52cc42ac8ef3.png)

To provide some context, I ran into this issue in a Shiny application where the user had the option of selecting 0 or more values, but if only 1 was selected the value would not appear. Using `as.list` doesn't effect the behavior of the chart when `foo` contains more than one value, as in the first example, so I was able to work around the problem by wrapping my argument to the `data` parameter in `as.list`. This is, of course, a minor issue I just thought I would post in case anyone else runs into the same problem since it caused some head-scratching for me.

**Comment by jbkunst** [comment]
Hi @jeromefroe.

Let me thank you for your kind words :smiley: 

This was discussed in #65. You just found one way to do it. The other one is change the `jsonlite::toJSON` behavior.
```
# 2
options(htmlwidgets.TOJSON_ARGS = list(auto_unbox = FALSE))
highchart() %>% hc_chart(type = "bar") %>% hc_add_series(data = 1)
````

Let me if this helps to you.

**Comment by jeromefroe** [comment]
This is perfect! I'll go ahead and close the issue since there's another that already covers it. Thanks again!
