### ISSUE TITLE
Generate "variable radius pie" chart

### ISSUE THREAD

**Issue by ckntav** [jbkunst/highcharter#710]
Hello,

Thank you for the package, I use it a lot

Is there a way to generate "variable radius pie" with highcharter?

https://www.highcharts.com/demo/variable-radius-pie

Thank you in advance

**Comment by LuShuYangMing** [comment]
And how to rotating dataLabels in a Highcharts pie chart
[https://stackoverflow.com/questions/28248855/rotating-datalabels-in-a-highcharts-pie-chart](url)
