### ISSUE TITLE
highcharts and latex

### ISSUE THREAD

**Issue by JoseCarlosMartinez** [jbkunst/highcharter#711]
Is it possible to include highcharts graphics with rMarkdown in a .pdf document generated with knit to PDF?

**Comment by robertogilsaura** [comment]
What is the problem? No publish or publish part of? Can you send reprex?
-.-.-.-.-
*Roberto Gil Saura  **
<https://www.facebook.com/InvestigaOnline-552640944937849/>
<https://twitter.com/robertogilsaura>
<https://www.linkedin.com/in/robertogilsaura/>*
* <https://www.investigaonline.com/>*
---
Este mensaje y los ficheros anexos que, en su caso, incorpore pueden
contener información confidencial o de uso exclusivamente interno de
investigaonline.com, sujeto a secreto profesional. Si usted lo recibe por
error o considera que no es el destinatario del mismo, debe destruirlo y
comunicar al emisor esta circunstancia, no pudiendo en ningún caso
distribuir, divulgar ni copiar el mensaje.
