### ISSUE TITLE
create_yaxis

### ISSUE THREAD

**Issue by why357** [jbkunst/highcharter#715]
Hi, 

Is it available to add title to multiple y axis? Tried the following code, but it failed.

test <- highchart() %>%
   hc_yAxis_multiples(create_yaxis(naxis = 2, heights = c(2, 1), title = list(text = "Doesn't work"))) %>%
   hc_add_series(data = c(1, 3, 2), yAxis = 0) %>%
   hc_add_series(data = c(20, 40, 10), yAxis = 1)

Thanks in advance,

JW

**Comment by adamivisonnhs** [comment]
I always find this cookbook to be really helpful with most `highcharter` issues.

https://www.tmbish.me/lab/highcharter-cookbook/

In your example, they have some sample code that can be amended to suit your use case. Notably:

```  
hc_yAxis_multiples(
    create_yaxis(
      naxis = 2,                                                       
      heights = c(2, 1),                                            
      title = map(c("title1", "title2"), ~list(text = .)) # Needs a list like: list(list(text = 'title1'), list(text = 'title2'),...)
    )
  ) %>%
```
