### ISSUE TITLE
[Feature Request] Default selection (selected vs deselected) for highcharter

### ISSUE THREAD

**Issue by yytsong** [jbkunst/highcharter#720]
Thanks for developing this package; it has been really effective and useful. 

I am looking for solutions to select partial legend by default (deselected legend should remain in the visual), the problem as described by the person from this [post](https://stackoverflow.com/questions/56020625/highcharter-deselect-variables-in-the-legend-in-the-code-on-rstudio). I attempted the suggested solution, which does not work (it does not return any error but just show all legend selected by default). 

In addition, I found another solution is JS from this [link](https://jsfiddle.net/core972/ct16cnpa/).  However, I am unsure how to reproduce this in R.

Please find a reproducible example created below. Basically, can highcharter enable deselect S1 while S1 remains in the legend? In addition, when the number of series increase, can highcharter enable multiple select/deselect?

```r
library(tidyverse)
library(lubridate)
library(highcharter)

dt <- data.frame(
  cat = c("S1", "S1", "S1","S1", "S1", "S1", "S2", "S2", "S2", "S2", "S2", "S2"),
  date = c("2020-01-01", "2020-01-02", "2020-01-03", "2020-01-04", "2020-01-05", "2020-01-06", 
           "2020-01-01", "2020-01-02", "2020-01-03", "2020-01-04", "2020-01-05", "2020-01-06"),
  val = c(1,2,3,4,5,6, 4,5,6,2,3,4)
) |> 
  mutate(date = as.Date(date))

hchart(object = dt, type = 'line',
       hcaes(x = date, y = val, group = cat),
       showInLegend = TRUE) |>  
  hc_xAxis(type = "datetime") |>  
  hc_rangeSelector(enabled= TRUE, verticalAlign = "bottom") 
```

**Comment by hdrab127** [comment]
You should be able to slightly modify your code to use `hc_add_series` instead and utilise the `visible` series option there (kind of the R way of achieving the accepted answer [here](https://stackoverflow.com/questions/16468534/disable-series-through-configuration-in-highcharts) for highcharts.js).

```r
highchart() %>% 
  # this could be all initially hidden series
  hc_add_series(filter(dt, cat == "S1"), 
                type = 'line',
                hcaes(x = date, y = val, group = cat),
                visible = FALSE) |>
  # and all visible series
  hc_add_series(filter(dt, cat == "S2"), 
                type = 'line',
                hcaes(x = date, y = val, group = cat)) |>
  hc_xAxis(type = "datetime") |>  
  hc_rangeSelector(enabled= TRUE, verticalAlign = "bottom")
```

**Comment by yytsong** [comment]
Thanks so much for the reference scenario. 
Hope this could be considered as an inbuilt feature later in the highcharter package.
