### ISSUE TITLE
change color of a button

### ISSUE THREAD

**Issue by learning-freak** [jbkunst/highcharter#726]
I would like to change the text color and the background color of a button (for example : text in red and background color in blue) using the function navigation (see here : https://api.highcharts.com/highmaps/navigation) but can not find how to do it from highcharter.

Here is my example :

```r
library(highcharter)
# data
df <- data.frame(dose=c("D0.5", "D1", "D2"),
                 len=c(4.2, 10, 29.5))

#graph
df %>%
  hchart('column', hcaes(x = dose, y = len))%>%
  hc_exporting(
    enabled = TRUE,
    buttons = list(
      contextButton = list(
        symbol = NULL,
        menuItems = NULL,
        text = 'mybutton',
        onclick = JS("
                   function() {
            this.exportChart({
              type: 'image/png'
            });
          }
                   
                   ")
      )
    )
  )
```
How can we change text color and background color of a button with Highcharter ?

**Comment by jbkunst** [comment]
_Hello_ @learning-freak 

1. Please, first read https://jkunst.com/highcharter/articles/highchartsjs-api-basics.html
1. Based in the first item, you can to search "theme buttons in highcharts" or "change export button style highcharts".
1. You'll reach https://api.highcharts.com/highcharts/exporting.buttons.contextButton.theme and  http://jsfiddle.net/BlackLabel/udhvazqo/ links.
1. Based in the previous information modify your R code to match the structure based on point1.

```r
#graph
df %>%
  hchart('column', hcaes(x = dose, y = len))%>%
  hc_exporting(
    enabled = TRUE,
    buttons = list(
      contextButton = list(
        symbol = NULL,
        menuItems = NULL,
        text = 'mybutton',
        onclick = JS("
                   function() {
            this.exportChart({
              type: 'image/png'
            });
          }
                   
                   "),
        theme = list(
          stroke = 'red',
          states = list(
            hover = list(
              fill = "blue"
            )
          )
        )
      )
    )
  ) 
```


_Kind regards_
