### ISSUE TITLE
Add example of accessibility module to modules & plugins vignette

### ISSUE THREAD

**Issue by batpigandme** [jbkunst/highcharter#736]
Hi,

This is basically a "do-you-want-this-PR?" issue, as I've already implemented it [added an example using the accessibility module to the Modules & plugins vignette] in a branch here: https://github.com/batpigandme/highcharter/commit/84d4ea738be261e08296ca4776c14a2e0c0f1ba9.

I've rendered the same chart [here](https://rpubs.com/maraaverick/highcharter-accessible-pie-chart).

Let me know if you'd like it, and I'll put in a PR.

Thanks,

Mara

**Comment by jbkunst** [comment]
Hi Mara @batpigandme ! 

Sorry for my late response.

I was thinking about make a specific vigneet for the accessibility module. I've already check all your rpubs about accesibily module and I think they need even more exposure :). 

I would be happy if all this information can be in the official highcharter website in a new vignette. What do you think?

Kindly regards

**Comment by batpigandme** [comment]
Sounds good to me! Had so much fun doing these!
