### ISSUE TITLE
Display issue occurs when creating a Sankey diagram with hchart() and data_to_sankey() functions

### ISSUE THREAD

**Issue by ISMAILManel** [jbkunst/highcharter#737]
Hello!

I am trying to build a Sankey diagram using the hchart() and data_to_sankey() functions. The group_by executed by the data_to_sankey() function seems to work :

```
df2<- data.frame(X= c("A","A","B","B", "C"),
                Y= c("B","B","C","D","D"))

data_to_sankey(df2)
```

<img src="https://user-images.githubusercontent.com/93122266/140721137-af0a509d-08e1-408a-87ad-c709eafaaf88.png" alt="data_to_sankey" width="200"/>

However, there seems to be a display error when applying the hchart() function : 

```hchart(data_to_sankey(df2),` "sankey", `name="steps")```

<img src="https://user-images.githubusercontent.com/93122266/140715769-afa87f93-bb31-4804-a5f7-d8cf129780d4.png" alt="hchart" width="400"/>

The following output built using d3js is what I should have :

<img src="https://user-images.githubusercontent.com/93122266/140715718-30f58564-36b1-4fae-9675-d985af1c2335.png" alt="d3js" width="400"/>

**Comment by jbkunst** [comment]
Hi!

```r
library(highcharter)

df2<- data.frame(X= c("A","A", "B","B", "C"),
                 Y= c("B","B", "C","D" ,"D"))

data_to_sankey(df2)

hchart(
  data_to_sankey(df2)[c(1,2,4,3),],
  "sankey",
  name = "steps", 
  nodes = list(
    list(id = "C", offsetVertical = -200)
    )
  )
```

![image](https://user-images.githubusercontent.com/56481/146488341-ed39c26c-6825-4106-ae6e-c10b4da676dd.png)
