### ISSUE TITLE
Export to JSFiddle

### ISSUE THREAD

**Issue by ctmann** [jbkunst/highcharter#74]
Love the package! Is there a way to export to JSFiddle?

P.S. You are awesome.

P.S.S. More documentation, please!

**Comment by jbkunst** [comment]
@ctmann 

I've implemented [`export_hc`] (https://github.com/jbkunst/highcharter/blob/master/R/export-hc.R) function, write the highcarts options to text files which you can **copy&paste** into JSFiddle. 

P.S Thanks

P.S.S. What type of documentation dou you need? I think with:

- http://jkunst.com/highcharter/, 
- https://cran.rstudio.com/web/packages/highcharter/vignettes/replicating-highcharts-demos.html
- https://cran.rstudio.com/web/packages/highcharter/highcharter.pdf 

I covered almost all the funcionalities.
