### ISSUE TITLE
hcmap - Error: parse error: trailing garbage

### ISSUE THREAD

**Issue by colantuono** [jbkunst/highcharter#741]
When I run hcmap() function, it downloads the data, but returns the following error:

![image](https://user-images.githubusercontent.com/76113840/145452331-b28b8b8d-c485-43d7-a258-0b55df47b098.png)

```r
library(highcharter)

hcmap(map = "countries/br/br-all") 
hcmap(map = "countries/us/us-all") 
hcmap(map = "countries/it/it-all") 
```

**Comment by jbkunst** [comment]
Hi @colantuono 

Can you test de development version?

```r
remotes::install_github("jbkunst/highcharter")
```

**Comment by MartinGuth** [comment]
@jbkunst I can confirm that your fix works! Thanks for the quick update!

**Comment by jameshenry1995** [comment]
I wrote a seperate post about this, but is anyone else having issues when integrating the plots to a flexdashboard? After the first plot, they don't render for me.

The hw_grid() function, which I previously used to make ggplot-like facet plot with highcharter also only returns one plot now.

Both those issues only materialize after loading the update, they don't occur with the standard package.

**Comment by colantuono** [comment]
@jbkunst It worked, thanks.

**Comment by dker92** [comment]
@jbkunst  When the fix will be available in production ?

**Comment by ahmedjoubest** [comment]
Hi @jbkunst  and thank you for this whole package!

Does it mean that for now it's not possible to use hcmap within shinyapps.io ?

**Comment by jbkunst** [comment]
Hi @ahmedjoubest 

It's possible. Shinyapp.io knows the source of the package cran/github. Give it a try.

**Comment by QuinHsieh** [comment]
In order to improve the above problems, when I enter 
**remotes::install_github("jbkunst/highcharter")** or **devtools::install_github("jbkunst/highcharter")**

but returns the following error:
![image](https://user-images.githubusercontent.com/51399083/146297345-c2ab9e9f-22c5-4718-9f1e-f61b60b9b3c6.png)
![image](https://user-images.githubusercontent.com/51399083/146297402-26c865fa-e573-4091-992d-9df16f99aa0e.png)

I use MAC os, how can this be solved? Thank.

**Comment by galoher** [comment]
@jbkunst 
Hola disculpa tengo el mismo problema , ya intente con el código que pusiste pero aun así no me vale, me sigue saliendo esto, de verdad te agradecería tu ayuda.
probando la URL 'https://code.highcharts.com/mapdata/countries/ec/ec-all.js'
Content type 'text/javascript' length 38994 bytes (38 KB)
downloaded 38 KB

Error: parse error: trailing garbage
          [[2454,8025],[1376,6314]]}}]};
                     (right here) ------^

**Comment by jbkunst** [comment]
hola @galoher! debes instalar la versión de desarrollo  https://github.com/jbkunst/highcharter/issues/741#issuecomment-990340644

**Comment by jbkunst** [comment]
> @jbkunst When the fix will be available in production ?

It will be soon, according to CRAN I have until January 5

**Comment by galoher** [comment]
@jbkunst ! ya realice ese procedimiento sin embargo me sigue saliendo esto, nose a que se deba, por favor agradezco tu ayuda:
probando la URL 'https://code.highcharts.com/mapdata/countries/ec/ec-all.js'
Error in download.file(url, tmpfile, quiet = quiet) : 
  no fue posible abrir la URL 'https://code.highcharts.com/mapdata/countries/ec/ec-all.js'
Además: Warning message:
In download.file(url, tmpfile, quiet = quiet) :
  fallo en InternetOpenUrl: 'No se pudo resolver el nombre de servidor ni su dirección'

**Comment by galoher** [comment]
@jbkunst te agradezco mucho, ya me valió de verdad muchas gracias colega
