### ISSUE TITLE
Highchart proxy not working on server

### ISSUE THREAD

**Issue by lakshyaduhan** [jbkunst/highcharter#745]
Hi,

I am trying to create some highcharts and update them with proxy. The code is perfectly working when i run it in Rstudio but doesnt work when i deploy the code on server. The highchart proxy is declared under observeEvent when it wait for user to update values and then display chart accordingly. When i include highcharts proxy code, all the charts disappears but if i comment out all the highchart proxy code, the static charts remain but doesn't update (which is obvious since we don't have any proxy). 

highcharter package - 0.9.3.9000

Anyone having this issue recently?

**Comment by jbkunst** [comment]
Hi @lakshyaduhan 

Can you get some logs: server and browser?

**Comment by lakshyaduhan** [comment]
Hi @jbkunst 

Please see the attached file for logs, if thats the one you were after. Let me know if you need further information.

[logs.txt](https://github.com/jbkunst/highcharter/files/7708350/logs.txt)

**Comment by jbkunst** [comment]
I don't see anything weird. What about the browser?

![image](https://user-images.githubusercontent.com/56481/145926179-344de328-7d26-47c3-a017-e32ee7248a55.png)

(https://kb.mailster.co/how-can-i-open-the-browsers-console/)

**Comment by lakshyaduhan** [comment]
Browser console does show chart undefined whereas that's not the case.
[console-log.txt](https://github.com/jbkunst/highcharter/files/7708577/console-log.txt)

**Comment by jbkunst** [comment]
Nothing I can see. Do you have a link?

**Comment by lakshyaduhan** [comment]
Here is the server link:
The Employment scenario should have  a chart something like the image shared and when update industry the chart should update, but when we add the proxy code the chart just disappears. It works fine over Rstudio and local machine, but doesnt on server.
![image](https://user-images.githubusercontent.com/90163642/145933828-8a118ab9-3dd1-4889-ae96-73dd2fb0961f.png)


https://remplan.shinyapps.io/wyndham_beta/

**Comment by jbkunst** [comment]
Can you put a button to update the series instead of doing automatically? I would try to:

1. First generate the chart.
2. When the chart is ready use a button `observeEvent(input$an_action_button)` to update the chart

**Comment by lakshyaduhan** [comment]
Thanks @jbkunst for the suggestion. I will do some testing to confirm if it works.

Also, I am trying to update the charts (mentioned in above comment), where we have to remove 'area range' series and then add them back to have the latest values in 'area range', is there any efficient and better way to update charts without removing and adding them back.

I am not able to update 'area range' using hcpxy_update_series, the chart keeps the old value for some reason whereas central value is updated easily.

Here is the code example which we are currently doing but wanted to improve this:
```r
highchartProxy("Employment Chart") %>%
          hcpxy_remove_series(
            id = "inner"
          ) %>%
          hcpxy_remove_series(
            id = "outer"
          ) %>%
            hcpxy_add_series(
              data = Data %>% rename("low" = `90%_lower`, "high" = `90%_upper`),
              id = "outer",
              name = "outer",
              type = "arearange",
              color = cols[4],
              fillOpacity = 0.3,
              lineWidth = 0
            ) %>%
            hcpxy_add_series(
              data = Data %>% rename("low" = `50%_lower`, "high" = `50%_upper`),
              id = "inner",
              name = "inner",
              type = "arearange",
              color = cols[4],
              fillOpacity = 0.3,
              lineWidth = 0
            ) %>%
            hcpxy_update_series(
              data = Data %>% pull(central),
              id = "central"
            )
            
 ```
