### ISSUE TITLE
devtools::install_github("jbkunst/highcharter")  returns error

### ISSUE THREAD

**Issue by QuinHsieh** [jbkunst/highcharter#746]
when I enter 
**remotes::install_github("jbkunst/highcharter")** or 
**devtools::install_github("jbkunst/highcharter")**

but returns the following error:
![image](https://user-images.githubusercontent.com/51399083/146297345-c2ab9e9f-22c5-4718-9f1e-f61b60b9b3c6.png)
![image](https://user-images.githubusercontent.com/51399083/146298253-ca3556ef-ff3d-46c6-9841-136545193438.png)

My operating system is MAC os, how can this be solved?  Thanks.

**Comment by jbkunst** [comment]
this happens with other packages?

**Comment by QuinHsieh** [comment]
I did not test other packages, 
but I just updated devtools and remotes package,
 the problem has been solved. 

Thank you.
