### ISSUE TITLE
hc_add_serie_scatter dataLabels issue

### ISSUE THREAD

**Issue by neek05** [jbkunst/highcharter#75]
Hi, 
I'm trying to change the color of the label of a scatter plot but it doesn't seem to be working.
For example, this code I found in your blog works in highcharter 0.2.0 but not in version 0.3.0:
```

hcmtcars <- highchart() %>% 
  hc_title(text = "Motor Trend Car Road Tests") %>% 
  hc_subtitle(text = "Source: 1974 Motor Trend US magazine") %>% 
  hc_xAxis(title = list(text = "Weight")) %>% 
  hc_yAxis(title = list(text = "Miles/gallon")) %>% 
  hc_chart(zoomType = "xy") %>% 
  hc_add_serie_scatter(mtcars$wt, mtcars$mpg,
                       mtcars$drat, mtcars$hp,
                       rownames(mtcars),
                       dataLabels = list(
                         enabled = TRUE,
                         format = "{point.label}",
                         color = '#FFFFFF'
                       )) %>% 
  hc_tooltip(useHTML = TRUE,
             headerFormat = "<table>",
             pointFormat = paste("<tr><th colspan=\"1\"><b>{point.label}</b></th></tr>",
                                 "<tr><th>Weight</th><td>{point.x} lb/1000</td></tr>",
                                 "<tr><th>MPG</th><td>{point.y} mpg</td></tr>",
                                 "<tr><th>Drat</th><td>{point.z} </td></tr>",
                                 "<tr><th>HP</th><td>{point.valuecolor} hp</td></tr>"),
             footerFormat = "</table>")
hcmtcars

```
Is this a bug or am I doing something wrong?

Thanks!

**Comment by jbkunst** [comment]
Hi @neek05 !

Your dataLabels options are not used because internally the `hc_add_serie_scatter` use their own data lables configurations (see [here](https://github.com/jbkunst/highcharter/blob/15fb0065f986e97b92cb35155448f6ae1e494cfb/R/shortcuts.R#L104))

You can override the option doing:

```
hcmtcars $x$hc_opts$series[[1]]$dataLabels <- list(
  enabled = TRUE,
  format = "{point.label}",
  color = '#FFFFFF'
)

hcmtcars 
```

Not so elegant :cry: , but I code some type of merge between the dataLabels argument (if is given) with the internal ones to avoid this hack.

Sorry and thanks for open this issue. I'll close due this related to #58. If you arent agree we can reopen the issue to discuss in detail ;).

Regards

**Comment by tbenschop** [comment]
Hi @jbkunst ,
How can I change the palette that is used for the colors? Say I want to use the 'bluemono' palette:
`bluemono<-"#084594" "#2171B5" "#4292C6" "#6BAED6" "#9ECAE1" "#C6DBEF" "#DEEBF7" "#F7FBFF"`
How can I use these in this scatter:
```
hc<-highchart()
hc_add_series_scatter(hc, mtcars$wt, mtcars$mpg, mtcars$drat,color= mtcars$gear,
                      name = rownames(mtcars))
``` 

Thanks, Tim

**Comment by jbkunst** [comment]
Hi Tim @tbenschop 

Currently this is not possible using `hc_add_series_scatter`. 

But is easy if you use `hc_add_series_df` renaming the columns using [this](http://api.highcharts.com/highcharts#series<bubble>.data) link:

We first create a function to `colorize` a vector (numeric or factor) given a list of colors which I will include in `highcharter`.

``` 
colorize <- function(x, colors = viridis::viridis(10)) {
  
  nuniques <- length(unique(x))
  palcols <- grDevices::colorRampPalette(colors)(nuniques)
  
  if (!is.numeric(x) | nuniques < 10) {
    
    y <- as.numeric(as.factor(x))
    xcols <- palcols[y]
    
  } else {
  
    ecum <- ecdf(x)
    xcols <- palcols[ceiling(nuniques*ecum(x))]
    
  }
  
  xcols
  
}
```

The create a data frame with the x, y, z, and color that we want and use `hc_add_series_df`.

```


colors <- c("#084594", "#2171B5", "#4292C6", "#6BAED6",
                  "#9ECAE1", "#C6DBEF", "#DEEBF7", "#F7FBFF")

options(highcharter.theme = hc_theme_flatdark())

mtcarts2 <- mtcars %>% mutate(x = wt, y = mpg, z = x) 
  
mtcarts2 %>% 
  mutate(color = colorize(gear, colors)) %>% 
  hc_add_series_df(highchart(), ., type = "bubble")

mtcarts2 %>% 
  mutate(color = colorize(gear)) %>% 
  hc_add_series_df(highchart(), ., type = "bubble")

mtcarts2 %>% 
  mutate(color = colorize(mpg, colors)) %>% 
  hc_add_series_df(highchart(), ., type = "bubble")

mtcarts2 %>% 
  mutate(color = colorize(mpg)) %>% 
  hc_add_series_df(highchart(), ., type = "bubble")
```
 
I think this is really nice. I like it. Thanks for comming with this issue ;).

![examples](https://cloud.githubusercontent.com/assets/56481/15590148/7750abec-236c-11e6-8474-8b3877c6cd12.jpg)
