### ISSUE TITLE
point vs line hchart inconsistency with geom_point and geom_line

### ISSUE THREAD

**Issue by hmaeda** [jbkunst/highcharter#765]
Hello, 

There appears to be some inconsistency when trying to translate `ggplot2` to `highcharter`. In particular using the `type="line"`does not seem to match ggplot's `geom_line()`

i.e. the following two point graphs generate similar plots
``` 
ggplot(iris,aes(x=Sepal.Length,y=Sepal.Width,group=Species,color=Petal.Length))+geom_point()
hchart(iris,'point',hcaes(x=Sepal.Length,y=Sepal.Width,group=Species,color=Petal.Length))
```

However when changing to a line graph for both frameworks in the below two lines of code...the `color` argument does not appear to be respected using the `hchart` function.

```
ggplot(iris,aes(x=Sepal.Length,y=Sepal.Width,group=Species,color=Petal.Length))+geom_line()
hchart(iris,'line',hcaes(x=Sepal.Length,y=Sepal.Width,group=Species,color=Petal.Length))
```

I think this is a bug...as the `hchart` function only seems to use the `group` argument to determine the color of the line. Please can this be fixed?

**Comment by robertogilsaura** [comment]
Hi, @hmaeda, Can you test ?

hchart(iris %>%
dplyr::arrange(Sepal.Length),'line',hcaes(x=Sepal.Length,y=Sepal.Width,group=Species))

Regards
-.-.-.-.-
*Roberto Gil Saura  **
<https://www.facebook.com/InvestigaOnline-552640944937849/>
<https://twitter.com/robertogilsaura>
<https://www.linkedin.com/in/robertogilsaura/>*
* <https://www.investigaonline.com/>*
---
Este mensaje y los ficheros anexos que, en su caso, incorpore pueden
contener información confidencial o de uso exclusivamente interno de
investigaonline.com, sujeto a secreto profesional. Si usted lo recibe por
error o considera que no es el destinatario del mismo, debe destruirlo y
comunicar al emisor esta circunstancia, no pudiendo en ningún caso
distribuir, divulgar ni copiar el mensaje.

**Comment by hmaeda** [comment]
Hi @robertogilsaura,

Thanks for coming back so quickly. Apologies I should have been clearer, my
issue is not with the order of the data to generate the lines for each
group but with regard to the colour of the lines themselves. Which using
your code, I still only see three distinct colours rather than a colour
gradient based on Petal Length.

Thanks,

**Comment by hmaeda** [comment]
@robeerogilsaura and @jbkunst

Can I confirm that you are able to replicate the bug and that it is indeed
a bug?

Or are you able to suggest a work arround?

Thanks,

**Comment by hmaeda** [comment]
@robertogilsaura & @jbkunst 

Are you able to help here at all?

Thanks,
