### ISSUE TITLE
Enabling accessibility module breaks chart

### ISSUE THREAD

**Issue by mrjoh3** [jbkunst/highcharter#778]
I am trying to include the `highcharts` accessibility module in a basic chart. The chart works fine but when I add the dependency via `hc_add_dependency` the chart becomes garbled. The axis' remain but the contents disappear. 

I have been reading through https://www.rpubs.com/maraaverick/accessible-highcharter as a quide and have also tried the method where the chart and dependencies are set up first before adding `xAxis` and series separately. This method also produced a gabled plot. So I have included the first method here as a repex.

```r
library(highcharter)

df <- data.frame(date = seq(as.Date('2022-01-01'), length.out = 10, by = 'month'),
                 value = rnorm(10))

hchart(df, 
         type = "line",
          hcaes(x = date, 
                    y = value),
       accessibility = list(
                  enabled = TRUE,
                  keyboardNavigation = list(enabled = TRUE),
                  linkedDescription = "My Chart"
                )) |>
    hc_add_dependency(name = "modules/accessibility.js")
```

![image](https://user-images.githubusercontent.com/1921793/197460884-427c6d0b-5e3e-42cd-bf15-601d9b9afe8d.png)

**Comment by humoroussmile** [comment]
This may help - this is what I'm doing until the accessibility module issue is corrected: https://github.com/jbkunst/highcharter/issues/755

**Comment by mrjoh3** [comment]
thanks @humoroussmile not sure how I missed the other issue this is clearly a duplicate. I used the older version and it work perfectly

```
remotes::install_github("jbkunst/highcharter@8ff41366c8c411b497b5378d27be48617360f81f")
```
