### ISSUE TITLE
Shiny app example down

### ISSUE THREAD

**Issue by zross** [jbkunst/highcharter#80]
A lot of great stuff in highcharter. I'm noticing that the shiny example is not loading https://jbkunst.shinyapps.io/highcharter/ -- it might be temporary but I tried several times. I'd love to take a look.

**Comment by jbkunst** [comment]
Hi @zross 

Thanks for your words! 

You can do `shiny::runGitHub("shiny-apps", "jbkunst", subdir = "highcharter")` to run the example in your pc. The example needs some updates but show in general how work with shiny ;)!.

I'll close the issue. If you want to discuss more in detail we can reopen.

Regards and thanks for try the package!
