### ISSUE TITLE
hc_exporting converts plot to dark mode

### ISSUE THREAD

**Issue by analytichealth** [jbkunst/highcharter#808]
Using hc_exporting the png or jpeg images are formatted with different colours than the original plot.

I tried on Linux and Mac and get the same outcome.

Highcharter version 0.9.4
R version 4.3.2 (also tried on 4.3.1)

In this example, the plot will have a white background and grey axis lines. But after selecting 'Download PNG image' from the chart context menu the downloaded image will have a black background and white axis lines.

In the past the downloaded image would be the same as the original.
 
```r
library(highcharter)
highchart() |> 
  hc_xAxis(categories = month.abb) |> 
  hc_add_series(name = "Tokyo", data = sample(1:12)) |> 
  hc_exporting(
    enabled = TRUE,
    filename = "custom-file-name"
  )
```

**Comment by tianhuidong** [comment]
```
 hc_exporting(
    chartOptions = list(chart = list(backgroundColor = "#FFFFFF")),
    enabled = TRUE,
    filename = "custom-file-name"
  )
```

**Comment by analytichealth** [comment]
Thank you this does solve it
