### ISSUE TITLE
hc_add_series_df in dev version

### ISSUE THREAD

**Issue by carbonmetrics** [jbkunst/highcharter#82]
thanks for making this available! 

http://jkunst.com/highcharter/shortcuts.html points to hc_add_series_df, 
however this is available in the dev version, not in the cran version.

**Comment by jbkunst** [comment]
Hi @carbonmetrics !

I'm planning update the package in CRAN in the next week.

Meanwhile you can download the dev version via devtools.

If you have more doubts we can discuss ;)!

**Comment by carbonmetrics** [comment]
Hola Josha!
No doubts, just discovering your excellent highcharter library and 
trying to reproduce some plots.
Is there a way to set the binwidth of histograms in hc_chart ?

The only thing I really miss is facetting.
In library metricsgraphics there is a way to do it (albeit without the 
free scaling), do you think that would be possible in highcharter?




On 25-04-16 17:28, Joshua Kunst wrote:
>
> Hi @carbonmetrics <https://github.com/carbonmetrics> !
>
> I'm planning update the package in CRAN in the next week.
>
> Meanwhile you can download the dev version via devtools.
>
> If you have more doubts we can discuss ;)!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/jbkunst/highcharter/issues/82#issuecomment-214360165>
>

-- 
Henk Harmsen
+ 254 7 9030 7166
skype: carbonmetrics
http://www.linkedin.com/in/carbonmetrics

**Comment by jbkunst** [comment]
Hola! :dancer: 

You can (`hc_`)chart `histogram`object  with your own parameters:

```
hchart(hist(rnorm(100), breaks = 10))
hchart(hist(rnorm(100), breaks = 50))
hchart(hist(rnorm(100), breaks = c(-5,-2,0,1,2,3)))
```

highchart dont have a facet implementation yet. but there's a `hw_grid` function to make grid inspired by metrcigraphics obviously. You can mix every hmltwidget object check here: http://rpubs.com/jbkunst/higcharter-grid-test

Regards,

**Comment by carbonmetrics** [comment]
Buenas dias Jpshua, thanks! I didn't know about hw_grid and didn't discover the histogram breaks yet. In a similar vein, the size of bubbles can be adjusted with minSize and maxSize. The bubbles in the example are too big and don't scale by adjusting z.

**Comment by jbkunst** [comment]
Hi!

```
require("dplyr")
n <- 50
df <- data_frame(
  x = rnorm(n),
  y = x * 2 + rnorm(n),
  z =  x ^ 2,
  color = colorize_vector(x),
  extrainfo = sprintf("I have (%s, %s) coordiantes!", round(x, 2), round(y, 2))
)

highchart() %>%
  hc_tooltip(pointFormat = "{point.extrainfo}") %>% 
  hc_add_series_df(data = df, type = "bubble")

highchart() %>%
  hc_tooltip(pointFormat = "{point.extrainfo}") %>% 
  hc_add_series_df(data = df, type = "bubble",
                   minSize = 2, maxSize = 10)

```

:smile:

**Comment by carbonmetrics** [comment]
Gracias! Works like sunshine. There was a library missing: purrr.
BTW - no need to quote libraries - you can just do library(purrr) .... 
less typing :-)

Henk

On 25-04-16 19:18, Joshua Kunst wrote:
>
> Hola! :dancer:
>
> You can (|hc_|)chart |histogram|object with your own parameters:
>
> |hchart(hist(rnorm(100), breaks = 10)) hchart(hist(rnorm(100), breaks = 
> 50)) hchart(hist(rnorm(100), breaks = c(-5,-2,0,1,2,3))) |
>
> highchart dont have a facet implementation yet. but there's a 
> |hw_grid| function to make grid inspired by metrcigraphics obviously. 
> You can mix every hmltwidget object check here: 
> http://rpubs.com/jbkunst/higcharter-grid-test
>
> Regards,
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/jbkunst/highcharter/issues/82#issuecomment-214426236>
>

-- 
Henk Harmsen
+ 254 7 9030 7166
skype: carbonmetrics
http://www.linkedin.com/in/carbonmetrics
