### ISSUE TITLE
Naming the series in drilldown

### ISSUE THREAD

**Issue by jingjingyangg** [jbkunst/highcharter#84]
Is there a way to name the series in drilldown? Both the example on Highcharts API and your reference manual left the name to be "Series 2". I tried adding 

> hc_drilldown(
    allowPointDrilldown = TRUE,
    series = list(name = "name of the series", list(
      list(
        id = "animals",
        data = dsan
      ),
      list(
        id = "fruits",
        data = dsfru
      ),
      list(
        id = "cars", data = dscar
      )
    )
  )
)

But I got the following error message:

> Error in FUN(X[[i]], ...) : 
  'options' must be a fully named list, or have no names (NULL)

**Comment by jbkunst** [comment]
Hi @jingjingyangg !

Thanks for point this. There are some issues in highcharter when you add a list of list due internally I use `list.merge` (to add and join components by names ), I'm working on create a function to make easy add this type of data (see #26).

You can use a hack alternative:
```
hc <- highchart()
hc$x$hc_opts$drilldown <- list(
  allowPointDrilldown = TRUE,
  series = list(name = "name of the series", list(
    list( ... )
    ...
)

hc
```

Sorry :pray:! But I will work on this. Can you give me some more detailed example  (w/data) to work with?

Regards,

**Comment by jbkunst** [comment]
Hi @jingjingyangg 

Can you run this code? Installing the development version of highcharter pls and tell me if this help you. Thanks!

```
rm(list = ls())
library("dplyr")
library("purrr")
library("highcharter")

df <- data_frame(
  name = c("Animals", "Fruits", "Cars"),
  y = c(5, 2, 4),
  drilldown = tolower(name)
)

df

hc <- highchart() %>%
  hc_chart(type = "column") %>%
  hc_title(text = "Basic drilldown") %>%
  hc_xAxis(type = "category") %>%
  hc_legend(enabled = FALSE) %>%
  hc_plotOptions(
    series = list(
      boderWidth = 0,
      dataLabels = list(enabled = TRUE)
    )
  ) %>%
  hc_add_series_df(
    data = df,
    name = "Things",
    colorByPoint = TRUE
  )


dfan <- data_frame(
  name = c("Cats", "Dogs", "Cows", "Sheep", "Pigs"),
  value = c(4, 3, 1, 2, 1)
)

dffru <- data_frame(
  name = c("Apple", "Organes"),
  value = c(4, 2)
)

dfcar <- data_frame(
  name = c("Toyota", "Opel", "Volkswagen"),
  value = c(4, 2, 2)
)

hc <- hc %>%
  hc_drilldown(
    allowPointDrilldown = TRUE,
    series = list(
      list(
        id = "animals",
        data = list.parse2(dfan)
      ),
      list(
        id = "fruits",
        data = list.parse2(dffru)
      ),
      list(
        id = "cars",
        data = list.parse2(dfcar)
      )
    )
  )

hc

```

**Comment by jingjingyangg** [comment]
Hi @jbkunst thank you for your prompt reply! But I don't see why you are showing me this new graph. The drilldown series is still named as the default "Series 2". I would like to be able to give the series a meaningful name because "Series 2: 4" doesn't really make sense.

**Comment by jbkunst** [comment]
@jingjingyangg 

Whoa. Sorry. Now I get it. 

You just need to name the series like:

```
      list(
        id = "cars",
        name = "what ever you want",
        data = list.parse2(dfcar)
      )
```

Check http://rpubs.com/jbkunst/176197

**Comment by jingjingyangg** [comment]
@jbkunst If I want to name all of them the same, i.e instead of "animals","fruits", and  "cars", I just want them all to be "count", is there a way to do that instead of naming each one individually?

**Comment by jbkunst** [comment]
Mmm...

I think you need to use tooltips options

Try:
```
hc %>% 
  hc_tooltip(pointFormat = "Im a constant text {point.y}",
             headerFormat = "I'm here!<br/>")
```

**Comment by jingjingyangg** [comment]
This worked wonderfully for my purpose. Thank you again for your help!
