### ISSUE TITLE
Add cross as marker symbol of survival curves

### ISSUE THREAD

**Issue by nuno-agostinho** [jbkunst/highcharter#96]
Currently, the default symbol for the survival curves (plotted using `hchart.survfit`) is a triangle instead of the commonly used cross.

As @jbkunst mentioned, Highcharts allows to create cross symbols like [this](http://stackoverflow.com/questions/21985319/highcharts-cross-symbol-with-fillcolor) and [this](http://stackoverflow.com/questions/27542928/extend-highcharts-renderer-symbols-to-have-plus-sign).

 Related discussion thread: #91

**Comment by jbkunst** [comment]
@nuno-agostinho 

done it! http://rpubs.com/jbkunst/highcharter-symbols :+1:

**Comment by nuno-agostinho** [comment]
Awesome! :smile:

**Comment by nuno-agostinho** [comment]
Hello @jbkunst ! It seems that running `hchart` in a `survfit` object in the latest version of highcharter is using circles instead of pluses as markers as expected: https://rpubs.com/nuno-agostinho/660377
