### ISSUE TITLE
datetime_to_timestamp breaks due to passing date to as.POSIXct() twice

### ISSUE THREAD

**Issue by sz-cgt** [jbkunst/highcharter#97]
Passing dt both via `%>%` and directly to `as.POSIXct()` causes it to choke on certain Date classes because the date is also being passed as the timezone.

I think these lines (92-94 in R/helpers.R)

    tmstmp <- dt %>% 
      as.POSIXct(dt) %>% 
      as.numeric() 

should be

    tmstmp <- dt %>% 
      as.POSIXct() %>% 
      as.numeric() 

Usually, `as.POSIX()` ignores invalid timezone strings, but in the examples below it fails.  As passing the date as it's own timezone specification makes little sense anyway, this seems like the simplest fix.

To see what I mean compare

    as.Date('2014-01-01') %>% as.POSIXct(as.Date('2014-01-01'))
    as.Date('2014-01-01') %>% as.POSIXct()

with

    as.IDate('2014-01-01') %>% as.POSIXct(as.IDate('2014-01-01'))
    as.IDate('2014-01-01') %>% as.POSIXct()

PS: as.IDate is in the data.table package.  `class(as.IDate('2014-01-01'))` returns `[1] "IDate" "Date"`.  It also passes `assertthat::is.date()`

**Comment by jbkunst** [comment]
Oops! Thanks @sz-cgt  for notice this. What a mistake!

I'll check it and fix it!

Thanks again!

**Comment by jbkunst** [comment]
@sz-cgt 

I fixed, so:

```
  tmstmp <- as.numeric(as.POSIXct(dt))
```

I didnt know about `as.IDate`, I'm not sure to add the data.table dependency yet for this particular scenario. Do you know about a similar and lighweight function?

**Comment by sz-cgt** [comment]
That approach works.  IDates are basically Dates that use integer instead of numeric under the covers so they are easier to sort/filter
