### ISSUE TITLE
hc_add_series_treemap - naming of the color value variable

### ISSUE THREAD

**Issue by joh024** [jbkunst/highcharter#98]
Currently `hc_add_series_treemap` renames `vColor` to `valuecolor`.

However based on [this example of a treemap with color axis](http://www.highcharts.com/demo/treemap-coloraxis), it looks like it should be renamed to `colorValue` instead, which allows it to be connected to the `hc_colorAxis`.

And once that's done, it might even be helpful to have `hc_add_series_treemap` automatically attach a color axis (controlled via an argument that defaults to `TRUE`), with code something like:

``` R
hc_colorAxis(minColor = tm$tm$color[which.min(tm$tm$vColorValue)],
             maxColor = tm$tm$color[which.max(tm$tm$vColorValue)])
```

**Comment by jbkunst** [comment]
This was fixed in #327. Thanks!
